src/objects/AccountTerritoryAssignmentValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the literal values used by apex classes for Account Territory Assignment</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Territory Assignment Values</label>
</CustomObject>

src/objects/Territory_Model__c.object
<CustomObject>
    <description>Main placeholder for territory definition.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>JDE Company</fullName>
                </value>
                <value>
                    <fullName>Win-back Customer Since</fullName>
                </value>
                <value>
                    <fullName>Purchasing Organization</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Norway</fullName>
                </value>
                <value>
                    <fullName>Sweden</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Definition_Status__c</fullName>
        <label>Definition Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Generating Results (Preview)</fullName>
                </value>
                <value>
                    <fullName>Results Generated (Preview)</fullName>
                </value>
                <value>
                    <fullName>Applying on Accounts</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Run__c</fullName>
        <label>Last Run</label>
        <type>DateTime</type>
    </fields>
    <label>Territory Model</label>
    <nameField>
        <label>Territory Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ValidationRulesSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ValidationRuleSettings__c) and create a CheckBox field per Object to turn the sets of Validation Rules off/on.</description>
    <fields>
        <fullName>AccountTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AccountTerritory</label>
        <type>Checkbox</type>
    </fields>
    <label>ValidationRulesSettings</label>
</CustomObject>

src/classes/ApplyTerritoryResultsController.cls
/**
* Class Name: ApplyTerritoryResultsController
* @author: James Azana
* Date: 16-Jun-2017
* Requirement: Batch process to update territory model on accounts
* @description: Updates territory model on the accounts
*
*/

public with sharing class ApplyTerritoryResultsController{
    
    public Territory_Model__c model;
    public boolean showButton{get;set;}
    public String messageValue{get;set;}
    public String buttonValue{get;set;}
      
    public ApplyTerritoryResultsController(ApexPages.StandardController controller) {

        this.model = (Territory_Model__c)controller.getRecord();
        //get territory model record that triggers the process
        if(Schema.sObjectType.Territory_Model__c.fields.Id.isAccessible() &&
           Schema.sObjectType.Territory_Model__c.fields.name.isAccessible() &&
           Schema.sObjectType.Territory_Model__c.fields.Country__c.isAccessible() &&
           Schema.sObjectType.Territory_Model__c.fields.Account_Type__c.isAccessible()){
            model = [SELECT id, name, Country__c, Last_Run__c FROM Territory_Model__c WHERE Id = :model.id];
        }
        showButton = false;
    }
    
    public void applyResults(){
        CustomLogging.push('applyResults', 'ApplyTerritoryResultsController');
        try{
            //update Territory Model definition status
            model.Definition_Status__c = SM_Constants.modelStatusApplying;
            
            if(Schema.sObjectType.Territory_Model__c.fields.Definition_Status__c.isUpdateable()){
                update model;
            }
            
            //trigger update batch
            TerritoryResult_UpdateBatch updateBat = new TerritoryResult_UpdateBatch();
            updateBat.modelId =  model.id;
            updateBat.modelCountry = model.Country__c;
            
            //get value from custom settings
            Map<String, AccountTerritoryAssignmentValues__c> cons = null;
            cons = AccountTerritoryAssignmentValues__c.getAll();
            AccountTerritoryAssignmentValues__c consVal = cons.get('updateBatchScope');
            
            database.executeBatch(updateBat, integer.valueOf(consVal.Value__c));
            
        } catch(Exception ex){
        	CustomLogging.debugException(ex);
            CustomLogging.pop();      
            System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());   
        }
    }
            
    public void applyResultsAndReturnToModel(){
        CustomLogging.push('applyResultsAndReturnToModel', 'ApplyTerritoryResultsController');
        //call method to apply results
        try{
            if (model.Last_Run__c != Null) {
                Datetime nextRun = model.Last_Run__c + 7;
                if (nextRun > Date.today() && ValidationRulesSettings__c.getInstance().AccountTerritory__c == true) {
                    modelCannotRun();
                } else {
                    applyModelAlert();
                }
            } else {
                applyModelAlert();
            }
            
        }
        catch(Exception ex){
        	CustomLogging.debugException(ex);
            CustomLogging.pop();      
            System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());   
        }
    }
    
    public pageReference modelCannotRun(){
  
        showButton = false;
        messageValue = 'Cannot run territory for the meantime. Please execute after 7 days of last run';
        buttonValue = 'Return Back';
        return null; 
        
    }
    
    public pageReference applyModelAlert() {
        showButton = true;
        messageValue = 'Irreversible, Existing Models will be inactivated. Do you want to continue?';
        buttonValue = 'No';
        return null;
        
    }
    
    public pageReference applyModeResult() {
        applyResults();
        PageReference pageRef = new PageReference('/'+model.id);
        return pageRef;
    }
    
    public pageReference returnToModel(){
        
        //open Territory Model details page
        PageReference pageRef = new PageReference('/'+model.id);
        return pageRef;
    }
    
}