src/objects/APTS_Agreement_PO_Details__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_PO_Detailss</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>APTS_PO_Number_Required__c</fullName>
        <label>PO Number Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_PO_Number_Type__c</fullName>
        <label>PO Number Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_PO_Number_Required__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Agreement PO Detail</label>
    <nameField>
        <displayFormat>PO-{00}</displayFormat>
        <label>PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement PO Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_PO_Details_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is being set to true from Agreement PO Details Trigger if the Agreement PO Details record is updated.</description>
        <label>PO Details Changed</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Asset Line Items (Physical Asset)</relationshipLabel>
        <relationshipName>Asset_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_relatedlist_agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last related Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items (Last related Agreement)</relationshipLabel>
        <relationshipName>Asset_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>PONumberMachines__c</fullName>
        <description>This indicates the PO number for machine orders.</description>
        <label>PO Number (Machines)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PONumberRequiredMachines__c</fullName>
        <description>This indicates whether a PO Number is required for machine orders.</description>
        <label>PO Number Required (Machines)?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberRequiredServices__c</fullName>
        <label>PO Number Required (Services)?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberServices__c</fullName>
        <description>This indicates the PO number for machine services.</description>
        <label>PO Number (Services)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PONumberTypeMachines__c</fullName>
        <description>This indicates whether a PO Number for machine orders is fixed or variable.</description>
        <label>PO Number Type (Machines)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberTypeServices__c</fullName>
        <description>This indicates whether a PO Number for machine servies is fixed or variable.</description>
        <label>PO Number Type (Services)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <label>Machine</label>
    </recordTypes>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <label>Option</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>APTS_AgreementPODetails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AgreementPODetails</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_AgreementPODetailsTriggerHandler.cls
/*******************************************************************************************
Name            : APTS_AgreementPODetailsTriggerHandler
Created By      : Shanmuga Prasath
Created Date    : 08/06/2018
Description     : Handler class of Agreement_PO_Details trigger 'APTS_AgreementPODetailsTrigger'.
Version history : 
*********************************************************************************************/
public with sharing class APTS_AgreementPODetailsTriggerHandler implements ITriggerHandler{
    
    /* Check custom setting for agreement trigger activation. */
    public Boolean isDisabled(){
        try{
            return TriggerSettings__c.getInstance().APTS_AgreementPODetails__c == true ? false : true;
        }catch(exception ex){APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'Apex', ex.getStackTraceString() , 'Agreement PO Details', null, 'CLM', false, false, null, true);return true;}
    }
    
    /* After agreement is updated. */
    public void afterUpdate(List<SObject> newList, Map<Id, SObject> mapPOAgreements, List<SObject> oldList, Map<Id, SObject> mapOldPOAgreements){
        /*try{
            Map<Id, Apttus_Config2__AssetLineItem__c> phyAssetIdToALIMap = new Map<Id, Apttus_Config2__AssetLineItem__c>();
            Map<Id, APTS_Agreement_PO_Details__c> agrIdToPODetailsMap = new Map<Id, APTS_Agreement_PO_Details__c>();
            List<PhysicalAsset__c> physicalAssetUpdateList = new List<PhysicalAsset__c>();
            Map<Id, APTS_Agreement_PO_Details__c> oldRecMap = (Map<Id, APTS_Agreement_PO_Details__c>) mapOldPOAgreements;
            Map<Id, PhysicalAsset__c> physicalAssetMap = new Map<Id, PhysicalAsset__c>();
            
            for(APTS_Agreement_PO_Details__c agreementPODetails : (List<APTS_Agreement_PO_Details__c>)newList){
                if(agreementPODetails.APTS_PO_Number_Required__c != oldRecMap.get(agreementPODetails.Id).APTS_PO_Number_Required__c || agreementPODetails.APTS_PO_Number_Type__c != oldRecMap.get(agreementPODetails.Id).APTS_PO_Number_Type__c || agreementPODetails.APTS_PO_Number__c != oldRecMap.get(agreementPODetails.Id).APTS_PO_Number__c){
                    agrIdToPODetailsMap.put(agreementPODetails.APTS_Agreement__c, agreementPODetails);
                }
            }
            
            if(agrIdToPODetailsMap.size() > 0){
                // PI fix # 190262 
                for(Apttus_Config2__AssetLineItem__c aLI : [SELECT Id, Name, APTS_Physical_Asset__c, Apttus_CMConfig__AgreementId__c FROM Apttus_Config2__AssetLineItem__c WHERE Apttus_CMConfig__AgreementId__c IN: agrIdToPODetailsMap.keySet() AND APTS_Physical_Asset__c != null]){
                    phyAssetIdToALIMap.put(aLI.APTS_Physical_Asset__c, aLI);
                }
                // PI fix # 190262 
                for(PhysicalAsset__c physicalAsset : [SELECT Id, RecordTypeId, PONumberMachines__c, PONumberRequiredMachines__c, PONumberTypeMachines__c, PONumberServices__c, PONumberRequiredServices__c, PONumberTypeServices__c FROM PhysicalAsset__c WHERE Id IN: phyAssetIdToALIMap.keySet()]){
                    APTS_Agreement_PO_Details__c poDetails = agrIdToPODetailsMap.get(phyAssetIdToALIMap.get(physicalAsset.Id).Apttus_CMConfig__AgreementId__c);
                   if(poDetails == null)
                   {
                     podetails = agrIdToPODetailsMap.get(phyAssetIdToALIMap.get(physicalAsset.Id).APTS_relatedlist_agreement__c);
                   }
                    if(physicalAsset.RecordTypeId != null && physicalAsset.RecordTypeId == Schema.SObjectType.PhysicalAsset__c.getRecordTypeInfosByName().get('Machine').getRecordTypeId()){
                        if(poDetails.APTS_PO_Number__c != null){
                            physicalAsset.PONumberMachines__c = poDetails.APTS_PO_Number__c;
                        }
                        if(poDetails.APTS_PO_Number_Required__c != null){
                            physicalAsset.PONumberRequiredMachines__c = poDetails.APTS_PO_Number_Required__c;
                        }
                        if( poDetails.APTS_PO_Number_Type__c != null){
                            physicalAsset.PONumberTypeMachines__c = poDetails.APTS_PO_Number_Type__c;
                        }
                        physicalAssetUpdateList.add(physicalAsset);
                    }else if(physicalAsset.RecordTypeId != null && physicalAsset.RecordTypeId == Schema.SObjectType.PhysicalAsset__c.getRecordTypeInfosByName().get('Option').getRecordTypeId()){
                        if(poDetails.APTS_PO_Number__c != null){
                            physicalAsset.PONumberServices__c = poDetails.APTS_PO_Number__c;
                        }
                        if(poDetails.APTS_PO_Number_Required__c != null){
                            physicalAsset.PONumberRequiredServices__c = poDetails.APTS_PO_Number_Required__c;
                        }
                        if( poDetails.APTS_PO_Number_Type__c != null){
                            physicalAsset.PONumberTypeServices__c = poDetails.APTS_PO_Number_Type__c;
                        }
                        physicalAssetUpdateList.add(physicalAsset);
                    }
                }
                
                Database.Update(physicalAssetUpdateList, false);
            }
        }
        catch(Exception ex){APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'APEX', ex.getStackTraceString() ,'Agreement PO Details', null,'CLM',false,false, null, true);} */
        
        //try
        {
            Map<ID, Apttus__APTS_Agreement__c> agreementsToUpdateMap = new Map<ID, Apttus__APTS_Agreement__c>();
            for(APTS_Agreement_PO_Details__c agreementPODetailsSO : (List<APTS_Agreement_PO_Details__c>)newList)
            {
                if(agreementPODetailsSO.APTS_Agreement__c != null)
                {
                    agreementsToUpdateMap.put(agreementPODetailsSO.APTS_Agreement__c, new Apttus__APTS_Agreement__c(ID = agreementPODetailsSO.APTS_Agreement__c, APTS_PO_Details_Changed__c = true));
                }    
            }
            if(agreementsToUpdateMap.size() > 0)
            {
                update agreementsToUpdateMap.values();
            }
        }
        //catch(Exception ex)
        {
        //    APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'APEX', ex.getStackTraceString()+' Message:'+ex.getMessage() ,'Agreement PO Details', null,'CLM',false,false, null, true);
        }
    }

    /* Before inserting agreement. */
    public void beforeInsert(List<SObject> newItems){}

    /* Before record updation. */
    public void beforeUpdate(List<SObject> newList, Map<Id, SObject> newItems,
    List<SObject> oldList, Map<Id, SObject> oldItems){}

    /* Before deleting agreement records. */
    public void beforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){}

    /* After inserting agreement records. */
    public void afterInsert(List<SObject> newList, Map<Id, SObject> newItems){}

    /* After deleting agreement records. */
    public void afterDelete(List<SObject> oldList, Map<Id, SObject> oldItems){}

     /* After undeleting agreement records. */
    public void afterUndelete(List<SObject> newList, Map<Id, SObject> newItems){}
}