src/objects/APTS_RSO_batch_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configurations used in RSO batch</description>
    <fields>
        <fullName>APTS_Initial_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check will determine if the batch is run for the first time, so all PLI records will be queried</description>
        <label>Initial Load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_RSO_Routesales_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the RSO Routesales Batch should be executed on RSO Product Catalog Batch finish</description>
        <label>RSO Routesales Batch</label>
        <type>Checkbox</type>
    </fields>
    <label>RSO batch settings</label>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>APTS_PriceList_Type__c</fullName>
        <description>This will hold price list type which will be used when assigning default Price List. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <inlineHelpText>This indicates the type of the Price List.</inlineHelpText>
        <label>Price List Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Routesales</fullName>
                </value>
                <value>
                    <fullName>CSP</fullName>
                    <label>Customer Specific Pricelist</label>
                </value>
                <value>
                    <fullName>Segment Specific Pricelist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the price list is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <label>General</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>Apttus_Config2__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the price list item is active. Inactive price list items are ignored.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <description>ID of the price list associated with the product</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the price list</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_RSOProductCatalogBatch.cls
/*************************************************************
@Name: APTS_RSOProductCatalogBatch
@Author: Raul Orozco
@CreateDate: 17-05-2018
@Description: RSO Product Catalog batch. 
@UsedBy: APTS_RSOProductCatalogSch
******************************************************************/
global class APTS_RSOProductCatalogBatch implements Database.Batchable<sObject> {
	
	String query;
	
	global APTS_RSOProductCatalogBatch(){
		//Get configuration to determine if the batch is running for initial load mode
		APTS_RSO_batch_settings__c mcs = APTS_RSO_batch_settings__c.getValues('General');
      	
      	Boolean initialLoad = (mcs != null && mcs.APTS_Initial_Load__c != null) ? mcs.APTS_Initial_Load__c : false;

      	if(initialLoad){
      		query = ' SELECT Id, ' +
				'Apttus_Config2__ProductId__c, ' + 
				'Apttus_Config2__PriceListId__c, ' + 
				'Apttus_Config2__ProductId__r.ProductCode, ' +
				'Apttus_Config2__PriceListId__r.APTS_Region__c, ' +
				'Apttus_Config2__PriceListId__r.APTS_PriceList_Type__c ' +
				'FROM Apttus_Config2__PriceListItem__c ' +
				'WHERE Apttus_Config2__PriceListId__r.APTS_PriceList_Type__c IN (\'Routesales\',\'Direct\') ' +
				'AND Apttus_Config2__Active__c = True  ';
  		}else{
  			query = ' SELECT Id, ' +
				'Apttus_Config2__ProductId__c, ' + 
				'Apttus_Config2__PriceListId__c, ' + 
				'Apttus_Config2__ProductId__r.ProductCode, ' +
				'Apttus_Config2__PriceListId__r.APTS_Region__c, ' +
				'Apttus_Config2__PriceListId__r.APTS_PriceList_Type__c ' +
				'FROM Apttus_Config2__PriceListItem__c ' +
				'WHERE Systemmodstamp >= LAST_N_DAYS:1 ' +
				'AND Apttus_Config2__PriceListId__r.APTS_PriceList_Type__c IN (\'Routesales\',\'Direct\') ' +
				'AND Apttus_Config2__Active__c = True ';
  		}
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Apttus_Config2__PriceListItem__c> lstPLI) {
		APTS_RSOProductCatalogBatchHelper.createRSOProductCatalogRecords(lstPLI);
	}
	
	global void finish(Database.BatchableContext BC) {
		//Get configuration to determine if the batch Routesales should be executed
		APTS_RSO_batch_settings__c mcsFinish = APTS_RSO_batch_settings__c.getValues('General');
      	
      	Boolean executeBatch = (mcsFinish != null && mcsFinish.APTS_RSO_Routesales_Batch__c != null) ? mcsFinish.APTS_RSO_Routesales_Batch__c : false;

		if(executeBatch){
			APTS_RSOPCRoutesalesBatch obj = new APTS_RSOPCRoutesalesBatch();
    		Database.executeBatch(obj);
		}
	}
	
}