src/objects/APTS_Recurring_Batch_Countries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APTS_Recurring_Batch_Countries</label>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Header_SAP_ID__c</fullName>
        <description>Denotes the SAP ID associated with Order</description>
        <externalId>true</externalId>
        <label>Order Header SAP ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Order_Sub_Type__c</fullName>
        <description>This is the Order Sub Type</description>
        <label>Order Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Order_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Standard Return</fullName>
                </value>
                <value>
                    <fullName>Unplanned Return</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>De-installation</fullName>
                </value>
                <value>
                    <fullName>Internal Movement</fullName>
                </value>
                <value>
                    <fullName>External Movement With Contract Change</fullName>
                </value>
                <value>
                    <fullName>External Movement Without Contract Change</fullName>
                </value>
                <value>
                    <fullName>Technical Swap</fullName>
                </value>
                <value>
                    <fullName>Commercial Swap</fullName>
                </value>
                <value>
                    <fullName>Route Sales and Operating</fullName>
                </value>
                <value>
                    <fullName>Subscription Order</fullName>
                </value>
                <value>
                    <fullName>Billing Schedule</fullName>
                </value>
                <value>
                    <fullName>Digital Order</fullName>
                </value>
                <value>
                    <fullName>Conversion Order</fullName>
                </value>
                <value>
                    <fullName>Stock Count</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Agreement Changes</fullName>
                </value>
                <value>
                    <fullName>Indexation</fullName>
                </value>
                <value>
                    <fullName>Consignment Issue for FSD</fullName>
                </value>
                <value>
                    <fullName>Consignment Fillup for FSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Machine Order</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Debit Memo</fullName>
                </value>
                <value>
                    <fullName>Admin Order</fullName>
                </value>
                <value>
                    <fullName>Route Sales Order</fullName>
                </value>
                <value>
                    <fullName>Operating Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_SAP_OrderType__c</fullName>
        <description>This is the SAP OrderType</description>
        <label>SAP OrderType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>XA01</fullName>
                </value>
                <value>
                    <fullName>XA02</fullName>
                </value>
                <value>
                    <fullName>XA13</fullName>
                </value>
                <value>
                    <fullName>XA14</fullName>
                </value>
                <value>
                    <fullName>XB01</fullName>
                </value>
                <value>
                    <fullName>XB02</fullName>
                </value>
                <value>
                    <fullName>XB13</fullName>
                </value>
                <value>
                    <fullName>XL01</fullName>
                </value>
                <value>
                    <fullName>XC01</fullName>
                </value>
                <value>
                    <fullName>XD01</fullName>
                </value>
                <value>
                    <fullName>XA23</fullName>
                </value>
                <value>
                    <fullName>XB05</fullName>
                </value>
                <value>
                    <fullName>XB03</fullName>
                </value>
                <value>
                    <fullName>XB04</fullName>
                </value>
                <value>
                    <fullName>XA04</fullName>
                </value>
                <value>
                    <fullName>XA07</fullName>
                </value>
                <value>
                    <fullName>XA03</fullName>
                </value>
                <value>
                    <fullName>XD09</fullName>
                </value>
                <value>
                    <fullName>XD12</fullName>
                </value>
                <value>
                    <fullName>XA06</fullName>
                </value>
                <value>
                    <fullName>XC09</fullName>
                </value>
                <value>
                    <fullName>XB23</fullName>
                </value>
                <value>
                    <fullName>XD02</fullName>
                </value>
                <value>
                    <fullName>Fixed Term</fullName>
                    <isActive>false</isActive>
                    <label>Fixed Term</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/APTS_IntegrationLogForBillingBatch.cls
/**********************************************************************************
 * @Author: Balashanthi A
 * @Description: Handles the integreation Log entry for the inserted Admin Orders
 * @Created Date: February 15, 2019
 * @History:
 **********************************************************************************
 *      Name            Version                 Date            Description
 **********************************************************************************
 *      Balashanthi     v100                     15.02.2019        Created
 * V101: Ankit Joshi - 11/4/2019 - To run Recurring Batch for all countires
 * V102: Balashanthi - 08/5/2019 - To run Recurring Batch for all countires 
 **********************************************************************************/
global class APTS_IntegrationLogForBillingBatch implements Database.Batchable<sObject> {
	Set<Id> adminOrderSubmissionToSAP = new Set<Id>();
	public String salesOrgToBeProcessedNext = '';
	
	global APTS_IntegrationLogForBillingBatch(Set<Id> orderIdSet, String salesOrgToBeProcessedNext){
		adminOrderSubmissionToSAP.addAll(orderIdSet);
		this.salesOrgToBeProcessedNext = salesOrgToBeProcessedNext;
		//system.debug('orderIdSet==>'+salesOrgToBeProcessedNext);
	}
	/** Method Name : start
    * Description : start method of Batch class
    **/
	global Database.QueryLocator start(Database.BatchableContext batchContext) {
		
		String query  = 'SELECT Id FROM Apttus_Config2__Order__c';
        query += ' WHERE APTS_Order_Type__c = \'Admin Order\' AND APTS_Order_Sub_Type__c = \'Billing Schedule\'AND CreatedDate >= TODAY';
        query += APTS_BIRUtils.EMPTY_STRING+' AND (APTS_SAP_OrderType__c =  \'XD09\' OR APTS_SAP_OrderType__c =  \'XD12\') AND APTS_Order_Header_SAP_ID__c = null';
        //system.debug('query==>'+query);
		return Database.getQueryLocator(query);
	}
	/** Method Name : execute
    * Description : execute method of Batch class
    **/
	global void execute(Database.BatchableContext BC, List<Apttus_Config2__Order__c> adminOrderInsertedRecords){
		List<Integration_Log__c> listIntegrationLog = new List<Integration_Log__c>();
		try{
			if(!adminOrderInsertedRecords.isEmpty()
				&& !adminOrderSubmissionToSAP.isEmpty()){
				for(Apttus_Config2__Order__c oOrder : adminOrderInsertedRecords){
					if(adminOrderSubmissionToSAP.contains(oOrder.Id)){
						Integration_Log__c oIntegrationLog = new Integration_Log__c();
			            oIntegrationLog.Object_Id__c = oOrder.Id;
			            oIntegrationLog.Object__c = APTS_BIRUtils.ORDEROBJECTNAME; 
			            oIntegrationLog.Integration_Status__c = INT_Constants.INITIAL;
			            oIntegrationLog.Order__c = oOrder.Id;
			            listIntegrationLog.add(oIntegrationLog);
					}
	       		}
			}
			if(!listIntegrationLog.isEmpty()){
           		Database.SaveResult[] srList = Database.insert(listIntegrationLog,false);
            	APTS_BIRUtils.logError(null,srList,null,null,APTS_BIRUtils.BATCH,APTS_BIRUtils.SUBMITORDER,APTS_BIRUtils.EMPTY_STRING,false,false,APTS_BIRUtils.EMPTY_STRING,false);
        	}
		}catch(Exception e){APTS_BIRUtils.logError(null,null,null,e,APTS_BIRUtils.BATCH,APTS_BIRUtils.SUBMITORDER,APTS_BIRUtils.EMPTY_STRING,false,false,APTS_BIRUtils.EMPTY_STRING,true);} 
	}
 	/** Method Name : finish
    * Description : finish method of Batch class
    **/
	global void finish(Database.BatchableContext BC){
		//v101 start
        try{
            /*String salesOrg = '';
            Map<String, APTS_Recurring_Batch_Countries__c> countryMap = APTS_Recurring_Batch_Countries__c.getAll();
            Map<Integer, APTS_Recurring_Batch_Countries__c> countrySeqMap = new Map<Integer, APTS_Recurring_Batch_Countries__c>();
            for(APTS_Recurring_Batch_Countries__c rbcRec : countryMap.values()){
                countrySeqMap.put(Integer.valueOf(rbcRec.APTS_Sequence__c), rbcRec);
            }

            APTS_Recurring_Batch_Countries__c rbcRec;
            for(Integer i=1 ; i<=countrySeqMap.size() ; i++){    
                rbcRec = countrySeqMap.get(i);
                if(!(rbcRec.APTS_Processed__c)){
                    if(countrySeqMap.size() >= (i)){
                        salesOrg = countrySeqMap.get(i).APTS_Sales_Org__c;
                        break;
                    }
                }
            }*/
            //system.debug('salesOrg @ Integration log Table ===>'+salesOrgToBeProcessedNext);
            APTS_RecurringBillingScheduleBatchHelper.callRecurringBatchIfReqd(salesOrgToBeProcessedNext);

        }catch(Exception e){APTS_BIRUtils.logError(null,null,null,e,APTS_BIRUtils.BATCH,APTS_BIRUtils.CREATEADMINORDERFINISH,APTS_BIRUtils.EMPTY_STRING,false,false,APTS_BIRUtils.EMPTY_STRING,true);}
        //v101 end
	}
}