src/objects/APTS_Order_Interface_Log__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Message__c</fullName>
        <description>A field to store JSON received from External System</description>
        <inlineHelpText>A field to store JSON received from External System</inlineHelpText>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Parent_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Self lookup to store external JSON data in multiple record in case JSON data exceed storing limits..</inlineHelpText>
        <label>Parent Log</label>
        <referenceTo>APTS_Order_Interface_Log__c</referenceTo>
        <relationshipName>EPI_Order_Interface_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Sequence__c</fullName>
        <inlineHelpText>Sequence of record in case of multiple records</inlineHelpText>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_SourceOrderNumber__c</fullName>
        <label>SourceOrderNumber</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Interface Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>To be removed</fullName>
                </value>
                <value>
                    <fullName>Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ConfigCustomClasses__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to register.custom classes that Implement Global interfaces exposed by Apttus for customization.</description>
    <label>Config Custom Classes</label>
</CustomObject>

src/objects/Apttus_Config2__ConfigLineItemCustomFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the list of field API names from the line item object used in pricing callbacks</description>
    <fields>
        <fullName>Apttus_Config2__CustomFieldNames__c</fullName>
        <description>Enter the list of field API names from the line item object used in pricing callbacks. Each field may be separated by a comma or a new line.</description>
        <inlineHelpText>Enter the list of field API names from the line item object used in pricing callbacks. Each field may be separated by a comma or a new line.</inlineHelpText>
        <label>Custom Field Names</label>
        <type>TextArea</type>
    </fields>
    <label>Config LineItem Custom Fields</label>
</CustomObject>

src/objects/Apttus_Config2__PaymentTerm__c.object
<CustomObject>
    <description>Represents a payment term associated with a quote, order or an agreement</description>
    <fields>
        <fullName>APTS_Ext_ID__c</fullName>
        <externalId>true</externalId>
        <label>SAP ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The payment term display sequence</description>
        <inlineHelpText>The payment term display sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>APTS_Ext_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS Ext ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>APTS_Ext_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS Ext ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>To be removed</fullName>
                </value>
                <value>
                    <fullName>Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The charge type sequence</description>
        <inlineHelpText>The charge type sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Ext_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS Ext ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>To be removed</fullName>
                </value>
                <value>
                    <fullName>Adjusted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>APTS_OrderFulfillmentLineItemTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable or disable OrderFulfillmentLineItem Trigger</description>
        <inlineHelpText>Enable or disable OrderFulfillmentLineItem Trigger</inlineHelpText>
        <label>OrderFulfillmentLineItemTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_OrderLineItemTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order line item trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Order_Adjustment_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Adjustment Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Order_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AccountTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreement Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaskTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TaskTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_DigitalOrderUtilsTest.cls
/**
* Class Name   : APTS_DigitalOrderUtils_Test
* Description  : Test class for APTS_DigitalOrderUtils
* Author       : Hariharan
* Date Created : 04/18/2018
**/
@isTest
private class APTS_DigitalOrderUtilsTest {

    @testSetup static void setupTestData() {
        User oTestUser = APTS_TestFacade.createTestUser();

        TriggerSettings__c oTriggerSettings = new TriggerSettings__c(AccountTrigger__c = false, Agreement__c = false, APTS_Order_Trigger__c = false, APTS_OrderLineItemTrigger__c = false, APTS_OrderFulfillmentLineItemTrigger__c = false, APTS_Order_Adjustment_Trigger__c = false, SetupOwnerId = oTestUser.ProfileId);
        Database.insert(oTriggerSettings);

        Apttus_Config2__ConfigLineItemCustomFields__c oConfigLineItemCustomFields = new Apttus_Config2__ConfigLineItemCustomFields__c();
        oConfigLineItemCustomFields.Name = 'System Properties';
        oConfigLineItemCustomFields.Apttus_Config2__CustomFieldNames__c = 'Apttus_Config2__HasIncentives__c';
        insert oConfigLineItemCustomFields;

        String acctName = 'Test' + string.valueOf(Math.random());
        Account testAccount = APTS_TestDataFactory.createAccount(acctName);
        insert testAccount;

        Group queue = new Group();
        queue.name = System.Label.APTS_CS_Queue;
        queue.Type = 'Queue';
        insert queue;

        Contact testContact = APTS_TestDataFactory.createContact(testAccount, '+912121212121');
        Database.insert(testContact, false);

        Apttus_Config2__PriceList__c testPriceList = APTS_TestDataFactory.createPriceList('testPriceList');
        Database.insert(testPriceList, false);

        Product2 testProduct = APTS_TestDataFactory.createProduct('TestCoffee', 'pc123', 'Coffee', 'Standalone', true, false);
        Database.Insert(testProduct, false);

        Apttus_Config2__PriceListItem__c oPriceListItemStandalone = APTS_TestDataFactory.createPriceListItem(testPriceList.Id, testProduct.Id);
        Database.Insert(oPriceListItemStandalone, false);

        Apttus__APTS_Agreement__c oAgr = APTS_TestDataFactory.createAgreement(testContact.Id, testPriceList.Id, testAccount.Id, 'Standard Deal');
        oAgr.Apttus__Status__c = 'Activated';
        oAgr.Apttus__Contract_End_Date__c = System.today().addYears(1);
        Database.insert(oAgr, FALSE);

        APTS_DOEPIReqWrapper oDOEPIReqWrapper = new APTS_DOEPIReqWrapper();
        oDOEPIReqWrapper.SourceOrderNumber = 'sn1232';
        oDOEPIReqWrapper.SalesforceAccountID = testAccount.Id;
        oDOEPIReqWrapper.SalesforceContactID = testContact.Id;
        oDOEPIReqWrapper.SalesforcePriceListID = testPriceList.Id;
        oDOEPIReqWrapper.SalesOrganization = 'SAP_0111';
        oDOEPIReqWrapper.AdjustmentType = 'Test Adjustment Type';
        /*oDOEPIReqWrapper.BillToCity = 'Test City';
        oDOEPIReqWrapper.BillToCompanyName = 'Test Company Name';
        oDOEPIReqWrapper.BillToContactName = 'Contact Name';
        oDOEPIReqWrapper.BillToCountry = 'Test Country';
        oDOEPIReqWrapper.BillToEmail = 'Test Email';
        oDOEPIReqWrapper.BillToOverride = 'No';
        oDOEPIReqWrapper.BillToPostalCode = '123545';
        oDOEPIReqWrapper.BillToStreet = 'Test Street'; */
        oDOEPIReqWrapper.CurrencyCode = 'EUR';
        oDOEPIReqWrapper.OneTimeContactName = 'Test OneTime Contact';
        oDOEPIReqWrapper.OneTimeCustomer = 'Yes';
        oDOEPIReqWrapper.OneTimeEmail = 'neshah@apttus.com';
        oDOEPIReqWrapper.ShipToCompanyName = 'Test ShipToCompanyName';
        oDOEPIReqWrapper.ShipToCountry = 'Test ShipToCountry';
        oDOEPIReqWrapper.ShipToCity = 'Test ShipToCity';
        oDOEPIReqWrapper.ShipToPostalCode = 'Test ShipToPostalCode';
        oDOEPIReqWrapper.ShipToStreetOnly = 'Test ShipToStreetOnly';
        oDOEPIReqWrapper.ShipToHouseNumber = 'Test ShipToHouseNumber';
        oDOEPIReqWrapper.ShipToHouseNumberSupplement = 'Test ShipToHouseNumberSupplement';
        oDOEPIReqWrapper.BillToContactName = 'Test BillToContactName';
        oDOEPIReqWrapper.BillToEmail = 'Test BillToEmail';
        oDOEPIReqWrapper.BillToCompanyName = 'Test BillToCompanyName';
        oDOEPIReqWrapper.BillToCountry = 'Test BillToCountry';
        oDOEPIReqWrapper.BillToCity = 'Test BillToCity';
        oDOEPIReqWrapper.BillToPostalCode = 'Test BillToPostalCode';
        oDOEPIReqWrapper.BillToStreetOnly = 'Test BillToStreetOnly';
        oDOEPIReqWrapper.BillToHouseNumber = 'Test BillToHouseNumber';
        oDOEPIReqWrapper.BillToHouseNumberSupplement = 'Test BillToHouseNumberSupplement';
        oDOEPIReqWrapper.ShipToOverride = 'Yes';
        oDOEPIReqWrapper.BillToOverride = 'Yes';
        oDOEPIReqWrapper.RequestDeliveryDate = dateTime.Now();
        oDOEPIReqWrapper.Source = 'Digital';
        oDOEPIReqWrapper.PrepaidFlag = 'Yes';
        oDOEPIReqWrapper.PaymentReferenceNumber = 'test Payment reference Number';
        oDOEPIReqWrapper.PaymentMethod = 'Test Payment Method';
        oDOEPIReqWrapper.PONumber = 'test PO';
        oDOEPIReqWrapper.ReferenceNumber = 'Test Reference Number';
        oDOEPIReqWrapper.AdjustmentType = 'Test Adjustment';
        oDOEPIReqWrapper.TotalOrderAmount = 4;
        oDOEPIReqWrapper.TotalShippingCost = 5;
        oDOEPIReqWrapper.TotalOrderAdjustment = 5;
        oDOEPIReqWrapper.TotalAdjustment = 5;
        oDOEPIReqWrapper.TotalAdjustedPrice = 5;
        oDOEPIReqWrapper.TotalTaxAmount = 8;
        oDOEPIReqWrapper.TotalVATAmount = 8;

        oDOEPIReqWrapper.OrderLineItems = new List<APTS_DOEPIReqWrapper.EPIOrderLI>();
        APTS_DOEPIReqWrapper.EPIOrderLI orderLineItem = new APTS_DOEPIReqWrapper.EPIOrderLI();
        orderLineItem.ProductCode = testProduct.productcode;
        orderLineItem.Quantity = 1;
        orderLineItem.ConfigurationType = 'Standalone';
        orderLineItem.SourceLineNumber = '1';
        orderLineItem.SellingUnitofMeasure = 'SAP_PCE';
        orderLineItem.ProductId = testProduct.id;
        orderLineItem.ReasonCode = 'Test Reason';
        orderLineItem.ParentBundleNumber = 1;
        orderLineItem.LineItemListPrice = 8;
        orderLineItem.LineItemAdjustmentAmount = 8;
        orderLineItem.LineItemAdustedPrice = 8;
        orderLineItem.LineItemTaxAmount = 8;
        orderLineItem.LineItemVATAmount = 8;

        orderLineItem.Adjustments = new List<APTS_DOEPIReqWrapper.EPIAdjustmentLI>();
        APTS_DOEPIReqWrapper.EPIAdjustmentLI oAdjust = new APTS_DOEPIReqWrapper.EPIAdjustmentLI();
        oAdjust.IncentiveAmount = 10;
        oAdjust.SubType = 'ZP08';
        orderLineItem.Adjustments.add(oAdjust);
        oDOEPIReqWrapper.OrderLineItems.add(orderLineItem);

        APTS_DOEPIReqWrapper.EPIOrderLI orderLineItem1 = new APTS_DOEPIReqWrapper.EPIOrderLI();
        orderLineItem1.ProductCode = testProduct.productcode;
        orderLineItem1.Quantity = 1;
        orderLineItem1.ConfigurationType = 'Standalone';
        orderLineItem1.SourceLineNumber = '2';
        orderLineItem1.SellingUnitofMeasure = 'SAP_PCE';
        orderLineItem1.ProductId = testProduct.id;
        orderLineItem1.ReasonCode = 'Test Reason';
        orderLineItem1.ParentBundleNumber = 1;
        orderLineItem1.LineItemListPrice = 8;
        orderLineItem1.LineItemAdjustmentAmount = 8;
        orderLineItem1.LineItemAdustedPrice = 8;
        orderLineItem1.LineItemTaxAmount = 8;
        orderLineItem1.LineItemVATAmount = 8;

        orderLineItem1.Adjustments = new List<APTS_DOEPIReqWrapper.EPIAdjustmentLI>();
        orderLineItem1.Adjustments.add(oAdjust);
        oDOEPIReqWrapper.OrderLineItems.add(orderLineItem1);

        String sJSONClass = JSON.serialize(oDOEPIReqWrapper);

        APTS_Order_Interface_Log__c oLog = new APTS_Order_Interface_Log__c();
        oLog.APTS_Message__c = sJSONClass;
        oLog.APTS_SourceOrderNumber__c = 'sn1232';
        oLog.APTS_Status__c = 'New';
        oLog.APTS_Sequence__c = 1;
        insert oLog;

        Apttus_Config2__PaymentTerm__c oTerm = new Apttus_Config2__PaymentTerm__c();
        oTerm.APTS_Ext_ID__c = 'SAP_ZOLP';
        oTerm.Name = 'Default';
        oTerm.Apttus_Config2__Sequence__c = 1;
        insert oTerm;
    }

    @isTest static void testOrder() {
        Group queue = [SELECT Id FROM Group LIMIT 1];
        User oTestUser = APTS_TestFacade.getTestUser();

        //remove all Callbacks
        List<Apttus_Config2__ConfigCustomClasses__c> listConfigSetting = [SELECT id FROM Apttus_Config2__ConfigCustomClasses__c];
        if (!listConfigSetting.isEmpty()) {
            delete listConfigSetting;
        }

        //disable Order triggers
        TaskTriggerHandler.isTriggerDisabled = true;
        Id userProfileId = userinfo.getProfileId();
        List<TriggerSettings__c> triggerSettingsList = [SELECT Id, APTS_Order_Trigger__c FROM TriggerSettings__c WHERE SetupOwnerId = :userProfileId LIMIT 1];
        if (!triggerSettingsList.isEmpty()) {
            triggerSettingsList[0].APTS_Order_Trigger__c = false;
            triggerSettingsList[0].APTS_OrderLineItemTrigger__c = FALSE;
            triggerSettingsList[0].TaskTrigger__c = FALSE;
            Database.update(triggerSettingsList);
        }

        List<APTS_Order_Interface_Log__c> listLog = [SELECT Id, APTS_Message__c, APTS_SourceOrderNumber__c, APTS_Status__c FROM APTS_Order_Interface_Log__c WHERE APTS_Parent_Log__c = NULL LIMIT 1];
        System.assertNotEquals(true, listLog.isEmpty());

        String sJSONStr = listLog != null ? listLog[0].APTS_Message__c : null;
        System.assertNotEquals(TRUE, String.isBlank(sJSONStr));

        APTS_DOEPIReqWrapper objWrapper = (APTS_DOEPIReqWrapper)JSON.deserialize(sJSONStr, APTS_DOEPIReqWrapper.class);
        System.assertNotEquals(null, objWrapper);
        System.assertNotEquals(null, objWrapper.OrderLineItems);
        System.assertNotEquals(true, objWrapper.OrderLineItems.isEmpty());

        Test.startTest();

        String sErrmsg = APTS_DigitalOrderUtils.validateData(objWrapper);
        System.assertEquals(TRUE, String.isBlank(sErrmsg));

        Set<Id> setSoldToID = new Set<Id> {};
        setSoldToID.add(objWrapper.SalesforceAccountID);

        //accounts
        Map<Id, Account> mapSoldTo = APTS_DigitalOrderUtils.getAccounts(setSoldToID);
        System.assertNotEquals(null, mapSoldTo);
        System.assertNotEquals(true, mapSoldTo.isEmpty());

        //contacts
        Map<Id, Contact> mapContacts = APTS_DigitalOrderUtils.getContacts(setSoldToID);
        System.assertNotEquals(null, mapContacts);
        System.assertNotEquals(true, mapContacts.isEmpty());

        //payment term
        Apttus_Config2__PaymentTerm__c oPaymentTerm = APTS_DigitalOrderUtils.getDefaultPaymentTerm();
        System.assertNotEquals(null, oPaymentTerm);

        Set<String> setProdCodes = new Set<String>();
        setProdCodes.add(objWrapper.OrderLineItems[0].ProductCode);
        Map<String, Product2> mapProducts = APTS_DigitalOrderUtils.getProductCodes(setProdCodes);
        System.assertNotEquals(null, mapProducts);
        System.assertNotEquals(true, mapProducts.isEmpty());

        Map<String, Product2> mapprod = APTS_DigitalOrderUtils.getProductCodes(new Set<String> {'pc123'});
        System.assertEquals(false, mapprod.isEmpty());

        Test.stopTest();
    }

    @isTest static void testValidation() {
        Group queue = [SELECT Id FROM Group LIMIT 1];
        User oTestUser = APTS_TestFacade.getTestUser();

        Test.startTest();
        APTS_DOEPIReqWrapper objWrapper;
        String sErrmsg = APTS_DigitalOrderUtils.validateData(objWrapper);
        System.assertEquals(TRUE, String.isNotBlank(sErrmsg));
        System.assertEquals(TRUE, sErrmsg.containsIgnoreCase('JSON cannot be NULL'));

        objWrapper = new APTS_DOEPIReqWrapper();
        sErrmsg = APTS_DigitalOrderUtils.validateData(objWrapper);
        System.assertEquals(TRUE, String.isNotBlank(sErrmsg));
        System.assertEquals(TRUE, sErrmsg.containsIgnoreCase('Source cannot be blank.'));

        objWrapper.Source = 'Digital';
        objWrapper.OrderLineItems = new List<APTS_DOEPIReqWrapper.EPIOrderLI>();
        sErrmsg = APTS_DigitalOrderUtils.validateData(objWrapper);
        System.assertEquals(TRUE, String.isNotBlank(sErrmsg));


        Test.stopTest();
    }

    @isTest static void testOrderMethod() {
        Group queue = [SELECT Id FROM Group LIMIT 1];
        system.assertNotEquals(null, queue);

        List<APTS_Order_Interface_Log__c> listEPILog = [SELECT Id, APTS_Message__c, APTS_SourceOrderNumber__c, APTS_Status__c FROM APTS_Order_Interface_Log__c WHERE APTS_Parent_Log__c = NULL];
        APTS_DigitalOrderBatchHelper.processdigitalorders(queue, listEPILog);
    }
}