src/objects/APTS_Credit_Batch_Countries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>APTS_Credit_Batch_Countries</label>
</CustomObject>

src/classes/APTS_CreditBillingBatchScheduler.cls
/**
* Class Name : APTS_CreditBillingBatchScheduler 
* Description : Apex Class to schedule APTS_CreditBillingBatchScheduler Class
* Author : Renuka (Accenture)
* Date Created : 07/08/2020
********************************************************************************************/
global without sharing class APTS_CreditBillingBatchScheduler implements Schedulable {
   global void execute(SchedulableContext sc) {
        //Get all the country values from custom setting and pass the one with Sequence=1
        String salesOrg = '';
        Map<Integer, APTS_Credit_Batch_Countries__c> countrySeqMap = new Map<Integer, APTS_Credit_Batch_Countries__c>();
        for(APTS_Credit_Batch_Countries__c bcRec : APTS_Credit_Batch_Countries__c.getAll().values()){
            countrySeqMap.put(Integer.valueOf(bcRec.APTS_Sequence__c), bcRec);
        }
        APTS_Credit_Batch_Countries__c rbcRec;
        for(Integer i=1 ; i<=countrySeqMap.size() ; i++){  
            rbcRec = countrySeqMap.get(i);
            if(!rbcRec.APTS_Processed__c && rbcRec.APTS_Sequence__c == 1){
                salesOrg = rbcRec.APTS_Sales_Org__c;
                break;
            }
        }
        APTS_CreditBillingBatch obj = new APTS_CreditBillingBatch(salesOrg);
        Database.executeBatch(obj,100);
    }
}