src/objects/APTS_MARA_MVKE_Status_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APTS_Has_PLI_Active_PLI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has PLI/Active PLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_MARA_MVKE_Addition_Removal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to check whether the combination of Cross Plant Status field code of Product Object and Sales Status field code of Sales Org Data field should be added or removed from &apos;Associated Sales Org&apos; field of Product Object. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <inlineHelpText>Field to check whether the combination of Cross Plant Status field code of Product Object and Sales Status field code of Sales Org Data field should be added or removed from &apos;Associated Sales Org&apos; field of Product Object.</inlineHelpText>
        <label>MARA/MVKE Addition/Removal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_MARA_MVKE_Field_Combination__c</fullName>
        <description>Field to store the combination of Cross Plant Status field code of Product Object and Sales Status field code of Sales Org Data field. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <inlineHelpText>Field to store the combination of Cross Plant Status field code of Product Object and Sales Status field code of Sales Org Data field.</inlineHelpText>
        <label>MARA/MVKE Field Combination</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_Visible_in_Catalogue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible in Catalogue</label>
        <type>Checkbox</type>
    </fields>
    <label>MARA MVKE Status Mapping</label>
</CustomObject>

src/objects/APTS_Sales_Org_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <formula>APTS_Product__r.APTS_Material_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Option_Group_Indicator__c</fullName>
        <formula>APTS_Product__r.APTS_Option_Group_Indicator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Option Group Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to price list item for the Sales Org</description>
        <inlineHelpText>This field is used extensively by the Pricing Batch, so please ensure we only relate a DIRECT PRICELIST to a SalesOrgData record.</inlineHelpText>
        <label>Direct Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Sales Org Datas</relationshipLabel>
        <relationshipName>Sales_Org_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Code__c</fullName>
        <label>Product Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Org Datas</relationshipLabel>
        <relationshipName>Sales_Org_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org_Data_Ext_ID__c</fullName>
        <externalId>true</externalId>
        <label>APTS Sales Org Data Ext. ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org_Data_Name__c</fullName>
        <inlineHelpText>This field MUST have the 4 digit code of the Sales Org, and this field must be populated as it’s required by the Pricing Batch</inlineHelpText>
        <label>Sales Org Data Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Selling_Unit__c</fullName>
        <label>Selling Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_LR</fullName>
                    <label>Layer</label>
                </value>
                <value>
                    <fullName>SAP_ZRE</fullName>
                    <label>Reporting</label>
                </value>
                <value>
                    <fullName>SAP_ZTU</fullName>
                    <label>Trade unit</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_ZVW</fullName>
                    <label>Vol.weight</label>
                </value>
                <value>
                    <fullName>SAP_ZZZ</fullName>
                    <label>St. UoM IB</label>
                </value>
                <value>
                    <fullName>SAP_PX1</fullName>
                    <label>HAP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PX2</fullName>
                    <label>FUP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_SMU</fullName>
                    <label>Smallest Unit</label>
                </value>
                <value>
                    <fullName>SAP_MTR</fullName>
                    <label>Meter</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_P4</fullName>
                    <label>Four Pack</label>
                </value>
                <value>
                    <fullName>SAP_DS</fullName>
                    <label>Display</label>
                </value>
                <value>
                    <fullName>None</fullName>
                    <isActive>false</isActive>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Org Data</label>
    <nameField>
        <displayFormat>SOD-{00000000}</displayFormat>
        <label>Sales Org Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Org Datas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>APTS_PriceList_Type__c</fullName>
        <description>This will hold price list type which will be used when assigning default Price List. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <inlineHelpText>This indicates the type of the Price List.</inlineHelpText>
        <label>Price List Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Routesales</fullName>
                </value>
                <value>
                    <fullName>CSP</fullName>
                    <label>Customer Specific Pricelist</label>
                </value>
                <value>
                    <fullName>Segment Specific Pricelist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_SalesOrg__c</fullName>
        <inlineHelpText>This must be populated with a unique 4 digit code for sales orgs for Batches to Run</inlineHelpText>
        <label>SalesOrg</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Cross_plant_material_status__c</fullName>
        <label>Cross-plant material status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <description>SAP Material Type, Used in EPI Integration
/ZMATMAS03I/IDOC/E1MARAM/MTART</description>
        <label>Material_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Option_Group_Indicator__c</fullName>
        <label>Option Group Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Catalog__c</fullName>
        <description>Concatenated code for Category, Sub-category and sub-sub category</description>
        <label>Sales Catalog</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>SalesOrgDataTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox field to mute Sales Org Data Trigger. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <label>SalesOrgDataTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_SalesOrgDataTriggerHandler_Test.cls
/**
* Class Name : APTS_SalesOrgDataTriggerHandler_Test
* Description :  Apex Class to test APTS_SalesOrgDataTriggerHandler class
* Author : V. Shankaranarayanan
* Date Created : 15-03-2018
**/
@isTest
private class APTS_SalesOrgDataTriggerHandler_Test{


    static testMethod void testSalesOrgTrigger(){
        test.starttest();
        TriggerSettings__c settings = new TriggerSettings__c();
        settings.SalesOrgDataTrigger__c = true;
        Database.insert(settings, false);
        APTS_Transactional_UOM__c tom = new APTS_Transactional_UOM__c(name='SAP_BX');
        insert tom;
        Product2 testProduct = TestDataFactory.createProduct(1)[0];
        testProduct.ProductCode = '12345678';
        //testProduct.APTS_Material_Type__c = Label.APTS_ZCMA;
        //testProduct.APTS_Option_Group_Indicator__c='04';
        //testProduct.APTS_Sales_Catalog__c='0702';
        Database.insert(testProduct, false);

        Apttus_Config2__PriceList__c testPriceList = TestDataFactory.createPriceList(1)[0];
        testPriceList.APTS_SalesOrg__c = 'TESTORG';
        testPriceList.APTS_PriceList_Type__c='Direct';
        Database.insert(testPriceList, false);
        
        APTS_Sales_Org_Data__c testSalesOrgData = TestDataFactory.createSalesOrgData(testProduct.Id);
        testSalesOrgData.APTS_Sales_Org_Data_Ext_ID__c = '12345678|TESTORG';
        testSalesOrgData.APTS_Sales_Org_Data_Name__c = 'TESTORG';
        testSalesOrgData.APTS_Product_Code__c=testProduct.ProductCode;
        Database.insert(testSalesOrgData, false);
        //insert testSalesOrgData;
        System.debug('testSalesOrgData=====>'+testSalesOrgData); 
        APTS_Sales_Org_Data__c updatedSalesOrgData = [SELECT Id, APTS_Product__c, APTS_Price_List__c FROM APTS_Sales_Org_Data__c where id=: testSalesOrgData.id];
        System.debug('updatedSalesOrgData=====>'+updatedSalesOrgData);
        System.AssertEquals(updatedSalesOrgData.APTS_Product__c, testProduct.Id);
        System.AssertEquals(updatedSalesOrgData.APTS_Price_List__c, testPriceList.Id);
        testSalesOrgData.APTS_Selling_Unit__c = 'SAP_BX';
        Database.update(testSalesOrgData, false);
        Database.delete(testSalesOrgData, false);
        Database.undelete(testSalesOrgData, false);

        test.stoptest();
    }

    static testMethod void testSalesOrgTrigger_AssocSalesOrgCase1(){

        test.startTest();

        TriggerSettings__c settings = new TriggerSettings__c();
        settings.SalesOrgDataTrigger__c = true;
        Database.insert(settings, false);

        APTS_MARA_MVKE_Status_Mapping__c mMSM = new APTS_MARA_MVKE_Status_Mapping__c();
        mMSM.Name = 'PR|SAP_01';
        mMSM.APTS_MARA_MVKE_Field_Combination__c = 'PR|SAP_01';
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_Has_PLI_active_PLI__c = true;
        mMSM.APTS_Visible_in_Catalogue__c = true;
        Database.insert(mMSM);

        Product2 assocSalesProduct = APTS_TestDataFactory.createProduct('TestCoffee', '123', 'Coffee', 'Standalone', true, false);
        assocSalesProduct.APTS_Cross_plant_material_status__c = 'PR';
        Database.insert(assocSalesProduct, false);

        APTS_Sales_Org_Data__c assocSalesOrg = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg.APTS_Sales_Org_Data_Name__c = '0333';
        assocSalesOrg.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_02';
        Database.insert(assocSalesOrg, false);

        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_01';
        Database.update(assocSalesOrg, false);
        test.stopTest();
    }

    static testMethod void testSalesOrgTrigger_AssocSalesOrgCase2(){
        test.startTest();

        TriggerSettings__c settings = new TriggerSettings__c();
        settings.SalesOrgDataTrigger__c = true;
        Database.insert(settings, false);

        APTS_MARA_MVKE_Status_Mapping__c mMSM = new APTS_MARA_MVKE_Status_Mapping__c();
        mMSM.Name = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Field_Combination__c = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_Has_PLI_active_PLI__c = true;
        mMSM.APTS_Visible_in_Catalogue__c = false;
        insert mMSM;

        Product2 assocSalesProduct = APTS_TestDataFactory.createProduct('TestCoffee', '123', 'Coffee', 'Standalone', true, false);
        assocSalesProduct.APTS_Cross_plant_material_status__c = 'PR';
        insert assocSalesProduct;

        APTS_Sales_Org_Data__c assocSalesOrg = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg.APTS_Sales_Org_Data_Name__c = '0333';
        assocSalesOrg.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_01';
        insert assocSalesOrg;

        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_02';
        update assocSalesOrg;
        test.stopTest();
    }

    static testMethod void testSalesOrgTrigger_AssocSalesOrgCase3(){
        test.startTest();
        List<APTS_Sales_Org_Data__c> salesOrgList = new  List<APTS_Sales_Org_Data__c>();

        TriggerSettings__c settings = new TriggerSettings__c();
        settings.SalesOrgDataTrigger__c = true;
        Database.insert(settings, false);
        
        APTS_MARA_MVKE_Status_Mapping__c mMSM = new APTS_MARA_MVKE_Status_Mapping__c();
        mMSM.Name = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Field_Combination__c = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_Has_PLI_active_PLI__c = true;
        mMSM.APTS_Visible_in_Catalogue__c = false;
        insert mMSM;

        Product2 assocSalesProduct = APTS_TestDataFactory.createProduct('TestCoffee', '123', 'Coffee', 'Standalone', true, false);
        assocSalesProduct.APTS_Cross_plant_material_status__c = 'PR';
        insert assocSalesProduct;

        APTS_Sales_Org_Data__c assocSalesOrg = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg.APTS_Sales_Org_Data_Name__c = '0333';
        assocSalesOrg.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_01';
        insert assocSalesOrg;

        APTS_Sales_Org_Data__c assocSalesOrg1 = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg1.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg1.APTS_Sales_Org_Data_Name__c = '0111';
        assocSalesOrg1.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg1.APTS_Distribution_chain_specific_materia__c='SAP_01';
        insert assocSalesOrg1;

        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_02';

        assocSalesOrg1.APTS_Distribution_chain_specific_materia__c='SAP_02';

        salesOrgList.add(assocSalesOrg1);
        salesOrgList.add(assocSalesOrg);

        update salesOrgList;
    }

    static testMethod void testSalesOrgTrigger_AssocSalesOrgCase4(){
        test.startTest();
        List<APTS_Sales_Org_Data__c> salesOrgList = new  List<APTS_Sales_Org_Data__c>();

        TriggerSettings__c settings = new TriggerSettings__c();
        settings.SalesOrgDataTrigger__c = true;
        Database.insert(settings, false);
        
        APTS_MARA_MVKE_Status_Mapping__c mMSM = new APTS_MARA_MVKE_Status_Mapping__c();
        mMSM.Name = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Field_Combination__c = 'PR|SAP_02';
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_Has_PLI_active_PLI__c = true;
        mMSM.APTS_Visible_in_Catalogue__c = false;
        insert mMSM;

        Product2 assocSalesProduct = APTS_TestDataFactory.createProduct('TestCoffee', '123', 'Coffee', 'Standalone', true, false);
        assocSalesProduct.APTS_Cross_plant_material_status__c = 'PR';
        assocSalesProduct.APTS_Associated_Sales_Org__c='SAP_0975;';
        insert assocSalesProduct;

        APTS_Sales_Org_Data__c assocSalesOrg = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg.APTS_Sales_Org_Data_Name__c = '0333';
        assocSalesOrg.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg.APTS_Product__c = assocSalesProduct.id;
        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_01';
        insert assocSalesOrg;

        APTS_Sales_Org_Data__c assocSalesOrg1 = TestDataFactory.createSalesOrgData(assocSalesProduct.Id);
        assocSalesOrg1.APTS_Sales_Org_Data_Ext_ID__c = '12345678|0333';
        assocSalesOrg1.APTS_Sales_Org_Data_Name__c = '0111';
        assocSalesOrg1.APTS_Product_Code__c=assocSalesProduct.ProductCode;
        assocSalesOrg1.APTS_Product__c = assocSalesProduct.id;
        assocSalesOrg1.APTS_Distribution_chain_specific_materia__c='SAP_01';
        insert assocSalesOrg1;

        assocSalesOrg.APTS_Distribution_chain_specific_materia__c='SAP_02';

        assocSalesOrg1.APTS_Distribution_chain_specific_materia__c='SAP_02';

        salesOrgList.add(assocSalesOrg1);
        salesOrgList.add(assocSalesOrg);

        update salesOrgList;

        test.stopTest();
    }
}