src/objects/APTS_Batch_Queries__mdt.object
<CustomObject>
    <description>Custom metadata to store batch queries</description>
    <fields>
        <fullName>APTS_Query_String__c</fullName>
        <description>Field to store queries</description>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch query</label>
    <pluralLabel>Batch queries</pluralLabel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_InstalledAssetsController.cls
public with sharing class APTS_InstalledAssetsController {

    @AuraEnabled(cacheable=true)
    public static List<Apttus_Config2__AssetLineItem__c> getAssetsRelatedToAccount(string recordId) {
        list<APTS_Batch_Queries__mdt> metadataQuery = [select id, APTS_Query_String__c,  DeveloperName from APTS_Batch_Queries__mdt where DeveloperName = 'Installed_Assets_Query'];
        List<Apttus_Config2__AssetLineItem__c> assetLineItems = new List<Apttus_Config2__AssetLineItem__c>();
        if(metadataQuery.size() > 0 &&  metadataQuery[0].APTS_Query_String__c != null){
            assetLineItems =  database.query(metadataQuery[0].APTS_Query_String__c);       
        }
        return assetLineItems;        
    }    

}