src/objects/APTS_Batch_Queries__mdt.object
<CustomObject>
    <description>Custom metadata to store batch queries</description>
    <fields>
        <fullName>APTS_Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Query_String__c</fullName>
        <description>Field to store queries</description>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Triggers__c</fullName>
        <description>Comma separated list of triggers to be deactivated</description>
        <label>Triggers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch query</label>
    <pluralLabel>Batch queries</pluralLabel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_CERRecordsGenerationBatch.cls
global class APTS_CERRecordsGenerationBatch implements Database.Batchable<sObject> {
	
	String agreementQuery;
    Set<string> setTriggers;
	
	global APTS_CERRecordsGenerationBatch() {
		//Get the query from custom metadata
        List<APTS_Batch_Queries__mdt> lstMetadata = new APTS_BatchMetadataCoverage().getMetadataCoverageRecords(
            'SELECT APTS_Batch_Name__c,'+
            'APTS_Query_String__c,'+
            'DeveloperName,'+
            'APTS_Triggers__c '+ 
            'FROM APTS_Batch_Queries__mdt '+ 
            'WHERE DeveloperName = \'CER_Creation\''
        );

        List<String> splitString = lstMetadata[0].APTS_Triggers__c.split(',');
        setTriggers = new Set<String>(splitString);
        agreementQuery = lstMetadata[0].APTS_Query_String__c;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		 //Inactivate triggers
        APTS_AgreementLoadBatchHelper.modifyTriggers(setTriggers,'Deactivate');

        return Database.getQueryLocator(agreementQuery);
	}

   	global void execute(Database.BatchableContext BC, List<Apttus__APTS_Agreement__c> lstAgreements) {
		APTS_AgreementLoadBatchHelper.createCERRecords(lstAgreements);
	}
	
	global void finish(Database.BatchableContext BC) {
		//Activate triggers
        APTS_AgreementLoadBatchHelper.modifyTriggers(setTriggers,'Activate');
	}
}