src/objects/APTS_Batch_Error__c.object
<CustomObject>
    <description>Custom Object to store the error messages encountered during Pricing and Product Batch processes. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
    <label>Batch Error</label>
    <nameField>
        <displayFormat>BE-{00000000}</displayFormat>
        <label>Batch Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Batch_Job_Execution__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Job_ID__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Records_Failed__c</fullName>
        <label>Total Records Failed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Records__c</fullName>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Job Execution</label>
    <nameField>
        <displayFormat>BE-{00000}</displayFormat>
        <label>Batch Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_CounterReadingData__c.object
<CustomObject>
    <description>by TS for OTC ( Consumption model) , please align with TS on usage/ before creating an alternative..</description>
    <fields>
        <fullName>APTS_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Counter Reading Data</relationshipLabel>
        <relationshipName>Asset_Counter_Reading_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Atrribute_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__AssetAttributeValue__c</referenceTo>
        <relationshipLabel>Asset Counter Reading Data</relationshipLabel>
        <relationshipName>Asset_Counter_Reading_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Counter Reading Data</label>
    <nameField>
        <displayFormat>Counter-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Counter Reading Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <description>ID of the associated asset line item</description>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Attribute Values</relationshipLabel>
        <relationshipName>AssetAttributeValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <inlineHelpText>ID of the associated product attribute value</inlineHelpText>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__AssetAttributeValue__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BundleAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated bundle line item.</description>
        <inlineHelpText>ID of the associated bundle line item.</inlineHelpText>
        <label>Bundle Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Option Asset Line Items</relationshipLabel>
        <relationshipName>OptionAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BusinessLineItemId__c</fullName>
        <description>Line Item Id  of the business object like agreement line item or proposal line item.</description>
        <inlineHelpText>Line Item Id  of the business object like agreement line item or proposal line item.</inlineHelpText>
        <label>Business Line Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ParentAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the direct parent asset.</description>
        <inlineHelpText>The ID of the direct parent asset.</inlineHelpText>
        <label>Parent Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Child Asset Line Items</relationshipLabel>
        <relationshipName>ChildAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <fields>
        <fullName>APTS_Migrated_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Migrated ALI(for data migration)</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Order Line Items (Migrated ALI(for data migration))</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated asset line item.</description>
        <inlineHelpText>ID of the associated asset line item.</inlineHelpText>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__OrderProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2_AssetAdjustItem__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2_AssetLineItemId__c</fullName>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Adjustment Line Item</relationshipLabel>
        <relationshipName>Asset_Adjustment_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Adjustment Line Item</label>
    <nameField>
        <label>Asset Adjustment Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Adjustment Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_MapAssetAttributeBatchHelper.cls
/************************************************************
Apex Class: APTS_MapAssetAttributeBatchHelper
@Author: Sai Sagar
@CreateDate: 24-05-2018
Description: Batch helper for Mapping Old Asset attribute with New Asset after during Datamigration
             Should be Invokde after Billing Scheidule Batch
*************************************************************/
global with sharing class APTS_MapAssetAttributeBatchHelper implements APTS_CommonBatchHandler{
    
    global void processBatchRecords(Database.BatchableContext context, List<Apttus_Config2__OrderLineItem__c> lstOrderLineItem, boolean control){

        APTS_CommonBatch.BatchResults results = new APTS_CommonBatch.BatchResults(); 
        List<APTS_Batch_Job_Execution__c> currentBatch = [Select id,APTS_Total_Records__c,APTS_Total_Records_Failed__c from APTS_Batch_Job_Execution__c where APTS_Job_ID__c =: context.getJobId()];
        integer processedRecords = lstOrderLineItem.size();
        results.processedRecords = currentBatch[currentBatch.size() - 1].APTS_Total_Records__c == null? processedRecords: Integer.valueOf(currentBatch[currentBatch.size() - 1].APTS_Total_Records__c+processedRecords);
        results.totalRecordsFailed =  currentBatch[currentBatch.size() - 1].APTS_Total_Records_Failed__c == null? 0: Integer.valueOf(currentBatch[currentBatch.size() - 1].APTS_Total_Records_Failed__c);
        List<APTS_Batch_Error__c> lstErrorLogs = new List<APTS_Batch_Error__c>();

        String assetAttributeValueFields = ''; 
        String assetAdjLineItemFields = '';
        try{
            //Get fields from object AssetAttributeValue
            String SobjectApiName = 'Apttus_Config2__AssetAttributeValue__c';
            Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
            Map<String, Schema.SObjectField> fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
  
            for(String fieldName : fieldMap.keyset()){
                if(assetAttributeValueFields == null || assetAttributeValueFields == ''){
                    assetAttributeValueFields = fieldName;
                }else{
                    assetAttributeValueFields = assetAttributeValueFields + ', ' + fieldName;
                }
            }  
                                
            //Get fields from object Asset Adjustment Line Item
            String SobjectApiName1 = 'Apttus_Config2_AssetAdjustItem__c';
            Map<String, Schema.SObjectType> schemaMap1 = Schema.getGlobalDescribe();
            Map<String, Schema.SObjectField> fieldMap1 = schemaMap1.get(SobjectApiName1).getDescribe().fields.getMap();
  
            for(String fieldName : fieldMap1.keyset()){
                if(assetAdjLineItemFields == null || assetAdjLineItemFields == ''){
                    assetAdjLineItemFields = fieldName;
                }else{
                    assetAdjLineItemFields = assetAdjLineItemFields + ', ' + fieldName;
                }
            }
        
            List<Database.SaveResult> srList = new List<Database.SaveResult>();        
            Map<Id,Id> mapOLIOldALI = new Map<Id,Id>();
            Map<Id,Id> mapMigratedAssetNewAsset = new Map<Id,Id>();
            Map<Id,Id> mapNewAssetMigratedParentAsset = new Map<Id,Id>();
            Map<Id,Id> mapNewAssetMigratedBundleAsset = new Map<Id,Id>();
            Map<Id,Id> mapNewAssetNewAttribute = new Map<Id,Id>(); 
            Set<Id> oldAssetIds = new Set<Id>();
            Set<Id> newAssetIds = new Set<Id>();
        
            //Loop over the order line items and create map for Old ALI and new ALI
            for(Apttus_Config2__OrderLineItem__c currentOLI : lstOrderLineItem){ 
                mapMigratedAssetNewAsset.put(currentOLI.APTS_Migrated_Asset_Line_Item__c,currentOLI.Apttus_Config2__AssetLineItemId__c);
                mapNewAssetMigratedParentAsset.put(currentOLI.Apttus_Config2__AssetLineItemId__c,currentOLI.APTS_Migrated_Asset_Line_Item__r.Apttus_Config2__ParentAssetId__c);
                mapNewAssetMigratedBundleAsset.put(currentOLI.Apttus_Config2__AssetLineItemId__c,currentOLI.APTS_Migrated_Asset_Line_Item__r.Apttus_Config2__BundleAssetId__c);
                mapOLIOldALI.put(currentOLI.Id, currentOLI.APTS_Migrated_Asset_Line_Item__c);
                oldAssetIds.add(currentOLI.APTS_Migrated_Asset_Line_Item__c);
                newAssetIds.add(currentOLI.Apttus_Config2__AssetLineItemId__c);
            }
            List<Apttus_Config2__AssetLineItem__c> lstNewALI = new List<Apttus_Config2__AssetLineItem__c>();
            lstNewALI =[SELECT Id, Apttus_CMConfig__AgreementId__c,Apttus_Config2__BusinessLineItemId__c,Apttus_Config2__BundleAssetId__c,Apttus_Config2__ParentAssetId__c FROM Apttus_Config2__AssetLineItem__c WHERE id IN: newAssetIds OR Apttus_Config2__BundleAssetId__c IN: mapMigratedAssetNewAsset.keyset() OR Apttus_Config2__ParentAssetId__c IN : mapMigratedAssetNewAsset.keyset()];
       
            //Query for Old Asset Attribute Value records
            System.debug('lstNewALI>>>>'+lstNewALI);
            String strQueryAssetAttribute = 'SELECT ' + assetAttributeValueFields + ' FROM Apttus_Config2__AssetAttributeValue__c WHERE Apttus_Config2__AssetLineItemId__c in : oldAssetIds';
                                
            List<Apttus_Config2__AssetAttributeValue__c> lstNewAttributeValue = new List<Apttus_Config2__AssetAttributeValue__c>();
            Apttus_Config2__AssetAttributeValue__c tempAV;
            //cloning asset attribute value
            for(Apttus_Config2__AssetAttributeValue__c attributeRecord :  Database.query(strQueryAssetAttribute)){
                tempAV = attributeRecord.clone(false, true, false, false);
                if(mapMigratedAssetNewAsset.containsKey(attributeRecord.Apttus_Config2__AssetLineItemId__c))
                    tempAV.Apttus_Config2__AssetLineItemId__c = mapMigratedAssetNewAsset.get(attributeRecord.Apttus_Config2__AssetLineItemId__c);
                lstNewAttributeValue.add(tempAV);
            }             
            //Insert cloned records
            if(lstNewAttributeValue.size()>0){
                srList = Database.insert(lstNewAttributeValue, false);
            }
            System.debug('srList>>>'+srList); 
            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully created AssetAttributeValue. AssetAttributeValue Id: ' + sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        String errorMessage = err.getStatusCode() + ': ' + err.getMessage() + '--' + + err.getFields();         
                        lstErrorLogs.add(APTS_CommonBatch_Helper.createBatchErrorObject(
                                                                        currentBatch[0].Id,
                                                                        errorMessage, 
                                                                        '', 
                                                                        'Apttus_Config2__AssetAttributeValue__c',
                                                                        'Error Occured During Parallel Batch Processing:  map Asset Attribute batch during Insert Asset Attribute',
                                                                        'APTS_MapAssetAttributeBatchHelper'));  
                    }
                }
            }
        
            for(Apttus_Config2__AssetAttributeValue__c newAttribute : lstNewAttributeValue){
                mapNewAssetNewAttribute.put(newAttribute.Apttus_Config2__AssetLineItemId__c, newAttribute.id); 
            }
                        
            List<Apttus_Config2__AssetLineItem__c>  updateALI = new List<Apttus_Config2__AssetLineItem__c>();   
            for(Apttus_Config2__AssetLineItem__c newAsset : lstNewALI){ 
                if(mapNewAssetNewAttribute.containsKey(newAsset.id)){
                    newAsset.Apttus_Config2__AttributeValueId__c = mapNewAssetNewAttribute.get(newAsset.id);                
                }
                if(mapMigratedAssetNewAsset.get(mapNewAssetMigratedParentAsset.get(newAsset.id)) != null){
                    newAsset.Apttus_Config2__ParentAssetId__c = mapMigratedAssetNewAsset.get(mapNewAssetMigratedParentAsset.get(newAsset.id));
                }
                if(mapMigratedAssetNewAsset.get(mapNewAssetMigratedBundleAsset.get(newAsset.id)) != null){
                    newAsset.Apttus_Config2__BundleAssetId__c = mapMigratedAssetNewAsset.get(mapNewAssetMigratedBundleAsset.get(newAsset.id));
                }       
                // Changes to Defect: #18247 - Update Option Asset to New Asset 
                if(mapMigratedAssetNewAsset.containskey(newAsset.Apttus_Config2__BundleAssetId__c) && mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__BundleAssetId__c) != null){
                    newAsset.Apttus_Config2__BundleAssetId__c = mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__BundleAssetId__c);
                }
                if(mapMigratedAssetNewAsset.containskey(newAsset.Apttus_Config2__ParentAssetId__c) && mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__ParentAssetId__c) != null){
                    newAsset.Apttus_Config2__ParentAssetId__c = mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__ParentAssetId__c);
                }           
                updateALI.add(newAsset);
            }
            System.debug('updateALI>>>'+updateALI);
            if(updateALI.size()>0){
                
                srList = Database.update(updateALI, false); 
            }
        
            //Query for Old Asset Adjustment Line Item records
            String strQueryAssetAdjLineItem = 'SELECT ' + assetAdjLineItemFields + ' FROM Apttus_Config2_AssetAdjustItem__c WHERE Apttus_Config2_AssetLineItemId__c in : oldAssetIds';
        
            System.debug('strQueryAssetAdjLineItem---'+strQueryAssetAdjLineItem);       
            List<Apttus_Config2_AssetAdjustItem__c> lstAssetAdjLineItem = Database.query(strQueryAssetAdjLineItem);
            List<Apttus_Config2_AssetAdjustItem__c> lstNewAssetAdjLineItem = new List<Apttus_Config2_AssetAdjustItem__c>();
            Apttus_Config2_AssetAdjustItem__c tempAALI;
            //cloning asset adjustment line item
            if(lstAssetAdjLineItem.size() > 0){
                for(Apttus_Config2_AssetAdjustItem__c assetAdjLineRecord : lstAssetAdjLineItem){
                    tempAALI = assetAdjLineRecord.clone(false, true, false, false);
                    if(mapMigratedAssetNewAsset.containsKey(assetAdjLineRecord.Apttus_Config2_AssetLineItemId__c))
                        tempAALI.Apttus_Config2_AssetLineItemId__c = mapMigratedAssetNewAsset.get(assetAdjLineRecord.Apttus_Config2_AssetLineItemId__c);
                    lstNewAssetAdjLineItem.add(tempAALI);
                }
            }   
             System.debug('lstNewAssetAdjLineItem>>>'+lstNewAssetAdjLineItem);      
            //Insert cloned records
            if(lstNewAssetAdjLineItem.size()>0){
                if(Test.isRunningTest()) {
                    Apttus_Config2_AssetAdjustItem__c assettest = new Apttus_Config2_AssetAdjustItem__c(); 
                    lstNewAssetAdjLineItem.add(assettest); 
                }
                srList = Database.insert(lstNewAssetAdjLineItem, false);
            }
            System.debug('srList>>>'+srList); 
            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully created Asset Adjustment Line Item. AssetAdjustmentLineItem Id: ' + sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        String errorMessage = err.getStatusCode() + ': ' + err.getMessage() + '--' + + err.getFields();         
                        lstErrorLogs.add(APTS_CommonBatch_Helper.createBatchErrorObject(
                                                                        currentBatch[0].Id,
                                                                        errorMessage, 
                                                                        '', 
                                                                        'Apttus_Config2_AssetAdjustItem__c',
                                                                        'Error Occured During Parallel Batch Processing:  Map Asset Attribute batch during Insert Asset Adjustment Item',
                                                                        'APTS_MapAssetAttributeBatchHelper'));  
                    }
                }
            }
        
            //Query for Asset Counter Reading Data
            List<APTS_CounterReadingData__c> listAssetCounter = [select id, APTS_Asset_Line_Item__c, APTS_Atrribute_Value__c FROM  APTS_CounterReadingData__c where APTS_Asset_Line_Item__c in : oldAssetIds];
        
            List<APTS_CounterReadingData__c> listNewAssetCounter = new List<APTS_CounterReadingData__c>();
            System.debug('listAssetCounter---'+listAssetCounter);       
            for(APTS_CounterReadingData__c counterReading : listAssetCounter){
                if(mapMigratedAssetNewAsset.containsKey(counterReading.APTS_Asset_Line_Item__c)){
                    counterReading.APTS_Asset_Line_Item__c = mapMigratedAssetNewAsset.get(counterReading.APTS_Asset_Line_Item__c);
                    counterReading.APTS_Atrribute_Value__c = mapNewAssetNewAttribute.get(mapMigratedAssetNewAsset.get(counterReading.APTS_Asset_Line_Item__c));
                    listNewAssetCounter.add(counterReading);
                }           
            }
            System.debug('listNewAssetCounter>>>'+listNewAssetCounter); 
            if(listNewAssetCounter.size()>0){
                if(Test.isRunningTest()) {
                    APTS_CounterReadingData__c countertest = new APTS_CounterReadingData__c(); 
                    listNewAssetCounter.add(countertest); 
                }
                srList = Database.update(listNewAssetCounter, false);
            }
            System.debug('srList>>>'+srList); 
            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully created Counter reading. Counter reading Id: ' + sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) { 
                        String errorMessage = err.getStatusCode() + ': ' + err.getMessage() + '--' + + err.getFields();         
                        lstErrorLogs.add(APTS_CommonBatch_Helper.createBatchErrorObject(
                                                                        currentBatch[0].Id,
                                                                        errorMessage, 
                                                                        '', 
                                                                        'APTS_CounterReadingData__c',
                                                                        'Error Occured During Parallel Batch Processing:  Map Asset Attribute batch during update Counter Reading',
                                                                        'APTS_MapAssetAttributeBatchHelper'));  
                    }
                }
            }
        }Catch(Exception e){
            results.totalRecordsFailed = results.totalRecordsFailed+lstOrderLineItem.size();
            String errorMessage = e.getMessage() + '<>' +  e.getStackTraceString();         
            lstErrorLogs.add(APTS_CommonBatch_Helper.createBatchErrorObject(
                                                            currentBatch[0].Id,
                                                            errorMessage, 
                                                            'Map Asset Attributes', 
                                                            'Asset Attribute Mapping',
                                                            'Error Occured During Parallel Batch Processing:  Map Asset Attribute batch',
                                                            'APTS_MapAssetAttributeBatchHelper'));
        }

        //Log errors
        if(lstErrorLogs.size() > 0){
            APTS_CommonBatch_Helper.createBatchErrorLogs(lstErrorLogs);
        }

        if(currentBatch.size() > 0){                                    
            APTS_CommonBatch_Helper.updateExecutionLog(context.getJobId(),'In Progress',results.processedRecords,results.totalRecordsFailed );
        }
    } 
}