src/objects/APTS_CER_Transaction__c.object
<CustomObject>
    <description>CER Transactions</description>
    <fields>
        <fullName>APTS_Agreement_Id__c</fullName>
        <description>To store the agreement id</description>
        <externalId>true</externalId>
        <label>Agreement Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Error__c</fullName>
        <label>Error Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Process_Status__c</fullName>
        <label>Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CER Transaction</label>
    <nameField>
        <displayFormat>CER-{00000}</displayFormat>
        <label>CER Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CER Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_CER_Batch_Executed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the CER batch was executed succesfully for the record</description>
        <label>CER Batch Executed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_updateCERRecordsBatch.cls
/*************************************************************
@Name: APTS_updateCERRecordsBatch 
@Author: Aftab Mohammed
@Description: Batch class to process CER Transaction records to update Agreements
*****************************************************************/
global class APTS_updateCERRecordsBatch implements Database.Batchable<sObject>{

    String query;
    private static String BATCHNAME = 'APTS_updateCERRecordsBatch';
    private static String STREAM = 'CLM';
    private static String TYPE = 'CER Transaction Batch';
    List<APTS_CER_Transaction__c> cerTransList = new List<APTS_CER_Transaction__c>();
    
    public APTS_updateCERRecordsBatch(List<APTS_CER_Transaction__c> cerTransList){
        this.cerTransList = cerTransList;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        try{
            query = 'SELECT Id, APTS_Agreement_Id__c FROM APTS_CER_Transaction__c WHERE APTS_Process_Status__c = \'Created\'';
            return Database.getQueryLocator(query);
        }catch(Exception ex){APTS_CustomLogging.createErrorLog(ex.getTypeName(), TYPE, String.valueOf(ex) ,BATCHNAME, null, STREAM, false, false, null, true); return null;}
    }

    global void execute(Database.BatchableContext BC, List<APTS_CER_Transaction__c> scope) {
        
        Set<String> agreementIdSet = new Set<String>();
        
        APTS_CER_Transaction__c cerTrans = scope[0];
        cerTrans.APTS_Process_Status__c = 'Processing';
        update cerTrans;
        agreementIdSet.add(cerTrans.APTS_Agreement_Id__c);
        
        List<Apttus__APTS_Agreement__c> agreementList = [SELECT Id, RecordTypeId, Apttus__Account__c,APTS_CER_Batch_Executed__c FROM Apttus__APTS_Agreement__c WHERE Id IN: agreementIdSet];
        
        if(agreementList.size() > 0){
            try{
                APTS_ManageCER.manageCERRecords(agreementList,APTS_ManageCER.BATCH,APTS_ManageCER.DMLUPDATE); 
            }catch(Exception ex){
                cerTrans.APTS_Process_Status__c = 'Failed';
                cerTrans.APTS_Error__c = String.valueOf(ex); update cerTrans;
            }
        }
        
        if(cerTrans.APTS_Process_Status__c != 'Failed'){
            cerTrans.APTS_Process_Status__c = 'Processed';
            update cerTrans;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {}
    
}