src/objects/APTS_Sales_Org_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <formula>APTS_Product__r.APTS_Material_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Option_Group_Indicator__c</fullName>
        <formula>APTS_Product__r.APTS_Option_Group_Indicator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Option Group Indicator</label>
        <type>Text</type>
    </fields>
    <label>Sales Org Data</label>
    <nameField>
        <displayFormat>SOD-{00000000}</displayFormat>
        <label>Sales Org Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Org Datas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ClassificationHierarchy__c.object
<CustomObject>
    <description>Represents a category hierarchy</description>
    <fields>
        <fullName>APTS_CategoryHierarchyOfferingExtId__c</fullName>
        <externalId>true</externalId>
        <label>Category Hierarchy-Offering External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>APTS_CategoryHierarchyOptionExtId__c</fullName>
        <externalId>true</externalId>
        <label>Category Hierarchy-Option External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__FieldExpression__c.object
<CustomObject>
    <description>Object model for field updates and rollups</description>
    <fields>
        <fullName>Apttus_Config2__ProductGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Group</label>
        <referenceTo>Apttus_Config2__ProductGroup__c</referenceTo>
        <relationshipLabel>Field Expressions</relationshipLabel>
        <relationshipName>FieldExpressions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Field Expressions (Product)</relationshipLabel>
        <relationshipName>Field_Expressions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Expression</label>
    <nameField>
        <label>Field Expression Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Expressions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__FrequencyConversionRate__c.object
<CustomObject>
    <description>Represents the conversion rates used to convert pricing from one frequency or unit of measure to another frequency or unit of measure</description>
    <fields>
        <fullName>APTS_ProductCode__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__FromFrequency__c</fullName>
        <description>The frequency to convert from</description>
        <label>From Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product</description>
        <inlineHelpText>ID of the associated product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Frequency/UOM Conversion Rates</relationshipLabel>
        <relationshipName>FrequencyUOMConversionRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Frequency/UOM Conversion Rate</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Conversion Rate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency/UOM Conversion Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductAttributeGroupMember__c.object
<CustomObject>
    <description>Represents the association between a product and an attribute group.</description>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the attribute group</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Attribute Groups</relationshipLabel>
        <relationshipName>AttributeGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Attribute Group Member</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Attribute Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductClassification__c.object
<CustomObject>
    <description>Represents a product classification which is a member of the list of products associated with a classification.</description>
    <fields>
        <fullName>Apttus_Config2__ClassificationId__c</fullName>
        <description>ID of the associated category</description>
        <label>Category</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Classification</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Classification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductGroupMember__c.object
<CustomObject>
    <description>Represents a single product in a product group.</description>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the group</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Groups</relationshipLabel>
        <relationshipName>ProductGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Group Member</label>
    <nameField>
        <displayFormat>GM-{0000000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductTranslation__c.object
<CustomObject>
    <description>This object holds the translated values of product object fields for all the languages</description>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the product record</description>
        <inlineHelpText>Lookup to the product record</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Translation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Translation</label>
    <nameField>
        <label>Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Associated_Sales_Org__c</fullName>
        <label>Associated Sales Org</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Associated_Sales_Organization__c</fullName>
        <description>Text field to store the list of associated Sales Organizations for a Product.</description>
        <label>Associated Sales Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Conversion_Option_Indicator__c</fullName>
        <label>Conversion Option Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Cross_plant_material_status__c</fullName>
        <label>Cross-plant material status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <description>SAP Material Type, Used in EPI Integration
/ZMATMAS03I/IDOC/E1MARAM/MTART</description>
        <label>Material_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Option_Group_Indicator__c</fullName>
        <label>Option Group Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Catalog__c</fullName>
        <description>Concatenated code for Category, Sub-category and sub-sub category</description>
        <label>Sales Catalog</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_To_Be_Processed_From_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox will be checked when the Product record is loaded from SAP and when the related Child records should be created. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <label>To Be Processed (From SAP)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Upserted_from_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upserted from SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProductRedistributionBatch_Test.cls
/**
* Class Name : APTS_ProductRedistributionBatch_Test
* Description :  Apex Class to test APTS_ProductRedistributionBatch Class
* Author : V. Shankaranarayanan
* Date Created : 03/02/2018
**/
@isTest
private with sharing class APTS_ProductRedistributionBatch_Test{
    
    private static Map<Id,List<APTS_Batch_Error__c>> batchErrorsMap=new Map<Id,List<APTS_Batch_Error__c>>();
    private static Set<String> offeringCodesSet = new set<String>();
    private static Set<String> tempOptSet=new Set<String>();
    private static Set<String> optionCodesSet = new set<String>();
    private static Map<String, Product2> activeProductMapNew = new Map<String, Product2>();
    private static Apttus_Config2__ProductGroup__c prodGrp = new Apttus_Config2__ProductGroup__c ();
    @testSetup
    //Test Data Setup Method to create all test Data to test "APTS_ProductRedistributionBatch" Class
    static void setupTestData(){ 
        List<Product2> prodInsertList = new List<Product2>();
        
        prodInsertList = TestDataFactory.createProduct(4);
        //APTS_CPQConstants.PRD_TYPE
        prodInsertList[0].Name = APTS_CPQConstants.PRD_NAME;
        prodInsertList[0].ProductCode = APTS_CPQConstants.PRD_CODE; 
        prodInsertList[0].APTS_Sales_Catalog__c = APTS_CPQConstants.PRD_SALE_CAT;
        prodInsertList[0].APTS_Conversion_Option_Indicator__c = APTS_CPQConstants.PRD_OPTION_INDICATOR;
        //Commented by Hari for fixing the defect 16724 releted to deleting redundant fields
        //prodInsertList[0].APTS_To_Be_Processed_From_SAP__c = true;
        prodInsertList[0].Apttus_Config2__ConfigurationType__c = APTS_CPQConstants.PRD_TYPE;
        prodInsertList[0].APTS_Material_Type__c = APTS_CPQConstants.PRD_MATERIAL_TYPE;
        prodInsertList[0].APTS_Cross_plant_material_status__c = APTS_CPQConstants.PRD_BL;
        //Commented by Hari for deleting the unwanted fields in Product2 object which is part of defect 16724
        //prodInsertList[0].APTS_Associated_Sales_Organization__c= '0111;6712';
        prodInsertList[0].APTS_Associated_Sales_Org__c = APTS_CPQConstants.PRD_SALS_ORG;
        prodInsertList[0].APTS_Upserted_from_SAP__c=TRUE;
        prodInsertList[0].APTS_Sales_Catalog__c= APTS_CPQConstants.PRD_SALES_CAT;
        prodInsertList[0].APTS_Option_Group_Indicator__c = APTS_CPQConstants.PRD_OPTION_INDI;
        
        
        prodInsertList[1].Name = APTS_CPQConstants.PRD_NME;
        prodInsertList[1].APTS_Option_Group_Indicator__c = APTS_CPQConstants.PRD_GRP_INDI;
        //Commented by Hari for fixing the defect 16724 releted to deleting redundant fields
        //prodInsertList[1].APTS_To_Be_Processed_From_SAP__c = true;
        prodInsertList[1].Apttus_Config2__ConfigurationType__c = APTS_CPQConstants.PRD_TYPE;
        prodInsertList[1].APTS_Material_Type__c = APTS_CPQConstants.PRD_MATERIAL_TYPE1;
        prodInsertList[1].APTS_Cross_plant_material_status__c = APTS_CPQConstants.PRD_BL;
        prodInsertList[1].APTS_Conversion_Option_Indicator__c = APTS_CPQConstants.PRD_OPTION_INDICATOR;
        //Commented by Hari for deleting the unwanted fields in Product2 object which is part of defect 16724
        //prodInsertList[1].APTS_Associated_Sales_Organization__c= '0111';
        prodInsertList[1].APTS_Upserted_from_SAP__c=TRUE;
        prodInsertList[0].APTS_Sales_Catalog__c= APTS_CPQConstants.PRD_OPTION_INDI;
        prodInsertList[0].APTS_Option_Group_Indicator__c = APTS_CPQConstants.PRD_SALES_CAT;
        
        prodInsertList[2].Name = APTS_CPQConstants.PRD_NAME1;
        prodInsertList[2].IsActive = false;
        prodInsertList[2].APTS_Sales_Catalog__c = APTS_CPQConstants.PRD_OPTION_INDI;
        //Commented by Hari for fixing the defect 16724 releted to deleting redundant fields
        //prodInsertList[2].APTS_To_Be_Processed_From_SAP__c = true;
        prodInsertList[2].Apttus_Config2__ConfigurationType__c = APTS_CPQConstants.PRD_TYPE;
        prodInsertList[2].APTS_Material_Type__c = APTS_CPQConstants.PRD_MATERIAL_TYPE1;
        prodInsertList[2].APTS_Cross_plant_material_status__c = APTS_CPQConstants.PRD_BL;
        prodInsertList[2].APTS_Conversion_Option_Indicator__c = APTS_CPQConstants.PRD_OPTION_INDICATOR;
        //Commented by Hari for deleting the unwanted fields in Product2 object which is part of defect 16724
        //prodInsertList[2].APTS_Associated_Sales_Organization__c= '0111';
        prodInsertList[0].APTS_Associated_Sales_Org__c = APTS_CPQConstants.PRD_SALS_ORG;
        prodInsertList[2].APTS_Upserted_from_SAP__c=TRUE;
        
        prodInsertList[3].Name = APTS_CPQConstants.PRD_NAME2;
        prodInsertList[3].IsActive = false;
        prodInsertList[3].APTS_Sales_Catalog__c = APTS_CPQConstants.PRD_OPTION_INDI;
        //Commented by Hari for fixing the defect 16724 releted to deleting redundant fields
        //prodInsertList[3].APTS_To_Be_Processed_From_SAP__c = true;
        prodInsertList[3].Apttus_Config2__ConfigurationType__c = APTS_CPQConstants.PRD_TYPE;
        prodInsertList[3].APTS_Material_Type__c = APTS_CPQConstants.PRD_MATERIAL_TYPE1;
        prodInsertList[3].APTS_Cross_plant_material_status__c = APTS_CPQConstants.PRD_HI;
        //Commented by Hari for deleting the unwanted fields in Product2 object which is part of defect 16724
        //prodInsertList[3].APTS_Associated_Sales_Organization__c= '0111';
        prodInsertList[0].APTS_Associated_Sales_Org__c = APTS_CPQConstants.PRD_SALS_ORG;
        prodInsertList[3].APTS_Upserted_from_SAP__c=TRUE;
        prodInsertList[3].APTS_Conversion_Option_Indicator__c = APTS_CPQConstants.PRD_OPTION_INDICATOR;
        
        Database.insert(prodInsertList);
        
        List<Apttus_Config2__ClassificationName__c> categoryList = TestDataFactory.createCategory(2);
        Database.insert(categoryList);
        
        List<Apttus_Config2__ClassificationHierarchy__c> hierarchyList = TestDataFactory.createHierarchy(2, categoryList);
        Database.insert(hierarchyList);
        
        Apttus_Config2__ProductClassification__c prodClassification = new Apttus_Config2__ProductClassification__c();
        prodClassification.Apttus_Config2__ProductId__c = prodInsertList[0].Id;
        prodClassification.Apttus_Config2__ClassificationId__c = hierarchyList[0].Id;
        Database.insert(prodClassification);
          
        hierarchyList[0].APTS_CategoryHierarchyOfferingExtId__c = APTS_CPQConstants.CAT_HYR; 
        hierarchyList[0].APTS_CategoryHierarchyOptionExtId__c = APTS_CPQConstants.PRD_GRP_INDI;
        hierarchyList[1].APTS_CategoryHierarchyOptionExtId__c = APTS_CPQConstants.CAT_HYR_OPTION1;
        System.assertNotEquals('040193',hierarchyList[0].APTS_CategoryHierarchyOfferingExtId__c);   // Added by Rajesh Patel
        System.assertEquals(APTS_CPQConstants.CAT_HYR_OPTION1 ,hierarchyList[1].APTS_CategoryHierarchyOptionExtId__c); // Added by Rajesh Patel
        Database.update(hierarchyList);
                      
                
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.PG_OFFERING, APTS_CPQConstants.PG_COFFEE);
        Database.insert(pDstGrpStgs);
        
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs0 = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.PG_OFFER_O4, APTS_CPQConstants.PG_MACH);
        Database.insert(pDstGrpStgs0);
        
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs1 = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.AG_OFFERING, APTS_CPQConstants.AG_MATCH);
        Database.insert(pDstGrpStgs1);
        
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs2 = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.PG_NAME_TIME, APTS_CPQConstants.PG_RES);
        Database.insert(pDstGrpStgs2);
        
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs3 = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.AG_OPTION, APTS_CPQConstants.AG_ONETIME);
        Database.insert(pDstGrpStgs3);
        
        APTS_ProdDistributionGroupSettings__c pDstGrpStgs4 = TestDataFactory.createProdDistbGrpStgs(APTS_CPQConstants.AG_NAME, APTS_CPQConstants.AG_ALLINCOVERAGE);
        Database.insert(pDstGrpStgs4);
        
        Apttus_Config2__FieldExpression__c fe = new Apttus_Config2__FieldExpression__c();
        fe.Name = APTS_CPQConstants.EXPRES_TEST;
        Database.insert(fe);
        
        Apttus_Config2__FrequencyConversionRate__c fCR = new Apttus_Config2__FrequencyConversionRate__c();
        fCR.Apttus_Config2__ProductId__c= prodInsertList[0].Id; 
        fCR.APTS_ProductCode__c = prodInsertList[0].ProductCode;
        fCR.Apttus_Config2__FromFrequency__c= APTS_CPQConstants.LABEL_MONTHLY;
        fCR.Apttus_Config2__ToFrequency__c= APTS_CPQConstants.LABEL_MONTHLY;
        insert fCR;
        
        Apttus_Config2__ProductTranslation__c prodTrans=new Apttus_Config2__ProductTranslation__c();
        prodTrans.Name= APTS_CPQConstants.TEST_TRANS;
        prodTrans.Apttus_Config2__ProductCode__c=prodInsertList[0].ProductCode;
        insert prodTrans;
        
        APTS_Sales_Org_Data__c sOD = TestDataFactory.createSlsOrgData(APTS_CPQConstants.TEST_SALES_ORG, APTS_CPQConstants.CODE_0333, prodInsertList[0].Id, APTS_CPQConstants.SAP_01);
        Database.insert(sOD);
        
        APTS_Sales_Org_Data__c sOD1 = TestDataFactory.createSlsOrgData(APTS_CPQConstants.TEST_SALES_ORG,APTS_CPQConstants.USR_SALES_ORG, prodInsertList[1].Id, APTS_CPQConstants.SAP_01);
        Database.insert(sOD1);
        
        APTS_MARA_MVKE_Status_Mapping__c mMSM = new APTS_MARA_MVKE_Status_Mapping__c();
        mMSM.Name = APTS_CPQConstants.BL_SAP_01;
        mMSM.APTS_MARA_MVKE_Field_Combination__c = APTS_CPQConstants.BL_SAP_01;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_MARA_MVKE_Addition_Removal__c = true;
        mMSM.APTS_Has_PLI_active_PLI__c = true;
        mMSM.APTS_Visible_in_Catalogue__c = false;
        Database.insert(mMSM); 
        
        Apttus_Config2__ProductAttributeGroup__c attributeGroup = new Apttus_Config2__ProductAttributeGroup__c();
        attributeGroup.Name = APTS_CPQConstants.TEST_ATT_GRP;
        attributeGroup.Apttus_Config2__BusinessObject__c = APTS_CPQConstants.APTS_PAV;
        attributeGroup.APTS_AttributeGroupExtId__c = APTS_CPQConstants.AG_MACH;
        Database.insert(attributeGroup); 
        
        Apttus_Config2__ProductAttribute__c prodAttr = new Apttus_Config2__ProductAttribute__c();
        prodAttr.Apttus_Config2__AttributeGroupId__c = attributeGroup.Id;
        prodAttr.Apttus_Config2__Field__c = APTS_CPQConstants.TEST_NM;
        prodAttr.Apttus_Config2__Sequence__c = 0;
        Database.insert(prodAttr); 
        
        Apttus_Config2__ProductAttributeGroupMember__c prodGroupMem = new Apttus_Config2__ProductAttributeGroupMember__c ();
         prodGroupMem.Apttus_Config2__AttributeGroupId__c= attributeGroup.Id;
         prodGroupMem.Name=attributeGroup.Name;
         prodGroupMem.Apttus_Config2__ProductId__c=prodInsertList[2].Id;
         prodGroupMem.Apttus_Config2__Sequence__c=0;
         Database.insert(prodGroupMem); 
        
        prodGrp = TestDataFactory.createprodGrp(APTS_CPQConstants.TEST_PRD_GRP, APTS_CPQConstants.PG_RES);
        Database.insert(prodGrp);
        
        Apttus_Config2__ProductGroup__c prodGrp0 = TestDataFactory.createprodGrp(APTS_CPQConstants.TEST_PRD_GRP, APTS_CPQConstants.AG_MACH);
        Database.insert(prodGrp0);
        
        Apttus_Config2__ProductGroup__c prodGrp1 = TestDataFactory.createprodGrp(APTS_CPQConstants.TEST_PRD_GRP, APTS_CPQConstants.AG_ONETIME);
        Database.insert(prodGrp1);
      
        Apttus_Config2__ProductGroupMember__c prodGrpMbr = new Apttus_Config2__ProductGroupMember__c();
        prodGrpMbr.Apttus_Config2__ProductId__c = prodInsertList[2].Id; 
        prodGrpMbr.Apttus_Config2__ProductGroupId__c = prodGrp.Id; 
        prodGrpMbr.Apttus_Config2__Sequence__c = 0;
        Database.insert(prodGrpMbr);
        
        //Database.UpsertResult[] srList = Database.upsert(hierarchyList,false);
        //APTS_ProductRedistributionBatchHandler.getUpsertErrorDetails(srList,batchErrorsMap,'Error');
        
    }
    //Test Method to test the "APTS_ProductRedistributionBatch" Class
    @isTest
    static void testProdClassDelink(){
        Test.startTest();
        APTS_ProductRedistributionBatch prodDstBtch = new APTS_ProductRedistributionBatch();
        prodDstBtch.query = APTS_ProductRedistributionBatchHandler.getObjectQuery('Product2')+' WHERE APTS_Upserted_from_SAP__c=TRUE';
        DataBase.executeBatch(prodDstBtch); 
        
        Set<string> statusList=new Set<String>();
        statusList.add('Completed');
        statusList.add('Aborted');
        System.assert(statusList != null); // Added by Rajesh Patel
        AsyncApexJob job=[Select Id,JobType,ApexClassId, ApexClass.Name, Status,JobItemsProcessed,TotalJobItems,
        NumberOfErrors,CompletedDate,MethodName,ExtendedStatus,ParentJobId,LastProcessed,LastProcessedOffset 
        from AsyncApexJob where Status not in : statusList];
        APTS_ProductRedistributionBatchHandler.sendEmail(job);
        List<id> prodids = new List<id>();
        for(Product2 p : [Select id from Product2])
        {
        prodids.add(p.id);
        }
        //APTS_ProductRedistributionBatchHandler.runMaintenanceBatches(prodids);
        APTS_ProductRedistributionBatchHandler.getCodesSet('testset');
        APTS_ProductRedistributionBatchHandler.createMemberRecord(prodGrp.id,prodids[0]);
        APTS_ProductRedistributionBatchHandler.changeStringToListValue('part1,part2');
        //prodDstBtch.execute(,);
        Test.stopTest();       
    }

}