src/objects/APTS_Agreement_PO_Details__c.object
<CustomObject>
    <label>Agreement PO Detail</label>
    <nameField>
        <displayFormat>PO-{00}</displayFormat>
        <label>PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement PO Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Agreement_Number__c</fullName>
        <description>FOR INTERNAL USE ONLY. DO NOT USE IN SCREENS, REPORTS, ETC.</description>
        <label>Agreement Number_Num (INTERNAL)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Asset Line Items (Physical Asset)</relationshipLabel>
        <relationshipName>Asset_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_relatedlist_agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last related Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items (Last related Agreement)</relationshipLabel>
        <relationshipName>Asset_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>PONumberMachines__c</fullName>
        <description>This indicates the PO number for machine orders.</description>
        <label>PO Number (Machines)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PONumberRequiredMachines__c</fullName>
        <description>This indicates whether a PO Number is required for machine orders.</description>
        <label>PO Number Required (Machines)?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberRequiredServices__c</fullName>
        <label>PO Number Required (Services)?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberServices__c</fullName>
        <description>This indicates the PO number for machine services.</description>
        <label>PO Number (Services)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PONumberTypeMachines__c</fullName>
        <description>This indicates whether a PO Number for machine orders is fixed or variable.</description>
        <label>PO Number Type (Machines)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PONumberTypeServices__c</fullName>
        <description>This indicates whether a PO Number for machine servies is fixed or variable.</description>
        <label>PO Number Type (Services)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Variable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProcessAssetsBatch.cls
/*******************************************************************************************
Name            : APTS_ProcessAssetsBatch
Created By      : Kushal Bhalodiya
Created Date    : 03/07/2019
Description     : Batch to update the Asset Line Items and Physical Assets on Agreement Activation.
Version history : v1.0 - Created.
Test Class      : APTS_AgreementTriggerHandlerTest
*********************************************************************************************/
global class APTS_ProcessAssetsBatch implements Database.Batchable<sObject> {
	
	public Set<ID> agreementIdSet;
	public Map<String, Id> agreementNoToIdMap;
	public Map<String, APTS_Agreement_PO_Details__c> agreementPODetailsMap;
	
	global APTS_ProcessAssetsBatch(Set<ID> agreementIdSet, Map<String, Id> agreementNoToIdMap, Map<String, APTS_Agreement_PO_Details__c> agreementPODetailsMap) {
		this.agreementIdSet = agreementIdSet;
		this.agreementNoToIdMap = agreementNoToIdMap;
		this.agreementPODetailsMap = agreementPODetailsMap;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT Id, APTS_relatedlist_agreement__c, Apttus_CMConfig__AgreementId__r.Apttus__Agreement_Number__c, ';
		query += 'APTS_Physical_Asset__r.PONumberMachines__c, APTS_Physical_Asset__r.PONumberRequiredMachines__c, ';
		query += 'APTS_Physical_Asset__r.PONumberTypeMachines__c, APTS_Physical_Asset__r.PONumberServices__c, ';
		query += 'APTS_Physical_Asset__r.PONumberRequiredServices__c, APTS_Physical_Asset__r.PONumberTypeServices__c, ';
        query += 'Apttus_CMConfig__AgreementId__c, APTS_Physical_Asset__c FROM Apttus_Config2__AssetLineItem__c ';
        query += 'WHERE Apttus_CMConfig__AgreementId__c IN: agreementIdSet';
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Apttus_Config2__AssetLineItem__c> assetLineItemList) {
   		
   		APTS_CLMUtil.updateAssetsOnAgreementActivation(assetLineItemList, agreementIdSet, agreementNoToIdMap, agreementPODetailsMap);
	}

	global void finish(Database.BatchableContext BC) {
		
	}
}