src/objects/APTS_CounterReadingData__c.object
<CustomObject>
    <description>by TS for OTC ( Consumption model) , please align with TS on usage/ before creating an alternative..</description>
    <fields>
        <fullName>APTS_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Counter Reading Data</relationshipLabel>
        <relationshipName>Asset_Counter_Reading_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Atrribute_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__AssetAttributeValue__c</referenceTo>
        <relationshipLabel>Asset Counter Reading Data</relationshipLabel>
        <relationshipName>Asset_Counter_Reading_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Counter Reading Data</label>
    <nameField>
        <displayFormat>Counter-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Counter Reading Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <description>ID of the associated asset line item</description>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Attribute Values</relationshipLabel>
        <relationshipName>AssetAttributeValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Batch_Billing_Schedules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine if the record was processed by the Billing Schedules batch</description>
        <label>Batch Billing Schedules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <inlineHelpText>ID of the associated product attribute value</inlineHelpText>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__AssetAttributeValue__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BundleAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated bundle line item.</description>
        <inlineHelpText>ID of the associated bundle line item.</inlineHelpText>
        <label>Bundle Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Option Asset Line Items</relationshipLabel>
        <relationshipName>OptionAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BusinessLineItemId__c</fullName>
        <description>Line Item Id  of the business object like agreement line item or proposal line item.</description>
        <inlineHelpText>Line Item Id  of the business object like agreement line item or proposal line item.</inlineHelpText>
        <label>Business Line Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsInactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the asset is inactive.</description>
        <inlineHelpText>Indicates whether the asset is inactive.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ParentAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the direct parent asset.</description>
        <inlineHelpText>The ID of the direct parent asset.</inlineHelpText>
        <label>Parent Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Child Asset Line Items</relationshipLabel>
        <relationshipName>ChildAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <fields>
        <fullName>APTS_Migrated_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Migrated ALI(for data migration)</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Order Line Items (Migrated ALI(for data migration))</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated asset line item.</description>
        <inlineHelpText>ID of the associated asset line item.</inlineHelpText>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__OrderProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2_AssetAdjustItem__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2_AssetLineItemId__c</fullName>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Adjustment Line Item</relationshipLabel>
        <relationshipName>Asset_Adjustment_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Adjustment Line Item</label>
    <nameField>
        <label>Asset Adjustment Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Adjustment Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_ScriptBatchHelper.cls
public class APTS_ScriptBatchHelper {
    public static void processOrderLineItems(List<Apttus_Config2__OrderLineItem__c> lstOrderLineItem,String AttributeValueFields, String assetAdjLineItemFields){
        List<Database.SaveResult> srList = new List<Database.SaveResult>();        
        Map<Id,Id> mapOLIOldALI = new Map<Id,Id>();
        Map<Id,Id> mapMigratedAssetNewAsset = new Map<Id,Id>();
        Map<Id,Id> mapNewAssetMigratedParentAsset = new Map<Id,Id>();
        Map<Id,Id> mapNewAssetMigratedBundleAsset = new Map<Id,Id>();
        Map<Id,Id> mapNewAssetNewAttribute = new Map<Id,Id>(); 
        Set<Id> oldAssetIds = new Set<Id>();
        Set<Id> newAssetIds = new Set<Id>();
        
        //Loop over the order line items and create map for Old ALI and new ALI
        for(Apttus_Config2__OrderLineItem__c currentOLI : lstOrderLineItem){ 
            mapMigratedAssetNewAsset.put(currentOLI.APTS_Migrated_Asset_Line_Item__c,currentOLI.Apttus_Config2__AssetLineItemId__c);
            mapNewAssetMigratedParentAsset.put(currentOLI.Apttus_Config2__AssetLineItemId__c,currentOLI.APTS_Migrated_Asset_Line_Item__r.Apttus_Config2__ParentAssetId__c);
            mapNewAssetMigratedBundleAsset.put(currentOLI.Apttus_Config2__AssetLineItemId__c,currentOLI.APTS_Migrated_Asset_Line_Item__r.Apttus_Config2__BundleAssetId__c);
            mapOLIOldALI.put(currentOLI.Id, currentOLI.APTS_Migrated_Asset_Line_Item__c);
            oldAssetIds.add(currentOLI.APTS_Migrated_Asset_Line_Item__c);
            newAssetIds.add(currentOLI.Apttus_Config2__AssetLineItemId__c);
        }
        List<Apttus_Config2__AssetLineItem__c> lstNewALI = new List<Apttus_Config2__AssetLineItem__c>();
        lstNewALI =[SELECT Id, Apttus_CMConfig__AgreementId__c,Apttus_Config2__BusinessLineItemId__c,Apttus_Config2__BundleAssetId__c,Apttus_Config2__ParentAssetId__c FROM Apttus_Config2__AssetLineItem__c WHERE id IN: newAssetIds OR Apttus_Config2__BundleAssetId__c IN: mapMigratedAssetNewAsset.keyset() OR Apttus_Config2__ParentAssetId__c IN : mapMigratedAssetNewAsset.keyset()];
       
        //Query for Old Asset Attribute Value records
        System.debug('lstNewALI>>>>'+lstNewALI);
        String strQueryAssetAttribute = 'SELECT ' + AttributeValueFields + ' FROM Apttus_Config2__AssetAttributeValue__c WHERE Apttus_Config2__AssetLineItemId__c in : oldAssetIds';
        
        System.debug('strQueryAssetAttribute---'+strQueryAssetAttribute);       
        List<Apttus_Config2__AssetAttributeValue__c> lstAttributeValue = Database.query(strQueryAssetAttribute);
        List<Apttus_Config2__AssetAttributeValue__c> lstNewAttributeValue = new List<Apttus_Config2__AssetAttributeValue__c>();
        Apttus_Config2__AssetAttributeValue__c tempAV;
        //cloning asset attribute value
        if(lstAttributeValue.size() > 0){
            for(Apttus_Config2__AssetAttributeValue__c attributeRecord : lstAttributeValue){
                tempAV = attributeRecord.clone(false, true, false, false);
                if(mapMigratedAssetNewAsset.containsKey(attributeRecord.Apttus_Config2__AssetLineItemId__c))
                    tempAV.Apttus_Config2__AssetLineItemId__c = mapMigratedAssetNewAsset.get(attributeRecord.Apttus_Config2__AssetLineItemId__c);
                lstNewAttributeValue.add(tempAV);
            }
        }   
         System.debug('lstNewAttributeValue>>>'+lstNewAttributeValue);      
        //Insert cloned records
        if(lstNewAttributeValue.size()>0){
            srList = Database.insert(lstNewAttributeValue, false);
        }
        System.debug('srList>>>'+srList); 
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully created AssetAttributeValue. AssetAttributeValue Id: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }
        
        for(Apttus_Config2__AssetAttributeValue__c newAttribute : lstNewAttributeValue){
            mapNewAssetNewAttribute.put(newAttribute.Apttus_Config2__AssetLineItemId__c, newAttribute.id); 
        }
                        
        List<Apttus_Config2__AssetLineItem__c>  updateALI = new List<Apttus_Config2__AssetLineItem__c>();   
        for(Apttus_Config2__AssetLineItem__c newAsset : lstNewALI){ 
            if(mapNewAssetNewAttribute.containsKey(newAsset.id)){
                newAsset.Apttus_Config2__AttributeValueId__c = mapNewAssetNewAttribute.get(newAsset.id);                
            }
            if(mapMigratedAssetNewAsset.get(mapNewAssetMigratedParentAsset.get(newAsset.id)) != null){
                newAsset.Apttus_Config2__ParentAssetId__c = mapMigratedAssetNewAsset.get(mapNewAssetMigratedParentAsset.get(newAsset.id));
            }
            if(mapMigratedAssetNewAsset.get(mapNewAssetMigratedBundleAsset.get(newAsset.id)) != null){
                newAsset.Apttus_Config2__BundleAssetId__c = mapMigratedAssetNewAsset.get(mapNewAssetMigratedBundleAsset.get(newAsset.id));
            }       
            // Changes to Defect: #18247 - Update Option Asset to New Asset 
            if(mapMigratedAssetNewAsset.containskey(newAsset.Apttus_Config2__BundleAssetId__c)){
                newAsset.Apttus_Config2__BundleAssetId__c = mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__BundleAssetId__c);
            }
            if(mapMigratedAssetNewAsset.containskey(newAsset.Apttus_Config2__ParentAssetId__c)){
                newAsset.Apttus_Config2__ParentAssetId__c = mapMigratedAssetNewAsset.get(newAsset.Apttus_Config2__ParentAssetId__c);
            }           
            updateALI.add(newAsset);
        }
        System.debug('updateALI>>>'+updateALI);
        if(updateALI.size()>0){
            srList = Database.update(updateALI, false); 
        }
        
        //Query for Old Asset Adjustment Line Item records
        String strQueryAssetAdjLineItem = 'SELECT ' + assetAdjLineItemFields + ' FROM Apttus_Config2_AssetAdjustItem__c WHERE Apttus_Config2_AssetLineItemId__c in : oldAssetIds';
        
        System.debug('strQueryAssetAdjLineItem---'+strQueryAssetAdjLineItem);       
        List<Apttus_Config2_AssetAdjustItem__c> lstAssetAdjLineItem = Database.query(strQueryAssetAdjLineItem);
        List<Apttus_Config2_AssetAdjustItem__c> lstNewAssetAdjLineItem = new List<Apttus_Config2_AssetAdjustItem__c>();
        Apttus_Config2_AssetAdjustItem__c tempAALI;
        //cloning asset adjustment line item
        if(lstAssetAdjLineItem.size() > 0){
            for(Apttus_Config2_AssetAdjustItem__c assetAdjLineRecord : lstAssetAdjLineItem){
                tempAALI = assetAdjLineRecord.clone(false, true, false, false);
                if(mapMigratedAssetNewAsset.containsKey(assetAdjLineRecord.Apttus_Config2_AssetLineItemId__c))
                    tempAALI.Apttus_Config2_AssetLineItemId__c = mapMigratedAssetNewAsset.get(assetAdjLineRecord.Apttus_Config2_AssetLineItemId__c);
                lstNewAssetAdjLineItem.add(tempAALI);
            }
        }   
         System.debug('lstNewAssetAdjLineItem>>>'+lstNewAssetAdjLineItem);      
        //Insert cloned records
        if(lstNewAssetAdjLineItem.size()>0){
            srList = Database.insert(lstNewAssetAdjLineItem, false);
        }
        System.debug('srList>>>'+srList); 
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully created Asset Adjustment Line Item. AssetAdjustmentLineItem Id: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }
        
        //Query for Asset Counter Reading Data
        List<APTS_CounterReadingData__c> listAssetCounter = [select id, APTS_Asset_Line_Item__c, APTS_Atrribute_Value__c FROM  APTS_CounterReadingData__c where APTS_Asset_Line_Item__c in : oldAssetIds];
        
        List<APTS_CounterReadingData__c> listNewAssetCounter = new List<APTS_CounterReadingData__c>();
        System.debug('listAssetCounter---'+listAssetCounter);       
        for(APTS_CounterReadingData__c counterReading : listAssetCounter){
            if(mapMigratedAssetNewAsset.containsKey(counterReading.APTS_Asset_Line_Item__c)){
                counterReading.APTS_Asset_Line_Item__c = mapMigratedAssetNewAsset.get(counterReading.APTS_Asset_Line_Item__c);
                counterReading.APTS_Atrribute_Value__c = mapNewAssetNewAttribute.get(mapMigratedAssetNewAsset.get(counterReading.APTS_Asset_Line_Item__c));
                listNewAssetCounter.add(counterReading);
            }           
        }
        System.debug('listNewAssetCounter>>>'+listNewAssetCounter); 
        if(listNewAssetCounter.size()>0){
            srList = Database.update(listNewAssetCounter, false);
        }
        System.debug('srList>>>'+srList); 
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully created Counter reading. Counter reading Id: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }
    }
    
    
    public static void InActivateAssetLineItems(List<Apttus_Config2__OrderLineItem__c> lstOrderLineItem,boolean deleteInActivateALI){  
       Map<Id,Apttus_Config2__AssetLineItem__c> assetLineItemMigratedUpdateMap = new Map<Id,Apttus_Config2__AssetLineItem__c>(); 
        for(Apttus_Config2__OrderLineItem__c currentOLI : lstOrderLineItem){ 
            if(currentOLI.APTS_Migrated_Asset_Line_Item__c != null){
                Apttus_Config2__AssetLineItem__c updateAsset = new Apttus_Config2__AssetLineItem__c(); 
                updateAsset.Id = currentOLI.APTS_Migrated_Asset_Line_Item__c;
                updateAsset.Apttus_Config2__IsInactive__c = true;
                updateAsset.APTS_Batch_Billing_Schedules__c = true;
                assetLineItemMigratedUpdateMap.put(updateAsset.Id,updateAsset);
            }
            
        }
         
        if(assetLineItemMigratedUpdateMap.size()>0){
            if(!deleteInActivateALI){
                update assetLineItemMigratedUpdateMap.values(); 
            }else{
                delete assetLineItemMigratedUpdateMap.values(); 
            } 
        }
        
    }
    
    public static void DeleteOrder(List<Apttus_Config2__Order__c> listOrder){   
        List <Apttus_Config2__Order__c> deleteListOrder  = new List <Apttus_Config2__Order__c>();
        for (Apttus_Config2__Order__c deleteOrder : listOrder ){
            deleteListOrder.add(deleteOrder);
        }
        if(deleteListOrder.size()>0){
            delete deleteListOrder;  
        }            
    }
}