src/objects/APTS_AgreementTotalVolumeObligation__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Total_Volume_Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Estimated_Contract_Value__c</fullName>
        <label>Total Estimated Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Expected_Cost_Amount__c</fullName>
        <label>Total Expected Cost Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Total_Expected_Discount_Amount__c</fullName>
        <label>Total Expected Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Volume Assumption Obligation</label>
    <nameField>
        <displayFormat>ATVO-{00000}</displayFormat>
        <label>APTS_AgreementTotalVolumeObligation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Assumption Obligation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APTS_Warehousing_Cost__c.object
<CustomObject>
    <label>Warehousing Cost</label>
    <nameField>
        <label>Warehousing Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehousing Costs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Base_Extended_Price_2_decimals__c</fullName>
        <label>Base Extended Price – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Depreciation_Cost__c</fullName>
        <label>Depreciation Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Extended_Cost_2_decimals__c</fullName>
        <label>Extended Cost – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Is_Not_Rollup_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Not Rollup Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Net_Adjustment_Amount_2_decimals__c</fullName>
        <label>Net Adjustment Amount – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__ClassificationHierarchy__c</fullName>
        <description>The category hierarchy</description>
        <label>Category Hierarchy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__ExtendedCost__c</fullName>
        <description>The extended cost is Quantity X Term X (Base Cost + Cost Adjustment + Option Cost)</description>
        <inlineHelpText>The extended cost is Quantity X Term X (Base Cost + Cost Adjustment + Option Cost)</inlineHelpText>
        <label>Extended Cost</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <inlineHelpText>Indicates whether the product has options.</inlineHelpText>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__LineType__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                    <default>true</default>
                    <label>Product/Service</label>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__NetPrice__c</fullName>
        <description>The net price for the product or service is the Adjusted Price after applying the Group Adjustment %</description>
        <label>Net Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Adj_EBIT__c</fullName>
        <formula>APTS_Gross_Profit__c -  APTS_Other_Expenses__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Adj. EBIT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Depreciation_Cost__c</fullName>
        <label>Depreciation Cost</label>
        <summarizedField>Apttus__AgreementLineItem__c.APTS_Depreciation_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__LineType__c</field>
            <operation>equals</operation>
            <value>Product/Service</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__HasOptions__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__IsPrimaryLine__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Apttus__AgreementLineItem__c.Apttus__AgreementId__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>APTS_Distribution_Cost__c</fullName>
        <label>Distribution Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_ROS__c</fullName>
        <label>ROS%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Warehousing_Cost__c</fullName>
        <label>Warehousing Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_CalculateROSControllerTest.cls
/**************************************************************
 * @Author: jason.e.mactal
 * @Company: Accenture
 * @Description: Test class for APTS_CalculateROSController
 * @Created Date: May 23, 2018
 * @Revisions:
 *      <Name>              <Date>          <Description>
 *      jason.e.mactal      May 23, 2018     Initial Version
 * 
 *************************************************************/
@isTest
private class APTS_CalculateROSControllerTest {
    
    @testSetup
    static void testSetup() {
        
        User testUser = APTS_TestDataFactory.createUser();
        testUser.Email = 'testuser123@jdecoffee.com';
        system.runAs(testUser){
            Account oAcc = APTS_TestDataFactory.createAccount('Test Account');
            insert oAcc;
            
            Apttus__APTS_Agreement__c oAgg = APTS_TestDataFactory.createAgreement(null, null, oAcc.id, 'Standard Deal');
            oAgg.APTS_Region__c = 'SAP_0111';
            oAgg.APTS_Distribution_Cost__c = 5;
            oAgg.APTS_Warehousing_Cost__c = 8;
            insert oAgg;
            
            Apttus__AgreementLineItem__c oAggLI = new Apttus__AgreementLineItem__c();
            oAggLI.Apttus__AgreementId__c = oAgg.Id;
            oAggLI.Apttus_CMConfig__IsPrimaryLine__c = true;
            oAggLI.Apttus_CMConfig__HasOptions__c = true;
            oAggLI.Apttus_CMConfig__LineType__c = 'Product/Service';
            oAggLI.Apttus__Quantity__c = 1;
            oAggLI.APTS_Depreciation_Cost__c = 15;
            oAggLI.Apttus_CMConfig__ClassificationHierarchy__c = 'Machines';
            insert oAggLI;
            
            Apttus__AgreementLineItem__c oAggLI2 = new Apttus__AgreementLineItem__c();
            oAggLI2.Apttus__AgreementId__c = oAgg.Id;
            oAggLI2.APTS_Is_Not_Rollup_Line__c = true;
            oAggLI2.APTS_Net_Adjustment_Amount_2_decimals__c = 15;
            oAggLI2.APTS_Base_Extended_Price_2_decimals__c = 100;
            oAggLI2.APTS_Extended_Cost_2_decimals__c = 10;
            oAggLI2.Apttus_CMConfig__ExtendedCost__c = 10;
            oAggLI2.Apttus_CMConfig__ClassificationHierarchy__c = 'Machines';
            oAggLI2.Apttus__NetPrice__c = 85;
            insert oAggLI2;
            
            APTS_AgreementTotalVolumeObligation__c oVAO = new APTS_AgreementTotalVolumeObligation__c();
            oVAO.APTS_Total_Expected_Discount_Amount__c = 20;
            oVAO.APTS_Total_Estimated_Contract_Value__c = 200;
            oVAO.APTS_Total_Expected_Cost_Amount__c = 25;
            oVAO.APTS_Agreement__c = oAgg.Id;
            insert OVAO;
        }
        
    }

    private static testMethod void calculateROS() {
        user testUser = [SELECT Id FROM USER WHERE Email = 'testuser123@jdecoffee.com'];
        Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        PageReference pr = page.APTS_CalculateROS;
        pr.getParameters().put('Id', String.valueOf(oAgg.Id));
        
        system.runAs(testUser){
            Test.startTest();
                Test.setCurrentPage(pr);
                ApexPages.StandardController scAgg = new ApexPages.StandardController(oAgg);
                APTS_CalculateROSController cont = new APTS_CalculateROSController(scAgg);
                cont.calculateROS();
            Test.stopTest();
        }
        Apttus__APTS_Agreement__c oAggCheck = [SELECT Id, APTS_ROS__c FROM Apttus__APTS_Agreement__c LIMIT 1];
        system.assert(oAggCheck.APTS_ROS__c!=null && oAggCheck.APTS_ROS__c!=0);

    }
    private static testMethod void negativeTest() {
        user testUser = [SELECT Id FROM USER WHERE Email = 'testuser123@jdecoffee.com'];
        Apttus__APTS_Agreement__c oAgg = [SELECT Id, APTS_Adj_EBIT__c FROM Apttus__APTS_Agreement__c LIMIT 1];
        PageReference pr = page.APTS_CalculateROS;
        pr.getParameters().put('Id', String.valueOf(oAgg.Id));
        
        try{
        system.runAs(testUser){
            Test.startTest();
                oAgg.APTS_Distribution_Cost__c = 0;
                update oAgg;
                Test.setCurrentPage(pr);
                ApexPages.StandardController scAgg = new ApexPages.StandardController(oAgg);
                APTS_CalculateROSController cont = new APTS_CalculateROSController(scAgg);
                cont.calculateROS();
                cont.doCancel();
            Test.stopTest();
        }
        }catch(exception e){
            system.assert(e.getMessage().contains(Label.APTS_ROSCalculationError));
        }

    }

}