src/objects/APTS_Sales_Org_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Distribution_chain_specific_materia__c</fullName>
        <label>Distribution-chain-specific material sta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_01</fullName>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>SAP_02</fullName>
                    <label>Blocked for selling</label>
                </value>
                <value>
                    <fullName>SAP_03</fullName>
                    <label>Warning when selling</label>
                </value>
                <value>
                    <fullName>SAP_04</fullName>
                    <label>New product</label>
                </value>
                <value>
                    <fullName>SAP_05</fullName>
                    <label>OOS prolonged</label>
                </value>
                <value>
                    <fullName>SAP_06</fullName>
                    <label>Only some customers</label>
                </value>
                <value>
                    <fullName>SAP_07</fullName>
                    <label>To sell old stocks</label>
                </value>
                <value>
                    <fullName>SAP_08</fullName>
                    <label>Product for deletion</label>
                </value>
                <value>
                    <fullName>SAP_09</fullName>
                    <label>Generic</label>
                </value>
                <value>
                    <fullName>SAP_10</fullName>
                    <label>Obsolete to consult</label>
                </value>
                <value>
                    <fullName>SAP_11</fullName>
                    <label>Only for catalog</label>
                </value>
                <value>
                    <fullName>SAP_12</fullName>
                    <label>End of service</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <isActive>false</isActive>
                    <label>01</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <isActive>false</isActive>
                    <label>02</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <isActive>false</isActive>
                    <label>03</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <isActive>false</isActive>
                    <label>04</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <isActive>false</isActive>
                    <label>05</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <isActive>false</isActive>
                    <label>06</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <isActive>false</isActive>
                    <label>07</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <isActive>false</isActive>
                    <label>08</label>
                </value>
                <value>
                    <fullName>09</fullName>
                    <isActive>false</isActive>
                    <label>09</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <isActive>false</isActive>
                    <label>10</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <isActive>false</isActive>
                    <label>11</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <isActive>false</isActive>
                    <label>12</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <formula>APTS_Product__r.APTS_Material_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Material Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Org Datas</relationshipLabel>
        <relationshipName>Sales_Org_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org_Data_Name__c</fullName>
        <inlineHelpText>This field MUST have the 4 digit code of the Sales Org, and this field must be populated as it’s required by the Pricing Batch</inlineHelpText>
        <label>Sales Org Data Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Org Data</label>
    <nameField>
        <displayFormat>SOD-{00000000}</displayFormat>
        <label>Sales Org Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Org Datas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Triggered_Timestamp__c</fullName>
        <description>Trigger date time from Salesforce.</description>
        <inlineHelpText>Trigger date time from Salesforce.</inlineHelpText>
        <label>Triggered Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Line Item</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Click_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to know if this record were already synchronized with Click.</description>
        <inlineHelpText>Indicator to know if this record were already synchronized with Click.</inlineHelpText>
        <label>Click Synchronized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TS_Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <description>SAP Material Type, Used in EPI Integration
/ZMATMAS03I/IDOC/E1MARAM/MTART</description>
        <label>Material_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TS_PriceBookEntrySyncToClick_Test.cls
/*
* @author        Marvin Gatchalian
* @date          9.mar.2018          
* @description   Test class for TS_PriceBookEntrySyncToClick this method has been called from Trigger
* @revision(s)
*/


@isTest
public with sharing class TS_PriceBookEntrySyncToClick_Test {

	public static void dataSetup() {
		//Create Product
		product2 p = new product2();
		p.Name = 'KTS-1028';
		p.APTS_Material_Type__c = 'ZSPR';
        p.IsActive = true;
		insert p;
		
		//Create sales org pricebook
		pricebook2 orgPB = new pricebook2();
		orgPB.name = 'BE Price Book';
		orgPB.IsActive = true;
		orgPB.Sales_Organization__c = 'SAP_0333';
		insert orgPB;
		
		//Create Pricebookentry with standard and sales org pricebook
		Pricebookentry pbe = new pricebookentry();
		pbe.product2id = p.id;
		pbe.pricebook2id = Test.getStandardPricebookId();
		pbe.UnitPrice = 1;
		pbe.IsActive = true;
		pbe.TS_Load_Id__c = String.valueOf(p.id) + String.valueOf(Test.getStandardPricebookId());
		insert pbe;
		
		Pricebookentry pbe2 = new pricebookentry();
		pbe2.product2id = p.id;
		pbe2.pricebook2id = orgPB.id;
		pbe2.UnitPrice = 11;
		pbe2.IsActive = true;
		pbe2.TS_Load_Id__c = String.valueOf(p.id) + String.valueOf(orgPB.id);
		insert pbe2;
        
        APTS_Sales_Org_Data__c aptsData = new APTS_Sales_Org_Data__c();
        aptsData.APTS_Sales_Org_Data_Name__c = '0333';
        aptsData.APTS_Product__c = p.id;   
		aptsData.APTS_Distribution_chain_specific_materia__c = 'SAP_01';
        insert aptsData;
            
    }

    private static testMethod void TS_PriceBookEntrySyncToClick() {
		dataSetup();
		
		Test.startTest();
			DescribeSObjectResult priceBookEntries = pricebookentry.getSObjectType().getDescribe();
	    	List <String> fields = new List<String>(priceBookEntries.fields.getMap().keySet());
	    	List <pricebookentry> pbeRecords  = new List <pricebookentry>();
	        pbeRecords = Database.query('SELECT ' + String.join(fields,',') + 
	           							' FROM ' + priceBookEntries.getName() + 
	    	   							' WHERE TS_Click_Synchronized__c = false AND TS_Load_Id__c != null');
	    	
	    	Map <pricebookentry, Integration_Log__c> priceBookEntryIntegrationLogMap = new 
	        Map <pricebookentry, Integration_Log__c>();
	    	   							
			for(PricebookEntry eachPriceBookEntry :pbeRecords) {
	            if (!eachPriceBookEntry.TS_Click_Synchronized__c) {
	            	
	            	Integration_Log__c integLog = new Integration_Log__c();
	            	
	                integLog.Object_Id__c = eachPriceBookEntry.Id;
	                integLog.Object__c = INT_Constants.CLICK_SYNCMASTERPRODUCT;
	                integLog.Integration_Status__c = INT_Constants.INITIAL;
	                integLog.Triggered_Timestamp__c = Datetime.now();
	                
	                eachPriceBookEntry.TS_Click_Synchronized__c = true;
	                
	                priceBookEntryIntegrationLogMap.put(eachPriceBookEntry, integLog);
	            }
			}
			if (!priceBookEntryIntegrationLogMap.values().isEmpty()) {
				insert priceBookEntryIntegrationLogMap.values();
				
				List<Integration_Log__c> updatedIlogList = [SELECT Id, Integration_Status__c, Work_Order_Line_Item__c, Object__c, Object_Id__c
	                                                    	 FROM Integration_Log__c WHERE Object__c =: INT_Constants.CLICK_SYNCMASTERPRODUCT];
	        	
	        	TS_PriceBookEntrySyncToClick.hasException=true;
                TS_PriceBookEntrySyncToClick sendToClick = new TS_PriceBookEntrySyncToClick();
	        	sendToClick.executeSendPartType(updatedIlogList);
			}
			if (!pbeRecords.isEmpty()) update pbeRecords;
				
			system.assertequals(pbeRecords[0].TS_Click_Synchronized__c, true);
		Test.stopTest();
	    	
    }
}