src/objects/APTS_Agreement_Budget__c.object
<CustomObject>
    <description>Agreement Budget</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <description>Budget created for agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Budgets</relationshipLabel>
        <relationshipName>Agreement_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Budget</label>
    <nameField>
        <displayFormat>AB-{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APTS_Agreement_PO_Details__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_PO_Detailss</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Agreement PO Detail</label>
    <nameField>
        <displayFormat>PO-{00}</displayFormat>
        <label>PO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement PO Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APTS_AgreementTotalVolumeObligation__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Total_Volume_Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volume Assumption Obligation</label>
    <nameField>
        <displayFormat>ATVO-{00000}</displayFormat>
        <label>APTS_AgreementTotalVolumeObligation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Assumption Obligation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APTS_AgreementVolumeObligation__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Volume_Obligations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Volume Assumption Obligation Schedule</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Agreement Volume Obligation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume Assumption Obligation Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Fixed_Term_Frequency__c</fullName>
        <label>Fixed Term Settlement Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                    <default>true</default>
                    <label>Yearly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Fixed_Term_Startdate__c</fullName>
        <defaultValue>Date(1990,1,1)</defaultValue>
        <label>Fixed Term Settlement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Fixed_Term_Type__c</fullName>
        <description>Type of fixed term</description>
        <label>Fixed Term Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Cost</fullName>
                </value>
                <value>
                    <fullName>All Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed Costs and Ingredients</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Subtype__c</fullName>
        <description>The subtype of the agreement for a given agreement type</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>Fixed-Term-Fixed Costs</fullName>
                </value>
                <value>
                    <fullName>Fixed Term-Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed Term-Both Fixed Costs and Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed End Date</fullName>
                </value>
                <value>
                    <fullName>3+1+1</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fixed_Terms_Internal_Freq__c</fullName>
        <label>Fixed Terms Internal Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                    <default>true</default>
                    <label>Quarterly</label>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kpi_internal_freq__c</fullName>
        <label>KPI / SLA internal Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                    <default>true</default>
                    <label>Quarterly</label>
                </value>
                <value>
                    <fullName>Half Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>volume_obligation_internal_freq__c</fullName>
        <label>Volume Obligation Internal Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                    <default>true</default>
                    <label>Quarterly</label>
                </value>
                <value>
                    <fullName>Half yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_ComplianceTask_Test.cls
@isTest
public class APTS_ComplianceTask_Test {
  @testSetup
   static void testData()
   {   
   
       APTS_ComplianceTaskBatch.todayDate = 1;
       
       /*Test Records creation for Monthly Frequency*/
       Account monthlyTestAccount = new Account();
       monthlyTestAccount.Name = 'Monthly Test Account';
       monthlyTestAccount.Phone = '+919898468401';
       monthlyTestAccount.Main_Street_Only__c = 'Test Street';
       monthlyTestAccount.Main_House_Number__c = 'Test no.';
       monthlyTestAccount.billingcountry = 'Netherlands';
       Database.Insert(monthlyTestAccount);
       
       Id RecId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Standard Deal').getRecordTypeId();
       
       Apttus__APTS_Agreement__c monthlyTestAgreement = new Apttus__APTS_Agreement__c(Apttus__Account__c = monthlyTestAccount.Id, 
                        Name = 'Monthly Test Agreement',RecordTypeId = RecId,
                        Apttus__Contract_Start_Date__c = Date.today() - 10, Apttus__Contract_End_Date__c = Date.today() + 7,
                        APTS_Fixed_Term_Startdate__c = Date.today(),                  
                        Apttus__Subtype__c ='Fixed-Term-Fixed Costs',
                        Apttus__Status_Category__c = 'In Effect', Apttus__Status__c = 'Activated', APTS_Fixed_Term_Type__c = 'Fixed Cost', Fixed_Terms_Internal_Freq__c = 'Monthly', kpi_internal_freq__c = 'Monthly', volume_obligation_internal_freq__c = 'Monthly', APTS_Fixed_Term_Frequency__c = 'Quarterly', budget_internal_freq__c = 'Monthly', volume_obligation_internal_triggerpoint__c = 90);
        Database.Insert(monthlyTestAgreement);
        
         Apttus__APTS_Agreement__c KPISLATestAgreement = new Apttus__APTS_Agreement__c(Apttus__Account__c = monthlyTestAccount.Id, 
                        Name = 'KPISLA Test Agreement',RecordTypeId = RecId,
                        Apttus__Contract_Start_Date__c = Date.today() - 10, Apttus__Contract_End_Date__c = Date.today() + 7,
                        APTS_Fixed_Term_Startdate__c = Date.today(),                  
                        Apttus__Subtype__c ='Fixed-Term-Fixed Costs',
                        Apttus__Status_Category__c = 'In Effect', Apttus__Status__c = 'Activated', APTS_Fixed_Term_Type__c = 'Fixed Cost', Fixed_Terms_Internal_Freq__c = 'Monthly', kpi_internal_freq__c = 'Monthly', volume_obligation_internal_freq__c = 'Monthly', APTS_Fixed_Term_Frequency__c = 'Quarterly', budget_internal_freq__c = 'Monthly', volume_obligation_internal_triggerpoint__c = 90);
        Database.Insert(KPISLATestAgreement);
       
       APTS_Agreement_Budget__c monthlyAgreeBudget = new APTS_Agreement_Budget__c(APTS_Category__c = 'Promotions', APTS_Subcategory__c = 'Merchandise', APTS_Start_Date__c = System.today() - 5, APTS_End_Date__c = System.today() + 5, Agreement__c = monthlyTestAgreement.Id);
       Database.Insert(monthlyAgreeBudget);
       
       Contracted_kpi_sla__c monthlyKPISLA = new Contracted_kpi_sla__c(kpi_contract__c = KPISLATestAgreement.Id, KPI_type__c = 'Availability % per machine', kpi_frequency__c = 'Monthly');
       Database.Insert(monthlyKPISLA);
       
       APTS_AgreementTotalVolumeObligation__c MonthlyAgrTotalVolObl = new APTS_AgreementTotalVolumeObligation__c(APTS_Agreement__c = monthlyTestAgreement.Id);
       Database.Insert(MonthlyAgrTotalVolObl);
       
       APTS_AgreementVolumeObligation__c monthlyAgrVolObl = new APTS_AgreementVolumeObligation__c(APTS_Agreement__c = monthlyTestAgreement.Id, APTS_Start_Date__c = System.today() - 10, APTS_End_Date__c = System.today() + 10, APTS_Volume_Obligation__c = 1000);
       Database.Insert(monthlyAgrVolObl);
        
       APTS_Agreement_PO_Details__c poDetails = new APTS_Agreement_PO_Details__c(APTS_PO_Number_Required__c = 'Yes', APTS_PO_Number_Type__c = 'Fixed', APTS_PO_Expiration_Date__c = System.Today()+7, APTS_Agreement__c = monthlyTestAgreement.Id);
       Database.insert(poDetails);
       
   }
   static testMethod void createMonthlyComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-2), System.Today().Day());
    Date secondQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-5), System.Today().Day());
    Date thirdQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date foruthQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c monthlyTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];    
                                                      
    Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];                                                   
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =: monthlyTestAgreement.Id                                                         LIMIT 1];
   
   APTS_Agreement_PO_Details__c poDetails = [SELECT APTS_PO_Number_Required__c, APTS_PO_Number_Type__c, APTS_PO_Expiration_Date__c, APTS_Agreement__c
                                             FROM APTS_Agreement_PO_Details__c WHERE APTS_Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
   
   /* ---------- Start of PI fix # 718083 ----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('FIXED TERM CHECK',tsklst[0].Touchpoint_Type__c);  
   /* ---------- End of PI fix # 718083----------------------- */  
                                                        
   }
   
   static testMethod void createFirstQuarterComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-2), System.Today().Day());
    Date secondQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-5), System.Today().Day());
    Date thirdQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date foruthQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c firstQuarterTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      firstQuarterTestAgreement.Apttus__Contract_Start_Date__c = firstQuarter;
                                                      firstQuarterTestAgreement.APTS_Fixed_Term_Startdate__c = firstQuarter;
                                                      firstQuarterTestAgreement.Fixed_Terms_Internal_Freq__c = 'Quarterly';
                                                      firstQuarterTestAgreement.kpi_internal_freq__c = 'Quarterly';
                                                      firstQuarterTestAgreement.APTS_Fixed_Term_Frequency__c = 'Quarterly'; 
                                                      firstQuarterTestAgreement.budget_internal_freq__c = 'Quarterly';
                                                      firstQuarterTestAgreement.volume_obligation_internal_freq__c = 'Quarterly';
                                                      Database.update(firstQuarterTestAgreement);
                                                      
    Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = firstQuarter1;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: firstQuarterTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Quarterly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: firstQuarterTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =: firstQuarterTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
   
   /* ---------- Start of PI fix # 718083----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('FIXED TERM CHECK',tsklst[0].Touchpoint_Type__c);
   /* ---------- End of PI fix # 718083----------------------- */ 
                                                        
   }
   
   static testMethod void createSecondQuarterComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-2), System.Today().Day());
    Date secondQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-5), System.Today().Day());
    Date thirdQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date foruthQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c secondQuarterTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      secondQuarterTestAgreement.Apttus__Contract_Start_Date__c = secondQuarter;
                                                      secondQuarterTestAgreement.APTS_Fixed_Term_Startdate__c = secondQuarter;
                                                      secondQuarterTestAgreement.Fixed_Terms_Internal_Freq__c = 'Quarterly';
                                                      secondQuarterTestAgreement.kpi_internal_freq__c = 'Quarterly';
                                                      secondQuarterTestAgreement.APTS_Fixed_Term_Frequency__c = 'Quarterly'; 
                                                      secondQuarterTestAgreement.budget_internal_freq__c = 'Quarterly';
                                                      secondQuarterTestAgreement.volume_obligation_internal_freq__c = 'Quarterly';
                                                      Database.update(secondQuarterTestAgreement);
                                                      
   Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = secondQuarter1;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: secondQuarterTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Quarterly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: secondQuarterTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =: secondQuarterTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
   
   /* ---------- Start of PI fix # 718083 ----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('P.O. NUMBER REQUEST',tsklst[0].Touchpoint_Type__c);  
   /* ---------- End of PI fix # 718083----------------------- */                                                
   }
   
   static testMethod void createThirdQuarterComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-2), System.Today().Day());
    Date secondQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-5), System.Today().Day());
    Date thirdQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date foruthQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c thirdQuarterTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      thirdQuarterTestAgreement.Apttus__Contract_Start_Date__c = thirdQuarter;
                                                      thirdQuarterTestAgreement.APTS_Fixed_Term_Startdate__c = thirdQuarter;
                                                      thirdQuarterTestAgreement.Fixed_Terms_Internal_Freq__c = 'Quarterly';
                                                      thirdQuarterTestAgreement.kpi_internal_freq__c = 'Quarterly';
                                                      thirdQuarterTestAgreement.APTS_Fixed_Term_Frequency__c = 'Quarterly'; 
                                                      thirdQuarterTestAgreement.budget_internal_freq__c = 'Quarterly';
                                                      thirdQuarterTestAgreement.volume_obligation_internal_freq__c = 'Quarterly';
                                                      Database.update(thirdQuarterTestAgreement);
                                                      
    Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = thirdQuarter1;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: thirdQuarterTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Quarterly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: thirdQuarterTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =: thirdQuarterTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
        
   /* ---------- Start of PI fix # 718083----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('P.O. NUMBER REQUEST',tsklst[0].Touchpoint_Type__c);  
   /* ---------- End of PI fix # 718083----------------------- */                                            
   }
   
   static testMethod void createFourthQuarterComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-2), System.Today().Day());
    Date secondQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-5), System.Today().Day());
    Date thirdQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date foruthQuarter1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c fourthQuarterTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      fourthQuarterTestAgreement.Apttus__Contract_Start_Date__c = foruthQuarter;
                                                      fourthQuarterTestAgreement.APTS_Fixed_Term_Startdate__c = foruthQuarter;
                                                      fourthQuarterTestAgreement.Fixed_Terms_Internal_Freq__c = 'Quarterly';
                                                      fourthQuarterTestAgreement.kpi_internal_freq__c = 'Quarterly';
                                                      fourthQuarterTestAgreement.APTS_Fixed_Term_Frequency__c = 'Quarterly'; 
                                                      fourthQuarterTestAgreement.budget_internal_freq__c = 'Quarterly';
                                                      fourthQuarterTestAgreement.volume_obligation_internal_freq__c = 'Quarterly';
                                                      Database.update(fourthQuarterTestAgreement);
                                                      
     Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = foruthQuarter1;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: fourthQuarterTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Quarterly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: fourthQuarterTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =:fourthQuarterTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
       
   /* ---------- Start of PI fix # 718083 ----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('FIXED TERM CHECK',tsklst[0].Touchpoint_Type__c);  
   /* ---------- End of PI fix # 718083----------------------- */                                               
   }
   
   static testMethod void createHalfYearComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstHalfYear = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date secondtHalfYear = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date firstHalfYear1 = Date.newInstance(System.Today().Year(), (System.Today().Month()-8), System.Today().Day());
    Date secondtHalfYear2 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c halfYearTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      halfYearTestAgreement.Apttus__Contract_Start_Date__c = firstHalfYear;
                                                      halfYearTestAgreement.APTS_Fixed_Term_Startdate__c = firstHalfYear;
                                                      halfYearTestAgreement.Fixed_Terms_Internal_Freq__c = 'Half Yearly';
                                                      halfYearTestAgreement.kpi_internal_freq__c = 'Half Yearly';
                                                      halfYearTestAgreement.APTS_Fixed_Term_Frequency__c = 'Half Yearly';
                                                      halfYearTestAgreement.budget_internal_freq__c = 'Half Yearly';
                                                      halfYearTestAgreement.volume_obligation_internal_freq__c = 'Half Yearly';
                                                      Database.update(halfYearTestAgreement);
                                                      
    Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = firstHalfYear1;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: halfYearTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Half-Yearly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: halfYearTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =:halfYearTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
       
   /* ---------- Start of PI fix # 718083 ----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('P.O. NUMBER REQUEST',tsklst[0].Touchpoint_Type__c);     
   /* ---------- End of PI fix # 718083----------------------- */                                            
   }
   
   static testMethod void createYearlyComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date Yearly = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Date Yearly2 = Date.newInstance(System.Today().Year(), (System.Today().Month()-11), System.Today().Day());
    
    Apttus__APTS_Agreement__c YearlyTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      YearlyTestAgreement.Apttus__Contract_Start_Date__c = Yearly;
                                                      YearlyTestAgreement.APTS_Fixed_Term_Startdate__c = Yearly;
                                                      YearlyTestAgreement.Fixed_Terms_Internal_Freq__c = 'Half Yearly';
                                                      YearlyTestAgreement.kpi_internal_freq__c = 'Half Yearly';
                                                      YearlyTestAgreement.APTS_Fixed_Term_Frequency__c = 'Yearly';
                                                      YearlyTestAgreement.budget_internal_freq__c = 'Half Yearly';
                                                      Database.update(YearlyTestAgreement);
                                                      
   Apttus__APTS_Agreement__c KPISLA = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'KPISLA Test Agreement' LIMIT 1];
                                                      KPISLA.Apttus__Contract_Start_Date__c = Yearly2;
                                                      KPISLA.kpi_internal_freq__c = 'Quarterly'; 
                                                      Database.update(KPISLA);
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: YearlyTestAgreement.Id LIMIT 1];
                                                 
   Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: KPISLA.Id LIMIT 1];
                                          monthlyKPISLA.kpi_frequency__c = 'Yearly';
                                          Database.update(monthlyKPISLA);
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: YearlyTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c FROM APTS_AgreementVolumeObligation__c WHERE APTS_Agreement__c =:YearlyTestAgreement.Id LIMIT 1];
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
      
      /* ---------- Start of PI fix # 718083 ----------------------- */
      List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
      System.assertEquals('FIXED TERM CHECK',tsklst[0].Touchpoint_Type__c); 
      /* ---------- End of PI fix # 718083 ----------------------- */                                                 
   }
   
    static testMethod void createVolObligationComlianceTask()
   {
    User testUser = [SELECT Id FROM User LIMIT 1];
    
    APTS_ComplianceTaskBatch.todayDate = 1;
    
    Date firstQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-3), System.Today().Day());
    Date secondQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-6), System.Today().Day());
    Date thirdQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-9), System.Today().Day());
    Date foruthQuarter = Date.newInstance(System.Today().Year(), (System.Today().Month()-12), System.Today().Day());
    
    Apttus__APTS_Agreement__c monthlyTestAgreement = [SELECT Id, Name, APTS_Country__c, recordtype.name, APTS_Fixed_Term_Type__c, Apttus__Contract_Start_Date__c, Apttus__Account__c, Apttus__Contract_End_Date__c, 
                                                      APTS_Fixed_Term_Startdate__c, Apttus__Subtype__c,
                                                      Apttus__Status_Category__c, Apttus__Status__c, Fixed_Terms_Internal_Freq__c, 
                                                      kpi_internal_freq__c, APTS_Fixed_Term_Frequency__c, budget_internal_freq__c,
                                                      volume_obligation_internal_triggerpoint__c
                                                      FROM Apttus__APTS_Agreement__c 
                                                      WHERE Name LIKE 'Monthly Test Agreement' LIMIT 1];
                                                      monthlyTestAgreement.Apttus__Contract_End_Date__c = System.Today()+1;
                                                      Database.update(monthlyTestAgreement);                                              
       
   APTS_Agreement_Budget__c monthlyAgreeBudget = [SELECT APTS_Category__c, APTS_Subcategory__c, APTS_Start_Date__c, APTS_End_Date__c, Agreement__c
                                                 FROM APTS_Agreement_Budget__c WHERE Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
                                                 
   //Contracted_kpi_sla__c monthlyKPISLA = [SELECT kpi_contract__c, KPI_type__c, kpi_frequency__c FROM Contracted_kpi_sla__c WHERE kpi_contract__c =: monthlyTestAgreement.Id LIMIT 1];
   
   APTS_AgreementTotalVolumeObligation__c monthlyAgreeTotalVolObli = [SELECT APTS_Agreement__c FROM APTS_AgreementTotalVolumeObligation__c WHERE APTS_Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
   
   APTS_AgreementVolumeObligation__c monthlyAgreeVolObli = [SELECT APTS_Agreement__c, APTS_Start_Date__c, APTS_End_Date__c, APTS_Volume_Obligation__c                                                         FROM APTS_AgreementVolumeObligation__c 
                                                            WHERE APTS_Agreement__c =: monthlyTestAgreement.Id LIMIT 1];
                                                            monthlyAgreeVolObli.APTS_End_Date__c = System.Today()-1;
                                                            Database.update(monthlyAgreeVolObli);
  
   test.startTest();
        APTS_ComplianceTaskBatch batch = new APTS_ComplianceTaskBatch();
        Database.executeBatch(batch, 200);
   test.stopTest();
   
   /* ---------- Start of PI fix # 718083----------------------- */
   List<Task> tsklst = [Select Id,WhoId,Touchpoint_Type__c from Task];
   System.assertEquals('FIXED TERM CHECK',tsklst[0].Touchpoint_Type__c);
   /* ---------- End of PI fix # 718083----------------------- */
                                                  
   }
   
 
}