src/objects/APTS_Index_Contract__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Additional_Conditions__c</fullName>
        <label>Additional Conditions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Communication_Deadline__c</fullName>
        <label>Communication Deadline</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 Month</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 Months</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 Months</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 Months</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 Months</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 Months</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Communication_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Communication Needed(Yes/No)?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Index Contracts</relationshipLabel>
        <relationshipName>Index_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>APTS_Customer_Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Approval Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Half-Yearly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Index_Type__c</fullName>
        <description>Type of Indexation</description>
        <inlineHelpText>Type of Indexation</inlineHelpText>
        <label>Index Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Indexation</fullName>
                    <default>true</default>
                    <label>Standard Indexation</label>
                </value>
                <value>
                    <fullName>Non-Standard Indexation</fullName>
                </value>
                <value>
                    <fullName>No Indexation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Indexation_Category__c</fullName>
        <description>Defines Indexation Category</description>
        <inlineHelpText>Defines Indexation Category</inlineHelpText>
        <label>Indexation Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Products (Ingredients and &amp;More)</fullName>
                </value>
                <value>
                    <fullName>Technical Services</fullName>
                </value>
                <value>
                    <fullName>Consumption Pricing</fullName>
                </value>
                <value>
                    <fullName>Machine Care Service</fullName>
                    <isActive>false</isActive>
                    <label>Machine Care Service</label>
                </value>
                <value>
                    <fullName>Maintenance Services</fullName>
                    <isActive>false</isActive>
                    <label>Maintenance Services</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Indexation_Number__c</fullName>
        <label>Indexation Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Maximum_Bandwidth__c</fullName>
        <label>Maximum Bandwidth</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>APTS_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Index Contract</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Index Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Index Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_IndexContractEditController.cls
/*************************************************************
@Name: APTS_IndexContractEditController
@Author: Santosh Kumar
@CreateDate: 7-Feb-2018
@Description: Allow users to change values based on Indexation
@UsedBy: APTS_IndexContractEditPage VF Page
******************************************************************/

public with sharing class APTS_IndexContractEditController {
    
    public APTS_Index_Contract__c indexContract{get;set;}
    public boolean istype{get;set;}
    public String ischanged{get;set;}
    private static final  String CONTRACT = 'APTS_Index_Contract__c';
    
    public APTS_IndexContractEditcontroller(ApexPages.StandardController stdController) {
        if(!Test.isRunningTest()) {
            stdController.addFields(new List<String>{'Name','APTS_Indexation_Category__c','APTS_Index_Type__c','APTS_Indexation_Number__c','APTS_Frequency__c','APTS_Communication_Deadline__c',
                'APTS_Start_Date__c','APTS_Maximum_Bandwidth__c','APTS_Communication_Needed__c','APTS_Additional_Conditions__c','APTS_Customer_Approval_Required__c','APTS_Contract__c'});
        }
        
        indexContract = (APTS_Index_Contract__c) stdController.getRecord();
        ischanged = 'false';
        identifytype();
    }
    
    /* Function Called when Index type picklist value is changed */
    public pagereference indextypechange() {
        identifytype();
        return null;
    }
    
    /* Function Called to identify type and dispaly message on screen */
    public void identifytype() {
        if(indexContract.APTS_Index_Type__c != 'Non-Standard Indexation') {
            istype = true;  
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'Cannot Edit any value as type is not Non-Standard Indexation'));            
        }else if(indexContract.APTS_Index_Type__c == 'Non-Standard Indexation') {
            istype = false;
        }
        
    }
    
    /* Function Called when clicked on save button on Page */
    public pagereference docontinue() {
        try{
        
           
        
            if(indexContract.APTS_Index_Type__c == 'Non-Standard Indexation' && ischanged == 'false') {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'You have defined an indexation without changing any Indexation specific values. Please change back to “Standard Indexation” or change any Indexation specific values'));
                return null;
            }
            if(indexContract.APTS_Index_Type__c == 'Standard Indexation(incl Fixed Prices)' && indexContract.APTS_Indexation_Category__c == 'Products (Ingredients and &More)') {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning,'You cannot save data with Standard Indexation(incl Fixed Prices) and Products (Ingredients and &More). Please change back to “Standard Indexation”'));
                return null;
            }
            
            
            DescribeSObjectResult objResultCON = APTS_OTCUtil.getsObjectAccess(CONTRACT);
            if(objResultCON != null &&  objResultCON.isUpdateable() )
            {
                update indexContract;
            }
            return new PageReference('/' + indexContract.id);
        }catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Warning, ex.getMessage()));
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'Apex', ex.getStackTraceString(), 'IndexContract', indexContract.Id, 'CLM', false, false, null, true);
            return null;
        }
    }
    
    /* Function Called when clicked on Cancel button on Page */
    public pagereference docancel() {
        return new PageReference('/' + indexContract.id);
    } 
    
    /* Function Called by Action function to capture value when any value changed on VF Page when index is Non-standard */
    public void valueupdate(){
        ischanged=Apexpages.currentPage().getParameters().get('valFromVf');
    }
}