src/objects/APTS_CER_Transaction__c.object
<CustomObject>
    <description>CER Transactions</description>
    <fields>
        <fullName>APTS_Agreement_Id__c</fullName>
        <description>To store the agreement id</description>
        <externalId>true</externalId>
        <label>Agreement Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Contributing_IND__c</fullName>
        <label>Contributing_IND</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Migrated</fullName>
                </value>
                <value>
                    <fullName>Agreement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Process_Status__c</fullName>
        <label>Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CER Transaction</label>
    <nameField>
        <displayFormat>CER-{00000}</displayFormat>
        <label>CER Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CER Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_updateCERRescordsQueueableTest.cls
/*******************************************************************************************
Name            : APTS_updateCERRescordsQueueableTest
Created By      : Sai Sagar
Created Date    : 09/12/2018
Description     : This Apex Class is test class for CER Update which covers APTS_updateCERRecordsQueueable.
Version history : 
Test Class      : 
*********************************************************************************************/
@isTest 
private class APTS_updateCERRescordsQueueableTest {
public static List<Account> oTestAccountlist = new List<Account>();
    public static Contact oTestContact;
    public static Product2 oproduct; 
    public static Apttus_Config2__PriceList__c oTestPricelist;
    public static List<Apttus__APTS_Agreement__c> oAggremtlist = new List<Apttus__APTS_Agreement__c>();
    public static List<APTS_CER_Transaction__c > certranslist = new list<APTS_CER_Transaction__c >();

    @isTest
    private static void testCERUpdate() {
        // Create purchasing organization
        //Account organisation = APTS_TestUtils.createBuyingGroup();
        //insert organisation;

        Test.startTest();  
        oTestAccountlist.add(APTS_TestUtils.createGrandParentAccount());
        oTestAccountlist.add(APTS_TestUtils.createGrandParentAccount());
        Database.Insert(oTestAccountlist);

        oTestContact = APTS_TestUtils.createContact();
        insert oTestContact;

        oproduct = APTS_TestUtils.createProduct('Test Package Cafitesse 50','26940997','Machines'); 
        insert oproduct;

        oTestPricelist = APTS_TestUtils.createPriceList();
        insert oTestPricelist;

        Apttus__APTS_Agreement__c oAggremt1 = APTS_TestUtils.createAgreement(oTestContact.Id, null, oTestPricelist.Id, oTestAccountlist[0].Id);
        oAggremt1.Apttus__Status_Category__c = 'In Effect';
        oAggremt1.Apttus__Status__c = 'Activated';
        oAggremt1.Apttus__Contract_End_Date__c = Date.today().addYears(3);
        oAggremtlist.add(oAggremt1);
        
        insert oAggremtlist;       

        APTS_CER_Transaction__c createTrans = new APTS_CER_Transaction__c();
        createTrans.APTS_Process_Status__c = 'Created';
        createTrans.APTS_Agreement_Id__c = oAggremt1.id;
       // createTrans.APTS_Contributing_IND__c ='Migrated';
        insert createTrans;
        certranslist.add(createTrans); 
      
            System.enqueueJob(new APTS_updateCERRecordsQueueable());
       
        Test.stopTest();
        
    }
}