src/objects/APTS_Agreement_Budget__c.object
<CustomObject>
    <description>Agreement Budget</description>
    <fields>
        <fullName>APTS_Start_Date__c</fullName>
        <description>This will capture budget start date.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <description>Budget created for agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Budgets</relationshipLabel>
        <relationshipName>Agreement_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Budget</label>
    <nameField>
        <displayFormat>AB-{0000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_SV</fullName>
                    <label>Swedish</label>
                </value>
                <value>
                    <fullName>SAP_EN</fullName>
                    <label>English</label>
                </value>
                <value>
                    <fullName>SAP_NL</fullName>
                    <label>Dutch</label>
                </value>
                <value>
                    <fullName>SAP_FR</fullName>
                    <label>French</label>
                </value>
                <value>
                    <fullName>SAP_NO</fullName>
                    <label>Norwegian</label>
                </value>
                <value>
                    <fullName>SAP_DA</fullName>
                    <label>Danish</label>
                </value>
                <value>
                    <fullName>SAP_SR</fullName>
                    <label>Serbian</label>
                </value>
                <value>
                    <fullName>SAP_ZH</fullName>
                    <label>Chinese</label>
                </value>
                <value>
                    <fullName>SAP_TH</fullName>
                    <label>Thai</label>
                </value>
                <value>
                    <fullName>SAP_KO</fullName>
                    <label>Korean</label>
                </value>
                <value>
                    <fullName>SAP_RO</fullName>
                    <label>Romanian</label>
                </value>
                <value>
                    <fullName>SAP_SL</fullName>
                    <label>Slovenian</label>
                </value>
                <value>
                    <fullName>SAP_HR</fullName>
                    <label>Croatian</label>
                </value>
                <value>
                    <fullName>SAP_MS</fullName>
                    <label>Malaysian</label>
                </value>
                <value>
                    <fullName>SAP_UK</fullName>
                    <label>Ukrainian</label>
                </value>
                <value>
                    <fullName>SAP_ET</fullName>
                    <label>Estonian</label>
                </value>
                <value>
                    <fullName>SAP_AR</fullName>
                    <label>Arabic</label>
                </value>
                <value>
                    <fullName>SAP_HE</fullName>
                    <label>Hebrew</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Czech</label>
                </value>
                <value>
                    <fullName>SAP_DE</fullName>
                    <label>German</label>
                </value>
                <value>
                    <fullName>SAP_EL</fullName>
                    <label>Greek</label>
                </value>
                <value>
                    <fullName>SAP_HU</fullName>
                    <label>Hungarian</label>
                </value>
                <value>
                    <fullName>SAP_IT</fullName>
                    <label>Italian</label>
                </value>
                <value>
                    <fullName>SAP_JA</fullName>
                    <label>Japanese</label>
                </value>
                <value>
                    <fullName>SAP_PL</fullName>
                    <label>Polish</label>
                </value>
                <value>
                    <fullName>SAP_ZF</fullName>
                    <label>Chinese trad</label>
                </value>
                <value>
                    <fullName>SAP_PT</fullName>
                    <label>Portuguese</label>
                </value>
                <value>
                    <fullName>SAP_SK</fullName>
                    <label>Slovakian</label>
                </value>
                <value>
                    <fullName>SAP_RU</fullName>
                    <label>Russian</label>
                </value>
                <value>
                    <fullName>SAP_ES</fullName>
                    <label>Spanish</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Subtype__c</fullName>
        <description>The subtype of the agreement for a given agreement type</description>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>Fixed-Term-Fixed Costs</fullName>
                </value>
                <value>
                    <fullName>Fixed Term-Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed Term-Both Fixed Costs and Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed End Date</fullName>
                </value>
                <value>
                    <fullName>3+1+1</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_BudgetTriggerHandlerTest.cls
@isTest
private class APTS_BudgetTriggerHandlerTest{

    private static testMethod void testExecute() {
                
        Account testAccount = APTS_TestUtils.createGrandParentAccount();
        testAccount.Name = 'Test Account';
        Database.Insert(testAccount);
        
        Apttus_Config2__PriceList__c priceList = APTS_TestUtils.createPriceList();
        Database.Insert(priceList);
        
        Id recordtype = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(System.Label.APTS_Standard_Deal).getRecordTypeId();
        
        
        Apttus__APTS_Agreement__c agrmnt = new Apttus__APTS_Agreement__c(Apttus__Account__c = testAccount.Id, 
                        Name = 'Test Agreement',RecordTypeId = recordtype,
                        Apttus__Contract_Start_Date__c = Date.today(), Apttus__Contract_End_Date__c = Date.today()+365, 
                        Apttus_CMConfig__PriceListId__c = priceList.id,Apttus__Subtype__c ='Fixed-Term-Fixed Costs',
                        Apttus__Status_Category__c = 'In Effect', Apttus__Status__c = 'Activated',APTS_Language__c = 'English');
        Database.Insert(agrmnt);
        
        APTS_Agreement_Budget__c budget = new APTS_Agreement_Budget__c();
        budget.Agreement__c = agrmnt.id;
        Database.Insert(budget);

        Map<ID,APTS_Agreement_Budget__c> budgetmap = new Map<ID,APTS_Agreement_Budget__c>();
        budgetmap.put(budget.id,budget);

        list<APTS_Agreement_Budget__c> budgetlist = new list<APTS_Agreement_Budget__c>();
        budgetlist.add(budget);

        budget.APTS_Start_Date__c = agrmnt.Apttus__Contract_Start_Date__c;
        Database.Update(budget);
        
        APTS_AgreementBudgetHandler handler = new APTS_AgreementBudgetHandler();
        handler.beforeDelete(null, null);
        handler.afterDelete(null, null);
        handler.afterUndelete(null, null);
        handler.afterInsert(budgetlist,budgetmap);
        handler.afterUpdate(budgetlist,budgetmap,budgetlist,budgetmap);
    }


}