src/objects/APTS_Order_Interface_Log__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Message__c</fullName>
        <description>A field to store JSON received from External System</description>
        <inlineHelpText>A field to store JSON received from External System</inlineHelpText>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_SourceOrderNumber__c</fullName>
        <label>SourceOrderNumber</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Interface Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The line description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Sub_Type__c</fullName>
        <description>This is the Order Sub Type</description>
        <label>Order Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Order_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Standard Return</fullName>
                </value>
                <value>
                    <fullName>Unplanned Return</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>De-installation</fullName>
                </value>
                <value>
                    <fullName>Internal Movement</fullName>
                </value>
                <value>
                    <fullName>External Movement With Contract Change</fullName>
                </value>
                <value>
                    <fullName>External Movement Without Contract Change</fullName>
                </value>
                <value>
                    <fullName>Technical Swap</fullName>
                </value>
                <value>
                    <fullName>Commercial Swap</fullName>
                </value>
                <value>
                    <fullName>Route Sales and Operating</fullName>
                </value>
                <value>
                    <fullName>Subscription Order</fullName>
                </value>
                <value>
                    <fullName>Billing Schedule</fullName>
                </value>
                <value>
                    <fullName>Digital Order</fullName>
                </value>
                <value>
                    <fullName>Conversion Order</fullName>
                </value>
                <value>
                    <fullName>Stock Count</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Agreement Changes</fullName>
                </value>
                <value>
                    <fullName>Indexation</fullName>
                </value>
                <value>
                    <fullName>Consignment Issue for FSD</fullName>
                </value>
                <value>
                    <fullName>Consignment Fillup for FSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Machine Order</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Debit Memo</fullName>
                </value>
                <value>
                    <fullName>Admin Order</fullName>
                </value>
                <value>
                    <fullName>Route Sales Order</fullName>
                </value>
                <value>
                    <fullName>Operating Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The order description</description>
        <inlineHelpText>The order description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PONumber__c</fullName>
        <description>The purchase order number</description>
        <inlineHelpText>The purchase order number</inlineHelpText>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The order status</description>
        <inlineHelpText>The order status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The description of the price list.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The description of the price list.item</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <formula>TEXT(Apttus_Config2__OrderId__r.APTS_Order_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Configurations (Sold To)</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The description for the product configuration</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Collaboration</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ATPCheckBatchTest.cls
@isTest
public class APTS_ATPCheckBatchTest { 
    private static final String ORDERTYPE_ROUTESALES = 'Route Sales Order';
    private static final String ORDERSUBTYPE_STANDARDORDER = 'Standard Order';

    @testSetup static void setupTestData() {
        User oTestUser = APTS_TestFacade.createTestUser();
        APTS_TestFacade.createMandatoryRecords(oTestUser);
        //APTS_TestFacade.createAndConfigureOrder(oTestUser);
        System.assert(oTestUser != Null);
    }

    private static testMethod void testRSOOrderBatch() {
        User oTestUser = APTS_TestFacade.getTestUser();

        test.startTest();

        Contact oContact = APTS_TestFacade.getContact();
        Account oAccount = APTS_TestFacade.getAccount();
        Opportunity oOpportunity = APTS_TestFacade.getOpportunity();
        Product2 oStandaloneProduct = APTS_TestFacade.getStandaloneProduct();
        Apttus_Config2__BillingPreference__c oBillingPreference = APTS_TestFacade.getBillingPreference();
        Apttus_Config2__PriceList__c oPriceList = APTS_TestFacade.getPriceList();
        Apttus_Config2__PriceListItem__c oPriceListItemStandalone = APTS_TestFacade.getPriceListItem(oStandaloneProduct.Id);
        
        System.runAs(otestuser) {
            Apttus_Config2__OrderSystemProperties__c oOrderSystemProperties = APTS_TestDataFactory.getOrderSystemProperties();
            Database.insert(oOrderSystemProperties);

            Set<Id> orderList = new Set<Id>();
            Apttus_Config2__Order__c oStandardOrder = APTS_TestDataFactory.createOrder(oAccount.Id, oPriceList.Id, oContact.Id);
            oStandardOrder.Apttus_Config2__Status__c = 'Activated';
            oStandardOrder.Apttus_Config2__Description__c = 'StandardOrder';
            oStandardOrder.Apttus_Config2__PONumber__c = '1234';
            oStandardOrder.APTS_Order_Sub_Type__c = 'Standard Order';
            oStandardOrder.APTS_Order_Type__c = 'Route Sales Order';
            oStandardOrder.RecordTypeId = Schema.SObjectType.Apttus_Config2__Order__c.getRecordTypeInfosByName().get('Standard Order').getRecordTypeId();
            Database.Insert(oStandardOrder, false);
            orderList.add(oStandardOrder.Id);

            Apttus_Config2__ProductConfiguration__c oProductConfiguration = APTS_TestDataFactory.createProductConfig(oStandardOrder);
            Database.Insert(oProductConfiguration, false);
            
            String acctName = 'Test' + string.valueOf(Math.random());
            Account acc = APTS_TestDataFactory.createAccount(acctName);
            acc.Account_Status__c = 'Valid';
            Database.insert(acc, false);

            Contact con = APTS_TestDataFactory.createContact(acc, '+912121212121');
            Database.insert(con, false);

            Case cse = TS_TestDataFactory.createFieldServiceCase();
            cse.ContactId = con.Id;
            insert cse;

            Apttus_Config2__AccountLocation__c loc = new Apttus_Config2__AccountLocation__c();
            loc.Apttus_Config2__AccountId__c = acc.Id;
            loc.Account_Location_Status__c  = 'Valid';
            insert loc;

            Product2 prod = APTS_TestDataFactory.createProduct('TestCoffee', 'pc123', 'Coffee', 'Standalone', true, false);
            Database.Insert(prod, false);

            APTS_DOEPIReqWrapper oWrapper = new APTS_DOEPIReqWrapper();
            oWrapper.SourceOrderNumber = 'sn1232';
            oWrapper.SalesforceAccountID = acc.Id;
            oWrapper.SalesforceContactID = con.Id;
            oWrapper.SalesforceAccountLocationID = loc.Id;
            oWrapper.CaseID =  cse.Id;
            oWrapper.Source = 'MobileApp';
            oWrapper.PONumber = 'PO5678';
            oWrapper.OrderType = 'Operating Order';
            oWrapper.OrderSubType = 'Standard Order';
            oWrapper.FulfilledFromVan = true;
            oWrapper.CustomerComment = 'test comments';
            oWrapper.RSOEmployeeEmail = 'testRSO@JDECoffee.com';

            oWrapper.OrderLineItems = new List<APTS_DOEPIReqWrapper.EPIOrderLI>();
            APTS_DOEPIReqWrapper.EPIOrderLI orderLineItem = new APTS_DOEPIReqWrapper.EPIOrderLI();
            orderLineItem.ProductId = prod.Id;
            orderLineItem.Quantity = 1;
            orderLineItem.SourceLineNumber = '1';
            orderLineItem.SellingUnitofMeasure = 'Box';
            orderLineItem.ReasonCode = '1';
            oWrapper.OrderLineItems.add(orderLineItem);

            Set<Id> setInterface = new Set<Id>();
            String sJSONClass = JSON.serializePretty(oWrapper);

            APTS_Order_Interface_Log__c oLog = new APTS_Order_Interface_Log__c();
            oLog.APTS_Message__c = sJSONClass;
            oLog.APTS_SourceOrderNumber__c = 'sn1232';
            oLog.APTS_Status__c = 'New';
            oLog.APTS_Source__c = 'RSOApp';
            oLog.APTS_Type__c = 'OrderData';
            insert oLog;

            APTS_Order_Interface_Log__c oLog1 = new APTS_Order_Interface_Log__c();
            oLog1.APTS_SourceOrderNumber__c = 'sn1232';
            oLog1.APTS_Status__c = 'New';
            oLog1.APTS_Source__c = 'RSOApp';
            oLog1.APTS_Type__c = 'Attachment';
            insert oLog1;

            for (APTS_Order_Interface_Log__c olog2 : [select id from APTS_Order_Interface_Log__c where APTS_Type__c <> 'Attachment' limit 1]) {
                setInterface.add(olog2.Id);
            }

            Apttus_Config2__Order__c oStandardOrder1 = APTS_TestDataFactory.createOrder(oAccount.Id, oPriceList.Id, oContact.Id);
            oStandardOrder1.Apttus_Config2__Status__c = 'Activated';
            oStandardOrder1.Apttus_Config2__Description__c = 'StandardOrder1';
            oStandardOrder.APTS_Order_Sub_Type__c = 'Standard Order';
            oStandardOrder1.Apttus_Config2__OrderStartDate__c = Date.today().addDays(1);
            oStandardOrder1.RecordTypeId = Schema.SObjectType.Apttus_Config2__Order__c.getRecordTypeInfosByName().get('Standard Order').getRecordTypeId();
            Database.Insert(oStandardOrder1, false);
            orderList.add(oStandardOrder1.Id);

            Apttus_Config2__LineItem__c oLineItemStandalone1 = APTS_TestDataFactory.createLineItem(oProductConfiguration, oPriceListItemStandalone.Id, NULL, oStandaloneProduct.Id, NULL, NULL, 1, 1, 1, 'Product/Service', null, 'Monthly', 'Bill In Advance', 'One Time', 'Per Unit', 'Each', 100, 2);
            oLineItemStandalone1.Apttus_Config2__PricingStatus__c = 'Completed';
            oLineItemStandalone1.APTS_Requested_Delivery_Date__c = System.today();
            oLineItemStandalone1.APTS_ATP_Cleared__c = true;
            insert oLineItemStandalone1;

            Apttus_Config2__LineItem__c oLineItemStandalone = APTS_TestDataFactory.createLineItem(oProductConfiguration, oPriceListItemStandalone.Id, NULL, oStandaloneProduct.Id, NULL, NULL, 1, 1, 1, 'Product/Service', null, 'Monthly', 'Bill In Advance', 'One Time', 'Per Unit', 'Each', 100, 2);
            oLineItemStandalone.Apttus_Config2__PricingStatus__c = 'Completed';
            oLineItemStandalone.APTS_Requested_Delivery_Date__c = System.today();
            oLineItemStandalone.APTS_ATP_Cleared__c = false;
            insert oLineItemStandalone;

            Test.setMock(WebServiceMock.class, new APTS_ATPCheckHTTPCalloutMockImpl());

            APTS_ATPCheckBatch objbatch = new APTS_ATPCheckBatch(orderList, setInterface, null);
            Database.executeBatch(objbatch, 200);

            objbatch = new APTS_ATPCheckBatch();
        }

        test.stopTest();
        
        List<Apttus_Config2__Order__c> orderLst = new List<Apttus_Config2__Order__c>();
        orderLst = [select id from Apttus_Config2__Order__c limit 1];
        system.assert(orderLst!=null);
    }
}