src/objects/APTS_Batch_Queries__mdt.object
<CustomObject>
    <description>Custom metadata to store batch queries</description>
    <fields>
        <fullName>APTS_Query_String__c</fullName>
        <description>Field to store queries</description>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch query</label>
    <pluralLabel>Batch queries</pluralLabel>
</CustomObject>

src/objects/APTS_Order_LSP_Details__c.object
<CustomObject>
    <description>Order LSP Details</description>
    <fields>
        <fullName>APTS_Area__c</fullName>
        <description>Area</description>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order LSP Detail</label>
    <nameField>
        <label>Order LSP Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order LSP Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetStatus__c</fullName>
        <description>The asset status</description>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Pending Re-activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Suspension</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Changed Configuration</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsInactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the asset is inactive.</description>
        <inlineHelpText>Indicates whether the asset is inactive.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type.</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the price list</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Apttus_Config2__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_AccountAssetsViewLightningCtrlTest.cls
/*************************************************************
@Name: APTS_AccountAssetsViewLightningCtrlTest
@Author: Wendy Kelley
@CreateDate: 31/01/2018
@Description: Test class for APTS_AccountAssetsViewLightningCtrl
@UsedBy:
******************************************************************/
@isTest
public with sharing class APTS_AccountAssetsViewLightningCtrlTest {
    private final static string STR_ASSET_STATUS_ACTIVATED = 'Activated';
    private final static string STR_LINETYPE_PROD_SERVICE = 'Product/Service';
    private final static string STR_LINETYPE_OPTION = 'Option';

    /**
     * setup test data
     */
    @TestSetup
    public static void buildTestData(){

        User usr = APTS_TestUtils.createUser();
        usr.Username += '.' + Integer.valueOf(math.rint(math.random()*1000000));
        Database.insert(usr);

        Account acc = APTS_TestUtils.createOrganisationproduct();
        acc.Name = 'Test Asset Acct';
        Database.insert(acc);

        List<Apttus_Config2__AssetLineItem__c> assetLineItemHeaderList = new List<Apttus_Config2__AssetLineItem__c>();

        Product2 prod = APTS_TestUtils.createProduct('Test Product', 'PRD001', 'Machines');
        Database.insert(prod);

        Apttus_Config2__AssetLineItem__c assetLineItemHeader = new Apttus_Config2__AssetLineItem__c();
        assetLineItemHeader.Name = 'Test Asset 1';
        assetLineItemHeader.Apttus_Config2__AccountId__c = acc.Id;
        assetLineItemHeader.Apttus_Config2__AssetStatus__c = STR_ASSET_STATUS_ACTIVATED;
        assetLineItemHeader.Apttus_Config2__IsInactive__c = false;
        assetLineItemHeader.Apttus_Config2__LineType__c = STR_LINETYPE_PROD_SERVICE ;
        assetLineItemHeader.Apttus_Config2__ProductId__c = prod.Id;
        assetLineItemHeader.Apttus_Config2__HasOptions__c = true;
        assetLineItemHeader.Apttus_Config2__IsPrimaryLine__c = true;
        assetLineItemHeaderList.add(assetLineItemHeader);

        assetLineItemHeader = new Apttus_Config2__AssetLineItem__c();
        assetLineItemHeader.Name = 'Test Asset 2';
        assetLineItemHeader.Apttus_Config2__ProductId__c = prod.Id;
        assetLineItemHeader.Apttus_Config2__AccountId__c = acc.Id;
        assetLineItemHeader.Apttus_Config2__AssetStatus__c = STR_ASSET_STATUS_ACTIVATED;
        assetLineItemHeader.Apttus_Config2__IsInactive__c = false;
        assetLineItemHeader.Apttus_Config2__LineType__c = STR_LINETYPE_PROD_SERVICE ;
        assetLineItemHeader.Apttus_Config2__HasOptions__c = false;
        assetLineItemHeaderList.add(assetLineItemHeader);

        Database.insert(assetLineItemHeaderList);

    }

    /**
     * positive test - test account with active assets
     */
    @isTest
    static void testAssetLineItemViewPage(){
        List<Account> accountList = [SELECT Id FROM Account WHERE Name LIKE '%Test Asset Acct%' LIMIT 1];

        List<Apttus_Config2__AssetLineItem__c> aliList = new List<Apttus_Config2__AssetLineItem__c>();
        Test.startTest();
        APTS_AccountAssetsViewLightningCtrl.activeAssetQueryMdt  = (List<APTS_Batch_Queries__mdt>) JSON.deserialize( '[{"Id ":"dummyValue","APTS_Query_String__c":"Select id from Apttus_Config2__AssetLineItem__c"}]', List<APTS_Batch_Queries__mdt>.class );
        aliList = APTS_AccountAssetsViewLightningCtrl.getBundleAssetLineItems(accountList[0].Id);
        Test.stopTest(); 

        //System.assertEquals(1, aliList.size());
    }

    /**
     * negative test - test account with no active assets
     */
    @isTest
    static void testAssetLineItemViewPageNoRecord(){
        User usr = [SELECT Id FROM User WHERE LastName LIKE '%123Smith%' LIMIT 1];
        Account acct = APTS_TestUtils.createOrganisationproduct();
        acct.Name = 'Test Account 1';
        Database.insert(acct);

        List<Apttus_Config2__AssetLineItem__c> aliList = new List<Apttus_Config2__AssetLineItem__c>();
        Test.startTest();
            System.runAs(usr) {
        APTS_AccountAssetsViewLightningCtrl.activeAssetQueryMdt  = (List<APTS_Batch_Queries__mdt>) JSON.deserialize( '[{"Id ":"dummyValue","APTS_Query_String__c":"Select id from Apttus_Config2__AssetLineItem__c"}]', List<APTS_Batch_Queries__mdt>.class );
                aliList = APTS_AccountAssetsViewLightningCtrl.getBundleAssetLineItems(acct.Id);
            }
        Test.stopTest();
    }

    static testMethod void testadminorder() {

        List<Apttus_Config2__AssetLineItem__c> aliList = new List<Apttus_Config2__AssetLineItem__c>();
        List<Account> accountList = [SELECT Id FROM Account WHERE Name LIKE '%Test Asset Acct%' LIMIT 1];
        
        Product2 oproduct = [select id,name,ProductCode from Product2 limit 1];
        Apttus_Config2__AccountLocation__c testAcclocation = APTS_TestUtils.createAccountLocation(accountList[0].Id);
        insert testAcclocation;

        PhysicalAsset__c testphAsset = APTS_TestUtils.createPhysicalAsset();
        insert testphAsset;

        Apttus_Config2__PriceList__c oTestPricelist = APTS_TestUtils.createPriceList();
        insert oTestPricelist;

        Apttus_Config2__PriceListItem__c opriceListItem = APTS_TestUtils.createPriceListItem(oTestPricelist.id,oproduct.id);
        insert opriceListItem;

        Apttus_Config2__BillingPreference__c obillpref = APTS_TestUtils.createBillingPrefrence('April');
        insert obillpref;

        Contact oTestContact = APTS_TestUtils.createContact();
        insert oTestContact;

        Apttus_Config2__AccountLocation__c location = APTS_TestUtils.createAccountLocation(accountList[0].ID);
        insert location;

        Apttus__APTS_Agreement__c oAggreement = APTS_TestUtils.createAgreement(oTestContact.Id, null, oTestPricelist.Id, accountList[0].Id);
        oAggreement.Apttus__Status_Category__c = 'In Effect';
        oAggreement.Apttus__Status__c = 'Activated';
        oAggreement.Apttus__Contract_End_Date__c = Date.today().addYears(3);
        insert oAggreement;

        APTS_Order_LSP_Details__c oLSPdetail = new APTS_Order_LSP_Details__c();
        oLSPdetail.APTS_Area__c = 'Test Area';
        oLSPdetail.APTS_Building__c = 'Test Building';
        oLSPdetail.APTS_Floor__c = 'Test Floor';
        oLSPdetail.APTS_SmokingArea__c = true;
        oLSPdetail.APTS_StairClimber__c = true;

        Apttus_Config2__AssetLineItem__c oAssetLItem = APTS_TestUtils.createAssetLineItem(accountList[0].Id, oproduct.Id, oTestPricelist.Id, opriceListItem.Id, obillpref.Id, null);
        oAssetLItem.Apttus_CMConfig__AgreementId__c = oAggreement.Id;
        oAssetLItem.APTS_Option_Group_Text__c = 'Technical Service';
        oAssetLItem.APTS_Physical_Asset__c = testphAsset.Id; 
        oAssetLItem.APTS_Sub_Status__c = 'Temporary Deactivated';
        insert oAssetLItem;
        APTS_AccountAssetsViewLightningCtrl.activeAssetQueryMdt  = (List<APTS_Batch_Queries__mdt>) JSON.deserialize( '[{"Id ":"dummyValue","APTS_Query_String__c":"Select id from Apttus_Config2__AssetLineItem__c"}]', List<APTS_Batch_Queries__mdt>.class );

        Test.startTest();
        APTS_AccountAssetsViewLightningCtrl.getAccountLocations(accountList[0].ID);
        APTS_AccountAssetsViewLightningCtrl.getRelatedAgreements(accountList[0].ID);
        aliList = APTS_AccountAssetsViewLightningCtrl.getDeactivatedAssetLineItems(accountList[0].Id);
        aliList = APTS_AccountAssetsViewLightningCtrl.getALIsBySerialNo(accountList[0].Id,'01232345');
        APTS_AccountAssetsViewLightningCtrl.updateAssets(new List<String>{oAssetLItem.Id},'Installation');
        APTS_AccountAssetsViewLightningCtrl.updateAssets(new List<String>{oAssetLItem.Id},'De-installation');
        APTS_AccountAssetsViewLightningCtrl.getKeyPrefixes();
        String result = APTS_AccountAssetsViewLightningCtrl.createAdminOrder(new List<string>{String.valueof(oAssetLItem.Id)},accountList[0].Id,oAggreement.Id,oLSPdetail,String.Valueof(testAcclocation.Id),false);
        String movementUtilResult = APTS_AccountAssetsViewLightningCtrl.invokeMovementUtil(oAssetLItem.Id, accountList[0].Id, oAggreement.Id, oLSPdetail, testAcclocation.Id, System.today(),TRUE);
        list<APTS_Error_Object__c>error = [select id,APTS_Error_Name__c,APTS_Error_Type__c,APTS_Description_Of_Error__c, APTS_Error_Description__c from APTS_Error_Object__c limit 1];
    

        Test.stopTest();
    }
}