src/objects/APTS_Order_Error_Log__c.object
<CustomObject>
    <label>Order Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTS_Order_Freight_Data__c.object
<CustomObject>
    <label>Order Freight Data</label>
    <nameField>
        <displayFormat>OFD-{0000}</displayFormat>
        <label>Order Freight ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Freights Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_Order_Interface_Log__c.object
<CustomObject>
    <label>Order Interface Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_ATP_Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ATP Cleared</label>
        <type>Checkbox</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Machine Order</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Debit Memo</fullName>
                </value>
                <value>
                    <fullName>Admin Order</fullName>
                </value>
                <value>
                    <fullName>Route Sales Order</fullName>
                </value>
                <value>
                    <fullName>Operating Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The order status</description>
        <inlineHelpText>The order status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <formula>TEXT(Apttus_Config2__OrderId__r.APTS_Order_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BusinessObjectType__c</fullName>
        <description>The type of the business object associated with the configuration</description>
        <label>Business Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                    <default>true</default>
                    <label>Agreement</label>
                </value>
                <value>
                    <fullName>Proposal</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Collaboration Request</fullName>
                </value>
                <value>
                    <fullName>Favorite Configuration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated order</description>
        <inlineHelpText>ID of the associated order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Collaboration</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__TaxBreakup__c.object
<CustomObject>
    <description>Represents the tax breakup of a product/service</description>
    <label>Tax Breakup</label>
    <nameField>
        <displayFormat>TB-{00000000}</displayFormat>
        <label>Breakup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Breakups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_ATPCheckBatch.cls
global class APTS_ATPCheckBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    private static final String S_ORDER = 'Order';
    private static final String S_FINALIZED = 'Finalized';
    private static final Set<String> S_RSO_ORDER = new Set<String> {'Route Sales Order', 'Operating Order'};

    private Set<Id> setNewOrderId;
    private Set<Id> setInterfaceId;
    private Map<String, APTS_DOEPIReqWrapper.EPIOrderLI> mapEPIOLI;

    public class testException extends Exception {}

    public APTS_ATPCheckBatch() {}

    public APTS_ATPCheckBatch(Set<Id> setNewOrderIdTmp, Set<Id> setInterfaceIdTmp, Map<String, APTS_DOEPIReqWrapper.EPIOrderLI> mapEPIOLITmp) {
        setNewOrderId = setNewOrderIdTmp;
        setInterfaceId = setInterfaceIdTmp;
        mapEPIOLI = mapEPIOLITmp;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Apttus_Config2__OrderId__c FROM Apttus_Config2__ProductConfiguration__c WHERE Apttus_Config2__BusinessObjectType__c = :S_ORDER and APTS_Order_Type__c IN :S_RSO_ORDER and Apttus_Config2__Status__c <> :S_FINALIZED AND Apttus_Config2__OrderId__c IN :setNewOrderId';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Apttus_Config2__ProductConfiguration__c> listPrevCart) {
        Boolean isATPPass;
        Group queue;
        Id orderID, cartId;
        APTS_ATPResultWrapper oATPResultWrapper;
        Set<Id> cartIdATPPass = new Set<id>();
        List<Apttus_Config2__LineItem__c> lineItemsToUpdateList = new List<Apttus_Config2__LineItem__c>();
        List<Apttus_Config2__TaxBreakup__c> taxBreakupsToInsertList = new List<Apttus_Config2__TaxBreakup__c>();
        List<APTS_Order_Freight_Data__c> freightDataToInsertList = new List<APTS_Order_Freight_Data__c>();
        List<APTS_Order_Error_Log__c> listErrorLog = new List<APTS_Order_Error_Log__c>();

        try {
            queue = APTS_DigitalOrderBatchHelper.getCSQueue();

            /*if (Test.isRunningTest()) {
                oATPResultWrapper = new APTS_ATPResultWrapper();
                oATPResultWrapper.lineItemsToUpdateList = [SELECT Id, APTS_ATP_Cleared__c FROM Apttus_Config2__LineItem__c];
            }*/

            for (Apttus_Config2__ProductConfiguration__c prevCart : listPrevCart) {
                isATPPass = false;
                cartId = prevCart.Id;
                orderID = prevCart.Apttus_Config2__OrderId__c;

                try {
                    oATPResultWrapper = APTS_OrderWSUtils.doATPCheck(orderID, cartId);
                } catch (exception e) {
                    APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() , 'Order', orderID, 'OM', false, true, null, true);
                }

                if (oATPResultWrapper != null) {
                    if (oATPResultWrapper.lineItemsToUpdateList != null && !oATPResultWrapper.lineItemsToUpdateList.isEmpty()) {
                        lineItemsToUpdateList.addAll(oATPResultWrapper.lineItemsToUpdateList);

                        isATPPass = true;
                        for (Apttus_Config2__LineItem__c oLineItem : oATPResultWrapper.lineItemsToUpdateList) {
                            isATPPass = oLineItem.APTS_ATP_Cleared__c == null || !oLineItem.APTS_ATP_Cleared__c ? false : isATPPass;
                        }
                    }

                    if (!oATPResultWrapper.taxBreakupsToInsertList.isEmpty()) {
                        taxBreakupsToInsertList.addAll(oATPResultWrapper.taxBreakupsToInsertList);
                    }

                    if (!oATPResultWrapper.freightDataToInsertList.isEmpty()) {
                        freightDataToInsertList.addAll(oATPResultWrapper.freightDataToInsertList);
                    }
                }

                if (isATPPass) {
                    cartIdATPPass.add(cartId);
                }
            }

            if (!lineItemsToUpdateList.isEmpty()) {
                Database.update(lineItemsToUpdateList);
            }

            if (!taxBreakupsToInsertList.isEmpty()) {
                Database.insert(taxBreakupsToInsertList);
            }

            if (!freightDataToInsertList.isEmpty()) {
                Database.insert(freightDataToInsertList);
            }

            Set<Id> setFinalizedOrder = new Set<Id>();
            List<Apttus_Config2__Order__c> listOrderToCSQue = new List<Apttus_Config2__Order__c>();

            for (Apttus_Config2__ProductConfiguration__c prevCart : listPrevCart) {
                system.debug('Inside Cart');

                cartId = prevCart.Id;
                orderID = prevCart.Apttus_Config2__OrderId__c;

                //IF ATP pass, than finalize cart
                if (cartIdATPPass.contains(cartId)) {
                    system.debug('ATP Pass');

                    //Finalize
                    APTS_OrderUtils.finalizeCart(cartId);
                    //Syncronize
                    Boolean isSuccess = APTS_OrderUtils.syncCart(cartId);

                    if (isSuccess) {
                        setFinalizedOrder.add(orderID);
                    }
                } else {
                    system.debug('ATP failed');

                    //IF ATP fails, than assign to CS Queue
                    Apttus_Config2__Order__c order = new Apttus_Config2__Order__c(Id = orderID, ownerId = queue.Id);
                    listOrderToCSQue.add(order);

                    APTS_Order_Error_Log__c oErrLog = APTS_DigitalOrderBatchHelper.createErrorLog('ATP Check failed, please reconfigure cart for more details', orderID, NULL, orderID, NULL, queue);
                    if (oErrLog != null) {
                        listErrorLog.add(oErrLog);
                    }
                }
            }

            //update order line items after finalizing cart
            if (!setFinalizedOrder.isEmpty()) {
                system.debug('after finalize code');
                APTS_DigitalOrderBatchHelper.updateOLIAndsubmit(queue, setFinalizedOrder, mapEPIOLI);
            }

            //assign order to CS-Queue
            if (!listOrderToCSQue.isEmpty()) {
                update listOrderToCSQue;
            }

            if (Test.isRunningTest()) {
                throw new testException('Test');
            }

        } catch (Exception ex) {
            String strMsg = 'Exception on Line Number = ' + ex.getLineNumber() + ' StraceTrace :: ' + ex.getStackTraceString() + ' error msg = ' + ex.getMessage();
            APTS_Order_Error_Log__c oErrLog = APTS_DigitalOrderBatchHelper.createErrorLog(strMsg, orderID, NULL, orderID, NULL, queue);
            if (oErrLog != null) {
                listErrorLog.add(oErrLog);
            }
        } finally {

            if (listErrorLog != null && !listErrorLog.isEmpty()) {
                Database.insert(listErrorLog, false);
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        Group queue;
        List<APTS_Order_Error_Log__c> listErrorLog = new List<APTS_Order_Error_Log__c>();

        try {

            queue = APTS_DigitalOrderBatchHelper.getCSQueue();

            if (setInterfaceId != null) {
                //v101
                List<APTS_Order_Interface_Log__c> listLog = APTS_DigitalOrderBatchHelper.getStatusInterfaceLog(queue, setInterfaceId);


                if (listLog != null && !listLog.isEmpty()) {
                    Database.update(listLog, false);
                }

                //Submit Order
                //APTS_DigitalOrderBatchHelper.updateOLIAndsubmit(queue, setNewOrderId, mapEPIOLI);
            }
            if (Test.isRunningTest()) {
                throw new testException('Test');
            }

        } catch (Exception ex) {
            string errorMsg = ex.getStackTraceString() + ex.getMessage();
            APTS_Order_Error_Log__c oErrLog = APTS_DigitalOrderBatchHelper.createErrorLog(errorMsg, NULL, NULL, NULL, NULL, queue);
            if (oErrLog != null) {
                listErrorLog.add(oErrLog);
            }

        } finally {

            if (listErrorLog != null && !listErrorLog.isEmpty()) {
                Database.insert(listErrorLog, false);
            }
        }
    }
}