src/objects/APTS_IntegrationLogFireForgetInterfaces__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Fire and Forget interfaces which are related to Integration Log deletion batch. Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
    <label>IntegrationLogFireAndForgetInterfaces</label>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IntegrationUserAndProfile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IntegrationUserAndProfile</label>
</CustomObject>

src/classes/APTS_DeleteFireAndForgetIntLogBatch_Test.cls
/**
* Class Name : APTS_DeleteFireAndForgetIntLogBatch_Test
* Description :  Apex Class to test APTS_DeleteFireAndForgetIntLogsBatch class
* Author : V. Shankaranarayanan (v.shankaranarayanan@accenture.com)
* Date Created : 07-05-2018
**/
@isTest
private class APTS_DeleteFireAndForgetIntLogBatch_Test{
    
    private static String status = 'Outbound Message Triggered';
    
    /**Method Name : testData
    * Description : Method used to create test data
    **/
    @testSetup
    static void testData(){
        IntegrationUserAndProfile__c custSetting = APTS_TestDataFactory.createIntegrationUserAndProfile();
        Database.insert(custSetting, false);
        
        List<APTS_IntegrationLogFireForgetInterfaces__c> interfaceSetting = APTS_TestDataFactory.createFandFInterfaces();
        Database.insert(interfaceSetting, false);
        
        List<Integration_Log__c> logList = APTS_TestDataFactory.createIntegrationLog(200, status);
        Database.insert(logList, false);
    }
    
    /**Method Name : testRelatedInvoiceDeletion
    * Description : Method used to test whether the old Integration Log records
    * related to 'RelatedInvoice__c' Fire and Forget interface are deleted properly
    **/
    @isTest
    static void testRelatedInvoiceDeletion(){
        IntegrationUserAndProfile__c custSetting =  IntegrationUserAndProfile__c.getOrgDefaults();
        
        List<Integration_Log__c> logUpdateList = new List<Integration_Log__c>();
        for(Integration_Log__c log : [SELECT Id, Object__c FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000]){
            log.Object__c = 'RelatedInvoice__c';
            logUpdateList.add(log);
        }
        Database.update(logUpdateList, false);
        
        test.startTest();
        APTS_DeleteFireAndForgetIntLogsBatch batch = new APTS_DeleteFireAndForgetIntLogsBatch();
        Database.executeBatch(batch, 200);
        test.stopTest();
        
        List<Integration_Log__c> deletedLogList = new List<Integration_Log__c>();
        for(Integration_Log__c deletedLog : [SELECT Id, IsDeleted FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000 ALL ROWS]){
            if(deletedLog.IsDeleted){
                deletedLogList.add(deletedLog);
            }
        }
        
        System.AssertEquals(200, deletedLogList.size());
    }
    
    /**Method Name : testAccountHierarchyDeletion
    * Description : Method used to test whether the old Integration Log records
    * related to 'Account Hierarchy' Fire and Forget interface are deleted properly
    **/
    @isTest
    static void testAccountHierarchyDeletion(){
        IntegrationUserAndProfile__c custSetting =  IntegrationUserAndProfile__c.getOrgDefaults();
        
        List<Integration_Log__c> logUpdateList = new List<Integration_Log__c>();
        for(Integration_Log__c log : [SELECT Id, Object__c FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000]){
            log.Object__c = 'Account Hierarchy';
            logUpdateList.add(log);
        }
        Database.update(logUpdateList, false);
        
        test.startTest();
        APTS_DeleteFireAndForgetIntLogsBatch batch = new APTS_DeleteFireAndForgetIntLogsBatch();
        Database.executeBatch(batch, 200);
        test.stopTest();
        
        List<Integration_Log__c> deletedLogList = new List<Integration_Log__c>();
        for(Integration_Log__c deletedLog : [SELECT Id, IsDeleted FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000 ALL ROWS]){
            if(deletedLog.IsDeleted){
                deletedLogList.add(deletedLog);
            }
        }
        
        System.AssertEquals(200, deletedLogList.size());
    }
    
    /**Method Name : testWOLICatsRecordDeletion
    * Description : Method used to test whether the old Integration Log records
    * related to 'Work Order Line Item - CATS-record' Fire and Forget interface are deleted properly
    **/
    @isTest
    static void testWOLICatsRecordDeletion(){
        IntegrationUserAndProfile__c custSetting =  IntegrationUserAndProfile__c.getOrgDefaults();
        
        List<Integration_Log__c> logUpdateList = new List<Integration_Log__c>();
        for(Integration_Log__c log : [SELECT Id, Object__c FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000]){
            log.Object__c = 'Work Order Line Item - CATS-record';
            logUpdateList.add(log);
        }
        Database.update(logUpdateList, false);
        
        test.startTest();
        APTS_DeleteFireAndForgetIntLogsBatch batch = new APTS_DeleteFireAndForgetIntLogsBatch();
        Database.executeBatch(batch, 200);
        test.stopTest();
        
        List<Integration_Log__c> deletedLogList = new List<Integration_Log__c>();
        for(Integration_Log__c deletedLog : [SELECT Id, IsDeleted FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000 ALL ROWS]){
            if(deletedLog.IsDeleted){
                deletedLogList.add(deletedLog);
            }
        }

        System.AssertEquals(200, deletedLogList.size());
    }
    
    /**Method Name : testNonFandFNonDeletion
    * Description : Method used to test whether the old Integration Log records not
    * related to Fire and Forget interfaces are not deleted
    **/
    @isTest
    static void testNonFandFNonDeletion(){
        IntegrationUserAndProfile__c custSetting =  IntegrationUserAndProfile__c.getOrgDefaults();
        
        List<Integration_Log__c> logUpdateList = new List<Integration_Log__c>();
        for(Integration_Log__c log : [SELECT Id, Object__c FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000]){
            log.Object__c = status;//Outbound Message Triggered
            logUpdateList.add(log);
        }
        Database.update(logUpdateList, false);
        
        test.startTest();
        APTS_DeleteFireAndForgetIntLogsBatch batch = new APTS_DeleteFireAndForgetIntLogsBatch();
        Database.executeBatch(batch, 200);
        test.stopTest();
        
        List<Integration_Log__c> deletedLogList = new List<Integration_Log__c>();
        for(Integration_Log__c deletedLog : [SELECT Id, IsDeleted FROM Integration_Log__c WHERE Integration_Status__c =: status LIMIT 50000 ALL ROWS]){
            if(deletedLog.IsDeleted){
                deletedLogList.add(deletedLog);
            }
        }

        System.AssertEquals(0, deletedLogList.size());
    }
}