src/objects/APTS_Index_Contract__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Index Contracts</relationshipLabel>
        <relationshipName>Index_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>APTS_Index_Type__c</fullName>
        <description>Type of Indexation</description>
        <inlineHelpText>Type of Indexation</inlineHelpText>
        <label>Index Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Indexation</fullName>
                    <default>true</default>
                    <label>Standard Indexation</label>
                </value>
                <value>
                    <fullName>Non-Standard Indexation</fullName>
                </value>
                <value>
                    <fullName>No Indexation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Indexation_Category__c</fullName>
        <description>Defines Indexation Category</description>
        <inlineHelpText>Defines Indexation Category</inlineHelpText>
        <label>Indexation Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Products (Ingredients and &amp;More)</fullName>
                </value>
                <value>
                    <fullName>Technical Services</fullName>
                </value>
                <value>
                    <fullName>Consumption Pricing</fullName>
                </value>
                <value>
                    <fullName>Machine Care Service</fullName>
                    <isActive>false</isActive>
                    <label>Machine Care Service</label>
                </value>
                <value>
                    <fullName>Maintenance Services</fullName>
                    <isActive>false</isActive>
                    <label>Maintenance Services</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Index Contract</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Index Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Index Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_IndexationRelatedListDetails__c</fullName>
        <label>IndexationRelatedListDetails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_SV</fullName>
                    <label>Swedish</label>
                </value>
                <value>
                    <fullName>SAP_EN</fullName>
                    <label>English</label>
                </value>
                <value>
                    <fullName>SAP_NL</fullName>
                    <label>Dutch</label>
                </value>
                <value>
                    <fullName>SAP_FR</fullName>
                    <label>French</label>
                </value>
                <value>
                    <fullName>SAP_NO</fullName>
                    <label>Norwegian</label>
                </value>
                <value>
                    <fullName>SAP_DA</fullName>
                    <label>Danish</label>
                </value>
                <value>
                    <fullName>SAP_SR</fullName>
                    <label>Serbian</label>
                </value>
                <value>
                    <fullName>SAP_ZH</fullName>
                    <label>Chinese</label>
                </value>
                <value>
                    <fullName>SAP_TH</fullName>
                    <label>Thai</label>
                </value>
                <value>
                    <fullName>SAP_KO</fullName>
                    <label>Korean</label>
                </value>
                <value>
                    <fullName>SAP_RO</fullName>
                    <label>Romanian</label>
                </value>
                <value>
                    <fullName>SAP_SL</fullName>
                    <label>Slovenian</label>
                </value>
                <value>
                    <fullName>SAP_HR</fullName>
                    <label>Croatian</label>
                </value>
                <value>
                    <fullName>SAP_MS</fullName>
                    <label>Malaysian</label>
                </value>
                <value>
                    <fullName>SAP_UK</fullName>
                    <label>Ukrainian</label>
                </value>
                <value>
                    <fullName>SAP_ET</fullName>
                    <label>Estonian</label>
                </value>
                <value>
                    <fullName>SAP_AR</fullName>
                    <label>Arabic</label>
                </value>
                <value>
                    <fullName>SAP_HE</fullName>
                    <label>Hebrew</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Czech</label>
                </value>
                <value>
                    <fullName>SAP_DE</fullName>
                    <label>German</label>
                </value>
                <value>
                    <fullName>SAP_EL</fullName>
                    <label>Greek</label>
                </value>
                <value>
                    <fullName>SAP_HU</fullName>
                    <label>Hungarian</label>
                </value>
                <value>
                    <fullName>SAP_IT</fullName>
                    <label>Italian</label>
                </value>
                <value>
                    <fullName>SAP_JA</fullName>
                    <label>Japanese</label>
                </value>
                <value>
                    <fullName>SAP_PL</fullName>
                    <label>Polish</label>
                </value>
                <value>
                    <fullName>SAP_ZF</fullName>
                    <label>Chinese trad</label>
                </value>
                <value>
                    <fullName>SAP_PT</fullName>
                    <label>Portuguese</label>
                </value>
                <value>
                    <fullName>SAP_SK</fullName>
                    <label>Slovakian</label>
                </value>
                <value>
                    <fullName>SAP_RU</fullName>
                    <label>Russian</label>
                </value>
                <value>
                    <fullName>SAP_ES</fullName>
                    <label>Spanish</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Indexation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non – Standard Deal (Indexation)</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>APTS_IndexContractTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IndexContractTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Index_Contract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Index Contract</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_IndexContractTriggerHandlerTest.cls
/**************************************************************
 * @Author: jason.e.mactal
 * @Company: Accenture
 * @Description: Test class for APTS_IndexContractTriggerHandler
 * @Created Date: May 7, 2018
 * @Revisions:
 *      <Name>              <Date>          <Description>
 *      jason.e.mactal      June 8, 2018     Initial Version
 * 
 *************************************************************/
@isTest
private class APTS_IndexContractTriggerHandlerTest {
    
    
    @testSetup
    static void testSetup() {
        
        User testUser = APTS_TestDataFactory.createUser();
        
        system.runAs(testUser){
        insert new TriggerSettings__c(APTS_IndexContractTrigger__c = true);
            
            Account oAcc = APTS_TestDataFactory.createAccount('Test Account');
            insert oAcc;
            
            Apttus__APTS_Agreement__c oAgg = APTS_TestDataFactory.createAgreement(null, null, oAcc.id, 'Standard Deal');
            oAgg.APTS_Language__c='English';
            insert oAgg;
        }
        
        
    }
	private static testMethod void rollUptoAggStandardIndexation() {
	    Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
	    User testUser = [SELECT Id FROM User LIMIT 1];
	    APTS_Index_Contract__c oIndexCont = new APTS_Index_Contract__c();
	    oIndexCont.APTS_Contract__c = oAgg.id;
	    oIndexCont.APTS_Index_Type__c = 'Standard Indexation';
	    oIndexCont.APTS_Start_Date__c=System.today();
        oIndexCont.APTS_Indexation_Category__c= 'Technical Services';
	    test.startTest();
        system.runAs(testUser){
            insert oIndexCont;
            oIndexCont.APTS_Index_Type__c = 'Non-Standard Indexation';
            update oIndexCont;
            oIndexCont.APTS_Index_Type__c = 'Standard Indexation';
            update oIndexCont;
            delete oIndexCont;
            undelete oIndexCont;
        }
        Apttus__APTS_Agreement__c oAggCheck = [SELECT Id, APTS_Non_Standard_Deal_Indexation__c FROM Apttus__APTS_Agreement__c LIMIT 1];
        system.assertEquals(FALSE, oAggCheck.APTS_Non_Standard_Deal_Indexation__c);
	}
        
    private static testMethod void rollUptoAggnonStandardIndexation() {
	    Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
	    User testUser = [SELECT Id FROM User LIMIT 1];
        APTS_Index_Contract__c oIndexCont1 = new APTS_Index_Contract__c();
	    oIndexCont1.APTS_Contract__c = oAgg.id;
	    oIndexCont1.APTS_Index_Type__c = 'Non-Standard Indexation';
        oIndexCont1.APTS_Indexation_Category__c= 'Technical Services';
	     oIndexCont1.APTS_Start_Date__c=System.today();
         insert oIndexCont1;

         APTS_Index_Contract__c oIndexCont2 = new APTS_Index_Contract__c();
         oIndexCont2.APTS_Contract__c = oAgg.id;
         oIndexCont2.APTS_Index_Type__c = 'Non-Standard Indexation';
         oIndexCont2.APTS_Indexation_Category__c= 'Technical Services';
         oIndexCont2.APTS_Start_Date__c=System.today();
         insert oIndexCont2;

	    APTS_Index_Contract__c oIndexCont = new APTS_Index_Contract__c();
	    oIndexCont.APTS_Contract__c = oAgg.id;
	    oIndexCont.APTS_Index_Type__c = 'Non-Standard Indexation';
	    oIndexCont.APTS_Start_Date__c=System.today();
        oIndexCont.APTS_Indexation_Category__c= 'Technical Services';
	    test.startTest();
        system.runAs(testUser){
            insert oIndexCont;
            oIndexCont.APTS_Index_Type__c = 'No Indexation';
            oAgg.APTS_IndexationRelatedListDetails__c='abc|';
            update oAgg;
            update oIndexCont;
            delete oIndexCont;
            delete oIndexCont1;
            delete oIndexCont2;
            undelete oIndexCont;
        }
        Apttus__APTS_Agreement__c oAggCheck = [SELECT Id, APTS_Non_Standard_Deal_Indexation__c FROM Apttus__APTS_Agreement__c LIMIT 1];
        system.assertEquals(TRUE, oAggCheck.APTS_Non_Standard_Deal_Indexation__c);
	}

}