src/objects/APTS_Batch_Queries__mdt.object
<CustomObject>
    <description>Custom metadata to store batch queries</description>
    <fields>
        <fullName>APTS_API__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to decide which api to use in pricing</description>
        <label>API</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Query_String__c</fullName>
        <description>Field to store queries</description>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>APTS_Triggers__c</fullName>
        <description>Comma separated list of triggers to be deactivated</description>
        <label>Triggers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Batch query</label>
    <pluralLabel>Batch queries</pluralLabel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProductConfigFinalizationBatch.cls
/*************************************************************
@Name: APTS_ProductConfigFinalizationBatch
@Author: Raul Orozco
@CreateDate: 09-05-2018
@Description: Batch class created for migration purposes.
@UsedBy: APTS_ProductConfigFinalizationBatch
******************************************************************/
global class APTS_ProductConfigFinalizationBatch implements Database.Batchable<sObject> {
	
	String strQuery;
    Boolean bAPI;
    Boolean bcreateCER;
    Set<String> setTriggers;
    global Set<Id> productConfigIdSet;

	global APTS_ProductConfigFinalizationBatch() {
        //Get the query from custom metadata
        List<APTS_Batch_Queries__mdt> lstMetadata = new APTS_BatchMetadataCoverage().getMetadataCoverageRecords(
            'SELECT APTS_Batch_Name__c,'+
            'APTS_Query_String__c, '+
            'DeveloperName, '+
            'APTS_API__c, '+
            'APTS_Triggers__c '+
            'FROM APTS_Batch_Queries__mdt '+
            'WHERE DeveloperName = \'ProductConfiguration_Finalization\''
        );

        //Set variables
        strQuery = lstMetadata[0].APTS_Query_String__c;
        bAPI = lstMetadata[0].APTS_API__c;
        List<String> splitString = lstMetadata[0].APTS_Triggers__c.split(',');
        setTriggers = new Set<String>(splitString);
    }

    //New constructor with line items id set as parameter, used for
    //batch scheduler class
    global APTS_ProductConfigFinalizationBatch(Set<Id> setProductConfigId) {
        productConfigIdSet = setProductConfigId;

        //Get the query from custom metadata
        List<APTS_Batch_Queries__mdt> lstMetadata = new APTS_BatchMetadataCoverage().getMetadataCoverageRecords(
            'SELECT APTS_Batch_Name__c,'+
            'APTS_Query_String__c,'+
            'DeveloperName,'+
            'APTS_API__c, '+
            'APTS_Triggers__c '+
            'FROM APTS_Batch_Queries__mdt '+
            'WHERE DeveloperName = \'Product_Config_Finalization_Scheduled\''
        );

        //Set variables
        strQuery = lstMetadata[0].APTS_Query_String__c;
        bAPI = lstMetadata[0].APTS_API__c;
        List<String> splitString = lstMetadata[0].APTS_Triggers__c.split(',');
        setTriggers = new Set<String>(splitString);
    }

	global Database.QueryLocator start(Database.BatchableContext BC) {
        // a) Inactivate triggers
        if(setTriggers.size() > 0){
            APTS_AgreementLoadBatchHelper.modifyTriggers(setTriggers,'Deactivate');
        }        
        
        return Database.getQueryLocator(strQuery);
	}

   	global void execute(Database.BatchableContext BC, List<Apttus_Config2__ProductConfiguration__c> lstProductConfigurations) {
		APTS_AgreementLoadBatchHelper.processProductConfigurations(lstProductConfigurations,bAPI);
	}
	
	global void finish(Database.BatchableContext BC) {
		//h)    Activate triggers
        if(setTriggers.size() > 0){
            APTS_AgreementLoadBatchHelper.modifyTriggers(setTriggers,'Activate');
        }           
	}
	
}