src/objects/APTS_Batch_Queries__mdt.object
<CustomObject>
    <description>Custom metadata to store batch queries</description>
    <fields>
        <fullName>APTS_Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Query_String__c</fullName>
        <description>Field to store queries</description>
        <label>Query String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch query</label>
    <pluralLabel>Batch queries</pluralLabel>
</CustomObject>

src/objects/APTS_Index_Contract__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Index Contracts</relationshipLabel>
        <relationshipName>Index_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>APTS_Indexation_Category__c</fullName>
        <description>Defines Indexation Category</description>
        <inlineHelpText>Defines Indexation Category</inlineHelpText>
        <label>Indexation Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Products (Ingredients and &amp;More)</fullName>
                </value>
                <value>
                    <fullName>Technical Services</fullName>
                </value>
                <value>
                    <fullName>Consumption Pricing</fullName>
                </value>
                <value>
                    <fullName>Machine Care Service</fullName>
                    <isActive>false</isActive>
                    <label>Machine Care Service</label>
                </value>
                <value>
                    <fullName>Maintenance Services</fullName>
                    <isActive>false</isActive>
                    <label>Maintenance Services</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Indexation_Number__c</fullName>
        <label>Indexation Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Index Contract</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Index Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Index Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_IndexationBatch_Phase1.cls
/**
 * @description       : APTS_IndexationBatch_Phase1
 * @author            : Karan Khatri
 * @group             : 
 * @last modified on  : 02-02-2021
 * @last modified by  : Karan Khatri
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   02-02-2021   Karan Khatri   Initial Version
**/
global class APTS_IndexationBatch_Phase1 implements Database.Batchable<sObject>,Database.Stateful{

    String region;
    String query;
    String batchType;
    Date batchDate;
    private static String SBATCHNAME = 'APTS_StandardIndexBatch';
    private static String BATCHNAME = 'APTS_IndexationBatch_Phase1';
    private static String NSBATCHNAME = 'APTS_NonStandardIndexBatch';
    private static String STANDARD = 'Standard';
    private static String NONSTANDARD = 'NonStandard';
    private static String STREAM = 'CLM';
    private static String TYPE = 'Batch';
    private static final String HYPHEN = '-';
    Set<ID> AgreementIDSet = new Set<ID>();
    Map<String, String> agmtIdToIndexNumberMap = new Map<String, String>();

    global APTS_IndexationBatch_Phase1(String region){
        if(region != null){
            this.region= region;
        }
        batchType=STANDARD;
    }
    
    global APTS_IndexationBatch_Phase1(Date batchDate){
        if(batchDate != null){
            this.batchDate= batchDate;
        }
         batchType=NONSTANDARD;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        try{
        
            APTS_AssetRenewalRollbackBatch.bypassCurrentUserfromTriggersandFlows();
        
            if(batchType==STANDARD){
                for(APTS_Batch_Queries__mdt batchQuery : [SELECT Id,
                                                              APTS_Query_String__c
                                                              FROM APTS_Batch_Queries__mdt
                                                              WHERE APTS_Batch_Name__c =: SBATCHNAME]){
                    query = batchQuery.APTS_Query_String__c;
                }
            }
            if(batchType==NONSTANDARD){
                for(APTS_Batch_Queries__mdt batchQuery : [SELECT Id,
                                                              APTS_Query_String__c
                                                              FROM APTS_Batch_Queries__mdt
                                                              WHERE APTS_Batch_Name__c =: NSBATCHNAME]){
                    query = batchQuery.APTS_Query_String__c;
                }
            }
            return Database.getQueryLocator(query);
        }catch(Exception ex){APTS_CustomLogging.createErrorLog(ex.getTypeName(), TYPE, String.valueOf(ex) ,BATCHNAME, null, STREAM, false, false, null, true); return null;}
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        for(APTS_Index_Contract__c indexContract : (List<APTS_Index_Contract__c>)scope){
            agreementIdSet.add(indexContract.APTS_Contract__c);
            if(String.IsNotBlank(indexContract.APTS_Indexation_Number__c)){
                String formattedNumber =indexContract.APTS_Indexation_Number__c.replace(',','.');
                agmtIdToIndexNumberMap.put(indexContract.APTS_Contract__c+ HYPHEN +indexContract.APTS_Indexation_Category__c, formattedNumber);
            }
         }
    }

    global void finish(Database.BatchableContext BC) {
        boolean isStdIndex = batchType == STANDARD ? true : false;
        Id batchInstanceId = Database.executeBatch(new APTS_IndexationBatch_Phase2(AgreementIDSet,agmtIdToIndexNumberMap, isStdIndex),200);
    }
}