src/objects/APTS_BizIsland__mdt.object
<CustomObject>
    <fields>
        <fullName>APTS_Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>APTS_BizIsland</label>
    <pluralLabel>APTS_BizIslands</pluralLabel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>APTS_Distribution_Channel__c</fullName>
        <formula>TEXT(APTS_Related_sales_org_data__r.APTS_Distribution_channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Plant__c</fullName>
        <formula>APTS_Related_sales_org_data__r.APTS_Default_Delivery_Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Org__c</fullName>
        <formula>TEXT(Apttus_Config2__PriceListId__r.APTS_Region__c)</formula>
        <label>Sales Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Cost__c</fullName>
        <description>The cost for the product</description>
        <label>Cost</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceUom__c</fullName>
        <description>The pricing unit of measure for the product</description>
        <label>Price Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductCode__c</fullName>
        <description>The product code</description>
        <formula>Apttus_Config2__ProductId__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The product code</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the price list</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BizIsland_Request__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Notify_Bonsai__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Bonsai</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Version</label>
        <type>AutoNumber</type>
    </fields>
    <label>BizIsland Request</label>
    <nameField>
        <label>BizIsland Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BizIslandRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bonsai__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Delta_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delta Load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Load</label>
        <type>Checkbox</type>
    </fields>
    <label>Bonsai Extraction Controller</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Cost_Price_Unit__c</fullName>
        <label>Cost Price Unit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Distribution_channel__c</fullName>
        <label>Distribution channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
                <value>
                    <fullName>Export</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Plant__c</fullName>
        <label>Plant</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_PriceListitemBizIsland_cost.cls
/**********************************************************************************
 * @Author: Keerthana
 * @Company: Accenture
 * @Description: Handles the Contents/file creation for Bizisland Pricelistitem and cost
 * @Created Date: Oct 4, 2018
 * @History:
 *      <Name>              <Date>          <Description>
 *      Keerthana          10.09.2018       Created
 **********************************************************************************/
global class APTS_PriceListitemBizIsland_cost implements Database.Batchable<sObject>, Database.Stateful {
   
    global String csvColumnHeader;
    global List<String> csvRowValues = new List<String>();
   
    global Database.QueryLocator start(Database.BatchableContext BC){
        Bonsai__c customSetting = Bonsai__c.getAll().values();
        String query;
        if(customSetting.Delta_Load__c){
            APTS_BizIsland__mdt bizmdt = [Select APTS_Query__c from APTS_BizIsland__mdt where DeveloperName= :'PriceListitemBizIsland_costDelta'][0];
            query = bizmdt.APTS_Query__c; 
        }else if(customSetting.Full_Load__c){
            APTS_BizIsland__mdt bizmdt = [Select APTS_Query__c from APTS_BizIsland__mdt where DeveloperName= :'PriceListitemBizIsland_costFull'][0];
            query = bizmdt.APTS_Query__c;
        }else{
            APTS_BizIsland__mdt bizmdt = [Select APTS_Query__c from APTS_BizIsland__mdt where DeveloperName= :'PriceListitemBizIsland_costDelta'][0];
            query = bizmdt.APTS_Query__c;
        }
            return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        String Status;
        String salesorg = '';
        String disChan = '';
        String uom = '';
        //String plan ='';
        for(Apttus_Config2__PriceListItem__c p : (List<Apttus_Config2__PriceListItem__c>) scope){
        if(p.CreatedDate.date()==System.Today())
            Status = 'New';
            else if(p.LastModifiedDate.date() ==System.Today())
            Status='Modified';
            else 
            Status='Not Modified';
            if((Status == 'Modified' || Status == 'New') && p.isDeleted == true)
            Status = 'Deleted';
            if(p.APTS_Sales_Org__c != NULL && p.APTS_Sales_Org__c.contains('SAP_')){
                salesorg = p.APTS_Sales_Org__c.replace('SAP_','');
            }else if(p.APTS_Sales_Org__c != NULL){
                salesorg = p.APTS_Sales_Org__c;
            }
            if(p.APTS_Distribution_Channel__c != NULL && p.APTS_Distribution_Channel__c.contains('SAP_')){
                disChan = p.APTS_Distribution_Channel__c.replace('SAP_','');
            }else if(p.APTS_Distribution_Channel__c != NULL){
               disChan = p.APTS_Distribution_Channel__c;
            }
                                                                                                                                                                                                    if(p.Apttus_Config2__PriceUom__c != NULL && p.Apttus_Config2__PriceUom__c.contains('SAP_')){
                uom = p.Apttus_Config2__PriceUom__c.replace('SAP_','');
            }else if (p.Apttus_Config2__PriceUom__c != NULL){
                uom = p.Apttus_Config2__PriceUom__c;
            }
            /*if(p.APTS_Plant__c != NULL && p.APTS_Plant__c.contains('SAP_')){
                plan = p.APTS_Plant__c.replace('SAP_','');
            }else if (p.APTS_Plant__c != NULL){
                plan = p.APTS_Plant__c;
            }*/
    
            String rowStrn = salesorg+','+disChan+','+p.APTS_Plant__c+','+p.Apttus_Config2__ProductCode__c+','+p.Apttus_Config2__Cost__c+','+p.CurrencyIsoCode+','+p.Apttus_Config2__ProductId__r.APTS_Cost_Price_Unit__c+','+uom+','+Status;
            csvRowValues.add(rowStrn);
            salesorg = '';
            disChan = '';
            uom = '';
        }
   
    }
    global void finish(Database.BatchableContext BC){
    
        Bonsai__c cs = Bonsai__c.getAll().values();
        Date d=system.today();
        String Bon='Bonsai Request'+' '+d;
        list<BizIsland_Request__c> biz=[SELECT Id, Name,Version__c FROM BizIsland_Request__c where name=:Bon];
            if(!biz.isEmpty()){
                csvColumnHeader ='Sales Organization,Distribution Channel,Plant,Product Number,Cost Price,Cost Price Currency,Price Unit,Base Unit of Measure,Status\n';
                String csvFile = csvColumnHeader + String.join(csvRowValues,'\n');
                APTS_BizIslandContentGenerator bizz=new APTS_BizIslandContentGenerator();
                    if(cs.Delta_Load__c){
                         String documentName = ' DELTA REPORT PROD_COST_WEBSHOP';
                         bizz.addAttachmentsToBonsai(biz[0],csvFile,documentName);
                    }else if(cs.Full_Load__c){
                        String documentName = 'FULL REPORT PROD_COST_WEBSHOP';
                        bizz.addAttachmentsToBonsai(biz[0],csvFile,documentName);
                    }
                biz[0].APTS_Notify_Bonsai__c = true;
                update biz;
            }
            
        }
    }