src/objects/APTS_Warehousing_Cost__c.object
<CustomObject>
    <label>Warehousing Cost</label>
    <nameField>
        <label>Warehousing Cost Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehousing Costs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Base_Extended_Price_2_decimals__c</fullName>
        <label>Base Extended Price – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Depreciation_Cost__c</fullName>
        <label>Depreciation Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Extended_Cost_2_decimals__c</fullName>
        <label>Extended Cost – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Is_Not_Rollup_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Not Rollup Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Net_Adjustment_Amount_2_decimals__c</fullName>
        <label>Net Adjustment Amount – 2 decimals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__ClassificationHierarchy__c</fullName>
        <description>The category hierarchy</description>
        <label>Category Hierarchy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__ExtendedCost__c</fullName>
        <description>The extended cost is Quantity X Term X (Base Cost + Cost Adjustment + Option Cost)</description>
        <inlineHelpText>The extended cost is Quantity X Term X (Base Cost + Cost Adjustment + Option Cost)</inlineHelpText>
        <label>Extended Cost</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <inlineHelpText>Indicates whether the product has options.</inlineHelpText>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__LineType__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                    <default>true</default>
                    <label>Product/Service</label>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__NetPrice__c</fullName>
        <description>The net price for the product or service is the Adjusted Price after applying the Group Adjustment %</description>
        <label>Net Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Depreciation_Cost__c</fullName>
        <label>Depreciation Cost</label>
        <summarizedField>Apttus__AgreementLineItem__c.APTS_Depreciation_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__LineType__c</field>
            <operation>equals</operation>
            <value>Product/Service</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__HasOptions__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Apttus__AgreementLineItem__c.Apttus_CMConfig__IsPrimaryLine__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Apttus__AgreementLineItem__c.Apttus__AgreementId__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>APTS_Distribution_Cost__c</fullName>
        <label>Distribution Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Warehousing_Cost__c</fullName>
        <label>Warehousing Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_RegenerateDiscountControllerTest.cls
/**************************************************************
 * @Author: jason.e.mactal
 * @Company: Accenture
 * @Description: Test class for APTS_RegenerateDiscountController
 * @Created Date: March 6, 2018
 * @Revisions:
 *      <Name>              <Date>          <Description>
 *      jason.e.mactal      March 6, 2018     Initial Version
 * 
 *************************************************************/
@isTest
private class APTS_RegenerateDiscountControllerTest {
    
    @testSetup
    static void testSetup() {
        
        User testUser = APTS_TestDataFactory.createUser();
        testUser.Email = 'testuser123@jdecoffee.com';
        system.runAs(testUser){
            Account oAcc = APTS_TestDataFactory.createAccount('Test Account');
            insert oAcc;
            
            Apttus__APTS_Agreement__c oAgg = APTS_TestDataFactory.createAgreement(null, null, oAcc.id, 'Standard Deal');
            oAgg.APTS_Region__c = 'SAP_0111';
            oAgg.APTS_Distribution_Cost__c = 5;
            oAgg.APTS_Warehousing_Cost__c = 8;
            insert oAgg;
            
            Apttus__AgreementLineItem__c oAggLI = new Apttus__AgreementLineItem__c();
            oAggLI.Apttus__AgreementId__c = oAgg.Id;
            oAggLI.Apttus_CMConfig__IsPrimaryLine__c = true;
            oAggLI.Apttus_CMConfig__HasOptions__c = true;
            oAggLI.Apttus_CMConfig__LineType__c = 'Product/Service';
            oAggLI.Apttus__Quantity__c = 1;
            oAggLI.APTS_Depreciation_Cost__c = 15;
            oAggLI.Apttus_CMConfig__ClassificationHierarchy__c = 'Machines';
            insert oAggLI;
            
            Apttus__AgreementLineItem__c oAggLI2 = new Apttus__AgreementLineItem__c();
            oAggLI2.Apttus__AgreementId__c = oAgg.Id;
            oAggLI2.APTS_Is_Not_Rollup_Line__c = true;
            oAggLI2.APTS_Net_Adjustment_Amount_2_decimals__c = 15;
            oAggLI2.APTS_Base_Extended_Price_2_decimals__c = 100;
            oAggLI2.APTS_Extended_Cost_2_decimals__c = 10;
            oAggLI2.Apttus_CMConfig__ExtendedCost__c = 10;
            oAggLI2.Apttus_CMConfig__ClassificationHierarchy__c = 'Machines';
            oAggLI2.Apttus__NetPrice__c = 85;
            insert oAggLI2;
            
        }
        
    }

    private static testMethod void regenerateDiscountsInsertTest() {
        user testUser = [SELECT Id FROM USER WHERE Email = 'testuser123@jdecoffee.com'];
        Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        PageReference pr = page.APTS_RegenerateDiscounts;
        pr.getParameters().put('Id', String.valueOf(oAgg.Id));
        
        system.runAs(testUser){
            Test.startTest();
                Test.setCurrentPage(pr);
                ApexPages.StandardController scAgg = new ApexPages.StandardController(oAgg);
                APTS_RegenerateDiscountsController cont = new APTS_RegenerateDiscountsController(scAgg);
                cont.regenerateDiscounts();
            Test.stopTest();
        }
        id agreementIdredirectCheck = ApexPages.currentPage().getParameters().get('id');
        system.assertEquals(agreementIdredirectCheck, oAgg.Id);

    }
    
    private static testMethod void regenerateDiscountsDeleteTest() {
        user testUser = [SELECT Id FROM USER WHERE Email = 'testuser123@jdecoffee.com'];
        Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        oAgg.Apttus__Status__c = 'Terminated';
        update oAgg;
        PageReference pr = page.APTS_RegenerateDiscounts;
        pr.getParameters().put('Id', String.valueOf(oAgg.Id));
        
        system.runAs(testUser){
            Test.startTest();
                Test.setCurrentPage(pr);
                ApexPages.StandardController scAgg = new ApexPages.StandardController(oAgg);
                APTS_RegenerateDiscountsController cont = new APTS_RegenerateDiscountsController(scAgg);
                cont.regenerateDiscounts();
            Test.stopTest();
        }
        id agreementIdredirectCheck = ApexPages.currentPage().getParameters().get('id');
        system.assertEquals(agreementIdredirectCheck, oAgg.Id);
    }
    private static testMethod void doCancelTest() {
        user testUser = [SELECT Id FROM USER WHERE Email = 'testuser123@jdecoffee.com'];
        Apttus__APTS_Agreement__c oAgg = [SELECT Id FROM Apttus__APTS_Agreement__c LIMIT 1];
        PageReference pr = page.APTS_RegenerateDiscounts;
        pr.getParameters().put('Id', String.valueOf(oAgg.Id));
        
        system.runAs(testUser){
            Test.startTest();
                Test.setCurrentPage(pr);
                ApexPages.StandardController scAgg = new ApexPages.StandardController(oAgg);
                APTS_RegenerateDiscountsController cont = new APTS_RegenerateDiscountsController(scAgg);
                cont.doCancel();
            Test.stopTest();
        }
        id agreementIdredirectCheck = ApexPages.currentPage().getParameters().get('id');
        system.assertEquals(agreementIdredirectCheck, oAgg.Id);
    }

}