src/objects/APTS_Order_Freight_Data__c.object
<CustomObject>
    <label>Order Freight Data</label>
    <nameField>
        <displayFormat>OFD-{0000}</displayFormat>
        <label>Order Freight ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Freights Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/APTS_SAP_Connection_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SAP Connection settings</description>
    <fields>
        <fullName>APTS_Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Endpoint__c</fullName>
        <description>Endpoint url</description>
        <inlineHelpText>Endpoint url</inlineHelpText>
        <label>Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>APTS_Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SAP Connection Settings</label>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_ATP_Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ATP Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Expected_Delivery_Date__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Expected_Delivery_Quantity__c</fullName>
        <label>Expected Delivery Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Plant_Code__c</fullName>
        <label>Plant Code</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PricingStatus__c</fullName>
        <description>The pricing status</description>
        <label>Pricing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__TaxBreakup__c.object
<CustomObject>
    <description>Represents the tax breakup of a product/service</description>
    <fields>
        <fullName>Apttus_Config2__LineItemId__c</fullName>
        <description>ID of the associated line item</description>
        <inlineHelpText>ID of the associated line item</inlineHelpText>
        <label>Line Item</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipName>TaxBreakups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Tax Breakup</label>
    <nameField>
        <displayFormat>TB-{00000000}</displayFormat>
        <label>Breakup Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Breakups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_PreviewOrderController.cls
/*************************************************************
@Name: APTS_PreviewOrderController
@Author: Galin Georgiev
@CreateDate: 04-01-2018
@Description: Order web service utils - Integration with SAP
@UsedBy:
******************************************************************/
//v100 16-03-2018 Galin Georgiev: Initial version.
//Comments in this format are mandatory for each change of code.
//Adding code comment example: v100++<< means start of changes and v100++>> means end of changes
//Removing code comment example: v100--<< means start of changes and v100-->> means end of changes

public without sharing class APTS_PreviewOrderController {

    private static final String ID = APTS_OrderConstants.ID;
    private static final String RETID = 'retId';
    private static final String FLOW = APTS_OrderConstants.Flow;
    private static final String NGSTANDARD_ORDER = APTS_OrderConstants.NGSTANDARD_ORDER;
    private static final String NGMACHINE_ORDER = APTS_OrderConstants.NG_MACHINEORDER;
    private static final String CARTPAGEURL = APTS_OrderConstants.CARTPAGEURL;
    private static final String EMAIL = APTS_OrderConstants.APTS_EMAIL;

    private Id cartId;
    private Id orderId;
    private String sFlow;

    public APTS_SAPWSFunctions.BAPI_SALESORDER_SIMULATE_Response_elementFuture responseFuture;
    public APTS_SAPXMLRequestWrapper oSAPXMLRequestWrapper;
    public List<Apttus_Config2__TaxBreakup__c> taxBreakupsToDeteList;

    public String sResult {get; set;}

    public APTS_PreviewOrderController() {

        cartId = ApexPages.currentPage().getParameters().get(ID);
        orderId = ApexPages.currentPage().getParameters().get(RETID);
        sFlow = ApexPages.currentPage().getParameters().get(FLOW);
    }

    public PageReference previewOrder() {

        PageReference pageRef;

        pageRef = doATPCheck();

        return pageRef;
    }

    public PageReference doATPCheck() {

        List<Apttus_Config2__LineItem__c> lineItemList = [
                    SELECT APTS_Expected_Delivery_Date__c, APTS_Expected_Delivery_Quantity__c, APTS_ATP_Cleared__c,
                    APTS_Plant_Code__c, Apttus_Config2__Quantity__c, Apttus_Config2__PricingStatus__c,
                    APTS_Requested_Delivery_Date__c
                    FROM Apttus_Config2__LineItem__c
                    WHERE Apttus_Config2__ConfigurationId__c = :cartId];

        Set<Id> lineItemIdSet = new Set<Id>();

        for (Apttus_Config2__LineItem__c oLineItem : lineItemList) {
            lineItemIdSet.add(oLineItem.Id);
        }

        List<Apttus_Config2__TaxBreakup__c> taxBreakupsToDeteList = [
                    SELECT Id
                    FROM Apttus_Config2__TaxBreakup__c
                    WHERE Apttus_Config2__LineItemId__c IN :lineItemIdSet];

        APTS_ATPResultWrapper oATPResultWrapper = new APTS_ATPResultWrapper();

        try {
            oATPResultWrapper = APTS_OrderWSUtils.doATPCheck(orderId, cartId);
        } catch (exception e) {
            APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getMessage() , 'Order', null, 'OM', false, true, null, true);
        }

        List<Apttus_Config2__LineItem__c> lineItemsToUpdateList = oATPResultWrapper.lineItemsToUpdateList;
        List<Apttus_Config2__TaxBreakup__c> taxBreakupsToInsertList = oATPResultWrapper.taxBreakupsToInsertList;
        List<APTS_Order_Freight_Data__c> freightDataToInsertList = oATPResultWrapper.freightDataToInsertList;

        if (!lineItemsToUpdateList.isEmpty()) {
            Database.update(lineItemsToUpdateList);
        }

        if (!taxBreakupsToDeteList.isEmpty()) {
            Database.delete(taxBreakupsToDeteList);
        }

        if (!taxBreakupsToInsertList.isEmpty()) {
            Database.insert(taxBreakupsToInsertList);
        }

        if (!freightDataToInsertList.isEmpty()) {
            Database.insert(freightDataToInsertList);
        }

        return goToCart();
    }

    public Continuation doAsyncATPCheck() {

        List<Apttus_Config2__LineItem__c> lineItemList = [
                    SELECT APTS_Expected_Delivery_Date__c, APTS_Expected_Delivery_Quantity__c, APTS_ATP_Cleared__c,
                    APTS_Plant_Code__c, Apttus_Config2__Quantity__c, Apttus_Config2__PricingStatus__c,
                    APTS_Requested_Delivery_Date__c
                    FROM Apttus_Config2__LineItem__c
                    WHERE Apttus_Config2__ConfigurationId__c = :cartId];

        Set<Id> lineItemIdSet = new Set<Id>();

        for (Apttus_Config2__LineItem__c oLineItem : lineItemList) {
            lineItemIdSet.add(oLineItem.Id);
        }

        taxBreakupsToDeteList = [
                                    SELECT Id
                                    FROM Apttus_Config2__TaxBreakup__c
                                    WHERE Apttus_Config2__LineItemId__c IN :lineItemIdSet];

        oSAPXMLRequestWrapper = APTS_OrderWSUtils.prepareXMLRequest(orderId, cartId);

        Integer TIMEOUT_INT_SECS = Integer.valueOf(APTS_SAP_Connection_Settings__c.getValues('ATP Check').APTS_Timeout__c * 1000);
        Continuation oContinuation = new Continuation(TIMEOUT_INT_SECS);
        oContinuation.continuationMethod = 'processResponse';

        APTS_SAPWSFunctions.AsyncHTTPS_Port oSAPWSFunctions = new APTS_SAPWSFunctions.AsyncHTTPS_Port();

        oSAPWSFunctions.endpoint_x = APTS_SAP_Connection_Settings__c.getValues('ATP Check').APTS_Endpoint__c;
        oSAPWSFunctions.clientCertName_x = APTS_SAP_Connection_Settings__c.getValues('ATP Check').APTS_Certificate_Name__c;
        oSAPWSFunctions.timeout_x = Integer.valueOf(APTS_SAP_Connection_Settings__c.getValues('ATP Check').APTS_Timeout__c * 1000);

        responseFuture = oSAPWSFunctions.doAsyncATPSimulation(
                             oContinuation, null, oSAPXMLRequestWrapper.ORDER_HEADER_IN,
                             null, null, null,
                             null, null, null,
                             null, null, null,
                             null, null, oSAPXMLRequestWrapper.ORDER_ITEMS_IN,
                             null, oSAPXMLRequestWrapper.ORDER_PARTNERS, null,
                             null, null);

        return oContinuation;
    }

    public Object processResponse() {

        APTS_SAPWSStructure.BAPI_SALESORDER_SIMULATE_Response_element response = responseFuture.getValue();
        APTS_ATPResultWrapper oATPResultWrapper = new APTS_ATPResultWrapper();
        oATPResultWrapper = APTS_OrderWSUtils.setAsyncATPCheckResults(response, oSAPXMLRequestWrapper.itemNumberToOrderLineItemMap);

        List<Apttus_Config2__LineItem__c> lineItemsToUpdateList = oATPResultWrapper.lineItemsToUpdateList;
        List<Apttus_Config2__TaxBreakup__c> taxBreakupsToInsertList = oATPResultWrapper.taxBreakupsToInsertList;
        List<APTS_Order_Freight_Data__c> freightDataToInsertList = oATPResultWrapper.freightDataToInsertList;

        if (!lineItemsToUpdateList.isEmpty()) {
            Database.update(lineItemsToUpdateList);
        }

        if (!taxBreakupsToDeteList.isEmpty()) {
            Database.delete(taxBreakupsToDeteList);
        }

        if (!taxBreakupsToInsertList.isEmpty()) {
            Database.insert(taxBreakupsToInsertList);
        }

        if (!freightDataToInsertList.isEmpty()) {
            Database.insert(freightDataToInsertList);
        }

        return goToCart();
    }

    public PageReference goToCart() {

        PageReference pageRef;

        Map<String, String> parameterMap = ApexPages.currentPage().getParameters();
        Id tempObjectId = parameterMap.get('configRequestId');

        List<String> filterList = new String[] {tempObjectId, cartId, sFlow};

        pageRef = new PageReference(String.format(CARTPAGEURL, filterList));

        return pageRef;
    }
}