src/objects/Apttus_Approval__Approval_Request__c.object
<CustomObject>
    <description>Designates an approval request created from an approval process</description>
    <fields>
        <fullName>APTS_Related_Credit_Memo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Credit Memo</label>
        <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
        <relationshipLabel>Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Related_IncentivePayoutSchedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Incentive Payout Schedule</label>
        <referenceTo>Apttus_Rebate__IncentivePayoutSchedule__c</referenceTo>
        <relationshipLabel>Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Approval Requests</relationshipLabel>
        <relationshipName>Approval_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Object_Id__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Approval Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__CreditMemo__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Billing__BillToAccountId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Bill To address on the associated Account.</description>
        <inlineHelpText>The Bill To address on the associated Account.</inlineHelpText>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Memos</relationshipLabel>
        <relationshipName>CreditMemos</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Billing__CreditAmount__c</fullName>
        <description>The total amount to set off against a balance from invoice or other transactions.</description>
        <inlineHelpText>Amount to set off against a balance from invoice or other transactions.</inlineHelpText>
        <label>Credit Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Billing__Description__c</fullName>
        <description>Description or notes for additional information on the Credit Memo.</description>
        <inlineHelpText>Description or notes for additional information.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Billing__InvoiceID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Invoice ID for which the Credit Memo is created.</description>
        <inlineHelpText>Invoice ID for which this Credit Memo is created.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>Apttus_Billing__Invoice__c</referenceTo>
        <relationshipLabel>Credit Memos</relationshipLabel>
        <relationshipName>CreditMemos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__Invoice__c.object
<CustomObject>
    <description>Represents an invoice associated with an account</description>
    <fields>
        <fullName>Apttus_Billing__BillToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the bill to account</description>
        <inlineHelpText>ID of the bill to account</inlineHelpText>
        <label>Bill To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Bill To)</relationshipLabel>
        <relationshipName>InvoicesBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Billing__TotalInvoiceAmount__c</fullName>
        <description>The total invoice amount</description>
        <inlineHelpText>The total invoice amount</inlineHelpText>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Incentive__c.object
<CustomObject>
    <description>Represents an incentive associated with one or more products</description>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The incentive priority sequence. Indicates the order of application of the incentive.</description>
        <inlineHelpText>The incentive priority sequence. Indicates the order of application of the incentive.</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The incentive status</description>
        <inlineHelpText>The incentive status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The order status</description>
        <inlineHelpText>The order status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Rebate__IncentivePayoutSchedule__c.object
<CustomObject>
    <description>Represents the payout for a particular incentive</description>
    <fields>
        <fullName>Apttus_Rebate__IncentiveId__c</fullName>
        <description>ID of the associated incentive</description>
        <inlineHelpText>ID of the associated incentive</inlineHelpText>
        <label>Incentive</label>
        <referenceTo>Apttus_Config2__Incentive__c</referenceTo>
        <relationshipLabel>Incentive Payout Schedules</relationshipLabel>
        <relationshipName>PayoutSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incentive Payout Schedule</label>
    <nameField>
        <displayFormat>PS-{0000000000}</displayFormat>
        <label>Schedule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Payout Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>APTS_ApprovalRequestTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APTS_ApprovalRequestTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_ApprovalRequestTriggerHandlerTest.cls
/**************************************************************
 * @Author: jason.e.mactal
 * @Company: Accenture
 * @Description: Test class for APTS_ApprovalRequestTriggerHandler
 * @Created Date: May 3, 2018
 * @Revisions:
 *      <Name>              <Date>          <Description>
 *      jason.e.mactal      June 20, 2018   Initial Version
 * 
 *************************************************************/
@isTest
private class APTS_ApprovalRequestTriggerHandlerTest {

    @testSetup
    static void testSetup() {
        
        User testUser = APTS_TestDataFactory.createUser();
        insert testUser;
        
        Account oAcc = APTS_TestDataFactory.createAccount('Test Acc');
        insert oAcc;
        
        Apttus_Config2__Order__c oOrder = APTS_TestDataFactory.createOrder(oAcc.Id, null, null);
        insert oOrder;
        
        Apttus_Billing__Invoice__c oInv = new Apttus_Billing__Invoice__c();
        oInv.Apttus_Billing__BillToAccountId__c = oAcc.id;
        oInv.Apttus_Billing__TotalInvoiceAmount__c = 100;
        insert oInv;
        
        Apttus_Billing__CreditMemo__c oCreditMemo = new Apttus_Billing__CreditMemo__c();
        oCreditMemo.Apttus_Billing__BillToAccountId__c = oAcc.Id;
        oCreditMemo.Apttus_Billing__CreditAmount__c = 100;
        oCreditMemo.Apttus_Billing__Description__c = 'Test Credit Memo';
        oCreditMemo.Apttus_Billing__InvoiceID__c = oInv.Id;
        insert oCreditMemo;
        
        Apttus_Config2__Incentive__c oIncentive = new Apttus_Config2__Incentive__c();
        oIncentive.Apttus_Config2__Sequence__c = 1;
        oIncentive.Apttus_Config2__Status__c = 'Draft';
        insert oIncentive;
        
        Apttus_Rebate__IncentivePayoutSchedule__c incentPS = new Apttus_Rebate__IncentivePayoutSchedule__c();
        incentPS.Apttus_Rebate__IncentiveId__c = oIncentive.id;
        insert incentPS;
        
        
        insert new TriggerSettings__c(APTS_ApprovalRequestTrigger__c = true);
        

    }

	private static testMethod void updateLookupFieldsTest() {
	    user testUser = [SELECT Id FROM User WHERE Username = 'testuser123@jdecoffee.com'];
	    
	    Apttus_Config2__Order__c oOrder = [SELECT ID FROM Apttus_Config2__Order__c LIMIT 1];
	    Apttus_Billing__CreditMemo__c oCreditMemo = [SELECT ID FROM Apttus_Billing__CreditMemo__c LIMIT 1];
	    Apttus_Rebate__IncentivePayoutSchedule__c oIPS = [SELECT ID FROM Apttus_Rebate__IncentivePayoutSchedule__c LIMIT 1];
	    
	    List<Apttus_Approval__Approval_Request__c> oAppReqList = new List<Apttus_Approval__Approval_Request__c>();
	    
	    Apttus_Approval__Approval_Request__c oAppReqOrder = new Apttus_Approval__Approval_Request__c();
	    oAppReqOrder.Apttus_Approval__Object_Id__c = oOrder.Id;
	    oAppReqOrder.Apttus_Approval__Object_Type__c = 'Apttus_Config2__Order__c';
	    oAppReqList.add(oAppReqOrder);
	    
	    Apttus_Approval__Approval_Request__c oAppReqCM = new Apttus_Approval__Approval_Request__c();
	    oAppReqCM.Apttus_Approval__Object_Id__c = oCreditMemo.Id;
	    oAppReqCM.Apttus_Approval__Object_Type__c = 'Apttus_Billing__CreditMemo__c';
	    oAppReqList.add(oAppReqCM);

	    Apttus_Approval__Approval_Request__c oAppReqIPS = new Apttus_Approval__Approval_Request__c();
	    oAppReqIPS.Apttus_Approval__Object_Id__c = oIPS.Id;
	    oAppReqIPS.Apttus_Approval__Object_Type__c = 'Apttus_Rebate__IncentivePayoutSchedule__c';
	    oAppReqList.add(oAppReqIPS);
	    
        system.runAs(testUser) {
            test.startTest();
            insert oAppReqList;
            update oAppReqList;
            delete oAppReqList;
            undelete oAppReqList;
            test.stopTest();
        }
        Apttus_Approval__Approval_Request__c oAppReqOrderCheck = [SELECT ID, APTS_Related_Order__c FROM Apttus_Approval__Approval_Request__c WHERE APTS_Related_Order__c != null LIMIT 1];
        Apttus_Approval__Approval_Request__c oAppReqOrderCMCheck = [SELECT ID, APTS_Related_Credit_Memo__c FROM Apttus_Approval__Approval_Request__c WHERE APTS_Related_Credit_Memo__c != null LIMIT 1];
        Apttus_Approval__Approval_Request__c oAppReqOrderIPSCheck = [SELECT ID, APTS_Related_IncentivePayoutSchedule__c FROM Apttus_Approval__Approval_Request__c WHERE APTS_Related_IncentivePayoutSchedule__c != null LIMIT 1];
        
        system.assertEquals(oAppReqOrderCheck.APTS_Related_Order__c,oOrder.id);
        system.assertEquals(oAppReqOrderCMCheck.APTS_Related_Credit_Memo__c,oCreditMemo.id);
        system.assertEquals(oAppReqOrderIPSCheck.APTS_Related_IncentivePayoutSchedule__c,oIPS.id);
        
	}

}