src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Confirmation_Status__c</fullName>
        <label>Order Confirmation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Resend Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SM_ResendEmailOrderConfirmation.cls
public without sharing class SM_ResendEmailOrderConfirmation {
    @InvocableMethod
    public static void resendOrderConfirmation(List<Id> orderRecId) {
        List<Apttus_Config2__Order__c> orderList = new List<Apttus_Config2__Order__c>();
        List<Apttus_Config2__Order__c> orderRecs = new List<Apttus_Config2__Order__c>();
        orderRecs = [Select Id, APTS_Order_Confirmation_Status__c FROM Apttus_Config2__Order__c WHERE Id IN :orderRecId];
        for (Apttus_Config2__Order__c orderRec : orderRecs) {
            orderRec.APTS_Order_Confirmation_Status__c = 'Resend Order Confirmation';
            orderList.add(orderRec);
        }
        
        if (!orderList.isEmpty()) {
            APTS_OrderUtils.stopOrderTrigger();
            update orderList;
        }
    }
}