src/objects/Apttus_Billing__CreditMemo__c.object
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Credit Memo Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Billing__CreditMemoLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Apttus_Billing__Amount__c</fullName>
        <description>Amount of each of the Credit Memo Line Item derived from the Credit Memo.</description>
        <inlineHelpText>Amount of the Credit Memo Line Item.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Billing__CreditMemoId__c</fullName>
        <description>Parent Credit Memo ID.</description>
        <inlineHelpText>Parent Credit Memo ID.</inlineHelpText>
        <label>Credit Memo</label>
        <referenceTo>Apttus_Billing__CreditMemo__c</referenceTo>
        <relationshipLabel>Credit Memo Line Items</relationshipLabel>
        <relationshipName>CreditMemoLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credit Memo Line Item</label>
    <nameField>
        <displayFormat>CMI-{00000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_CreditMemoApprovalEmailController.cls
public with sharing class APTS_CreditMemoApprovalEmailController {
    
    public Id creditMemoId {get; set;}
    
    public Apttus_Billing__CreditMemo__c getCreditMemo(){
        Apttus_Billing__CreditMemo__c oCreditMemo = [SELECT Id, Name, Owner.Name FROM Apttus_Billing__CreditMemo__c WHERE Id =: creditMemoId];
        return oCreditMemo;
    }
    public List<Apttus_Billing__CreditMemoLineItem__c> getCreditMemoLineItems(){
        List<Apttus_Billing__CreditMemoLineItem__c> oCreditMemoLIList = [SELECT Id, Name, Apttus_Billing__Amount__c FROM Apttus_Billing__CreditMemoLineItem__c WHERE Apttus_Billing__CreditMemoId__c =: creditMemoId];
        return oCreditMemoLIList;
    }

}