src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>APTS_Number_of_Weeks__c</fullName>
        <formula>Apttus_CMConfig__AttributeValueId__r.APTS_Number_of_weeks__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trial Period – Number of Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Type_of_Contract__c</fullName>
        <label>Type of contract</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__ClassificationHierarchy__c</fullName>
        <description>The category hierarchy</description>
        <label>Category Hierarchy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__DerivedFromId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the line item this was derived from</description>
        <label>Derived From</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Derived Agreement Line Items</relationshipLabel>
        <relationshipName>DerivedAgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <inlineHelpText>Indicates whether the product has options.</inlineHelpText>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_NetSalesValue__c</fullName>
        <formula>APTS_GrossSalesValue__c - APTS_Trade_Spend__c</formula>
        <label>Net Sales Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Billing_Arrears__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non – Standard Deal (Billing Arrears)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Fixed_End_Date__c</fullName>
        <formula>IF( ISPICKVAL(  Apttus__Subtype__c , &apos;Fixed end date&apos;) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non – Standard Deal (Fixed End Date)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Fixed_Term__c</fullName>
        <formula>IF(  ISBLANK( TEXT(APTS_Fixed_Term_Type__c) )  , false , true)</formula>
        <label>Non – Standard Deal (Fixed Term)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Indexation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non – Standard Deal (Indexation)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Payment_Method__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non – Standard Deal (Payment Method)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Payment_Terms__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Non – Standard Deal (Payment Terms)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Non_Standard_Deal_Trial__c</fullName>
        <formula>IF(APTS_Count_of_Contract_Trial__c &gt; 0, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non – Standard Deal (Trial)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Number_of_Drinks_per_year__c</fullName>
        <label>Number of Drinks per year</label>
        <summarizedField>APTS_AgreementTotalVolumeObligation__c.APTS_NumberofDrinks__c</summarizedField>
        <summaryForeignKey>APTS_AgreementTotalVolumeObligation__c.APTS_Agreement__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Term_Value_1__c</fullName>
        <label>Payment Term Value 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Payment_Term_Value_2__c</fullName>
        <label>Payment Term Value 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Preferred_way_of_ingredient_orderi__c</fullName>
        <label>Preferred way of ingredient ordering</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routesales</fullName>
                </value>
                <value>
                    <fullName>Operator</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Sales Support</fullName>
                </value>
                <value>
                    <fullName>Indirect channel</fullName>
                </value>
                <value>
                    <fullName>Partner Portal</fullName>
                </value>
                <value>
                    <fullName>Platform Integration</fullName>
                </value>
                <value>
                    <fullName>3rd party sales</fullName>
                </value>
                <value>
                    <fullName>Cash &amp; Carry</fullName>
                    <isActive>false</isActive>
                    <label>Cash &amp; Carry</label>
                </value>
                <value>
                    <fullName>Caterer</fullName>
                    <isActive>false</isActive>
                    <label>Caterer</label>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                    <isActive>false</isActive>
                    <label>Distributor</label>
                </value>
                <value>
                    <fullName>LSP</fullName>
                    <isActive>false</isActive>
                    <label>LSP</label>
                </value>
                <value>
                    <fullName>Mail</fullName>
                    <isActive>false</isActive>
                    <label>Mail</label>
                </value>
                <value>
                    <fullName>Office</fullName>
                    <isActive>false</isActive>
                    <label>Office</label>
                </value>
                <value>
                    <fullName>Self pick up</fullName>
                    <isActive>false</isActive>
                    <label>Self pick up</label>
                </value>
                <value>
                    <fullName>Special Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Special Delivery</label>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                    <isActive>false</isActive>
                    <label>Supplier</label>
                </value>
                <value>
                    <fullName>Wholesaler</fullName>
                    <isActive>false</isActive>
                    <label>Wholesaler</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_ROS__c</fullName>
        <label>ROS%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_Type_of_Contract__c</fullName>
        <formula>TEXT(Apttus_Config2__AttributeValueId__r.APTS_Type_of_contract__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__ProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <formula>LEFT(Apttus_Config2__ClassificationHierarchy__c, FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c )-1) +
if(FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c ) &lt; 1, &quot;&quot;, &quot;| &quot;)+
if(FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c ) &lt; 1, &quot;&quot;,
MID(Apttus_Config2__ClassificationHierarchy__c, FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c )+2, 
FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c ,FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c )+2)-2-FIND(&quot;|&quot; , Apttus_Config2__ClassificationHierarchy__c )+2)) +

 Apttus_Config2__ClassificationId__r.Apttus_Config2__Label__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Group</label>
        <type>Text</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_AgreementApprovalEmailCtrl.cls
/**********************************************************************************
 * @Author: Juhi Rawal
 * @Company: Apttus
 * @Description: Controller for APTS_AgreementApprovalEmail Component
 * @Created Date: June 7, 2018
 * @History:
 *      <Name>              <Date>          <Description>
 *      juhi.rawal      6.07.2018           Created
 *      jason.e.mactal  8.01.2018           Added methods to handle fetching of Billing Setting and Incentive Records
 *      jason.e.mactal  11.20.2018          Added listMainBundleLines, and with sharing access modifer
 **********************************************************************************/
public with sharing class APTS_AgreementApprovalEmailCtrl{
    public Id agreementId;   
    public String approvalType{get; set;} 
    public List<Apttus__AgreementLineItem__c> listAgreementLineItems{get;set;}
    public List<Apttus__AgreementLineItem__c> listTrialALI{get;set;}
    public List<Apttus__AgreementLineItem__c> listMainBundleLines{get;set;}

    public Id getagreementId(){ return agreementId;}
    
    /*@methodName - setagreementId
    * @description - set agreementId
    * @author - Juhi Rawal
    * @param - Id
    * @return - void
    */  
    public void setagreementId(Id idAgr){
        agreementId = idAgr;
        agreementLineItems();
    }
    
    /*@methodName - agreementLineItems
    * @description - get Agreement Line Items
    * @author - Juhi Rawal
    * @param - void
    * @return - void
    */ 
    public void agreementLineItems(){
        try{
            listTrialALI = new List<Apttus__AgreementLineItem__c>();
            listMainBundleLines = new List<Apttus__AgreementLineItem__c>();
            listAgreementLineItems = [select id,name,Apttus__ProductId__r.Name,Apttus__Quantity__c,APTS_Type_of_Contract__c,Apttus_CMConfig__ClassificationHierarchy__c,
                                        Apttus__AgreementId__r.Apttus__Account__r.Name,Apttus__ProductId__r.Family,Apttus_CMConfig__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Number_of_weeks__c,
                                        Apttus_CMConfig__IsPrimaryLine__c, Apttus_CMConfig__HasOptions__c, Apttus_CMConfig__DerivedFromId__r.Category_Group__c
                                        from Apttus__AgreementLineItem__c
                                        where Apttus__AgreementId__c=: AgreementId];
            System.debug(' listAgreementLineItems;====> ' + listAgreementLineItems);
            for(Apttus__AgreementLineItem__c oALI : listAgreementLineItems){
                if(oALI.APTS_Type_of_Contract__c == 'Trial' && oALI.Apttus_CMConfig__IsPrimaryLine__c == TRUE && oALI.Apttus_CMConfig__HasOptions__c == TRUE){
                    listTrialALI.add(oALI);
                }
                if(oALI.Apttus_CMConfig__IsPrimaryLine__c == TRUE && oALI.Apttus_CMConfig__HasOptions__c == TRUE){
                    listMainBundleLines.add(oALI);
                }
            }
        } catch(Exception e){APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() ,'APTS_AgreementApprovalEmailCtrl','','CPQ',false,true,'cpqerror@accenture.com',true);             } 
    } 
    
    /*@methodName - getagreementDetails
    * @description - get Agreement fields
    * @author - Juhi Rawal
    * @param - void
    * @return - Apttus__APTS_Agreement__c
    */ 
    public Apttus__APTS_Agreement__c  getagreementDetails(){
        Apttus__APTS_Agreement__c oAgr = [select Apttus__Account__r.Name, APTS_NetSalesValue__c,APTS_ROS__c, Apttus__Account__r.Creditworthiness_Flag__c,Apttus__Contract_Start_Date__c,
                                            Apttus__Contract_End_Date__c,APTS_Preferred_way_of_ingredient_orderi__c, APTS_Non_Standard_Deal_Payment_Terms__c, APTS_Non_Standard_Deal_Fixed_Term__c,
                                            APTS_Non_Standard_Deal_Fixed_End_Date__c, APTS_Non_Standard_Deal_Indexation__c, APTS_Non_Standard_Deal_Payment_Method__c, APTS_Non_Standard_Deal_Billing_Arrears__c,
                                            APTS_Non_Standard_Deal_Trial__c, APTS_Payment_Term_Value_1__c, APTS_Payment_Term_Value_2__c, APTS_Number_of_Drinks_per_year__c, APTS_NSV__c, CurrencyIsoCode
                                            from Apttus__APTS_Agreement__c 
                                            where Id =: agreementId];
        return oAgr;
    }
    
    /*@methodName - getbShowIngredient
    * @description - checks whether ingredients should be showed
    * @author - Juhi Rawal
    * @param - void
    * @return - Boolean
    */ 
    public Boolean getbShowIngredient(){
        Boolean bShowIngredient = false;
        for(Apttus__AgreementLineItem__c oALI : listAgreementLineItems){
            if(oALI.Apttus__ProductId__r.Family == 'SAP_01' || oALI.Apttus__ProductId__r.Family == 'SAP_02' || oALI.Apttus__ProductId__r.Family == 'SAP_03'){
                bShowIngredient = true;
                break;
            }
        }
        return bShowIngredient;
    }
    
    /*@methodName - getIngredientCategory
    * @description - get Ingredient's Category|Sub-Category|SubSubCategory
    * @author - Jason Mactal
    * @param - void
    * @return - Boolean
    */ 
    public string getIngredientCategory(){
        string ingCategory = '';
        try{
            for(Apttus__AgreementLineItem__c oALI : listAgreementLineItems){
                if((oALI.Apttus__ProductId__r.Family == 'SAP_01' || oALI.Apttus__ProductId__r.Family == 'SAP_02' || oALI.Apttus__ProductId__r.Family == 'SAP_03') && !ingCategory.contains(oALi.Apttus_CMConfig__DerivedFromId__r.Category_Group__c)){
                    boolean isNotBlank = ingCategory.length()!=0? true: false;
                    ingCategory += isNotBlank? ', ': '';
                    ingCategory += oALi.Apttus_CMConfig__DerivedFromId__r.Category_Group__c;
                }
            }
        } catch(Exception e){APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() ,'APTS_AgreementApprovalEmailCtrl','','CPQ',false,true,'cpqerror@accenture.com',true); return null; } 
        return ingCategory;
    }
    
    /*@methodName - getKPIRecord
    * @description - get KPI/SLA Records
    * @author - Juhi Rawal
    * @param - void
    * @return - List<Contracted_kpi_sla__c>
    */ 
    public List<Contracted_kpi_sla__c> getKPIRecord(){
        List<Contracted_kpi_sla__c> listKpiRecords = [select kpi_type_value__c from Contracted_kpi_sla__c where kpi_contract__c =: agreementId];
        return listKpiRecords;
    }

    /*@methodName - getBillingSettingsRecords
    * @description - getBillingSettingsRecords
    * @author - Jason Mactal
    * @param - void
    * @return - string
    */ 
    public string getPaymentMethods(){
        string paymentMethodName = '';
        try{
            Set<String> setSAPIds = new Set<String> {'SAP_02024','SAP_0202D','SAP_0202I','SAP_0067D','SAP_01546','SAP_0154J','SAP_0154Q','SAP_6706Q','SAP_6750D','SAP_00794','SAP_0079D','SAP_0079E','SAP_0079H','SAP_0079I','SAP_0160D'};
            List<APTS_Billing_Settings__c> billingSettingsList = [select APTS_Payment_Term_Setting__r.Apttus_Config2__Value__c, APTS_Payment_Method__r.APTS_Ext_ID__c, APTS_Payment_Method__r.Name from APTS_Billing_Settings__c where APTS_Agreement_ID__c =: agreementId];
            
            for(APTS_Billing_Settings__c billSet: billingSettingsList){
                //get Payment Methods that Triggered Approval
                if(setSAPIds.contains(billSet.APTS_Payment_Method__r.APTS_Ext_ID__c) && !paymentMethodName.contains(billSet.APTS_Payment_Method__r.Name)){
                    boolean isNotBlank = paymentMethodName.length()!=0? true: false;
                    paymentMethodName += isNotBlank? ', ': '';
                    paymentMethodName += billSet.APTS_Payment_Method__r.Name;
                }
            }
        } catch(Exception e){APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() ,'APTS_AgreementApprovalEmailCtrl','','CPQ',false,true,'cpqerror@accenture.com',true); return null; } 
        return paymentMethodName;
    }
    
    /*@methodName - getWithIncentives
    * @description - check if Agreement has Incentives
    * @author - Jason Mactal
    * @param - void
    * @return - boolean
    */ 
    public boolean getWithIncentives(){
        boolean withIncentives = FALSE;
        try{
            List<Apttus_Config2__Incentive__c> incentivesList = [select id from Apttus_Config2__Incentive__c where Apttus_CMConfig__AgreementId__c =: agreementId];
            
            if(incentivesList!=null && incentivesList.size()!=0){
                withIncentives = TRUE;
            }
        } catch(Exception e){APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() ,'APTS_AgreementApprovalEmailCtrl','','CPQ',false,true,'cpqerror@accenture.com',true); return null;} 
        return withIncentives;
    }
}