src/objects/Apttus__AgreementLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an agreement</description>
    <fields>
        <fullName>Apttus_CMConfig__AssetLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated asset line item from which the line item is created.</description>
        <inlineHelpText>ID of the associated asset line item from which the line item is created.</inlineHelpText>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__DerivedFromId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the line item this was derived from</description>
        <label>Derived From</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Derived Agreement Line Items</relationshipLabel>
        <relationshipName>DerivedAgreementLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__EndDate__c</fullName>
        <description>The end date for products and services</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__LineStatus__c</fullName>
        <description>The line status</description>
        <label>Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__StartDate__c</fullName>
        <description>The start date for products and services</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__AgreementId__c</fullName>
        <description>ID of the associated agreement</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Line Items</relationshipLabel>
        <relationshipName>AgreementLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Line Item</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Sub_Status_Update_Date__c</fullName>
        <label>Sub Status Update Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary Deactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetStatus__c</fullName>
        <description>The asset status</description>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Pending Re-activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Suspension</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Changed Configuration</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BundleAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated bundle line item.</description>
        <inlineHelpText>ID of the associated bundle line item.</inlineHelpText>
        <label>Bundle Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Option Asset Line Items</relationshipLabel>
        <relationshipName>OptionAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EndDate__c</fullName>
        <description>The end date for products and services</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ParentAssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the direct parent asset.</description>
        <inlineHelpText>The ID of the direct parent asset.</inlineHelpText>
        <label>Parent Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Child Asset Line Items</relationshipLabel>
        <relationshipName>ChildAssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__StartDate__c</fullName>
        <description>The start date for products and services</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__EndDate__c</fullName>
        <description>The end date for products and services</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__StartDate__c</fullName>
        <description>The start date for products and services</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Sub_Type__c</fullName>
        <description>This is the Order Sub Type</description>
        <label>Order Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Order_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Standard Return</fullName>
                </value>
                <value>
                    <fullName>Unplanned Return</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>De-installation</fullName>
                </value>
                <value>
                    <fullName>Internal Movement</fullName>
                </value>
                <value>
                    <fullName>External Movement With Contract Change</fullName>
                </value>
                <value>
                    <fullName>External Movement Without Contract Change</fullName>
                </value>
                <value>
                    <fullName>Technical Swap</fullName>
                </value>
                <value>
                    <fullName>Commercial Swap</fullName>
                </value>
                <value>
                    <fullName>Route Sales and Operating</fullName>
                </value>
                <value>
                    <fullName>Subscription Order</fullName>
                </value>
                <value>
                    <fullName>Billing Schedule</fullName>
                </value>
                <value>
                    <fullName>Digital Order</fullName>
                </value>
                <value>
                    <fullName>Conversion Order</fullName>
                </value>
                <value>
                    <fullName>Stock Count</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Agreement Changes</fullName>
                </value>
                <value>
                    <fullName>Indexation</fullName>
                </value>
                <value>
                    <fullName>Consignment Issue for FSD</fullName>
                </value>
                <value>
                    <fullName>Consignment Fillup for FSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__SoldToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>OrdersSoldTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>AssetStatus__c</fullName>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                    <default>true</default>
                    <label>Pending Activation</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <label>Option</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_DeInstallAdminOrderController.cls
/*************************************************************
@Name: APTS_DeInstallAdminOrderController
@Author: V. Shankaranarayanan
@CreateDate: 01-06-2018
@Description: Controller for APTS_DeInstallAdminOrder VF page
@UsedBy: APTS_DeInstallAdminOrder VF page
******************************************************************/
public with sharing class APTS_DeInstallAdminOrderController{

    private final Apttus_Config2__AssetLineItem__c oAssetLineItem;
    private Id orderId;
    private String orderSubType;
    private static final String ADMIN = System.Label.APTS_AdminOrder;
    private static final String ID = System.Label.APTS_Id;
    private static final String CONVERSION = System.Label.APTS_ConversionOrder;
    private static final String ACTIVATED = System.Label.APTS_Activated;
    private static final String INSTALLATION = System.Label.APTS_Installation;
    private static final String DEINSTALLATION = System.Label.APTS_De_installation;
    private static final String RENEWAL = System.Label.APTS_Renewal;
    private static final String TEMPDEACTIVATED = System.Label.APTS_TemporaryDeactivated;
    private static final String CANCELLED = System.Label.APTS_Cancelled;
    private static final String OPTION = System.Label.APTS_Option;
    private static List<Apttus_Config2__Order__c> orderList = new List<Apttus_Config2__Order__c>();
    private static Set<Id> installphysicalasset = new set<Id>();
    private static Set<Id> deinstallphysicalasset = new set<Id>();
    private static final String ASSETLINEITEM = 'Apttus_Config2__AssetLineItem__c';
    private static final String PHYASSET = 'PhysicalAsset__c ';


    
    public Apttus_Config2__Order__c oOrder {get; set;}
    public List<AssetLineItemWrapper> assetLineItemWrapperList {get; set;}
    Map<Id, Id> aLIIdToDerivedFromIdMap = new Map<Id, Id>();
    Map<Id, Apttus__AgreementLineItem__c> aLIIdToAggLIMap = new Map<Id, Apttus__AgreementLineItem__c>();
    public Boolean bShowInstalledAssets {get; set;}
    public Boolean bShowDeinstalledAssets {get; set;}
    public Boolean bShowRenewedAssets {get; set;}
    
    public APTS_DeInstallAdminOrderController(){
        orderId = ApexPages.currentPage().getParameters().get(ID);
        bShowInstalledAssets = false;
        bShowDeinstalledAssets = false;
        bShowRenewedAssets = false;
    }
    
    
    public PageReference getAssets(){
        try{
            orderList = [SELECT Id, APTS_Order_Sub_Type__c, Apttus_Config2__SoldToAccountId__c, Apttus_CMConfig__AgreementId__c FROM Apttus_Config2__Order__c WHERE Id =: orderId LIMIT 1];
            if(orderList.size() > 0){
                oOrder = orderList[0];
                orderSubType = oOrder.APTS_Order_Sub_Type__c;
                String accountId = oOrder.Apttus_Config2__SoldToAccountId__c;
                String lineType = 'Product/Service';
                String renewed = 'Renewed';
                String agreementId = oOrder.Apttus_CMConfig__AgreementId__c;
                assetLineItemWrapperList = new List<AssetLineItemWrapper>();
                String query;
                Set<Id> aLIIdSet = new Set<Id>();
                
                if(oOrder != null){
                    if(RENEWAL.equalsIgnoreCase(orderSubType)){
                        for(Apttus__AgreementLineItem__c aggLI : [SELECT Id, Apttus__AgreementId__c, Apttus_CMConfig__DerivedFromId__c, Apttus_CMConfig__LineStatus__c, Apttus_CMConfig__AssetLineItemId__c, Apttus_CMConfig__StartDate__c, Apttus_CMConfig__EndDate__c FROM Apttus__AgreementLineItem__c WHERE Apttus__AgreementId__c =: agreementId AND Apttus_CMConfig__LineStatus__c =: renewed AND Apttus_CMConfig__AssetLineItemId__c != null LIMIT 50000]){
                            aLIIdToDerivedFromIdMap.put(aggLI.Apttus_CMConfig__AssetLineItemId__c, aggLi.Apttus_CMConfig__DerivedFromId__c);
                            aLIIdSet.add(aggLI.Apttus_CMConfig__AssetLineItemId__c);
                            aLIIdToAggLIMap.put(aggLI.Apttus_CMConfig__AssetLineItemId__c, aggLI);
                        }               
                        
                        query = 'SELECT Id, Name, Apttus_Config2__AssetStatus__c, Apttus_Config2__ProductId__c, Apttus_Config2__ParentAssetId__c, Apttus_Config2__BundleAssetId__c, Apttus_Config2__AccountId__r.Name, Apttus_Config2__StartDate__c, Apttus_Config2__EndDate__c, APTS_Sub_Status__c, APTS_Sub_Status_Update_Date__c, APTS_Physical_Asset__c FROM Apttus_Config2__AssetLineItem__c WHERE Id IN: aLIIdSet AND Apttus_Config2__IsPrimaryLine__c=true AND Apttus_Config2__LineType__c=: lineType LIMIT 50000'; 
                        bShowRenewedAssets = true;
                        
                    }else if(INSTALLATION.equalsIgnoreCase(orderSubType) || DEINSTALLATION.equalsIgnoreCase(orderSubType)){
                        query = 'SELECT Id, Name, Apttus_Config2__AssetStatus__c, Apttus_Config2__ProductId__c, Apttus_Config2__ParentAssetId__c, Apttus_Config2__BundleAssetId__c, Apttus_Config2__AccountId__r.Name, Apttus_Config2__StartDate__c, Apttus_Config2__EndDate__c, APTS_Sub_Status__c, APTS_Sub_Status_Update_Date__c, APTS_Physical_Asset__c FROM Apttus_Config2__AssetLineItem__c WHERE Apttus_Config2__AccountId__c =: accountId AND Apttus_Config2__LineType__c =: lineType AND APTS_Sub_Status__c = null AND Apttus_Config2__BundleAssetId__c = null AND Apttus_Config2__ParentAssetId__c = null LIMIT 50000';
                        if(INSTALLATION.equalsIgnoreCase(orderSubType)){
                            //query = query.replace('=: ACTIVATED', '!=: ACTIVATED');
                            query = query.replace('APTS_Sub_Status__c = null','APTS_Sub_Status__c =:TEMPDEACTIVATED');
                        }
                        bShowInstalledAssets = (INSTALLATION.equalsIgnoreCase(orderSubType) ? true : false);
                        bShowDeinstalledAssets = (DEINSTALLATION.equalsIgnoreCase(orderSubType) ? true : false);
        
                    }
                    for(Apttus_Config2__AssetLineItem__c assetLineItem : Database.query(query)){
                        AssetLineItemWrapper oAssetLineItemWrapper = new AssetLineItemWrapper(false, assetLineItem);
                        assetLineItemWrapperList.add(oAssetLineItemWrapper);
                    }
                }
            }
        }catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Exception occurred : '+ex.getMessage()));
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'Apex', ex.getStackTraceString(), '', '', 'CLM', false, false, null, true);
        }
        return null;
    }
    
    public PageReference deinstallAssets(){
        try{
            if(Apttus_Config2__AssetLineItem__c.sObjectType.getDescribe().isUpdateable()){//Performance issue fixes by Ajith
            List<Apttus_CPQApi.CPQ.AddBundleRequestDO> addBundleRequestDO = new List<Apttus_CPQApi.CPQ.AddBundleRequestDO>();
            List<Apttus_Config2__AssetLineItem__c> aLIList = new List<Apttus_Config2__AssetLineItem__c>();
            PageReference pageRef;
            List<Id> assetIdList = new List<Id>();
            Set<Id> idSet = new Set<Id>();
            Id cartId = APTS_OrderUtils.createCart(orderId);
            
            for(AssetLineItemWrapper aLIWrapper : assetLineItemWrapperList){
                if(aLIWrapper.selected){
                    assetIdList.add(aLIWrapper.oAssetLineItem.Id);
                    aLIList.add(aLIWrapper.oAssetLineItem);
                }
            }
            
            for(Id id : aLIIdToDerivedFromIdMap.values()){
                idSet.add(id);
            }
            
            if(RENEWAL.equalsIgnoreCase(orderSubType)){
                for(Apttus_Config2__AssetLineItem__c asset : aLIList){
                    Apttus_CPQApi.CPQ.AddBundleRequestDO request = new Apttus_CPQApi.CPQ.AddBundleRequestDO();
                    request.CartId = cartId;
                    request.SelectedBundle = new Apttus_CPQApi.CPQ.SelectedBundleDO();
                    request.SelectedBundle.SelectedProduct = new Apttus_CPQApi.CPQ.SelectedProductDO();
                    request.SelectedBundle.SelectedProduct.ProductId = asset.Apttus_Config2__ProductId__c;
                    request.SelectedBundle.SelectedProduct.StartDate = aLIIdToAggLIMap.get(asset.Id).Apttus_CMConfig__StartDate__c;
                    request.SelectedBundle.SelectedProduct.EndDate = aLIIdToAggLIMap.get(asset.Id).Apttus_CMConfig__EndDate__c;
                    request.SelectedBundle.SelectedProduct.Quantity = 1;
                    
                    Map<Id, Apttus_Config2__LineItem__c> oliMap = APTS_OrderUtils.getLineItemDataAll(idSet);
                    Apttus_Config2__LineItem__c oLineItem = oliMap.get(aLIIdToDerivedFromIdMap.get(asset.Id));
                    request.SelectedBundle.SelectedProduct.CustomData = oLineItem;
                    request.SelectedBundle.SelectedProduct.CustomFields = APTS_OrderUtils.setLineItemFieldList();
                    
                    Apttus_CPQApi.CPQ.AddBundleResponseDO response = Apttus_CPQApi.CPQWebService.addBundle(request);
                }
            }else if(INSTALLATION.equalsIgnoreCase(orderSubType)) {
                aLIList = getAssetstoupdate(aLIList);
                for(Apttus_Config2__AssetLineItem__c asset : aLIList){
                    asset.APTS_Sub_Status__c = null;
                    asset.APTS_Sub_Status_Update_Date__c = null;
                    if(asset.APTS_Physical_Asset__c != null) {
                        installphysicalasset.add(asset.APTS_Physical_Asset__c);
                    }
                }
                DescribeSObjectResult objResultALI = APTS_OTCUtil.getsObjectAccess(ASSETLINEITEM);
                if(objResultALI != null &&  objResultALI.isUpdateable() )
                {
                    update aLIList;
                }
                if(!installphysicalasset.isEmpty()) {
                    updatephysicalassets(installphysicalasset, ACTIVATED);    
                }
                
            }
            else if(DEINSTALLATION.equalsIgnoreCase(orderSubType)){
                //Map<Id, Apttus_Config2__LineItem__c> cancelAssetsMap = APTS_OrderUtils.cancelAssets(cartId, assetIdList);
                aLIList = getAssetstoupdate(aLIList);
                for(Apttus_Config2__AssetLineItem__c asset : aLIList){
                    asset.APTS_Sub_Status__c = TEMPDEACTIVATED;
                    asset.APTS_Sub_Status_Update_Date__c = system.today();
                    if(asset.APTS_Physical_Asset__c != null) {
                        deinstallphysicalasset.add(asset.APTS_Physical_Asset__c);
                    }
                }
                DescribeSObjectResult objResultALI = APTS_OTCUtil.getsObjectAccess(ASSETLINEITEM);
                if(objResultALI != null &&  objResultALI.isUpdateable() )
                {
                    update aLIList;
                }
                if(!deinstallphysicalasset.isEmpty()) {
                    updatephysicalassets(deinstallphysicalasset, CANCELLED);
                }
            }}
            //APTS_OrderUtils.repriceCart(cartId);
            //APTS_OrderUtils.finalizeCart(cartId);
            //APTS_OrderUtils.syncCart(cartId);

            return new PageReference('/' + orderId);
        }catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Exception occurred : '+ex.getMessage()));
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'Apex', ex.getStackTraceString(), 'Admin Order', orderId , 'CLM', false, false, null, true);
            return null;
        }
    }
    

    public PageReference back(){
        return new PageReference('/' + orderId);
    }

    public void updatephysicalassets(Set<Id> physicalasset, string status) {
        List<PhysicalAsset__c> phassetlist = new List<PhysicalAsset__c>();
        try{
            if(PhysicalAsset__c.sObjectType.getDescribe().isUpdateable()){//Performance issue fixes by Ajith
                for(Id phassetid: physicalasset) {
                    PhysicalAsset__c oPhAsset = new PhysicalAsset__c(id=phassetid, AssetStatus__c = status);
                    phassetlist.add(oPhAsset);
                }
                DescribeSObjectResult objResultPA = APTS_OTCUtil.getsObjectAccess(PHYASSET);
                if(objResultPA != null && objResultPA.isUpdateable() )
                {
                    update phassetlist;
                }
            }
        }catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Exception occurred : '+ex.getMessage()));
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'Apex', ex.getStackTraceString(), 'Physical Asset', phassetlist[0].Id, 'CLM', false, false, null, true);
        }
    }

    public List<Apttus_Config2__AssetLineItem__c> getAssetstoupdate(List<Apttus_Config2__AssetLineItem__c> assetList) {
        Set<Id> assetidset = new Set<Id>();
        for(Apttus_Config2__AssetLineItem__c oASL : assetList) {
            assetidset.add(oASL.Id);
        }
        for(Apttus_Config2__AssetLineItem__c oASLI : [select id,name,APTS_Sub_Status__c,APTS_Sub_Status_Update_Date__c,APTS_Physical_Asset__c from Apttus_Config2__AssetLineItem__c where Apttus_Config2__LineType__c =: OPTION and Apttus_Config2__BundleAssetId__c IN: assetidset]) {
            assetList.add(oASLI);
        }
        return assetList;
    }
   
    public with sharing class AssetLineItemWrapper{
        public Boolean selected {get; set;}
        public Apttus_Config2__AssetLineItem__c oAssetLineItem {get; set;}

        public AssetLineItemWrapper(Boolean selected, Apttus_Config2__AssetLineItem__c oAssetLineItem) {
            this.selected = selected;
            this.oAssetLineItem = oAssetLineItem;
        }
    }

}