src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Exclude_TAX__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked will exclude tax calculation on cart.</description>
        <label>Exclude TAX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Exclude_VAT__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked will exclude VAT calculation on cart</description>
        <inlineHelpText>if checked will exclude VAT calculation on cart</inlineHelpText>
        <label>Exclude VAT</label>
        <type>Checkbox</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__FrequencyConversionRate__c.object
<CustomObject>
    <description>Represents the conversion rates used to convert pricing from one frequency or unit of measure to another frequency or unit of measure</description>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product</description>
        <inlineHelpText>ID of the associated product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Frequency/UOM Conversion Rates</relationshipLabel>
        <relationshipName>FrequencyUOMConversionRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Frequency/UOM Conversion Rate</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Conversion Rate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency/UOM Conversion Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>APTS_is_Tax_and_VAT_calculated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checked if tax is calculated for this line item</description>
        <inlineHelpText>checked if tax is calculated for this line item</inlineHelpText>
        <label>is Tax and VAT calculated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AdjustmentAmount__c</fullName>
        <description>The manual price adjustment amount.</description>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AdjustmentType__c</fullName>
        <description>The manual price adjustment type</description>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>% Discount</fullName>
                </value>
                <value>
                    <fullName>% Discount Off List</fullName>
                </value>
                <value>
                    <fullName>Discount Amount</fullName>
                </value>
                <value>
                    <fullName>% Uplift</fullName>
                </value>
                <value>
                    <fullName>% Markup</fullName>
                </value>
                <value>
                    <fullName>Markup Amount</fullName>
                </value>
                <value>
                    <fullName>Price Override</fullName>
                </value>
                <value>
                    <fullName>Base Price Override</fullName>
                </value>
                <value>
                    <fullName>Price Factor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__ProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OptionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected option</description>
        <label>Option</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Option Line Items</relationshipLabel>
        <relationshipName>OptionLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list item</description>
        <label>Price List Item</label>
        <referenceTo>Apttus_Config2__PriceListItem__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceUom__c</fullName>
        <description>The pricing unit of measure for the product</description>
        <label>Pricing Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__SellingUom__c</fullName>
        <description>The selling unit of measure for the product</description>
        <inlineHelpText>The selling unit of measure for the product</inlineHelpText>
        <label>Selling Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <fields>
        <fullName>APTS_TXP_Disposal_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TXP Disposal Fee</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceUom__c</fullName>
        <description>The pricing unit of measure for the product</description>
        <label>Price Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the product associated with the price list</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class</description>
    <fields>
        <fullName>APTS_Refurbished__c</fullName>
        <description>Created as part of Kauri Wave 3 Nov&apos;18 Release.</description>
        <label>Refurbished?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Attribute Value</label>
    <nameField>
        <displayFormat>AV-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the agreement associated with the configuration</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_CalculateTaxesCtrl.cls
/*
 * This class is used to calculate VAT and Additional tax on cart.
 * Created By - Karan Khatri
 * Created Date - 21st March, 2018
 * 
 * v100 - Aftab - Adding action method
*/

public without sharing class APTS_CalculateTaxesCtrl{
    private String flow;
    private String configRequestId;
    private String configId;
    private boolean excludeTAX;
    private boolean excludeVAT;
    public APTS_CalculateTaxesCtrl(Id configId){
        this.configId = configId;
        flow = null;
        configRequestId = null;
        excludeTAX=false;
        excludeVAT=false;
        Apttus_Config2__ProductConfiguration__c productConfig = new Apttus_Config2__ProductConfiguration__c();
        if(configId!=null)
        {
        productConfig = [select Apttus_CMConfig__AgreementId__r.APTS_Exclude_TAX__c,Apttus_CMConfig__AgreementId__r.APTS_Exclude_VAT__c,Apttus_CMConfig__AgreementId__c from Apttus_Config2__ProductConfiguration__c where id =: configId];
        if(productConfig.Apttus_CMConfig__AgreementId__c!=null){
            excludeTAX = productConfig.Apttus_CMConfig__AgreementId__r.APTS_Exclude_TAX__c;
            excludeVAT = productConfig.Apttus_CMConfig__AgreementId__r.APTS_Exclude_VAT__c;
        }
        }
    }
    public APTS_CalculateTaxesCtrl(ApexPages.StandardController stdController){
        this(ApexPages.currentPage().getParameters().get(APTS_CPQConstants.TAX_ID));
        flow = ApexPages.currentPage().getParameters().get(APTS_CPQConstants.FLOW);
        configRequestId = ApexPages.currentPage().getParameters().get(APTS_CPQConstants.CONFIG_REQUEST_ID);
    }
    
    public void calculateVATandAddTaxAction(){
        calculateVATandAddTax();
    }
    
    public PageReference calculateVATandAddTax(){
        List<Apttus_Config2__LineItem__c> lineItemsToUpdate = new List<Apttus_Config2__LineItem__c>();
        Map<ID,Apttus_Config2__FrequencyConversionRate__c> uomConversionMap= new Map<ID,Apttus_Config2__FrequencyConversionRate__c>();
        Set<String> toUOMSet = new Set<String>();
        Set<String> prodCodeSet = new Set<String>();
        Set<String> uomAPIParamSet = new Set<String>();
        try{
            //get exclude tax and exclude vat field from agreement in order to bypass logic
            if(configId!=null){
                //creating set for Pricing UOM and selling UOM
                for(Apttus_Config2__LineItem__c lineitem : [select id, Apttus_Config2__PriceUom__c,Apttus_Config2__OptionId__c,Apttus_Config2__OptionId__r.productcode,Apttus_Config2__SellingUom__c,Apttus_Config2__ProductId__r.productcode from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c=:configId]){
                    if(lineitem.Apttus_Config2__PriceUom__c!=null && lineitem.Apttus_Config2__SellingUom__c!=null){
                        if(lineitem.Apttus_Config2__OptionId__c!=null){

                            uomAPIParamSet.add(lineitem.Apttus_Config2__OptionId__r.productcode+';'+lineitem.Apttus_Config2__PriceUom__c+';'+lineitem.Apttus_Config2__SellingUom__c);

                            uomAPIParamSet.add(lineitem.Apttus_Config2__OptionId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__PriceUom__c);
                        }else{

                            uomAPIParamSet.add(lineitem.Apttus_Config2__ProductId__r.productcode+';'+lineitem.Apttus_Config2__PriceUom__c+';'+lineitem.Apttus_Config2__SellingUom__c);
                            
                            uomAPIParamSet.add(lineitem.Apttus_Config2__ProductId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__PriceUom__c);
                        }
                    }
                }
                //Created map for UOM table | gets all UOM table records matching with line item pricing UOM and selling UOM
                Map<String,Decimal> uomAPIResponseMap = APTS_UOMConversionUtils.getUOMConversions(uomAPIParamSet);
                //Iterate over line items and calculate additional taxes,weight and VAT
                for(Apttus_Config2__LineItem__c lineitem : [select id,Apttus_Config2__PriceListItemId__r.APTS_TXP_Disposal_Fee__c,Apttus_Config2__AttributeValueId__r.APTS_Refurbished__c,Apttus_Config2__AdjustmentType__c,Apttus_Config2__AdjustmentAmount__c,APTS_is_Tax_and_VAT_calculated__c,Apttus_Config2__ConfigurationId__c,Apttus_Config2__OptionId__c,Apttus_Config2__OptionId__r.productcode, Apttus_Config2__ProductId__c,Apttus_Config2__ProductId__r.productcode, Apttus_Config2__PriceUom__c,Apttus_Config2__SellingUom__c,APTS_Net_Price_Inc_taxes__c,Apttus_Config2__Quantity__c,Apttus_Config2__PriceListItemId__c,Apttus_Config2__PriceListItemId__r.APTS_Tax_per_UOM__c,Apttus_Config2__PriceListItemId__r.APTS_VAT_indicator__c,Apttus_Config2__PriceListItemId__r.APTS_VAT_percentage__c,Apttus_Config2__PricingStatus__c,APTS_Tax__c,APTS_VAT__c,Apttus_Config2__NetPrice__c from Apttus_Config2__LineItem__c where Apttus_Config2__ConfigurationId__c=:configId limit 50000]){
                    //imitialize all computing values to 0 | helps to see updated data
                    Decimal sellingUomConversionRate=0;
                    Decimal pricingUomConversionRate=0;
                    lineitem.APTS_Tax__c=0;
                    lineitem.APTS_VAT__c=0;
                    lineitem.APTS_Net_Price_Inc_taxes__c = 0;
                    // Added checks for Tax CR | If 100% discount then tax should be zero
                    if(lineitem.Apttus_Config2__PriceListItemId__c!=null && lineitem.Apttus_Config2__Quantity__c!=null && lineitem.Apttus_Config2__Quantity__c!=0 && lineitem.Apttus_Config2__NetPrice__c!=0) {
                         if(!uomAPIResponseMap.isEmpty() && lineitem.Apttus_Config2__PriceUom__c!=null && lineitem.Apttus_Config2__SellingUom__c!=null){
                            //get UOM converted value for line item based on Pricing UOM and Selling UOM
                            if(lineitem.Apttus_Config2__OptionId__c!=null && uomAPIResponseMap.get(lineitem.Apttus_Config2__OptionId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__SellingUom__c)!=null){
                                sellingUomConversionRate = uomAPIResponseMap.get(lineitem.Apttus_Config2__OptionId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__SellingUom__c);
                                pricingUomConversionRate = uomAPIResponseMap.get(lineitem.Apttus_Config2__OptionId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__PriceUom__c);
                            }else if(uomAPIResponseMap.get(lineitem.Apttus_Config2__ProductId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__SellingUom__c)!=null)     {                   
                                sellingUomConversionRate = uomAPIResponseMap.get(lineitem.Apttus_Config2__ProductId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__SellingUom__c);
                                pricingUomConversionRate = uomAPIResponseMap.get(lineitem.Apttus_Config2__ProductId__r.productcode+';'+APTS_CPQConstants.PIECE_UOM_API+';'+lineitem.Apttus_Config2__PriceUom__c);
                            }
                        }
                        //calculate tax for line item 
                        if(sellingUomConversionRate!=null && pricingUomConversionRate!=null && sellingUomConversionRate!=0 && pricingUomConversionRate!=0 && !excludeTAX && lineitem.Apttus_Config2__PriceListItemId__r.APTS_Tax_per_UOM__c!=null){
                            // Added checks for Tax CR | If second hand machine is being bought , then tax should not be charged else normal flow
                            if(lineitem.Apttus_Config2__AttributeValueId__c!=null && lineitem.Apttus_Config2__AttributeValueId__r.APTS_Refurbished__c==APTS_CPQConstants.LABEL_YES && lineitem.Apttus_Config2__PriceListItemId__r.APTS_TXP_Disposal_Fee__c!=null && lineitem.Apttus_Config2__PriceListItemId__r.APTS_TXP_Disposal_Fee__c!=0){
                                lineitem.APTS_Tax__c = (lineitem.Apttus_Config2__Quantity__c * sellingUomConversionRate) * ((lineitem.Apttus_Config2__PriceListItemId__r.APTS_Tax_per_UOM__c - lineitem.Apttus_Config2__PriceListItemId__r.APTS_TXP_Disposal_Fee__c) / pricingUomConversionRate);
                            }else{
                                lineitem.APTS_Tax__c = (lineitem.Apttus_Config2__Quantity__c * sellingUomConversionRate) * (lineitem.Apttus_Config2__PriceListItemId__r.APTS_Tax_per_UOM__c / pricingUomConversionRate);
                            }       
                        }
                        //calculate Net Price Inclusive of taxes
                        if(lineitem.Apttus_Config2__NetPrice__c!=0){
                            if(lineitem.APTS_Tax__c!=0){
                                lineitem.APTS_Net_Price_Inc_taxes__c = lineitem.Apttus_Config2__NetPrice__c + lineitem.APTS_Tax__c;
                            }else{
                                 lineitem.APTS_Net_Price_Inc_taxes__c = lineitem.Apttus_Config2__NetPrice__c;
                            }
                        }
                        //calculate VAT for line item
                        if(lineitem.Apttus_Config2__PriceListItemId__r.APTS_VAT_percentage__c!=null &&  lineitem.Apttus_Config2__PriceListItemId__r.APTS_VAT_percentage__c!=0 && lineitem.Apttus_Config2__NetPrice__c!=null && lineitem.Apttus_Config2__NetPrice__c!=0 && !excludeVAT){
                           lineitem.APTS_VAT__c = lineitem.APTS_Net_Price_Inc_taxes__c * (lineitem.Apttus_Config2__PriceListItemId__r.APTS_VAT_percentage__c/100);
                        }
                    }
                     //update flag on line item to restrict user if he hasnt calculated tax and VAT
                    lineitem.APTS_is_Tax_and_VAT_calculated__c = true;

                    //lineitem.Apttus_Config2__PricingStatus__c= APTS_CPQConstants.LABEL_PRICING_COMPLETE;

                    //Add line items in List for updating
                    lineItemsToUpdate.add(lineitem);
                }
                //update line item list
                if(!lineItemsToUpdate.isEmpty()){
                    update lineItemsToUpdate;
                }
            }
            //Once everything is done redirect back to the cart.
            return GoBacktoCart();
        }catch(Exception e){
            APTS_CustomLogging.createErrorLog(e.getTypeName(), APTS_CPQConstants.APEX_NAME, e.getMessage()+'\n\n'+e.getStackTraceString() , APTS_CPQConstants.LINE_ITEM, ApexPages.currentPage().getParameters().get(APTS_CPQConstants.BSN_OBJ_ID),APTS_CPQConstants.CPQ,false,true,APTS_CPQConstants.KK_EAMIL,true);
            return null;
        }
    }
    //Method used to redirect back to the cart 
    public PageReference GoBacktoCart(){  
         PageReference pg;
         pg = Page.Apttus_Config2__Cart;
         pg.getParameters().put(APTS_CPQConstants.TAX_ID, configId);
         pg.getParameters().put(APTS_CPQConstants.FLOW,flow);       
         pg.getParameters().put(APTS_CPQConstants.CONFIG_REQUEST_ID, configRequestId);  
         pg.getParameters().put(APTS_CPQConstants.LAUNCH_STATE, APTS_CPQConstants.CART);     
         return pg; 
    }
    //gets converted rate for Pricing UOM and Selling UOM
    public static decimal getConversionRate(Map<ID,Apttus_Config2__FrequencyConversionRate__c> uomConversionMap,String fromUom,String toUom,String productCode){
        String prodID,prodFamily;
        Decimal conversionRate=0;
        if(toUom!=null && productCode!=null && fromUom!=null && !uomConversionMap.isEmpty()){
            //check if UOM conversion data exists for Product
            for(Apttus_Config2__FrequencyConversionRate__c uomConversion : uomConversionMap.values()){
                if(uomConversion.APTS_ProductCode__c == productCode && uomConversion.Apttus_Config2__FromUom__c == fromUom && uomConversion.Apttus_Config2__ToUom__c == toUom && uomConversion.Apttus_Config2__ConversionFactor__c!=null){
                    conversionRate = uomConversion.Apttus_Config2__ConversionFactor__c;
                    return conversionRate;
                }
            }
            /* COMMENTED because below scenerios wont exist --- only filtering with product code
             //check if UOM conversion data exists for Product Family
            if(conversionRate==0){
                for(Apttus_Config2__FrequencyConversionRate__c uomConversion : uomConversionMap.values()){
                    if(productFamily!=null && uomConversion.Apttus_Config2__ProductId__c==null && uomConversion.Apttus_Config2__ProductFamily__c == productFamily && uomConversion.Apttus_Config2__FromUom__c == fromUom && uomConversion.Apttus_Config2__ToUom__c == toUom && uomConversion.Apttus_Config2__ConversionFactor__c!=null){
                        conversionRate = uomConversion.Apttus_Config2__ConversionFactor__c;
                    }
                }
            }
            //If both of the above data doesnt exist choose generic data.
            if(conversionRate==0){
                for(Apttus_Config2__FrequencyConversionRate__c uomConversion : uomConversionMap.values()){
                    if(uomConversion.Apttus_Config2__FromUom__c == fromUom && uomConversion.Apttus_Config2__ToUom__c == toUom && uomConversion.Apttus_Config2__ConversionFactor__c!=null && uomConversion.Apttus_Config2__ProductFamily__c == null && uomConversion.Apttus_Config2__ProductId__c==null){
                        conversionRate = uomConversion.Apttus_Config2__ConversionFactor__c;
                    }
                }
            }*/
        }
        return 0;
    } 
}