src/objects/Apttus_Config2__AdjustmentLineItem__c.object
<CustomObject>
    <description>Represents an adjustment to the price of a product/service</description>
    <fields>
        <fullName>Apttus_Config2__CouponCode__c</fullName>
        <description>The incentive coupon code</description>
        <inlineHelpText>The incentive coupon code</inlineHelpText>
        <label>Coupon Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IncentiveCode__c</fullName>
        <description>The incentive code available to customers to identify the incentive</description>
        <inlineHelpText>The incentive code available to customers to identify the incentive</inlineHelpText>
        <label>Incentive Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IncentiveId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated incentive</description>
        <inlineHelpText>ID of the associated incentive</inlineHelpText>
        <label>Incentive</label>
        <referenceTo>Apttus_Config2__Incentive__c</referenceTo>
        <relationshipLabel>Adjustment Line Items</relationshipLabel>
        <relationshipName>AdjustmentLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineNumber__c</fullName>
        <description>The line number</description>
        <label>Line Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceRuleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the adjustment rule</description>
        <inlineHelpText>ID of the adjustment rule</inlineHelpText>
        <label>Price Rule</label>
        <referenceTo>Apttus_Config2__PriceRule__c</referenceTo>
        <relationshipLabel>Adjustment Line Items</relationshipLabel>
        <relationshipName>AdjustmentLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adjustment Line Item</label>
    <nameField>
        <displayFormat>AD-{0000000000}</displayFormat>
        <label>Adjustment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Incentive__c.object
<CustomObject>
    <description>Represents an incentive associated with one or more products</description>
    <fields>
        <fullName>Apttus_Config2__ApplicationMethod__c</fullName>
        <description>The incentive application method, depends on the application type.</description>
        <inlineHelpText>The incentive application method, depends on the application type.</inlineHelpText>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buy X Get X</fullName>
                    <default>true</default>
                    <label>Buy X Get X</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EffectiveDate__c</fullName>
        <defaultValue>DATE(2000,01,01)</defaultValue>
        <description>The incentive effective date. The incentive becomes effective on this date.</description>
        <inlineHelpText>The incentive effective date. The incentive becomes effective on this date.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The incentive priority sequence. Indicates the order of application of the incentive.</description>
        <inlineHelpText>The incentive priority sequence. Indicates the order of application of the incentive.</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__IncentiveCoupon__c.object
<CustomObject>
    <description>Represents a coupon associated with an incentive</description>
    <fields>
        <fullName>Apttus_Config2__CouponCode__c</fullName>
        <description>The coupon code</description>
        <externalId>true</externalId>
        <inlineHelpText>The coupon code</inlineHelpText>
        <label>Coupon Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EffectiveDate__c</fullName>
        <description>The coupon effective date. The coupon becomes effective on this date.</description>
        <inlineHelpText>The coupon effective date. The coupon becomes effective on this date.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IncentiveId__c</fullName>
        <description>ID of the associated incentive</description>
        <inlineHelpText>ID of the associated incentive</inlineHelpText>
        <label>Incentive</label>
        <referenceTo>Apttus_Config2__Incentive__c</referenceTo>
        <relationshipLabel>Coupons</relationshipLabel>
        <relationshipName>Coupons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incentive Coupon</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Coupon Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Coupons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__ConfigurationId__c</fullName>
        <description>ID of the associated configuration</description>
        <label>Configuration</label>
        <referenceTo>Apttus_Config2__ProductConfiguration__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__CouponCode__c</fullName>
        <description>The incentive coupon code</description>
        <inlineHelpText>The incentive coupon code</inlineHelpText>
        <label>Coupon Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IncentiveId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated incentive</description>
        <inlineHelpText>ID of the associated incentive</inlineHelpText>
        <label>Incentive</label>
        <referenceTo>Apttus_Config2__Incentive__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ItemSequence__c</fullName>
        <description>The sequence of items belonging to a line</description>
        <label>Item Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineNumber__c</fullName>
        <description>The line number</description>
        <label>Line Number</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceRule__c.object
<CustomObject>
    <description>Represents a single rule in a price ruleset</description>
    <fields>
        <fullName>Apttus_Config2__ApplicationMethod__c</fullName>
        <description>The rule application method. This field is deprecated. The Application method is moved to the Price Ruleset..</description>
        <label>Application Method (Deprecated)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aggregate</fullName>
                </value>
                <value>
                    <fullName>Allocate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EffectiveDate__c</fullName>
        <description>The rule or benefit effective date. The rule or benefit becomes effective on this date. It may also indicate the start date of a price ramp.</description>
        <inlineHelpText>The rule or benefit effective date. The rule or benefit becomes effective on this date. It may also indicate the start date of a price ramp.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__RulesetId__c</fullName>
        <description>ID of the associated rule set</description>
        <label>Ruleset</label>
        <referenceTo>Apttus_Config2__PriceRuleset__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The rule evaluation sequence</description>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceRuleEntry__c.object
<CustomObject>
    <description>Represents a single entry in a price rule</description>
    <fields>
        <fullName>Apttus_Config2__PriceRuleId__c</fullName>
        <description>ID of the associated rule</description>
        <label>Price Rule</label>
        <referenceTo>Apttus_Config2__PriceRule__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>RuleEntries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <description>The rule entry sequence</description>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price Rule Entry</label>
    <nameField>
        <displayFormat>RE-{0000000000}</displayFormat>
        <label>Rule Entry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceRuleset__c.object
<CustomObject>
    <description>Represents a rule set that contains the a list of rules to modify prices of products the organization sells.</description>
    <fields>
        <fullName>Apttus_Config2__ApplicationMethod__c</fullName>
        <description>The ruleset application method. Only applicable to aggregate price rules.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus_Config2__UseType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Apply to Line Items</fullName>
                </value>
                <value>
                    <fullName>Create Summary Lines</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EffectiveDate__c</fullName>
        <description>The rule set effective date. The rule set becomes effective on this date and time.</description>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IncentiveId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the incentive associated with the ruleset. Only applicable for incentives.</description>
        <inlineHelpText>ID of the incentive associated with the ruleset. Only applicable for incentives.</inlineHelpText>
        <label>Incentive</label>
        <referenceTo>Apttus_Config2__Incentive__c</referenceTo>
        <relationshipLabel>Price Rulesets</relationshipLabel>
        <relationshipName>PriceRulesets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Sequence__c</fullName>
        <inlineHelpText>The rule set evaluation sequence</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price Ruleset</label>
    <nameField>
        <label>Ruleset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rulesets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_Config2__EffectiveDate__c</fullName>
        <description>The configuration effective date.</description>
        <label>Config Effective Date</label>
        <type>DateTime</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>AdjustmentLineItemTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for APTS_AdjustmentLineItemTriggerHandler Mute/Unmute</description>
        <label>AdjustmentLineItemTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_AdjustmentLineItemHandler_Test.cls
/**
* Class Name : APTS_AdjustmentLineItemHandler_Test
* Description :  Test class to test APTS_AdjustmentLineItemTriggerHandler Apex Class
* Author : Lavanya Ravindran
* Date Created : 12-04-2018
**/
@isTest 
private class APTS_AdjustmentLineItemHandler_Test{

    @isTest
    static void testHandler(){
        Test.startTest();
        // Create Trigger Settings
        TriggerSettings__c settings = new TriggerSettings__c();
        settings.AdjustmentLineItemTrigger__c = true;
        insert settings;
        System.assertequals([ Select id from TriggerSettings__c limit 1].size(),1);
        // Create Product Configuration
        Apttus_Config2__ProductConfiguration__c prodConfig = new Apttus_Config2__ProductConfiguration__c (Name= 'Test Product');
        insert prodConfig;
        System.assertequals([ Select id from Apttus_Config2__ProductConfiguration__c limit 1].size(),1);
        // Create Price Rule Set
        Apttus_Config2__PriceRuleset__c priceRuleSet= new Apttus_Config2__PriceRuleset__c (Name = 'Test',Apttus_Config2__Sequence__c =1);
        insert priceRuleSet;
        System.assertequals([ Select id from Apttus_Config2__PriceRuleset__c limit 1].size(),1);
        // Create Price Rule 
        Apttus_Config2__PriceRule__c priceRule = new Apttus_Config2__PriceRule__c (Name = 'Test',Apttus_Config2__RulesetId__c=priceRuleSet.id,Apttus_Config2__Sequence__c =1);
        insert priceRule;
        System.assertequals([ Select id from Apttus_Config2__PriceRule__c limit 1].size(),1);
        // Create Price Rule Entry
        Apttus_Config2__PriceRuleEntry__c priceEntry = new Apttus_Config2__PriceRuleEntry__c (Apttus_Config2__Sequence__c= 1,Apttus_Config2__PriceRuleId__c= priceRule.id);
        insert priceEntry;
        System.assertequals([ Select id from Apttus_Config2__PriceRuleEntry__c limit 1].size(),1);
        // Create Incentive
        Apttus_Config2__Incentive__c incentive = new Apttus_Config2__Incentive__c (Name='Test Incentive',
                                                                                   Apttus_Config2__ApplicationMethod__c='Buy X Get X',
                                                                                   Apttus_Config2__EffectiveDate__c = system.today(),
                                                                                   Apttus_Config2__Sequence__c=1);
        insert incentive;
        System.assertequals([ Select id from Apttus_Config2__Incentive__c limit 1].size(),1);
        // Create Incentive Coupon
        Apttus_Config2__IncentiveCoupon__c incentiveCoupon= new Apttus_Config2__IncentiveCoupon__c (Apttus_Config2__CouponCode__c='Test', Apttus_Config2__IncentiveId__c = incentive.id);
        insert incentiveCoupon;
        System.assertequals([ Select id from Apttus_Config2__IncentiveCoupon__c limit 1].size(),1);
        // Create  Line Item
        Apttus_Config2__LineItem__c lineItem = new Apttus_Config2__LineItem__c (Apttus_Config2__LineNumber__c=12345, 
        Apttus_Config2__ConfigurationId__c = prodConfig.id,CurrencyIsoCode='EUR',Apttus_Config2__ItemSequence__c = 1,Apttus_Config2__IncentiveId__c = incentive.id,
        Apttus_Config2__IncentiveCode__c = incentiveCoupon.id);
        insert lineItem;
        
        System.assertequals([ Select id from Apttus_Config2__LineItem__c limit 1].size(),1);
        // Create  Adjustment Line Item
        Apttus_Config2__AdjustmentLineItem__c adjustlineItem = new Apttus_Config2__AdjustmentLineItem__c (Apttus_Config2__LineNumber__c=12345,
                                                                                               Apttus_Config2__PriceRuleEntryId__c = priceEntry.id, 
                                                                                               Apttus_Config2__LineItemId__c = lineItem.id,
                                                                                               Apttus_Config2__IncentiveId__c = incentive.id,
                                                                                               Apttus_Config2__Type__c= APTS_CPQConstants.LABEL_PROMOTION,
                                                                                               Apttus_Config2__IncentiveCode__c = incentiveCoupon.id);
        adjustlineItem.CurrencyIsoCode='EUR';
        System.debug('**abhi'+adjustlineItem);
        //insert adjustlineItem;  
        Test.stopTest();
        List<Apttus_Config2__AdjustmentLineItem__c> newItems = new List<Apttus_Config2__AdjustmentLineItem__c>();
        newItems.add(adjustlineItem);
        APTS_AdjustmentLineItemTriggerHandler handler = new APTS_AdjustmentLineItemTriggerHandler();
        handler.BeforeInsert(newItems);
        handler.AfterInsert(newItems,null);
       handler.BeforeUpdate(newItems, null, null, null);
        handler.BeforeDelete(newItems, null);
        handler.AfterUpdate(newItems, null, null, null);
        handler.AfterDelete(newItems, null);
        handler.AfterUndelete(newItems, null);
        System.assertequals(newItems.size(),1);
    }
}