src/objects/Apttus_Billing__UsageInput__c.object
<CustomObject>
    <description>The usage input for a product or service</description>
    <fields>
        <fullName>Apttus_Billing__Status__c</fullName>
        <description>The usage status</description>
        <inlineHelpText>The usage status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Loaded</fullName>
                    <default>true</default>
                    <label>Loaded</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Usage Input</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Input Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProcessUsageInputBatch.cls
/*
 * Author: Amit
 * Version: V1
 * Class : Batch class to rate usage input 
 */
global class APTS_ProcessUsageInputBatch implements Database.Batchable<sObject>{
	global Database.QueryLocator start(Database.BatchableContext BC){
 		string query = 'Select Id from Apttus_Billing__UsageInput__c where Apttus_Billing__Status__c = \'Loaded\'';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Apttus_Billing__UsageInput__c> scope){
        Set<ID> usageInputIDs = new Set<ID>(); 
        for(Apttus_Billing__UsageInput__c usgInp : scope){
            usageInputIDs.add(usgInp.Id);
        }
        system.debug('usageInputIDs ==> '+usageInputIDs);
        Apttus_Billing.BillingService.processPendingUsageInput(usageInputIDs,true); 
    }
    global void finish(Database.BatchableContext BC){
    }
}