src/objects/Apttus_Config2__FrequencyConversionRate__c.object
<CustomObject>
    <description>Represents the conversion rates used to convert pricing from one frequency or unit of measure to another frequency or unit of measure</description>
    <fields>
        <fullName>Apttus_Config2__ConversionFactor__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The conversion factor to apply to convert one frequency to another</description>
        <label>Conversion Factor</label>
        <precision>18</precision>
        <required>true</required>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__FromUom__c</fullName>
        <description>The unit of measure to convert from</description>
        <inlineHelpText>The unit of measure to convert from</inlineHelpText>
        <label>From Uom</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_CC</fullName>
                    <label>Cubic Centimeter</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>SAP_DRKS</fullName>
                    <label>Drinks</label>
                </value>
                <value>
                    <fullName>SAP_PX2</fullName>
                    <label>FUP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_PX1</fullName>
                    <label>HAP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LR</fullName>
                    <label>Layer</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_MTR</fullName>
                    <label>Meter</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
                <value>
                    <fullName>SAP_ZRE</fullName>
                    <label>Reporting</label>
                </value>
                <value>
                    <fullName>SAP_SMU</fullName>
                    <label>Smallest Unit</label>
                </value>
                <value>
                    <fullName>SAP_ZZZ</fullName>
                    <label>St. UoM IB</label>
                </value>
                <value>
                    <fullName>SAP_ZTU</fullName>
                    <label>Trade unit</label>
                </value>
                <value>
                    <fullName>SAP_ZVW</fullName>
                    <label>Vol.weight</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product</description>
        <inlineHelpText>ID of the associated product</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Frequency/UOM Conversion Rates</relationshipLabel>
        <relationshipName>FrequencyUOMConversionRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ToUom__c</fullName>
        <description>The unit of measure to convert to</description>
        <inlineHelpText>The unit of measure to convert to</inlineHelpText>
        <label>To Uom</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>SAP_LR</fullName>
                    <label>Layer</label>
                </value>
                <value>
                    <fullName>SAP_ZRE</fullName>
                    <label>Reporting</label>
                </value>
                <value>
                    <fullName>SAP_ZTU</fullName>
                    <label>Trade unit</label>
                </value>
                <value>
                    <fullName>SAP_ZVW</fullName>
                    <label>Vol.weight</label>
                </value>
                <value>
                    <fullName>SAP_ZZZ</fullName>
                    <label>St. UoM IB</label>
                </value>
                <value>
                    <fullName>SAP_PX1</fullName>
                    <label>HAP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PX2</fullName>
                    <label>FUP120*80</label>
                </value>
                <value>
                    <fullName>SAP_SMU</fullName>
                    <label>Smallest Unit</label>
                </value>
                <value>
                    <fullName>SAP_MTR</fullName>
                    <label>Meter</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
                <value>
                    <fullName>SAP_CC</fullName>
                    <label>Cubic Centimeter</label>
                </value>
                <value>
                    <fullName>SAP_DRKS</fullName>
                    <label>Drinks</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Frequency/UOM Conversion Rate</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Conversion Rate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frequency/UOM Conversion Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_CreateUOMsBatch_test.cls
@isTest
private class APTS_CreateUOMsBatch_test {
	
	@isTest static void test_createUOM_usecase1() {
		test.startTest();

		List<Product2> productList = TestDataFactory.createProduct(10);
		insert productList;

		List<Apttus_Config2__FrequencyConversionRate__c> insertFrequencyList = new List<Apttus_Config2__FrequencyConversionRate__c>();
		for(integer i=0;i<productList.size();i++){
			Apttus_Config2__FrequencyConversionRate__c freqConversionBX = new Apttus_Config2__FrequencyConversionRate__c();
			freqConversionBX.Apttus_Config2__ProductId__c=productList[i].id;
			freqConversionBX.Apttus_Config2__ConversionFactor__c=5;
			freqConversionBX.Apttus_Config2__FromUom__c = 'SAP_PCE';
			freqConversionBX.Apttus_Config2__ToUom__c = 'SAP_BX';
			insertFrequencyList.add(freqConversionBX);

			Apttus_Config2__FrequencyConversionRate__c freqConversionPF = new Apttus_Config2__FrequencyConversionRate__c();
			freqConversionPF.Apttus_Config2__ProductId__c=productList[i].id;
			freqConversionPF.Apttus_Config2__ConversionFactor__c=10;
			freqConversionPF.Apttus_Config2__FromUom__c = 'SAP_PCE';
			freqConversionPF.Apttus_Config2__ToUom__c = 'SAP_PF';
			insertFrequencyList.add(freqConversionPF);
		}
		insert insertFrequencyList;
		APTS_CreateUOMsBatchHandler handler = new APTS_CreateUOMsBatchHandler();
		Database.executeBatch(new APTS_CreateUOMsBatch(),200);
		test.stopTest();
	}
}