src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Agreement_Category__c</fullName>
        <description>Used to categorize agreement types.  When setting up a new agreement type make sure to seect approrpiate values for that agreement type and to set the right default</description>
        <label>Agreement Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BusinessObjectId__c</fullName>
        <description>ID of the business object associated with the asset line item</description>
        <label>Business Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__BillingPreference__c.object
<CustomObject>
    <description>Represents a functional preference for billing purposes</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Billing Preferences</relationshipLabel>
        <relationshipName>BillingPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_SAP_OrderType__c</fullName>
        <description>This is the SAP OrderType</description>
        <label>SAP OrderType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>XA01</fullName>
                </value>
                <value>
                    <fullName>XA02</fullName>
                </value>
                <value>
                    <fullName>XA13</fullName>
                </value>
                <value>
                    <fullName>XA14</fullName>
                </value>
                <value>
                    <fullName>XB01</fullName>
                </value>
                <value>
                    <fullName>XB02</fullName>
                </value>
                <value>
                    <fullName>XB13</fullName>
                </value>
                <value>
                    <fullName>XL01</fullName>
                </value>
                <value>
                    <fullName>XC01</fullName>
                </value>
                <value>
                    <fullName>XD01</fullName>
                </value>
                <value>
                    <fullName>XA23</fullName>
                </value>
                <value>
                    <fullName>XB05</fullName>
                </value>
                <value>
                    <fullName>XB03</fullName>
                </value>
                <value>
                    <fullName>XB04</fullName>
                </value>
                <value>
                    <fullName>XA04</fullName>
                </value>
                <value>
                    <fullName>XA07</fullName>
                </value>
                <value>
                    <fullName>XA03</fullName>
                </value>
                <value>
                    <fullName>XD09</fullName>
                </value>
                <value>
                    <fullName>XD12</fullName>
                </value>
                <value>
                    <fullName>XA06</fullName>
                </value>
                <value>
                    <fullName>XC09</fullName>
                </value>
                <value>
                    <fullName>XB23</fullName>
                </value>
                <value>
                    <fullName>XD02</fullName>
                </value>
                <value>
                    <fullName>Fixed Term</fullName>
                    <isActive>false</isActive>
                    <label>Fixed Term</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceListItem__c.object
<CustomObject>
    <description>Represents a product entry in a price list.</description>
    <label>Price List Item</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the agreement associated with the configuration</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Configurations (Sold To)</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BusinessObjectId__c</fullName>
        <description>ID of the business object associated with the configuration</description>
        <label>Business Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated order</description>
        <inlineHelpText>ID of the associated order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_AssetLineCallbackTest.cls
/************************************************************* 
@Name: APTS_AssetLineCallbackTest 
@Author: Santosh Kumar
@CreateDate: 19th July, 2018
@Description: Test Class of APTS_AssetLineCallback.
******************************************************************/ 

@isTest
private class APTS_AssetLineCallbackTest {
    
    public static Account oTestAccount;
    public static Contact oTestContact;
    public static Opportunity oTestOpp;
    public static Product2 oproduct; 
    public static Apttus_Config2__PriceList__c oTestPricelist;
    public static Apttus_Config2__PriceListItem__c opriceListItem;
    public static Apttus_Config2__BillingPreference__c oBillPref;
    public static Apttus__APTS_Agreement__c oAggremt;
    public static Apttus_Config2__Order__c order;
    public static Apttus_Config2__Order__c orderxb23;
    public static Apttus_Config2__ProductConfiguration__c oProdconfig;
    public static Apttus_Config2__ProductConfiguration__c ordProdconfig;
    public static List<Apttus_Config2__AssetLineItem__c> oAssetLIList = new List<Apttus_Config2__AssetLineItem__c>();
    public static Boolean Trial=false;

    public static void init() {

        oTestAccount = APTS_TestUtils.createOrganisation();
        insert oTestAccount;

        oTestContact = APTS_TestUtils.createContact();
        insert oTestContact;

        oTestOpp = APTS_TestUtils.createOpportunity(oTestAccount.Id);
        insert oTestOpp;

        oproduct = APTS_TestUtils.createProduct('Test Package Cafitesse 50', '26940997', 'Machines');   
        insert oproduct;

        oTestPricelist = APTS_TestUtils.createPriceList();
        insert oTestPricelist;

        opriceListItem = APTS_TestUtils.createPriceListItem(oTestPricelist.id, oproduct.id);
        insert opriceListItem;


        oBillPref = APTS_TestUtils.createBillingPrefrence();
        insert oBillPref;

        oAggremt = APTS_TestUtils.createAgreement(oTestContact.Id, null, oTestPricelist.Id, oTestAccount.Id);
        oAggremt.Apttus__Contract_Start_Date__c = System.Today();
        oAggremt.Apttus__Agreement_Category__c = 'In Effect';
        oAggremt.Apttus__Contract_End_Date__c = System.Today().adddays(60);
        insert oAggremt;

        orderxb23 = APTS_TestUtils.createOrder('New', oTestPricelist.Id, oTestAccount.Id, oBillPref.Id);
        orderxb23.Apttus_CMConfig__AgreementId__c = oAggremt.Id;
        orderxb23.APTS_SAP_OrderType__c= 'XB23';
        insert orderxb23;
        
        order = APTS_TestUtils.createOrder('New', oTestPricelist.Id, oTestAccount.Id, oBillPref.Id);
        order.Apttus_CMConfig__AgreementId__c = oAggremt.Id;
        insert order;

        oProdconfig = APTS_TestUtils.getProductConfiguration2('Test config', 1, null, 'Agreement', 'Category' ,oTestPricelist.Id, 'Finalized', System.Today(), System.Today(), true);
        oProdconfig.Apttus_Config2__OrderId__c = order.Id;
        oProdconfig.Apttus_CMConfig__AgreementId__c = oAggremt.Id;
        oProdconfig.Apttus_Config2__BusinessObjectId__c = oAggremt.Id;
        oProdconfig.Apttus_Config2__AccountId__c=oTestAccount.Id;
        insert oProdconfig;
        
        ordProdconfig = APTS_TestUtils.getProductConfiguration2('Test config', 1, null, 'Agreement', 'Category' ,oTestPricelist.Id, 'Finalized', System.Today(), System.Today(), true);
        ordProdconfig.Apttus_Config2__OrderId__c = orderxb23.Id;
        ordProdconfig.Apttus_CMConfig__AgreementId__c = oAggremt.Id;
        ordProdconfig.Apttus_Config2__BusinessObjectId__c = oAggremt.Id;
        ordProdconfig.Apttus_Config2__AccountId__c=oTestAccount.Id;
        insert ordProdconfig;
        
        for(integer count=0;count<5;count++) {
            Apttus_Config2__AssetLineItem__c oAssetlineItem = APTS_TestUtils.createAssetLineItem(oTestAccount.Id, oproduct.Id, oTestPricelist.Id, opriceListItem.Id, oBillPref.Id, order.Id);
            if(math.mod(count,2) == 0 ) {
                oAssetlineItem.Apttus_CMConfig__AgreementId__c = oAggremt.Id;
            }
            oAssetLIList.add(oAssetlineItem);
        }
        insert oAssetLIList;

    }

    public static testMethod void filtermethodtest() {

        init();

        Test.startTest();
    
        APTS_AssetLineCallBack assetLineItemCallback = new APTS_AssetLineCallBack();
         assetLineItemCallback.isTrialOrder=true;
        Apttus_Config2.CustomClass.ActionParams params = new Apttus_Config2.CustomClass.ActionParams() ;
        params.AccountId = oTestAccount.Id;
    
       if(assetLineItemCallback.isTrialOrder) {
       Apttus_Config2.CallbackTester.testAssetLineItemCallback(ordProdconfig.Id, null, null, assetLineItemCallback, params);
       }
       

        List<Apttus_Config2__AssetLineItem__c> oALIList = [select id from Apttus_Config2__AssetLineItem__c where Apttus_CMConfig__AgreementId__c =: oAggremt.Id];
        system.assertNotEquals(oALIList.size(), 0);

        Test.stopTest();

    }
    
    public static testMethod void filtermethodtest1() {

        init();

        Test.startTest();
    
        APTS_AssetLineCallBack assetLineItemCallback = new APTS_AssetLineCallBack();
        Apttus_Config2.CustomClass.ActionParams params = new Apttus_Config2.CustomClass.ActionParams() ;
        params.AccountId = oTestAccount.Id;
    
       if(assetLineItemCallback.isTrialOrder) {
            Apttus_Config2.CallbackTester.testAssetLineItemCallback(oProdconfig.Id, null, null, assetLineItemCallback, params);
       }
      
        List<Apttus_Config2__AssetLineItem__c> oALIList = [select id from Apttus_Config2__AssetLineItem__c where Apttus_CMConfig__AgreementId__c =: oAggremt.Id];
        system.assertNotEquals(oALIList.size(), 0);

        Test.stopTest();

    }
    
    
}