src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <description>This is the Custom Status ; to manage statuses in Submit Order &amp; Update Order logics.</description>
        <label>Status Custom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Sent For Invoicing</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__SoldToAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Sold To)</relationshipLabel>
        <relationshipName>OrdersSoldTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The order status</description>
        <inlineHelpText>The order status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <fields>
        <fullName>APTS_Status__c</fullName>
        <description>This is the Custom Status ; to manage statuses in Submit Order &amp; Update Order logics.</description>
        <label>Status Custom</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Sent For Invoicing</fullName>
                    <isActive>false</isActive>
                    <label>Sent For Invoicing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The order line status</description>
        <inlineHelpText>The order line status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Partially Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Being Cancelled</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account object if related to this transaction</description>
        <inlineHelpText>Lookup to Account object if related to this transaction</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/APTS_SubmitTriangularOrderQueueable.cls
global class APTS_SubmitTriangularOrderQueueable implements Queueable {

    private List<Apttus_Config2__Order__c> orderList = null;
    private static final String ACCOUNT_HIERARCHY = 'Account Hierarchy';
    private static final String ORDER = System.Label.APTS_Order;

    global APTS_SubmitTriangularOrderQueueable(List<Apttus_Config2__Order__c> submitOrderList) {

        this.orderList = submitOrderList;

       APTS_CustomLogging.createErrorLog('OM_TRIO_DEBUG', 'Apex', String.valueOf(submitOrderList) , 'APTS_SubmitTriangularOrderQueueable', null, 'OM', false, false, null, false);

    }

    global void execute(QueueableContext context) {

        try {
            List<sObject> objList = new List<sObject>();
            List<sObject> objOLIList = new List<sObject>();

            if (!orderList.isEmpty()) {
                List<Integration_Log__c> listIntegrationLog = new List<Integration_Log__c>();
                set<Id> orderIDsToSubmit = new set<Id>();
                for (Apttus_Config2__Order__c oOrder : orderList) {
                    //Create Integration Log
                    //v100 << ++ Added as part of the Duplicate Integration Log Issue
                    if ((oOrder.APTS_Status__c == 'Draft') && !(oOrder.APTS_Status__c == 'Submitted')) {

                        //v100 ++ >>
                        Integration_Log__c oIntegrationLog = new Integration_Log__c(Object_Id__c = oOrder.Id,
                                Object__c = ORDER, Integration_Status__c = INT_Constants.INITIAL,
                                Account__c = oOrder.Apttus_Config2__SoldToAccountId__c, Order__c = oOrder.Id);
                        listIntegrationLog.add(oIntegrationLog);
                        if (oOrder.Apttus_Config2__SoldToAccountId__r.SAP_Customer_Id__c == null && oOrder.Apttus_Config2__SoldToAccountId__r.RecordType.Name == 'Prospect' &&
                                oOrder.Apttus_Config2__SoldToAccountId__r.Parent_Valid_From__c == null && oOrder.Apttus_Config2__SoldToAccountId__r.Parent_Valid_To__c == null && oOrder.Apttus_Config2__SoldToAccountId__r.Parent_Change_Indicator__c != 'I') {
                            listIntegrationLog.add(new Integration_Log__c(Object_Id__c = oOrder.Apttus_Config2__SoldToAccountId__c, Object__c = ACCOUNT_HIERARCHY, Integration_Status__c = INT_Constants.INITIAL, Account__c = oOrder.Apttus_Config2__SoldToAccountId__c, Order__c = oOrder.Id));
                        }
                        oOrder.Apttus_Config2__Status__c = APTS_OrderConstants.PENDING;
                        oOrder.APTS_Status__c = APTS_OrderConstants.SUBMITTED;
                        objList.add(oOrder);
                        orderIDsToSubmit.add(oOrder.Id);

                    }
                }

                if (!listIntegrationLog.isEmpty()) {
                    Database.insert(listIntegrationLog, false);
                }
                Map<Id, Apttus_Config2__OrderLineItem__c> submittedOliMaptoOrder = APTS_OrderLineItemDAO.getAllOrderLineItems(orderIDsToSubmit);
                for (Apttus_Config2__OrderLineItem__c submittedOli : submittedOliMaptoOrder.Values()) {

                    submittedOli.Apttus_Config2__Status__c = APTS_OrderConstants.PENDING;
                    submittedOli.APTS_Status__c = APTS_OrderConstants.SUBMITTED;
                    objOLIList.add(submittedOli);
                     

                }
                if (objList != null) {
                    try {
                        APTS_OrderUtils.stopOrderTrigger();
                        APTS_OrderUtils.stopOrderLineItemTrigger();
                        APTS_TriangularInvoiceBatchHandler.updatesObject(objOLIList);
                        APTS_TriangularInvoiceBatchHandler.updatesObject(objList);                    
                        APTS_OrderUtils.startOrderLineItemTrigger();
                        APTS_OrderUtils.startOrderTrigger();
                        
                    } catch (Exception e) {APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() , 'Order', null, 'OM', false, false, null, true);}
                }

            }
        } catch (Exception e) {APTS_CustomLogging.createErrorLog(e.getTypeName(), 'Apex', e.getStackTraceString() , 'Order', null, 'OM', false, false, null, true);}

    }
}