src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Bill_to_Party_Ingredients__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Party (Ingredients)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Bill to Party (Ingredients))</relationshipLabel>
        <relationshipName>Agreements4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Check_on_Account_Ingredients__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Updated field label only per Defect 19560.</description>
        <inlineHelpText>If True than   
Check Related Fields on Account   
If related fields are blank than set Account as Bill to and Payer To  
If False than   
Check Related fields from Agreement</inlineHelpText>
        <label>Use BT/Payer Ingredients from Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Payer_Ingredients__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payer Ingredients</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements (Payer)</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Bill_to_Party_Ingredients_and_Payer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill to Party (Ingredients)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Bill to Party (Ingredients))</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_InvoiceType__c</fullName>
        <label>Invoice Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Invoice_List_Indicator__c</fullName>
        <description>This is the Invoice list indicator</description>
        <label>Invoice List Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YE</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_PayerIngredients__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payer Ingredients</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Payer Ingredients)</relationshipLabel>
        <relationshipName>Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Payer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Payer</description>
        <label>Payer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders (Payer)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BillingPreferenceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated billing preference</description>
        <inlineHelpText>ID of the associated billing preference</inlineHelpText>
        <label>Billing Preference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Apttus_Config2__BillingPreference__c.Apttus_Config2__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Please select a billing preference</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Apttus_Config2__BillingPreference__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The order description</description>
        <inlineHelpText>The order description</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PaymentTermId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the payment term associated with the order</description>
        <inlineHelpText>ID of the payment term associated with the order</inlineHelpText>
        <label>Payment Term</label>
        <referenceTo>Apttus_Config2__PaymentTerm__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <inlineHelpText>ID of the associated price list</inlineHelpText>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Source__c</fullName>
        <description>The order source</description>
        <inlineHelpText>The order source</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>APTS_SalesOrg__c</fullName>
        <inlineHelpText>This must be populated with a unique 4 digit code for sales orgs for Batches to Run</inlineHelpText>
        <label>SalesOrg</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Description__c</fullName>
        <description>The description of the price list.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_CreateDebitMemoOrderFromAccount.cls
/*************************************************************
@Name: APTS_CreateDebitMemoOrderFromAccount
@Author: Ankit Joshi
@CreateDate: 03-07-2018
@Description: Create Debit Memo Order from Account
@UsedBy: Create Debit Memo button on Account page
***************************************************************/
//v101 Renuka : Defect#6048 Setting PriceList in the DebitOrder is modified.
//v102 13-Nov-2019 Renuka: QTCFLEX1-1583 Enable BTP checkbox logic for Credit and Debit memo orders

public with sharing class APTS_CreateDebitMemoOrderFromAccount{

    private final Apttus__APTS_Agreement__c oAgreement;
    private Id accountId;
    private String sType;
    private Account initialAccount;
    private static final String DEBIT_MEMO = System.Label.APTS_DebitMemo;
    private static final String ID = System.Label.APTS_Id;
    private static final String TYPE = System.Label.APTS_Type;
    private static final String IN_EFFECT = System.Label.APTS_In_Effect;
    private static final String ACTIVATED = System.Label.APTS_Activated;
    private static final String ACCOUNT = System.Label.APTS_Account;
    private static final String APEX = 'Apex';
    private static final String BIR = 'BIR';
    private static final String SLASH = '/';
    private static final String EXCEPTION_OCCURED = 'Exception: ';
    private static final String XD01 = System.Label.APTS_XD01;
    private static final String ORDER = 'Order';
    private static final String SAP = 'SAP_';
    private static final String STANDARD = 'Standard';
    private static final String STANDARD_DEAL = 'Standard Deal';
    private static final string SINGLEINVOICE = 'Single Invoice';
    private static final string NO= 'No';
    
    public Apttus_Config2__Order__c oOrder {get; set;}
    
    /** Controller Constructor 
    * Description : will be invoked on Page load
    **/
    public APTS_CreateDebitMemoOrderFromAccount() {

        accountId = ApexPages.currentPage().getParameters().get(ID);
        sType = ApexPages.currentPage().getParameters().get(TYPE);               
    }
    
    /** MethodName : createOrder 
    * Description : It is used to create the Order when Debit Memo button on Account is clicked
    **/
    public PageReference createOrder() {

        try{
            PageReference pageRef;
            Id standardAccountId = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(STANDARD_DEAL).getRecordTypeId();

            initialAccount = [SELECT Id, Ultimate_Parent_Account__c, APTS_Account_Level__c,
                          Language__c, Apttus_Config2__BillingPreferenceId__c, Apttus_Config2__PaymentTermId__c,
                          Bill_To_Payer_Account__c, Related_Payer_Account__c,APTS_Price_List__c,
                          /*Related_Bill_to_Machines_Services__c,*/ Related_Payer_Machines_Services__c,
                          Sales_Organization__c, Division__c, Distribution_Channel__c, Partner__c, Description,
                          (Select Id,APTS_Payer_Ingredients__c,APTS_Bill_to_Party_Ingredients__c,APTS_Check_on_Account_Ingredients__c from Apttus__R00N50000001Xl0UEAS__r
                            WHERE RecordTypeId =: standardAccountId and Apttus__Status__c =: ACTIVATED order by LastModifiedDate desc)
                          FROM Account
                          WHERE Id = :accountId limit 1];

            oOrder = new Apttus_Config2__Order__c();
            oOrder = APTS_OrderUtils.setOrderHeaderMandatoryFields(oOrder, sType);
            oOrder.Apttus_Config2__Source__c = ACCOUNT;
            oOrder.Apttus_Config2__Description__c = initialAccount.Description;

            APTS_OrderUtils.setOrderHeader(oOrder, initialAccount);
            
            //Set partner Functions for Order
            if(initialAccount.Apttus__R00N50000001Xl0UEAS__r != null && initialAccount.Apttus__R00N50000001Xl0UEAS__r.size() > 0){
                oOrder.APTS_Payer__c = initialAccount.Apttus__R00N50000001Xl0UEAS__r[0].APTS_Payer_Ingredients__c;
                oOrder.APTS_PayerIngredients__c = initialAccount.Apttus__R00N50000001Xl0UEAS__r[0].APTS_Payer_Ingredients__c;
                oOrder.APTS_Bill_to_Party_Ingredients_and_Payer__c = initialAccount.Apttus__R00N50000001Xl0UEAS__r[0].APTS_Bill_to_Party_Ingredients__c;
                //Added to fix defect #21150 and #21148
                oOrder.Apttus_CMConfig__AgreementId__c=initialAccount.Apttus__R00N50000001Xl0UEAS__r[0].Id;
                //v102 ++<< Added If condition
                if(!initialAccount.Apttus__R00N50000001Xl0UEAS__r[0].APTS_Check_on_Account_Ingredients__c){
                    APTS_BIRUtils.setInvoiceDataForDB(initialAccount.Apttus__R00N50000001Xl0UEAS__r[0], oOrder);    
                }
            }
            else{
                oOrder.APTS_Payer__c = initialAccount.Related_Payer_Account__c;
                oOrder.APTS_PayerIngredients__c = initialAccount.Related_Payer_Account__c;
                oOrder.APTS_Bill_to_Party_Ingredients_and_Payer__c = initialAccount.Bill_To_Payer_Account__c;
               
            }            
            oOrder.APTS_InvoiceType__c =SINGLEINVOICE;
            oOrder.APTS_Invoice_List_Indicator__c = NO;
            //Populate Pricelist on Order based on the Account's Sales Org
            /*Map<string, string> salesOrgMap = new Map<string, string>();
            Schema.DescribeFieldResult salesOrgList = Schema.sObjectType.Account.fields.Sales_Organization__c.getSObjectField().getDescribe();
            for(Schema.PicklistEntry salesOrgRec : salesOrgList.getPicklistValues()){
              salesOrgMap.put(salesOrgRec.getValue(), salesOrgRec.getLabel());
            }
            string accSalesOrg = (initialAccount.Sales_Organization__c).length() > 4 ? (initialAccount.Sales_Organization__c).substring(4) : initialAccount.Sales_Organization__c;
            for(Apttus_Config2__PriceList__c priceList : [Select id from Apttus_Config2__PriceList__c where APTS_SalesOrg__c =: accSalesOrg ]){
                oOrder.Apttus_Config2__PriceListId__c = priceList.Id;
            }*/ 
            //Defect#6048 Setting PriceList in the DebitOrder from APTS_DefaultPriceList class.          
            APTS_DefaultPriceList oDefaultPriceList = new APTS_DefaultPriceList();
            oOrder.Apttus_Config2__PriceListId__c = oDefaultPriceList.getDefaultPriceListId(initialAccount);
            
            Database.insert(oOrder);
            pageRef = new ApexPages.StandardController(oOrder).view();
            return pageRef;
        }catch(Exception ex){
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), APEX, ex.getMessage() , ACCOUNT , ApexPages.currentPage().getParameters().get(Label.APTS_Id),BIR,false,false,null,true);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, EXCEPTION_OCCURED+ex.getMessage()));
            return null;
        }
    }
     
    /** Method Name : back()
    * Description : Will redirect to Account Header detail page
    **/   
    public PageReference back() {
        try{
            return new PageReference(SLASH + accountId);
        }catch(Exception ex){
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), APEX, ex.getMessage() , ACCOUNT , ApexPages.currentPage().getParameters().get(Label.APTS_Id),BIR,false,false,null,true);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, EXCEPTION_OCCURED+ex.getMessage()));
            return null;
        }
    }
}