src/objects/Apttus_Config2__ProductOptionComponent__c.object
<CustomObject>
    <description>Represents a product option component which is a member of the list of options associated with a product.option group</description>
    <fields>
        <fullName>APTS_Product_Active__c</fullName>
        <formula>Apttus_Config2__ComponentProductId__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Product_Enabled_for_web_shop_s__c</fullName>
        <formula>Apttus_Config2__ComponentProductId__r.APTS_Product_Enabled_for_web_shop_s__c</formula>
        <label>Product Enabled for web shop(s)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ComponentProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the component product</description>
        <label>Component Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Parent Products</relationshipLabel>
        <relationshipName>ParentProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option Component</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Option Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Product_Enabled_for_web_shop_s__c</fullName>
        <label>Product Enabled for web shop(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>ProdOptionCompTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ProdOptionCompTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_ProdOptionCompTriggerHandler.cls
/**********************
Purpose: 
Revision History:
#No    Name         Date        Purpose
1.0    Nagavi       15/01/2017  Created the class to handle logics related to snding updates to SAP PO
************************/
public with sharing class APTS_ProdOptionCompTriggerHandler implements ITriggerHandler {
  public static Boolean isTriggerDisabled = true;
  public class ApplicationException extends Exception {}
  /*@methodName- IsDisabled
  *@description- method is used to prevent recursion
  *@param- empty
  *@return- returns boolean
  */
  public Boolean isDisabled(){
     try{
         Boolean disabled=false;
         if (TriggerSettings__c.getInstance().ProdOptionCompTrigger__c) {
           disabled=false;
         } 
         else {
           disabled=isTriggerDisabled;
         }
       return disabled;
     }catch(Exception e) {throw new ApplicationException(e);}
    }
  /*@methodName- beforeInsert
  *@description- method is used to call logic 
  *@param- Pass the 
  *@return- no returntype
  */
    public void beforeInsert(List<SObject> newProdOptionCompList){
      /*try{}
      catch(Exception e) {
        throw new ApplicationException(e);
      }*/
    } 
 
    /*@methodName- beforeUpdate
  *@description- method is used to call logic 
  *@param- Pass the 
  *@return- no returntype
  */
    public void beforeUpdate(List<SObject> newProdOptionCompList, Map<Id, SObject> newProdOptionCompMap, List<SObject> oldProdOptionCompList, Map<Id, SObject> oldProdOptionCompMap){
      /*try{}
      catch(Exception e) {
        throw new ApplicationException(e);
      }*/
    }
    
    /*@methodName- beforeDelete
  *@description- method is used to call logic related to the beforeDelete event
  *@param- Pass the 
  *@return- no returntype
  */
    public void beforeDelete(List<SObject> oldProdOptionCompList, Map<Id, SObject> oldProdOptionCompMap){
      /*try{}
      catch(Exception e) {
        throw new ApplicationException(e);
      }*/ 
    }
 
  /*@methodName- afterInsert
  *@description- method is used to call logic related to the after insert event
  *@param- Pass the new records as list and Map
  *@return- no returntype
  */
    public void afterInsert(List<SObject> newProdOptionCompList, Map<Id, SObject> newProdOptionCompMap){
      //Logic to check if the product is active and it is newly inserted.If so will trigger digital product
      try{
        onAfterInsertProdOptionComp((List<Apttus_Config2__ProductOptionComponent__c>)newProdOptionCompList);  
      }catch(DmlException e) {throw new ApplicationException(e);}

    }
    /*@methodName- afterUpdate
  *@description- method is used to call logic related to the after update event
  *@param- Pass the new and old records as list and Map from trigger
  *@return- no returntype
  */
    public void afterUpdate(List<SObject> newProdOptionCompList , Map<Id, SObject> newProdOptionCompMap, List<SObject> oldProdOptionCompList, Map<Id, SObject> oldProdOptionCompMap){
       //Logic to check if the product's isactive field has changed.If so will trigger digital pricing
      try{
        onAfterUpdateProdOptionComp((Map<Id, Apttus_Config2__ProductOptionComponent__c>)newProdOptionCompMap,(Map<Id, Apttus_Config2__ProductOptionComponent__c>)oldProdOptionCompMap);
      }catch(DmlException e) {throw new ApplicationException(e);}
    }
    /*@methodName- afterDelete
  *@description- method is used to call logic related to the afterDelete event
  *@param- Pass the 
  *@return- no returntype
  */
    public void afterDelete(List<SObject> oldProdOptionCompList, Map<Id, SObject> oldProdOptionCompMap){
      /*try{}
      catch(Exception e) {
        throw new ApplicationException(e);
      } */
    }
    /*@methodName- afterUndelete
  *@description- method is used to call logic related to the afterUndelete event
  *@param- Pass the 
  *@return- no returntype
  */
    public void afterUndelete(List<SObject> newProdOptionCompList, Map<Id, SObject> newProdOptionCompMap){
      /*try{}
      catch(Exception e) {
        throw new ApplicationException(e);
      } */
    }
    
    /*************** Business Logic Methods ***********************/
    /*@methodName- onAfterInsertProduct2
  *@description- method is used to call logic related to the after insert event
  *@param- Pass only the records to be processed as a list
  *@return- no returntype
  */
     public static void onAfterInsertProdOptionComp(List<Apttus_Config2__ProductOptionComponent__c> newProdOptionCompList){
        try{
         Set<Id> prodOptionCompIdsToBeSentToSAPPO=  new Set<Id>();
           for(Apttus_Config2__ProductOptionComponent__c prodOpt:newProdOptionCompList){
               if(prodOpt.APTS_Product_Active__c && APTS_IntegrationLogHandlerUtility.checkIfWebshopIsValid(prodOpt.APTS_Product_Enabled_for_web_shop_s__c)){
                  prodOptionCompIdsToBeSentToSAPPO.add(prodOpt.Apttus_Config2__ComponentProductId__c);   
               }    
           }
           
           if(!prodOptionCompIdsToBeSentToSAPPO.isEmpty()){
             APTS_IntegrationLogHandlerUtility.checkAndCreateIntegrationLogs(prodOptionCompIdsToBeSentToSAPPO);      
           }
         }catch(Exception e) {throw new ApplicationException(e);}
     }
     /*@methodName- onAfterUpdateProduct2
   *@description- method is used to call logic related to the after update event
   *@param- Pass the map of new and old records
   *@return- no returntype
   */
    public static void onAfterUpdateProdOptionComp(Map<Id, Apttus_Config2__ProductOptionComponent__c> newProdOptionCompMap,Map<Id, Apttus_Config2__ProductOptionComponent__c> oldProdOptionCompMap){
        try{
        Set<Id> prodOptionCompIdsToBeSentToSAPPO=new Set<Id>();
        List<Schema.FieldSetMember> relatedFieldSet=new List<Schema.FieldSetMember>();
        relatedFieldSet=APTS_IntegrationLogHandlerUtility.readFieldSet('APTS_ProdOptForDigitalIntegration','Apttus_Config2__ProductOptionComponent__c');    
        //List<Product2> productsToBeSentToSAPPO=  new List<Product2>();
           for(Id prodOptId:newProdOptionCompMap.keySet()){
               if(newProdOptionCompMap.get(prodOptId).APTS_Product_Active__c && APTS_IntegrationLogHandlerUtility.checkIfWebshopIsValid(newProdOptionCompMap.get(prodOptId).APTS_Product_Enabled_for_web_shop_s__c) &&
                   APTS_IntegrationLogHandlerUtility.checkIfValidToSend(newProdOptionCompMap.get(prodOptId),oldProdOptionCompMap.get(prodOptId),relatedFieldSet)){
                        prodOptionCompIdsToBeSentToSAPPO.add(newProdOptionCompMap.get(prodOptId).Apttus_Config2__ComponentProductId__c);   
               }    
           }
           
           if(!prodOptionCompIdsToBeSentToSAPPO.isEmpty()){
             APTS_IntegrationLogHandlerUtility.checkAndCreateIntegrationLogs(prodOptionCompIdsToBeSentToSAPPO);      
           }
        }catch(Exception e) {throw new ApplicationException(e);}
     }
}