src/objects/Apttus_Config2__AssetUsagePriceTier__c.object
<CustomObject>
    <description>Represents a single entry in a asset usage price tier</description>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <description>ID of the associated asset line item</description>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Usage Price Tiers</relationshipLabel>
        <relationshipName>AssetUsagePriceTiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__TierEndValue__c</fullName>
        <description>The tier end value</description>
        <inlineHelpText>The tier end value</inlineHelpText>
        <label>To</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__TierStartValue__c</fullName>
        <description>The tier start value</description>
        <inlineHelpText>The tier start value</inlineHelpText>
        <label>From</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Asset Usage Price Tier</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Tier Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Usage Price Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__LineItem__c.object
<CustomObject>
    <description>Represents a product or service line item</description>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated asset line item from which the line item is created.</description>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__ProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__DerivedFromId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the line item this was derived from</description>
        <label>Derived From</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Derived Line Items</relationshipLabel>
        <relationshipName>DerivedLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OrderLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated order line item</description>
        <inlineHelpText>ID of the associated order line item</inlineHelpText>
        <label>Order Line Item</label>
        <referenceTo>Apttus_Config2__OrderLineItem__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__Order__c.object
<CustomObject>
    <description>Represents an order associated with an account</description>
    <fields>
        <fullName>APTS_Order_Sub_Type__c</fullName>
        <description>This is the Order Sub Type</description>
        <label>Order Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>APTS_Order_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Standard Return</fullName>
                </value>
                <value>
                    <fullName>Unplanned Return</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>De-installation</fullName>
                </value>
                <value>
                    <fullName>Internal Movement</fullName>
                </value>
                <value>
                    <fullName>External Movement With Contract Change</fullName>
                </value>
                <value>
                    <fullName>External Movement Without Contract Change</fullName>
                </value>
                <value>
                    <fullName>Technical Swap</fullName>
                </value>
                <value>
                    <fullName>Commercial Swap</fullName>
                </value>
                <value>
                    <fullName>Route Sales and Operating</fullName>
                </value>
                <value>
                    <fullName>Subscription Order</fullName>
                </value>
                <value>
                    <fullName>Billing Schedule</fullName>
                </value>
                <value>
                    <fullName>Digital Order</fullName>
                </value>
                <value>
                    <fullName>Conversion Order</fullName>
                </value>
                <value>
                    <fullName>Stock Count</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Agreement Changes</fullName>
                </value>
                <value>
                    <fullName>Indexation</fullName>
                </value>
                <value>
                    <fullName>Consignment Issue for FSD</fullName>
                </value>
                <value>
                    <fullName>Consignment Fillup for FSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Machine Order</fullName>
                </value>
                <value>
                    <fullName>Credit Memo</fullName>
                </value>
                <value>
                    <fullName>Debit Memo</fullName>
                </value>
                <value>
                    <fullName>Admin Order</fullName>
                </value>
                <value>
                    <fullName>Route Sales Order</fullName>
                </value>
                <value>
                    <fullName>Operating Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Admin_Order</fullName>
        <active>true</active>
        <description>Record Type for Admin Orders</description>
        <label>Admin Order</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderLineItem__c.object
<CustomObject>
    <description>Represents a product or service line item associated with an order</description>
    <fields>
        <fullName>APTS_Order_Sub_Type__c</fullName>
        <description>This is the sub type of Order Line Item</description>
        <label>Order Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Order</fullName>
                </value>
                <value>
                    <fullName>Standard Return</fullName>
                </value>
                <value>
                    <fullName>Unplanned return</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetLineItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated asset line item.</description>
        <inlineHelpText>ID of the associated asset line item.</inlineHelpText>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AttributeValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated product attribute value</description>
        <label>Attribute Value</label>
        <referenceTo>Apttus_Config2__OrderProductAttributeValue__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__DerivedFromId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The ID of the line item this was derived from</description>
        <label>Derived From</label>
        <referenceTo>Apttus_Config2__LineItem__c</referenceTo>
        <relationshipLabel>Derived Order Line Items</relationshipLabel>
        <relationshipName>DerivedOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OrderId__c</fullName>
        <description>ID of the associated order</description>
        <inlineHelpText>ID of the associated order</inlineHelpText>
        <label>Order</label>
        <referenceTo>Apttus_Config2__Order__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>OrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OI-{0000000000}</displayFormat>
        <label>Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderProductAttributeValue__c.object
<CustomObject>
    <description>Represents the attribute values for a product class in a order line item</description>
    <fields>
        <fullName>APTS_Base_Price_Override_per_cup_FV__c</fullName>
        <label>Base Price Override per cup (Free Vend)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Base_Price_Override_per_cup__c</fullName>
        <label>Base Price Override per cup (Paid)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_List_Price_per_cup_FV__c</fullName>
        <label>List Price per cup (Free Vend)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_List_Price_per_cup__c</fullName>
        <label>List Price per cup (Paid)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>APTS_Type_of_Consumption__c</fullName>
        <label>Type of Consumption Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Free Vend</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Product Attribute Value</label>
    <nameField>
        <displayFormat>OA-{0000000000}</displayFormat>
        <label>Attribute Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Product Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__OrderUsagePriceTier__c.object
<CustomObject>
    <description>Represents a single entry in an order usage price tier</description>
    <fields>
        <fullName>Apttus_Config2__OrderLineItemId__c</fullName>
        <description>ID of the associated order line item</description>
        <inlineHelpText>ID of the associated order line item</inlineHelpText>
        <label>Order Line Item</label>
        <referenceTo>Apttus_Config2__OrderLineItem__c</referenceTo>
        <relationshipLabel>Order Usage Price Tiers</relationshipLabel>
        <relationshipName>OrderUsagePriceTiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__TierEndValue__c</fullName>
        <description>The tier end value</description>
        <inlineHelpText>The tier end value</inlineHelpText>
        <label>To</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__TierStartValue__c</fullName>
        <description>The tier start value</description>
        <inlineHelpText>The tier start value</inlineHelpText>
        <label>From</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Order Usage Price Tier</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Tier Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Usage Price Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_OrderUsagePriceTierTriggerHandler.cls
/**
* Class Name : APTS_OrderUsagePriceTierTriggerHandler
* Description : Populate From and To as per the assets so it doesnt get override
* Author : Karan Khatri
* Date Created : 10-08-2019
**/
public with sharing class APTS_OrderUsagePriceTierTriggerHandler implements ITriggerHandler{

    
    
    public void BeforeInsert(List<Apttus_Config2__OrderUsagePriceTier__c> newItems){
       List<Apttus_Config2__OrderUsagePriceTier__c> oliTierList = new List<Apttus_Config2__OrderUsagePriceTier__c>();
        Set<Id> oliIdList = new Set<Id>();
        Map<Id,id> assetIdMap = new Map<Id,id>();
        Map<Id,Decimal> usageRateFVMap = new Map<Id,Decimal>();
        Map<Id,Decimal> usageRatePaidMap = new Map<Id,Decimal>();
        Map<Id,Decimal> unitPriceFVMap = new Map<Id,Decimal>();
        Map<Id,Decimal> unitPricePaidMap = new Map<Id,Decimal>();
        Map<String,Apttus_Config2__AssetUsagePriceTier__c> assetUsageTierMap = new Map<String,Apttus_Config2__AssetUsagePriceTier__c>();
        For(Apttus_Config2__OrderUsagePriceTier__c oupt : newItems){
            oliIdList.add(oupt.Apttus_Config2__OrderLineItemId__c);
        }
        System.debug('oliIdList====>'+oliIdList);
        if(!oliIdList.isEmpty()){
            For(Apttus_Config2__OrderLineItem__c orderlineitem : [select id,
            Apttus_Config2__AssetLineItemId__c,
            Apttus_Config2__OrderId__r.APTS_Order_Type__c,
            Apttus_Config2__OrderId__r.APTS_Order_Sub_Type__c,
            Apttus_Config2__DerivedFromId__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup_FV__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup_FV__c,
            Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Type_of_Consumption__c 
            from Apttus_Config2__OrderLineItem__c where id IN: oliIdList]){
                if(orderlineitem.Apttus_Config2__OrderId__r.APTS_Order_Type__c.equalsIgnoreCase(APTS_OrderConstants.ADMIN_ORDER) && !orderlineitem.Apttus_Config2__OrderId__r.APTS_Order_Sub_Type__c.equalsIgnoreCase(APTS_BIRUtils.ORDERSUBTYPE)){
                    if(assetIdMap.get(orderlineitem.id)==null){
                        assetIdMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__AssetLineItemId__c);
                    }
                    System.debug('***BU***orderlineitem.orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r====>'+orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__c);
                    System.debug('***BU***Type of consumption====>'+orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Type_of_Consumption__c);
                    
                    if(orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__c!=null && orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Type_of_Consumption__c!=null){
                        if(usageRateFVMap.get(orderlineitem.id)==null && orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Type_of_Consumption__c.equalsIgnoreCase('Free Vend')){
                            if(orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup_FV__c!=null){
                                usageRateFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup_FV__c);
                            }else{
                                usageRateFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup_FV__c);
                            }
                            unitPriceFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup_FV__c);
                        }else if(usageRatePaidMap.get(orderlineitem.id)==null && orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Type_of_Consumption__c.equalsIgnoreCase('Paid')){
                            if(orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup__c!=null){
                                usageRatePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup__c);
                            }else{
                                usageRatePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup__c);
                            }
                            unitPricePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup__c);
                        }
                        else{
                            if(usageRateFVMap.get(orderlineitem.id)==null){
                                if(orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup_FV__c!=null){
                                    usageRateFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup_FV__c);
                                }else{
                                    usageRateFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup_FV__c);
                                }
                                unitPriceFVMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup_FV__c);
                            }
                            if(usageRatePaidMap.get(orderlineitem.id)==null){
                                if(orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup__c!=null){
                                    usageRatePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_Base_Price_Override_per_cup__c);
                                }else{
                                    usageRatePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup__c);
                                }
                                unitPricePaidMap.put(orderlineitem.id,orderlineitem.Apttus_Config2__DerivedFromId__r.Apttus_Config2__AttributeValueId__r.APTS_List_Price_per_cup__c);
                            }
                        }
                    }
                }
            }
        }
        System.debug('assetIdMap====>'+assetIdMap);
         if(!assetIdMap.isEmpty()){
            For(Apttus_Config2__AssetUsagePriceTier__c assetUsageTier : [select id,Apttus_Config2__TierStartValue__c, Apttus_Config2__TierEndValue__c,Apttus_Config2__Dimension1Value__c,Apttus_Config2__AssetLineItemId__c from Apttus_Config2__AssetUsagePriceTier__c where Apttus_Config2__AssetLineItemId__c IN: assetIdMap.values()]){
                System.debug('assetUsageTier====>'+assetUsageTier);
                if(assetUsageTier.Apttus_Config2__Dimension1Value__c!=null && assetUsageTier.Apttus_Config2__AssetLineItemId__c!=null && assetUsageTierMap.get(assetUsageTier.Apttus_Config2__Dimension1Value__c+assetUsageTier.Apttus_Config2__AssetLineItemId__c)==null){
                    assetUsageTierMap.put(assetUsageTier.Apttus_Config2__Dimension1Value__c+assetUsageTier.Apttus_Config2__AssetLineItemId__c,assetUsageTier);
                }
            }
        }
        System.debug('usageRatePaidMap====>'+usageRatePaidMap);
        System.debug('assetUsageTierMap====>'+assetUsageTierMap);
        System.debug('usageRateFVMap====>'+usageRateFVMap);
        if(!assetUsageTierMap.isEmpty() && !assetIdMap.isEmpty()){
            For(Apttus_Config2__OrderUsagePriceTier__c oupt : newItems){    
                
                if(oupt.Apttus_Config2__Dimension1Value__c!=null && assetIdMap.get(oupt.Apttus_Config2__OrderLineItemId__c)!=null && assetUsageTierMap.get(oupt.Apttus_Config2__Dimension1Value__c+assetIdMap.get(oupt.Apttus_Config2__OrderLineItemId__c))!=null){
                    oupt.Apttus_Config2__TierStartValue__c=assetUsageTierMap.get(oupt.Apttus_Config2__Dimension1Value__c+assetIdMap.get(oupt.Apttus_Config2__OrderLineItemId__c)).Apttus_Config2__TierStartValue__c;
                    oupt.Apttus_Config2__TierEndValue__c=assetUsageTierMap.get(oupt.Apttus_Config2__Dimension1Value__c+assetIdMap.get(oupt.Apttus_Config2__OrderLineItemId__c)).Apttus_Config2__TierEndValue__c;
                    if(oupt.Apttus_Config2__Dimension1Value__c.equalsIgnoreCase('Free Vend') && !usageRateFVMap.isEmpty() && usageRateFVMap.get(oupt.Apttus_Config2__OrderLineItemId__c)!=null && !unitPriceFVMap.isEmpty() && unitPriceFVMap.get(oupt.Apttus_Config2__OrderLineItemId__c)!=null){
                        oupt.Apttus_Config2__AdjustmentAmount__c = usageRateFVMap.get(oupt.Apttus_Config2__OrderLineItemId__c);
                        oupt.Apttus_Config2__UsageRate__c = unitPriceFVMap.get(oupt.Apttus_Config2__OrderLineItemId__c);
                    }
                    if(oupt.Apttus_Config2__Dimension1Value__c.equalsIgnoreCase('Paid') && !usageRatePaidMap.isEmpty() && usageRatePaidMap.get(oupt.Apttus_Config2__OrderLineItemId__c)!=null && !unitPricePaidMap.isEmpty() && unitPricePaidMap.get(oupt.Apttus_Config2__OrderLineItemId__c)!=null){
                        oupt.Apttus_Config2__AdjustmentAmount__c = usageRatePaidMap.get(oupt.Apttus_Config2__OrderLineItemId__c);
                        oupt.Apttus_Config2__UsageRate__c = unitPricePaidMap.get(oupt.Apttus_Config2__OrderLineItemId__c);
                    }
                }
            }
        }
    }
    public void BeforeUpdate(List<Apttus_Config2__OrderUsagePriceTier__c> newItems, Map<Id, SObject> newItemsMap, List<SObject> oldList, Map<Id, SObject> oldItemsMap){
       
    }
    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){
    
    }
    public void AfterInsert(List<Apttus_Config2__OrderUsagePriceTier__c> newItems, Map<Id, SObject> newItemsMap){
        
    }
    
    public void AfterUpdate(List<SObject> newList, Map<Id, SObject> newItems, List<SObject> oldList, Map<Id, SObject> oldItems){}
 
    public void AfterDelete(List<SObject> oldList, Map<Id, SObject> oldItems){}
 
    public void AfterUndelete(List<SObject> newList, Map<Id, SObject> newItems){}
    
    public Boolean IsDisabled(){
        return (TriggerSettings__c.getInstance().APTS_OrderUsagePriceTierTrigger__c == true ? false : true);
    }
}