src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductConfiguration__c.object
<CustomObject>
    <description>Represents a product configuration</description>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the agreement associated with the configuration</description>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Configurations</relationshipLabel>
        <relationshipName>Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Status__c</fullName>
        <description>The current status of the configuration</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Ready For Approvals</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>In Collaboration</fullName>
                </value>
                <value>
                    <fullName>Ready For Finalization</fullName>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CERDiscountCache__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Configuration__c</fullName>
        <label>Configuration</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CER Discount Cache</label>
</CustomObject>

src/classes/APTS_cerCachceleanupBatch.cls
global class APTS_cerCachceleanupBatch implements Database.Batchable<sObject> {
     global Database.QueryLocator start(Database.BatchableContext BC) {
             //String  fullQueryString =  'select id,name,Configuration__c, Name__c,Sub_Type__c from CERDiscountCache__c where Configuration__c IN:configiddellist limit 50000';
             set<id> configidfull=new set<id>();
             set<id> configiddellist=new set<id>();
             for(CERDiscountCache__c cer:[select id,name,Configuration__c, Name__c,Sub_Type__c from CERDiscountCache__c limit 50000]){
             configidfull.add(cer.Configuration__c);
             }
             system.debug('++configidfull+++'+configidfull);
             list<Apttus_Config2__ProductConfiguration__c > configlist=[select id,Apttus_Config2__Status__c,Apttus_CMConfig__AgreementId__r.Apttus__Status_Category__c,Apttus_CMConfig__AgreementId__r.Apttus__Status__c from Apttus_Config2__ProductConfiguration__c where id IN:configidfull];
             for(Apttus_Config2__ProductConfiguration__c pc:[select id,Apttus_Config2__Status__c,Apttus_CMConfig__AgreementId__r.Apttus__Status_Category__c,Apttus_CMConfig__AgreementId__r.Apttus__Status__c from Apttus_Config2__ProductConfiguration__c where id IN:configidfull]){
             if(pc.Apttus_CMConfig__AgreementId__r.Apttus__Status__c=='Cancelled Request'||
             pc.Apttus_CMConfig__AgreementId__r.Apttus__Status__c=='Superseded' ||
             pc.Apttus_CMConfig__AgreementId__r.Apttus__Status__c=='Expired' ||
             pc.Apttus_CMConfig__AgreementId__r.Apttus__Status__c=='Terminated'){
             configiddellist.add(pc.Id); 
             }
             else if(pc.Apttus_Config2__Status__c=='Superseded'||
             pc.Apttus_Config2__Status__c=='Finalized'){
             configiddellist.add(pc.Id);
             }
             }
             system.debug('++configiddellist+++'+configiddellist);
             String  fullQueryString='select id,Apttus_Config2__Status__c,Apttus_CMConfig__AgreementId__r.Apttus__Status_Category__c,Apttus_CMConfig__AgreementId__r.Apttus__Status__c from Apttus_Config2__ProductConfiguration__c where id IN:configiddellist';
             system.debug('++fullQueryString+++'+fullQueryString);
             return Database.getQueryLocator(fullQueryString);
             }
             
     global void execute(Database.BatchableContext BC, List<sObject> scope) {
      system.debug('++debug_cache+++'+scope);
      list<id> deleteCERCachedel=new list<Id>();
      list<CERDiscountCache__c> deleteCERCachedel1=new list<CERDiscountCache__c>();
      list<Apttus_Config2__ProductConfiguration__c> newlist=(List<Apttus_Config2__ProductConfiguration__c>)scope;
      for(Apttus_Config2__ProductConfiguration__c pr:newlist){
      deleteCERCachedel.add(pr.Id);
      }
      deleteCERCachedel1=[select id from CERDiscountCache__c where Configuration__c IN:deleteCERCachedel];
         if(deleteCERCachedel1.size()>0){
         Delete deleteCERCachedel1;
         }
         
     
     } 
       global void finish(Database.BatchableContext BC) {}
}