src/objects/Apttus_Config2__ClassificationHierarchy__c.object
<CustomObject>
    <description>Represents a category hierarchy</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductHierarchyView__c.object
<CustomObject>
    <description>Represents a denormalized (materialized) view of product and classification hierarchies</description>
    <fields>
        <fullName>Apttus_Config2__ChildProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the child product</description>
        <label>Child Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Hierarchy View</relationshipLabel>
        <relationshipName>ProductHierarchyView</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ParentClassificationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the parent category</description>
        <label>Parent Category</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Hierarchy View (Parent)</relationshipLabel>
        <relationshipName>HierarchyView</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Hierarchy View</label>
    <nameField>
        <displayFormat>PV-{0000000000}</displayFormat>
        <label>View Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy Views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/APTS_DummyApttusBatch.cls
/*
Class Owner - Lavanya 
Dexcription - Apex class that identifies the Products with wrong hierarchies untill Apttus Category OOB Batch works as expected.
*/

global class APTS_DummyApttusBatch implements Database.Batchable<sObject>,Database.Stateful{

public Map<Id,Set<String>> mapProductHierarchy = new Map<Id,Set<String>>();
/** Method Name : start
    * Description : start method of Batch class
    **/
    global Database.QueryLocator start(Database.BatchableContext batchContext){
    String query = 'Select Apttus_Config2__ChildProductId__c,Apttus_Config2__ParentClassificationId__r.Name,Apttus_Config2__ParentClassificationId__c from Apttus_Config2__ProductHierarchyView__c';
        return Database.getQueryLocator(query);
    }
    
    /** Method Name : execute
    * Description : execute method of Batch class
    **/
    global void execute(Database.BatchableContext batchContext, List<Apttus_Config2__ProductHierarchyView__c> records){
    for(Apttus_Config2__ProductHierarchyView__c instView : records){
   
                        if(instView.Apttus_Config2__ChildProductId__c != NULL && instView.Apttus_Config2__ParentClassificationId__c != NULL)
    {
if(mapProductHierarchy.containskey(instView.Apttus_Config2__ChildProductId__c))
                        {
                           Set<String> setView = new Set<String>();
                            setView = mapProductHierarchy.get(instView.Apttus_Config2__ChildProductId__c);
                            setView.add(instView.Apttus_Config2__ParentClassificationId__r.Name);
                            mapProductHierarchy.put(instView.Apttus_Config2__ChildProductId__c,setView);                            
                            
                        }
                        else
                        {
                             Set<String> setView = new Set<String>();
                             setView.add(instView.Apttus_Config2__ParentClassificationId__r.Name);
                             mapProductHierarchy.put(instView.Apttus_Config2__ChildProductId__c,setView);
                        } 
    }


                                            
}
                                            
  }    
        
         global void finish(Database.BatchableContext batchContext){

for(Id instProdId : mapProductHierarchy.keySet())
{
    Set<String> setView = new Set<String>();
    List<String> newString = new List<String>();
    setView = mapProductHierarchy.get(instProdId);    
    newString.addAll(setView);
    if(setView.size()>1)
   APTS_CustomLogging.createErrorLog('Hierarchy Updated','Apex',instProdId,newString[0],null,'CPQ',false,false,null,true);
   
}

}
}