src/objects/Apttus_Config2__ClassificationHierarchy__c.object
<CustomObject>
    <description>Represents a category hierarchy</description>
    <label>Category Hierarchy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ClassificationName__c.object
<CustomObject>
    <description>Represents a category</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductClassification__c.object
<CustomObject>
    <description>Represents a product classification which is a member of the list of products associated with a classification.</description>
    <label>Product Classification</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Classification Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductOptionComponent__c.object
<CustomObject>
    <description>Represents a product option component which is a member of the list of options associated with a product.option group</description>
    <fields>
        <fullName>APTS_Cross_plant_material_status__c</fullName>
        <formula>Apttus_Config2__ComponentProductId__r.APTS_Cross_plant_material_status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cross-plant material status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ParentProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the parent product</description>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option Component</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Option Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__ProductOptionGroup__c.object
<CustomObject>
    <description>Represents a product option group which is a member of the list of option groups associated with a product.</description>
    <fields>
        <fullName>Apttus_Config2__ParentOptionGroupId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the parent option group</description>
        <label>Parent Option Group</label>
        <referenceTo>Apttus_Config2__ClassificationHierarchy__c</referenceTo>
        <relationshipLabel>Child Option Groups</relationshipLabel>
        <relationshipName>ChildOptionGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Option Group</label>
    <nameField>
        <displayFormat>PG-{0000000000}</displayFormat>
        <label>Option Group Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Option Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BizIsland_Request__c.object
<CustomObject>
    <label>BizIsland Request</label>
    <nameField>
        <label>BizIsland Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BizIslandRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bonsai__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Delta_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delta Load</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Load__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Load</label>
        <type>Checkbox</type>
    </fields>
    <label>Bonsai Extraction Controller</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Associated_Sales_Org__c</fullName>
        <label>Associated Sales Org</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>APTS_Cross_plant_material_status__c</fullName>
        <label>Cross-plant material status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Sales_Catalog__c</fullName>
        <description>Concatenated code for Category, Sub-category and sub-sub category</description>
        <label>Sales Catalog</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ConfigurationType__c</fullName>
        <description>The product configuration type</description>
        <label>Configuration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standalone</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Uom__c</fullName>
        <description>The default unit of measure for the product</description>
        <label>Uom</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_EA</fullName>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>SAP_BX</fullName>
                    <label>Box</label>
                </value>
                <value>
                    <fullName>SAP_CS</fullName>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>SAP_PCE</fullName>
                    <label>Piece</label>
                </value>
                <value>
                    <fullName>SAP_PF</fullName>
                    <label>Pallet</label>
                </value>
                <value>
                    <fullName>SAP_GRM</fullName>
                    <label>Gram</label>
                </value>
                <value>
                    <fullName>SAP_KGM</fullName>
                    <label>Kilogram</label>
                </value>
                <value>
                    <fullName>SAP_LR</fullName>
                    <label>Layer</label>
                </value>
                <value>
                    <fullName>SAP_ZRE</fullName>
                    <label>Reporting</label>
                </value>
                <value>
                    <fullName>SAP_ZTU</fullName>
                    <label>Trade unit</label>
                </value>
                <value>
                    <fullName>SAP_LTR</fullName>
                    <label>Liter</label>
                </value>
                <value>
                    <fullName>SAP_ZVW</fullName>
                    <label>Vol.weight</label>
                </value>
                <value>
                    <fullName>SAP_ZZZ</fullName>
                    <label>St. UoM IB</label>
                </value>
                <value>
                    <fullName>SAP_PY1</fullName>
                    <label>HAP120*100</label>
                </value>
                <value>
                    <fullName>SAP_PX1</fullName>
                    <label>HAP120*80</label>
                </value>
                <value>
                    <fullName>SAP_PY2</fullName>
                    <label>FUP120*100</label>
                </value>
                <value>
                    <fullName>SAP_LZ</fullName>
                    <label>LAY120*80</label>
                </value>
                <value>
                    <fullName>SAP_LY</fullName>
                    <label>LAY120*100</label>
                </value>
                <value>
                    <fullName>SAP_SMU</fullName>
                    <label>Smallest Unit</label>
                </value>
                <value>
                    <fullName>SAP_MTR</fullName>
                    <label>Meter</label>
                </value>
                <value>
                    <fullName>SAP_ZQH</fullName>
                    <label>Quarter of Hour</label>
                </value>
                <value>
                    <fullName>SAP_PX2</fullName>
                    <label>FUP120*80</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_ProductBizIslandlevelTest.cls
/**************************************************************
* @Author: saranya.a.rajagopal
* @Company: Accenture
* @Description: Test class for  APTS_ProductBizIslandlevel
* @Created Date: OCT 10, 2018
* @Revisions:
*      <Name>                  <Date>          <Description>
*      saranya.a.rajagopal      Oct 10, 2018    Initial Version
* 
*************************************************************/
@isTest
private class APTS_ProductBizIslandlevelTest {

     @testSetup
     static void testData(){
     
            Account acc = APTS_TestDataFactory.createAccount('testAccount');
            acc.APTS_BizIsland_Bonsai_Account__c=true;
            Database.insert(acc);
            
            Product2 prod1 = APTS_TestDataFactory.createProduct('TestProduct','test1000','Coffee', 'Option', FALSE, TRUE);
            prod1.APTS_Associated_Sales_Org__c= 'SAP_0975';
            prod1.APTS_Cross_plant_material_status__c= 'PR';
            prod1.APTS_Sales_Catalog__c = '1234';
            prod1.Apttus_Config2__Uom__c = 'SAP_EA';
            prod1.Apttus_Config2__ConfigurationType__c='Option';
            prod1.Family='SAP_01';
            Database.insert(prod1);
            
            Apttus_Config2__ClassificationName__c catego = APTS_TestDataFactory.createCategory();
            Database.insert(catego);
            
            Apttus_Config2__ClassificationHierarchy__c catehi = APTS_TestDataFactory.createCategoryHierarchy(catego.id, 'test');
            Database.insert(catehi);
            
            Apttus_Config2__ClassificationHierarchy__c catSub = APTS_TestDataFactory.createSubCategory(catego.id,catehi.id);
            Database.insert(catSub); 
              
            Apttus_Config2__ProductOptionGroup__c optionGr = APTS_TestDataFactory.createProductOptionGroup(catehi.id,catSub.id);
            optionGr.Apttus_Config2__ParentOptionGroupId__c =catehi.id;
            Database.insert(optionGr);
            
            Apttus_Config2__ProductOptionComponent__c produOp = APTS_TestDataFactory.createProductOptionComponent(optionGr.id);
            produOp.Apttus_Config2__ParentProductId__c= prod1.id;
            Database.insert (produOp);
            
            Apttus_Config2__ProductClassification__c classpr = APTS_TestDataFactory.createProductClassification(catsub.id,prod1.id);
            Database.insert(classpr);
            
            Bonsai__c customSetting = new Bonsai__c();
            customSetting.Name = 'test';
            customSetting.Delta_Load__c = true;
            customSetting.Full_Load__c = true;
            insert customSetting;
        
            BizIsland_Request__c bizland = new BizIsland_Request__c();
            bizland.name = 'Bonsai Request '+Date.Today();
            Database.insert(bizland);
            
        }
          @isTest
        static void testElseBatch(){
        Bonsai__c customSetting = Bonsai__c.getAll().values();
        customSetting.Delta_Load__c = false;
        customSetting.Full_Load__c = true;
        update customSetting;
       
        Test.startTest();
        APTS_AccountBizIsland accountBizbatch = new APTS_AccountBizIsland();
        Database.executeBatch(accountBizbatch,200);
        Test.stopTest();
    }
        
       @isTest
        static void testBatch(){
            Test.startTest();
            APTS_ProductBizIslandlevel  productBizbatchlevel = new APTS_ProductBizIslandlevel ();
            Database.executeBatch(productBizbatchlevel, 200);
            Test.stopTest();
       }
}