src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Fixed_Term_Type__c</fullName>
        <description>Type of fixed term</description>
        <label>Fixed Term Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Cost</fullName>
                </value>
                <value>
                    <fullName>All Ingredients</fullName>
                </value>
                <value>
                    <fullName>Fixed Costs and Ingredients</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated price list</description>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Agreement_Category__c</fullName>
        <description>Used to categorize agreement types.  When setting up a new agreement type make sure to seect approrpiate values for that agreement type and to set the right default</description>
        <label>Agreement Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Agreement_Number__c</fullName>
        <description>FOR INTERNAL USE ONLY. DO NOT USE IN SCREENS, REPORTS, ETC.</description>
        <label>Agreement Number_Num (INTERNAL)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Consumption</fullName>
        <active>true</active>
        <label>Consumption Model</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Amendment_Effective_Date__c</fullName>
        <label>Amendment Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Asset_Validaton_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset Validation Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Is_Primary_L1_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Is Primary L1 Asset</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Line Items (Is Primary L1 Asset)</relationshipLabel>
        <relationshipName>Primary_L1_Asset_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Asset Line Items (Physical Asset)</relationshipLabel>
        <relationshipName>Asset_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Type_Of_Contract__c</fullName>
        <label>Type Of Contract</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>RentBuy</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Free On Loan</fullName>
                </value>
                <value>
                    <fullName>Consumption</fullName>
                    <label>Consumption Model</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BasePrice__c</fullName>
        <description>The base price is List price + Automatic Adjustments for individual products and options</description>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BillingStartDate__c</fullName>
        <description>The billing start date. Also known as the first billing period end date.</description>
        <inlineHelpText>The billing start date. Also known as the first billing period end date.</inlineHelpText>
        <label>Billing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ChargeType__c</fullName>
        <description>The charge type  associated with the product or service</description>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rental Fee</fullName>
                </value>
                <value>
                    <fullName>Usage Fee</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Additional Service Fee</fullName>
                </value>
                <value>
                    <fullName>Sales Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__EndDate__c</fullName>
        <description>The end date for products and services</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__IsPrimaryLine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the line is the primary line for the product or option</description>
        <label>Is Primary Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type.</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ListPrice__c</fullName>
        <description>The list price for the product or service with no adjustments</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__OriginalStartDate__c</fullName>
        <description>The original start date associated with the asset</description>
        <inlineHelpText>The original start date associated with the asset</inlineHelpText>
        <label>Original Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>Apttus_Config2__PriceList__c</referenceTo>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the selected product or service</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__Quantity__c</fullName>
        <description>The product or service quantity</description>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__SellingTerm__c</fullName>
        <description>The selling term associated with the product or service</description>
        <label>Selling Term</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__StartDate__c</fullName>
        <description>The start date for products and services</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>InitialActivationDate__c</fullName>
        <label>Initial Activation Date</label>
        <type>Date</type>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Option</fullName>
        <active>true</active>
        <label>Option</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Option_Group_Indicator__c</fullName>
        <label>Option Group Indicator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RTR_LAE_Staging_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship field with physical asset object</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>RTR-LAE Staging Data</relationshipLabel>
        <relationshipName>APTS_RTR_LAE_Staging_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RTR-LAE Staging Data</label>
    <nameField>
        <displayFormat>AIL-{00000000}</displayFormat>
        <label>RTR-LAE Staging Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTR-LAE Staging Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_UpdateFinancialStartDateQueueTest.cls
/*************************************************************
@Name: APTS_UpdateFinancialStartDateQueueable
@Author: Mahesh Chilaka
@CreateDate: 09-09-2020
@Description: DQ-369 - This queueable job is used to updated the FinancialStartDate on Assets when an Asset Movement successfully moved to RAR/LAE (SAP).
@UsedBy: 
******************************************************************/
@isTest
private  class APTS_UpdateFinancialStartDateQueueTest {
    
    @testSetup
    static void testSetup(){
        Account account = APTS_TestUtils.createaccount();
            account.Duplicate_Reason__c = 'Office building';
        account.Mini_Company_Code__c = 'SAP_0079';    
            Database.insert(account);
    
            account.SAP_Customer_ID__c = '2423';
        account.Distribution_Channel__c = 'SAP_10';
        account.Sales_Organization__c = 'SAP_0111';
            Database.update(account);
        
        Product2 prod = APTS_TestUtils.createProduct('Test Product', 'P-0001', 'SAP_01');
            Database.insert(prod);
        prod.APTS_Option_Group_Indicator__c = '0102';
        update prod;
        
        Apttus_Config2__PriceList__c prcLst = APTS_TestUtils.createPriceList(); 
            Database.insert(prcLst);
        
        Apttus__APTS_Agreement__c agreement = new Apttus__APTS_Agreement__c(recordtypeid = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Consumption Model').getRecordTypeId(),
            Name = 'Agreement',
            Apttus__Agreement_Category__c = 'Sales',
            Apttus_CMConfig__PriceListId__c = prcLst.Id,
            APTS_Fixed_Term_Type__c = 'Fixed Cost', Apttus__Agreement_Number__c = '1124');
        
            insert agreement;
        
        Apttus__APTS_Agreement__c agreement2 = new Apttus__APTS_Agreement__c(recordtypeid = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get('Consumption Model').getRecordTypeId(),
            Name = 'Agreement',
            Apttus__Agreement_Category__c = 'Sales',
            Apttus_CMConfig__PriceListId__c = prcLst.Id,
            APTS_Fixed_Term_Type__c = 'Fixed Cost');
            insert agreement2;
        
        PhysicalAsset__c testPhysicalAsset = APTS_TestUtils.createPhysicalAsset();
            testPhysicalAsset.InitialActivationDate__c = Date.today().addDays(-30);    
            Database.insert(testPhysicalAsset, false);
    
    
    
            // Assert APTS_Is_Primary_L1_Asset__c       
            Map<Id, Apttus_Config2__AssetLineItem__c> mapAssetLineItem = new Map<Id, Apttus_Config2__AssetLineItem__c>();  
            List<Apttus_Config2__AssetLineItem__c> listAssetLineItem_PriL1 = new List <Apttus_Config2__AssetLineItem__c>();    
        for(integer i=0; i<10; i++){
          Apttus_Config2__AssetLineItem__c tstAssetPos = new Apttus_Config2__AssetLineItem__c();
          tstAssetPos.Apttus_Config2__StartDate__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__EndDate__c = Date.today().addDays(-2);
          tstAssetPos.APTS_Amendment_Effective_Date__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__OriginalStartDate__c = Date.today();
          if(math.mod(i, 2) == 0) {
          tstAssetPos.Apttus_Config2__ChargeType__c = 'Sales Price';
          }else {
          tstAssetPos.Apttus_Config2__ChargeType__c = 'Service Fee';
          }
          tstAssetPos.Apttus_CMConfig__AgreementId__c = agreement.id;
          tstAssetPos.APTS_Physical_Asset__c = testPhysicalAsset.id;
          tstAssetPos.Apttus_Config2__LineType__c = 'Product/Service';
          tstAssetPos.APTS_Type_Of_Contract__c = 'Rent';
          tstAssetPos.APTS_Asset_Validaton_Error__c = false;
          tstAssetPos.Apttus_Config2__IsPrimaryLine__c  = true;
          tstAssetPos.Apttus_Config2__BasePrice__c = 10.00;
          tstAssetPos.Apttus_Config2__Quantity__c = 10;
          tstAssetPos.Apttus_Config2__SellingTerm__c = 1;
          tstAssetPos.Apttus_Config2__ListPrice__c = 10.00;      
          tstAssetPos.Apttus_Config2__AccountId__c = account.Id;
          tstAssetPos.Apttus_Config2__ProductId__c = prod.Id;
          tstAssetPos.Apttus_Config2__BillingStartDate__c = Date.today();
          tstAssetPos.Apttus_Config2__PriceListId__c = prcLst.Id;
          tstAssetPos.Apttus_Config2__AssetStatus__c = 'Pending Activation';   
          
          listAssetLineItem_PriL1.add(tstAssetPos);
                
        }
    
            insert listAssetLineItem_PriL1;
    
        
        // New Asset creation for Sales/Rent
        List<Apttus_Config2__AssetLineItem__c> listAssetLineItem = new List <Apttus_Config2__AssetLineItem__c>();
        List<Apttus_Billing__BillingSchedule__c> bs = new List<Apttus_Billing__BillingSchedule__c>();
        List<Apttus_Config2__AssetTransactionHistory__c> lstALIHis = new List<Apttus_Config2__AssetTransactionHistory__c>();
        List<RTR_LAE_Transaction_Data__c> lstTransData = new List<RTR_LAE_Transaction_Data__c>();
        List<RTR_LAE_Staging_Data__c> lstStagingData = new List<RTR_LAE_Staging_Data__c>();
        for(integer i=0; i<10; i++){
          Apttus_Config2__AssetLineItem__c tstAssetPos = new Apttus_Config2__AssetLineItem__c();
          tstAssetPos.Apttus_Config2__StartDate__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__EndDate__c = Date.today().addDays(-2);
          tstAssetPos.APTS_Amendment_Effective_Date__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__OriginalStartDate__c = Date.today();
          if(math.mod(i, 2) == 0) {
          tstAssetPos.Apttus_Config2__ChargeType__c = 'Sales Price';
          }else {
          tstAssetPos.Apttus_Config2__ChargeType__c = 'Service Fee';
          }
          tstAssetPos.Apttus_CMConfig__AgreementId__c = agreement.id;
          tstAssetPos.APTS_Physical_Asset__c = testPhysicalAsset.id;
          tstAssetPos.Apttus_Config2__LineType__c = 'Option';
          tstAssetPos.APTS_Type_Of_Contract__c = 'Rent';
          tstAssetPos.APTS_Asset_Validaton_Error__c = false;
          tstAssetPos.Apttus_Config2__IsPrimaryLine__c  = true;
          tstAssetPos.Apttus_Config2__BasePrice__c = 10.00;
          tstAssetPos.Apttus_Config2__Quantity__c = 10;
          tstAssetPos.Apttus_Config2__SellingTerm__c = 1;
          tstAssetPos.Apttus_Config2__ListPrice__c = 10.00;
          //tstAssetPos.APTS_MigrationDate__c = Date.today().addDays(-1);
                tstAssetPos.APTS_Is_Primary_L1_Asset__c = listAssetLineItem_PriL1[i].Id;
          tstAssetPos.Apttus_Config2__AccountId__c = account.Id;
          tstAssetPos.Apttus_Config2__ProductId__c = prod.Id;
          tstAssetPos.Apttus_Config2__BillingStartDate__c = Date.today();
          tstAssetPos.Apttus_Config2__PriceListId__c = prcLst.Id;
          tstAssetPos.Apttus_Config2__AssetStatus__c = 'Pending Activation';   
          
          listAssetLineItem.add(tstAssetPos);
        }
        
        for(integer i=0; i<10; i++){
          Apttus_Config2__AssetLineItem__c tstAssetPos = new Apttus_Config2__AssetLineItem__c();
          tstAssetPos.Apttus_Config2__StartDate__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__EndDate__c = Date.today().addDays(-2);
          tstAssetPos.APTS_Amendment_Effective_Date__c = Date.today().addDays(-1);
          tstAssetPos.Apttus_Config2__OriginalStartDate__c = Date.today();
          tstAssetPos.Apttus_Config2__ChargeType__c = 'Rental Fee';
          tstAssetPos.Apttus_CMConfig__AgreementId__c = agreement.id;
          tstAssetPos.APTS_Physical_Asset__c = testPhysicalAsset.id;
          tstAssetPos.Apttus_Config2__LineType__c = 'Product/Service';
          tstAssetPos.APTS_Type_Of_Contract__c = 'Rent';
          tstAssetPos.APTS_Is_Primary_L1_Line__c = true;
          tstAssetPos.APTS_Asset_Validaton_Error__c = false;
          tstAssetPos.Apttus_Config2__IsPrimaryLine__c  = true;
          tstAssetPos.Apttus_Config2__BasePrice__c = 10.00;
          tstAssetPos.Apttus_Config2__Quantity__c = 10;
          tstAssetPos.Apttus_Config2__SellingTerm__c = 1;
          tstAssetPos.Apttus_Config2__ListPrice__c = 10.00;
          //tstAssetPos.APTS_MigrationDate__c = Date.today().addDays(-1);
                tstAssetPos.APTS_Is_Primary_L1_Asset__c = listAssetLineItem_PriL1[i].Id;
          tstAssetPos.Apttus_Config2__AccountId__c = account.Id;
          tstAssetPos.Apttus_Config2__ProductId__c = prod.Id;
          tstAssetPos.Apttus_Config2__BillingStartDate__c = Date.today();
          tstAssetPos.Apttus_Config2__PriceListId__c = prcLst.Id;
          tstAssetPos.Apttus_Config2__AssetStatus__c = 'Pending Activation';  
          
          listAssetLineItem.add(tstAssetPos);
        }
        
        insert listAssetLineItem;
    
            for(Apttus_config2__AssetLineItem__c tstAssetPos : listAssetLineItem){
          
          tstAssetPos.Apttus_Config2__AssetStatus__c = 'Activated';  
          
          Apttus_Billing__BillingSchedule__c bilScdl = new Apttus_Billing__BillingSchedule__c ();
          //bilScdl.Apttus_Billing__BillToAccountId__c = account0.Id;
          //bilScdl.Apttus_Billing__AssetLineItemId__c = tstAssetPos.APTS_Is_Primary_L1_Asset__c;
                bilScdl.Apttus_Billing__AssetLineItemId__c = tstAssetPos.Id;
          bilScdl.APTS_AddToExternalOrderlineItem__c = false;
          bilScdl.Apttus_Billing__FeeAmount__c = 250;
          //bilScdl.Apttus_Billing__ShipToAccountId__c = account0.Id;
          bilScdl.Apttus_Billing__Type__c = 'Contracted';
          bilScdl.Apttus_Billing__Status__c = 'Pending Invoiced';
          bilScdl.Apttus_Billing__PeriodStartDate__c = System.today();
          bilScdl.Apttus_Billing__PeriodEndDate__c = System.today() + 15;
          //insert bilScdl;
          bs.add(bilScdl);
          
          Apttus_Config2__AssetTransactionHistory__c newH = new Apttus_Config2__AssetTransactionHistory__c();
          newH.Apttus_Config2__AssetLineItemId__c = tstAssetPos.Id;
          newH.Apttus_Config2__Action__c = 'New';
          lstALIHis.add(newH);
          
          RTR_LAE_Transaction_Data__c testData = new RTR_LAE_Transaction_Data__c();
          testData.APTS_Asset_Line_Item__c = tstAssetPos.Id;
          testData.APTS_Business_Transaction_Type__c = '0001';
          testData.APTS_Contract_Effective_Date__c = Date.today();
                testData.APTS_Controlled_Interface_Flag__c = false;
          lstTransData.add(testData);
                mapAssetLineItem.put(tstAssetPos.Id, tstAssetPos);
                
            RTR_LAE_Staging_Data__c sd = new RTR_LAE_Staging_Data__c();
            sd.APTS_Start_Date__c = System.Today();
            sd.APTS_Asset_Line_Item__c = tstAssetPos.Id;
            sd.APTS_Business_Transaction_Type__c = 'B005';
            sd.APTS_Integration_Log_Id__c = '123456789';
            lstStagingData.add(sd);
        }
         
         
         insert bs;
         insert lstALIHis;
         update listAssetLineItem;
         insert lstTransData;
         insert lstStagingData;

        
    }

    static testMethod void updateFinancialStartDate() {
        Test.startTest();
        Date todayDate = System.Today();

        List<RTR_LAE_Staging_Data__c> listStagingData = [SELECT Id FROM RTR_LAE_Staging_Data__c 
                                                         WHERE APTS_Integration_Log_Id__c != null 
                                                        AND APTS_Asset_Line_Item__c != null
                                                        AND APTS_Business_Transaction_Type__c = 'B005'
                                                        AND APTS_isFinancialStartDateUpdated__c = false
                                                        AND CreatedDate >=: todayDate];
        
        System.AssertEquals( 20, listStagingData.size()) ;
        System.enqueueJob(new APTS_UpdateFinancialStartDateQueueable());
        Test.stopTest();
    }

}