src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>APTS_Order_Non_Contracted_Products__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Order Non-Contracted Products?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__Auto_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the agreement has an auto renewal provision</description>
        <label>Auto Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account associated with the price list</description>
        <inlineHelpText>ID of the account associated with the price list</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Main_Commercial_Person__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Main Commercial Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Touchpoint_Type__c</fullName>
        <label>Touchpoint Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_TouchpointType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Inbound</fullName>
        <active>true</active>
        <description>Record type for manual creation of task</description>
        <label>Inbound</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>ContentDocumentLinkTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ContentDocumentLinkTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/ContentDocumentLinkTriggerHandler_Test.cls
@isTest
public class ContentDocumentLinkTriggerHandler_Test {
    private static testMethod void taskwithaccount(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        Id serviceRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Inbound').getRecordTypeId();
        
        Task taskRec = new Task();
        taskRec.WhatId = acc.Id;
        taskRec.RecordTypeId = serviceRecordTypeId;
        taskRec.Touchpoint_Type__c = 'Inbound Call';
            
        insert taskRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = taskRec.Id;
        insert notes;
        
        ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(newnote.LinkedEntityId, acc.Id);
    }
    
    private static testMethod void contactwithaccount(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        
        Contact conRec = new Contact();
        conRec.FirstName = 'Test';
        conRec.LastName = 'Test';
        conRec.AccountId = acc.id;
        conRec.Phone = '+31302979111';
        conRec.Main_Commercial_Person__c = True;
        conRec.MobilePhone = '+31302979122';
            
        insert conRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = conRec.Id;
        insert notes;
        
        ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(newnote.LinkedEntityId, acc.Id);
    }
    
    private static testMethod void opportunitywithaccount(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'oppName';
        opp.AccountId = acc.id;
        opp.CLoseDate = Date.Today();
        opp.StageName = 'Open';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SM_Constants.OppStandardRT).getRecordTypeId();
            
        insert opp;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = opp.Id;
        insert notes;
        
        ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(newnote.LinkedEntityId, acc.Id);
    }
     private static testMethod void eventwithaccount(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        
        Event eventRec = new Event();
        eventRec.WhatId = acc.Id;
        eventRec.Touchpoint_Type__c = 'Inbound Call';
        eventRec.StartDateTime = System.Now();
        eventRec.EndDateTime = System.Now() + 1;
            
        insert eventRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = eventRec.Id;
        insert notes;
        
        ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(newnote.LinkedEntityId, acc.Id);
    }
    
    private static testMethod void eventwithoppty(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'oppName';
        opp.AccountId = acc.id;
        opp.CLoseDate = Date.Today();
        opp.StageName = 'Open';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SM_Constants.OppStandardRT).getRecordTypeId();
        
        insert opp;
        
        Event eventRec = new Event();
        eventRec.WhatId = opp.Id;
        eventRec.Touchpoint_Type__c = 'Inbound Call';
        eventRec.StartDateTime = System.Now();
        eventRec.EndDateTime = System.Now() + 1;
            
        insert eventRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = eventRec.Id;
        insert notes;
        
        // ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(opp.AccountId, acc.Id);
        
        ContentDocumentLink notes1 = new ContentDocumentLink();
        notes1.ShareType = 'V';
        notes1.Visibility = 'InternalUsers';
        notes1.ContentDocumentId = testcontent.ContentDocumentId;
        notes1.LinkedEntityId = opp.Id;
        insert notes1;
    }
    
    private static testMethod void eventwithaccloc(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        Apttus_Config2__AccountLocation__c accloc = new Apttus_Config2__AccountLocation__c();
        accloc.Apttus_Config2__AccountId__c = acc.Id;
        accloc.Name = 'accName';
        accloc.Mini_Language__c = 'SAP_EN';
        accloc.Apttus_Config2__Street__c = 'Prins Hendrikkade 123';
        accloc.Shipping_House_Number__c = '123';
        accloc.Apttus_Config2__PostalCode__c = '1011 AM';
        accloc.Apttus_Config2__City__c = 'AMSTERDAM';
        accloc.Apttus_Config2__Country__c = 'NETHERLANDS';
        insert accloc;
        
        Event eventRec = new Event();
        eventRec.WhatId = accloc.Id;
        eventRec.Touchpoint_Type__c = 'Inbound Call';
        eventRec.StartDateTime = System.Now();
        eventRec.EndDateTime = System.Now() + 1;
            
        insert eventRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = eventRec.Id;
        insert notes;
        
        // ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(accloc.Apttus_Config2__AccountId__c, acc.Id);
        
        ContentDocumentLink notes1 = new ContentDocumentLink();
        notes1.ShareType = 'V';
        notes1.Visibility = 'InternalUsers';
        notes1.ContentDocumentId = testcontent.ContentDocumentId;
        notes1.LinkedEntityId = accloc.Id;
        insert notes1;
    }
    
    private static testMethod void taskwithoppty(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'oppName';
        opp.AccountId = acc.id;
        opp.CLoseDate = Date.Today();
        opp.StageName = 'Open';
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SM_Constants.OppStandardRT).getRecordTypeId();
        
        insert opp;
        
        Id serviceRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Inbound').getRecordTypeId();
        
        Task taskRec = new Task();
        taskRec.WhatId = opp.Id;
        taskRec.RecordTypeId = serviceRecordTypeId;
        taskRec.Touchpoint_Type__c = 'Inbound Call';
            
        insert taskRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = taskRec.Id;
        insert notes;
        
        // ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(opp.AccountId, acc.Id);
        
        ContentDocumentLink notes1 = new ContentDocumentLink();
        notes1.ShareType = 'V';
        notes1.Visibility = 'InternalUsers';
        notes1.ContentDocumentId = testcontent.ContentDocumentId;
        notes1.LinkedEntityId = opp.Id;
        insert notes1;
    }
    
     private static testMethod void taskwithaccloc(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        acc.Sales_Organization__c = 'SAP_0333';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Account_Tier__c = 'Platinum';
        insert acc;
        
        Apttus_Config2__AccountLocation__c accloc = new Apttus_Config2__AccountLocation__c();
        accloc.Apttus_Config2__AccountId__c = acc.Id;
        accloc.Name = 'accName';
        accloc.Mini_Language__c = 'SAP_EN';
        accloc.Apttus_Config2__Street__c = 'Prins Hendrikkade 123';
        accloc.Shipping_House_Number__c = '123';
        accloc.Apttus_Config2__PostalCode__c = '1011 AM';
        accloc.Apttus_Config2__City__c = 'AMSTERDAM';
        accloc.Apttus_Config2__Country__c = 'NETHERLANDS';
        insert accloc;
        
        Id serviceRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Inbound').getRecordTypeId();
        
        Task taskRec = new Task();
        taskRec.WhatId = accloc.Id;
        taskRec.RecordTypeId = serviceRecordTypeId;
        taskRec.Touchpoint_Type__c = 'Inbound Call';
            
        insert taskRec;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes1 = new ContentDocumentLink();
        notes1.ShareType = 'V';
        notes1.Visibility = 'InternalUsers';
        notes1.ContentDocumentId = testcontent.ContentDocumentId;
        notes1.LinkedEntityId = accloc.Id;
        insert notes1;
        
        // ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: acc.Id];
        System.assertEquals(accloc.Apttus_Config2__AccountId__c, acc.Id);
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = taskRec.Id;
        insert notes;
    }
    
    private static testMethod void attachmentOnAgreement(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.ContentDocumentLinkTrigger__c = true;
        insert ts;
        
        Contact contact = APTS_TestUtils.createContact();
        Database.insert(contact, false);

        Apttus_Config2__PriceList__c priceList = APTS_TestUtils.createPriceList();
        Database.insert(priceList, false);
        
        List<Account> childAccountList = new List<Account>();

        Account account = APTS_TestUtils.createaccount();
        insert account;

        Account childAccount = APTS_TestUtils.createChildAccount(account);
        insert childAccount;

        childAccountList.add(childAccount);

        Apttus__APTS_Agreement__c agreement = APTS_TestUtils.createAgreement(contact.Id, null, priceList.Id, account.Id);
        agreement.Apttus__Status__c = Label.Apttus.Activated;
        agreement.Apttus__Status_Category__c = Label.APTS_In_Effect;
        agreement.Apttus__Auto_Renewal__c = false;
        agreement.Apttus__Contract_End_Date__c = System.Today() - 1;
        agreement.APTS_Order_Non_Contracted_Products__c = true;
        Database.insert(agreement, false);
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink notes = new ContentDocumentLink();
        notes.ShareType = 'V';
        notes.Visibility = 'InternalUsers';
        notes.ContentDocumentId = testcontent.ContentDocumentId;
        notes.LinkedEntityId = agreement.Id;
        insert notes;
        
        ContentDocumentLink newnote = [Select Id, LinkedEntityId from ContentDocumentLink where LinkedEntityId =: agreement.Id];
        System.assertEquals(newnote.LinkedEntityId, agreement.Id);
    }
}