src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Is_Primary_L1_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Is Primary L1 Asset</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipLabel>Asset Line Items (Is Primary L1 Asset)</relationshipLabel>
        <relationshipName>Primary_L1_Asset_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Asset Line Items (Physical Asset)</relationshipLabel>
        <relationshipName>Asset_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Serial_Number__c</fullName>
        <description>Serial Number of Physical Asset</description>
        <formula>IF(
	AND(
		APTS_Is_Primary_L1_Line__c = False,
		Apttus_Config2__HasOptions__c = True,
		APTS_Is_Primary_L1_Asset__c != null,
		ISPICKVAL(Apttus_Config2__LineType__c,&quot;Product/Service&quot;),
                Apttus_Config2__IsOptionRollupLine__c = false
	),
	APTS_Is_Primary_L1_Asset__r.APTS_Physical_Asset__r.SerialNumber__c,
	APTS_Physical_Asset__r.SerialNumber__c
)</formula>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>InitialActivationDate__c</fullName>
        <label>Initial Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentPhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a link to the parent physical asset used when entering an option.</description>
        <label>Parent Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RTR_LAE_Staging_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_AssetProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipName>Apttus_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Business_Transaction_Type__c</fullName>
        <label>Business Transaction Type</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Contract_Effective_Date__c</fullName>
        <description>This field will capture Asset Contract Effective Date. 

05/08/2019 &lt;Mahesh Chilaka&gt; This formula field now moved to static field.</description>
        <label>Contract Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Contract_Number__c</fullName>
        <description>This field will hold Asset associated Agreement Contract Number.</description>
        <label>Contract Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Integration_Log_Id__c</fullName>
        <label>Integration Log Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APTS_Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship field with physical asset object</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>RTR-LAE Staging Data</relationshipLabel>
        <relationshipName>APTS_RTR_LAE_Staging_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APTS_Remaining_Useful_Life__c</fullName>
        <description>Remaining Useful Life</description>
        <label>Remaining Useful Life</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APTS_Serial_Number__c</fullName>
        <formula>APTS_Physical_Asset__r.APTS_FinanceId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Serial Number</label>
        <type>Text</type>
    </fields>
    <label>RTR-LAE Staging Data</label>
    <nameField>
        <displayFormat>AIL-{00000000}</displayFormat>
        <label>RTR-LAE Staging Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTR-LAE Staging Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APTS_IntegationLogJob.cls
/*************************************************************
@Name: APTS_IntegationLogJob
@Author: Pranjal Mittal
@CreateDate: 23-01-2018
@Description: 
@UsedBy: 
******************************************************************/
//v101 09-Sept-2019 Mahesh Chilaka : DFT2C-856 - Added ExecuteExt method for ad-hoc request.

global class APTS_IntegationLogJob implements Database.Batchable<sObject>, Database.Stateful {
    
    String query;
    public Map<Id, RTR_LAE_Staging_Data__c> mapStageData = new Map<Id, RTR_LAE_Staging_Data__c>();
    static final String TRANS_A005 = 'A005';
    static final String TRANS_B005 = 'B005';
    Map<Id, Integration_Log__c> mapAssetLogId = new Map<Id, Integration_Log__c>();
    Date effectiveDate;
    Set<ID> assetIdSet = new Set<ID>();

    global APTS_IntegationLogJob(){}

    global APTS_IntegationLogJob(Map<Id, RTR_LAE_Staging_Data__c> mapStageData, Date effectiveDate) {
        try
        {
            this.mapStageData = mapStageData;
            this.effectiveDate = effectiveDate;
            for(RTR_LAE_Staging_Data__c stagingSO : [Select ID, APTS_Asset_Line_Item__c, APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c from RTR_LAE_Staging_Data__c where ID IN: mapStageData.values()])
            {
                if(stagingSO.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c != null)
                {
                    assetIdSet.add(stagingSO.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c);
                }
                else
                {
                    assetIdSet.add(stagingSO.APTS_Asset_Line_Item__c);
                }
            }
            query = 'Select ID from Apttus_Config2__AssetLineItem__c where ID IN :assetIdSet';
        }
        catch(Exception ex)
        {
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'APEX', ex.getStackTraceString()+' Message:'+ex.getMessage() ,'APTS_IntegationLogJob Constructor', null,'CLM',false,false, null, true);
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Apttus_Config2__AssetLineItem__c> scope) {
        List<Apttus_Config2__AssetLineItem__c> assetLineItemWithStaging = [SELECT ID, (SELECT Id, APTS_Asset_Line_Item__c,  APTS_Serial_Number__c, APTS_Contract_Number__c, APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c, 
                                                                                        APTS_Business_Transaction_Type__c FROM Apttus_Integration_Logs__r 
                                                                                        WHERE APTS_Contract_Effective_Date__c =: effectiveDate 
                                                                                             ORDER BY CreatedDate DESC LIMIT 1 ) 
                                                                           FROM Apttus_Config2__AssetLineItem__c 
                                                                           WHERE (ID IN :scope OR APTS_Is_Primary_L1_Asset__c IN :scope)];

        executeExt(assetLineItemWithStaging, false);
    }
    
    global void finish(Database.BatchableContext BC){
        try
        {
            update mapStageData.values();
            for(Integration_Log__c tmpLog : mapAssetLogId.values()){
                tmpLog.Object_Id__c = tmpLog.Id;
                tmpLog.Integration_Status__c = 'Initial';
            }
            upsert mapAssetLogId.values();
        }
        catch(Exception ex)
        {
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'APEX', ex.getStackTraceString()+' Message:'+ex.getMessage() ,'APTS_IntegationLogJob finish', null,'CLM',false,false, null, true);
        }
    }

    //v101 09-Sept-2019 Mahesh Chilaka : DFT2C-856 - START.
    @TestVisible
    public void executeExt(List<Apttus_Config2__AssetLineItem__c> assetLineItemWithStaging, Boolean adhocRequest){
        try
        {
            Map<Id, Integration_Log__c> mapTempAssetLogId = new Map<Id, Integration_Log__c>();            
            Map<Id, Set<Id>> mapParentChildAsset = new Map<Id, Set<Id>>();
            Map<Id, Id> mapAssetStageId = new Map<Id, Id>();
            Map<String, Id> mapSerialAssetId = new Map<String, Id>();

            //if(mapStageData.isEmpty()){ adhocRequest = true; }

            for(Apttus_Config2__AssetLineItem__c assetLineItemSO : assetLineItemWithStaging)
            {
                for(RTR_LAE_Staging_Data__c tmpStageData : assetLineItemSO.Apttus_Integration_Logs__r){
                    
                    
                    if((adhocRequest || !mapStageData.containsKey(tmpStageData.Id)) && !tmpStageData.APTS_Business_Transaction_Type__c.equalsIgnoreCase(TRANS_A005) ){
                        mapStageData.put(tmpStageData.Id, tmpStageData);
                        mapAssetStageId.put(tmpStageData.APTS_Asset_Line_Item__c, tmpStageData.Id);
                    }
    
                    if(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c == NULL
                         && !mapParentChildAsset.containsKey(tmpStageData.APTS_Asset_Line_Item__c)){
                        
                            mapParentChildAsset.put(tmpStageData.APTS_Asset_Line_Item__c, new Set<Id>{tmpStageData.APTS_Asset_Line_Item__c});
                    }
                    else if(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c != NULL){
                        if(mapParentChildAsset.containsKey(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c)){
                            mapParentChildAsset.get(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c).add(tmpStageData.APTS_Asset_Line_Item__c);
                        }
                        else{
                            Set<Id> setChildId = new Set<Id>();
                            setChildId.add(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c);
                            setChildId.add(tmpStageData.APTS_Asset_Line_Item__c);
                            mapParentChildAsset.put(tmpStageData.APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c, setChildId);
                        }
                    }
    
                    if(tmpStageData.APTS_Business_Transaction_Type__c.equalsIgnoreCase(TRANS_B005) && tmpStageData.APTS_Serial_Number__c != NULL){
                        mapSerialAssetId.put(tmpStageData.APTS_Serial_Number__c, tmpStageData.APTS_Asset_Line_Item__c);
                    }
                }
            }
            system.debug('$$$$$$ mapParentChildAsset '+mapParentChildAsset);
            system.debug('$$$$$$ mapStageData : '+mapStageData);
            Boolean toUpsert = false;
    
            for(Id tmpId : mapParentChildAsset.keySet()){
                if(!mapTempAssetLogId.containsKey(tmpId)){
                    system.debug('mapStageData :'+mapAssetStageId.get(tmpId)+' '+mapStageData.containsKey(mapAssetStageId.get(tmpId)));
                    if(mapAssetStageId.containsKey(tmpId) && mapStageData.containsKey(mapAssetStageId.get(tmpId)) && !mapStageData.get(mapAssetStageId.get(tmpId)).APTS_Business_Transaction_Type__c.equalsIgnoreCase(TRANS_A005)){
                        Integration_Log__c newLog = new Integration_Log__c();
                        newLog.Object__c = 'RTR_LAE_Staging_Data__c';
                        newLog.Integration_Status__c = 'Paused';
                        newLog.Object_Id__c = 'dummyId';
                        //mapAssetLogId.put(tmpId, newLog);
                        mapTempAssetLogId.put(tmpId, newLog);
                        toUpsert = true;
                    }else if(!mapAssetStageId.containsKey(tmpId)){
                        Set<Id> noL1Staging = mapParentChildAsset.get(tmpId);
                        for(Id processId: noL1Staging){
                            if(processId != tmpId){
                                Integration_Log__c newLog = new Integration_Log__c();
                                newLog.Object__c = 'RTR_LAE_Staging_Data__c';
                                newLog.Integration_Status__c = 'Paused';
                                newLog.Object_Id__c = 'dummyId';
                                //mapAssetLogId.put(tmpId, newLog);
                                mapTempAssetLogId.put(tmpId, newLog);
                                toUpsert = true;
                            }
                        }
                    }
                }
            }
            
            if(toUpsert){
                upsert mapTempAssetLogId.values();
                mapAssetLogId.putAll(mapTempAssetLogId);
            }
    
            for(Id bundleId : mapParentChildAsset.keySet()){
                if(mapAssetStageId.containsKey(bundleId) && mapStageData.containsKey(mapAssetStageId.get(bundleId)) && mapAssetLogId.containsKey(bundleId) && mapAssetLogId.get(bundleId).Id != null)
                {
                    mapStageData.get(mapAssetStageId.get(bundleId)).APTS_Integration_Log_Id__c = mapAssetLogId.get(bundleId).Id;
                }
                for(Id childId : mapParentChildAsset.get(bundleId)){
                    if(mapStageData.containsKey(mapAssetStageId.get(childId)) && mapAssetStageId.containsKey(childId) && mapAssetLogId.containsKey(bundleId) && mapAssetLogId.get(bundleId).Id != null){
                        mapStageData.get(mapAssetStageId.get(childId)).APTS_Integration_Log_Id__c = mapAssetLogId.get(bundleId).Id;
                    }
                }
            }
    
            List<RTR_LAE_Staging_Data__c> lstOfOldStagingData = [SELECT Id, APTS_Integration_Log_Id__c, APTS_Serial_Number__c, APTS_Business_Transaction_Type__c, APTS_Asset_Line_Item__r.APTS_Physical_Asset__r.ParentPhysicalAsset__r.InitialActivationDate__c, APTS_Asset_Line_Item__r.APTS_Physical_Asset__r.InitialActivationDate__c, APTS_Remaining_Useful_Life__c, APTS_Contract_Effective_Date__c, APTS_Asset_Line_Item__r.APTS_Is_Primary_L1_Asset__c, APTS_AssetProcessed__c FROM RTR_LAE_Staging_Data__c WHERE APTS_Serial_Number__c IN: mapSerialAssetId.keySet() AND APTS_Business_Transaction_Type__c = 'A005' AND APTS_AssetProcessed__c =: false];
            Boolean oldUpdateRequired = false;
            system.debug('$$$$ lstOfOldStagingData '+lstOfOldStagingData);
            if(lstOfOldStagingData != NULL && lstOfOldStagingData.size() > 0){
                oldUpdateRequired = true;
                for(RTR_LAE_Staging_Data__c tmpOld : lstOfOldStagingData){
                    Id parentBundleId;
                    for(Id bundleId : mapParentChildAsset.keySet()){
                        for(Id childId : mapParentChildAsset.get(bundleId)){
                            if(mapSerialAssetId.containsKey(tmpOld.APTS_Serial_Number__c) && childId == mapSerialAssetId.get(tmpOld.APTS_Serial_Number__c)){
                                parentBundleId = bundleId;
                                break;
                            }
                        }
                    }
                    if(mapAssetLogId.containsKey(parentBundleId) && mapAssetLogId.get(parentBundleId).Id != null)
                    {
                        tmpOld.APTS_Integration_Log_Id__c = (mapAssetLogId.get(parentBundleId)).Id;
                        tmpOld.APTS_AssetProcessed__c = true;
                    }
                }
            }
    
            if(oldUpdateRequired){
                update lstOfOldStagingData;
            }

            if(adhocRequest){

                 update mapStageData.values();
                for(Integration_Log__c tmpLog : mapAssetLogId.values()){
                    tmpLog.Object_Id__c = tmpLog.Id;
                    tmpLog.Integration_Status__c = 'Initial';
                }
                upsert mapAssetLogId.values();
            }
        }
        catch(Exception ex)
        {
            APTS_CustomLogging.createErrorLog(ex.getTypeName(), 'APEX', ex.getStackTraceString()+' Message:'+ex.getMessage() ,'APTS_IntegationLogJob execute', null,'CLM',false,false, null, true);
        }
    }
    //v101 09-Sept-2019 Mahesh Chilaka : DFT2C-856 - END.
    

}