src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>Apttus_Config2__AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the sold to account</description>
        <inlineHelpText>ID of the sold to account</inlineHelpText>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset Line Items (Sold To)</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetNumber__c</fullName>
        <description>The asset number</description>
        <externalId>true</externalId>
        <inlineHelpText>The asset number</inlineHelpText>
        <label>Asset Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>AssetLineItemTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AssetLineItemTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Elevated_Access_Reason__c</fullName>
        <label>Elevated Access Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Authorization Issue</fullName>
                </value>
                <value>
                    <fullName>Batch job execution</fullName>
                </value>
                <value>
                    <fullName>Defect or Incident Resolution</fullName>
                </value>
                <value>
                    <fullName>Manual deployment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Elevated_Access_Reference__c</fullName>
        <label>Elevated Access Reference</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AssetLineItemSharingRecalcTest.cls
/**
 * This class contains unit tests for validating the behavior of AssetLineItemSharingRecalc
 * and triggers.
 */
//-------------------------------------------------------------------------------------------//
// Author       :   Alvin Lomod - Accenture
// Created Date :   November 24, 2017
// Usage        :   
// Updates      :   
//-------------------------------------------------------------------------------------------//
@isTest
private class AssetLineItemSharingRecalcTest{
    
    private static User createAdminUser(){
    
        Id PAdmin = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        Id RAdmin = [SELECT Id FROM UserRole WHERE Name = 'JDE Professional'].Id;
        
        User systemAdmin = new User(alias = 'admin123', email='admintest123@noemail.com',
                emailencodingkey='UTF-8', lastname='LastNameAdmin', firstName = 'FirstNameAdmin', languagelocalekey='en_US',
                localesidkey='en_US', profileid = PAdmin, country='United States',IsActive =true, userroleId = RAdmin,
                Sales_Organization__c = 'SAP_0333',
                timezonesidkey='America/Los_Angeles', username='admin123test@noemail.com',
                Elevated_Access_Reason__c = 'Defect or Incident Resolution', Elevated_Access_Reference__c = 'ASDF');
        
        insert systemAdmin;
        
        return systemAdmin;
        
    }
    
    private static User createPartnerUser(Id ConId, Id profId, String x, String pEmail, String pAlias, String pUsername){     
                  
        User PartnerUser = new User(alias = pAlias, email = pEmail,
                emailencodingkey='UTF-8', lastname='LastNamePartner'+x, firstName = 'FirstNamePartner'+x, languagelocalekey='en_US',
                localesidkey='en_US', profileid = profId, country='United States', IsActive =true,
                             ContactId = ConId, Sales_Organization__c = 'SAP_0333',
                timezonesidkey='America/Los_Angeles', username = pUsername);
        
        return PartnerUser;
    }
    
    private static Apttus_Config2__AssetLineItem__c createALI(Id AccId, String aliName){
        
        Apttus_Config2__AssetLineItem__c ali = new Apttus_Config2__AssetLineItem__c();
        ali.Name = aliName;
        ali.Apttus_Config2__AccountId__c = AccId;
        ali.Apttus_Config2__AssetNumber__c = aliName;
        
        return ali;
        
    }
    
    static testMethod void ALISharingRecalcTest(){
        
        Test.startTest();
        
        User AdminUser = createAdminUser();
        User partnerUser;
        
        system.runAs(AdminUser){
            
            //insert new TriggerSettings__c(AssetLineItemTrigger__c = true);
            
            Account acc = new Account() ;
            acc.Name = 'Test Partner Account';
            acc.Sales_Organization__c = 'SAP_0333';
            acc.Phone = '+0987654321';
            acc.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.Customer).getRecordTypeId();
            acc.Main_Street_Only__c = 'Test Street';
            acc.Account_Type__c = 'Customer';
            insert acc; 
           
            Contact con = new Contact();
            con.FirstName = 'FirstNamePartner';
            con.LastName = 'LastNamePartner';
            con.AccountId = acc.Id;
            con.Phone = '+0987654321';
            con.Title = 'Tester';
            insert con;  
            
            Id prof = [SELECT Id FROM Profile WHERE Name='Partner Community User'].Id;
            
            partnerUser = createPartnerUser(con.Id, prof, 'Test', 'partnerTest1@usertriggertest.com', 'testa1', 'partnerTest1@usertriggertest.com');           
            insert partnerUser;
            
            
            //Insert ALI
            List<Apttus_Config2__AssetLineItem__c> aliList = new List<Apttus_Config2__AssetLineItem__c>();
            for(Integer x = 0; x < 3; x++){
                aliList.add(createALI(acc.Id, 'TEST ALI '+x));
            }
            
            insert aliList;
            System.debug('aliList ' + aliList);
            AssetLineItemSharingRecalc aliBatch = new AssetLineItemSharingRecalc();
            Database.executeBatch(aliBatch);
            
        }
        
        Test.stopTest();
        
        //Check ALI Share
        
        List<Apttus_Config2__AssetLineItem__Share> ALIshareList = new List<Apttus_Config2__AssetLineItem__Share>();
        
        ALIshareList = [SELECT Id, UserOrGroupId, AccessLevel, RowCause FROM Apttus_Config2__AssetLineItem__Share WHERE RowCause =: Schema.Apttus_Config2__AssetLineItem__Share.RowCause.Asset_Line_Item_Apex_Sharing__c];
        System.debug('ALIshareList ' + ALIshareList + ' ' + Schema.Apttus_Config2__AssetLineItem__Share.RowCause.Asset_Line_Item_Apex_Sharing__c);
        system.Assert(ALIshareList.size() >= 0);
        //system.Assert(ALIshareList[0].AccessLevel == 'Read');
        //system.Assert(ALIshareList[0].UserOrGroupId == partnerUser.Id);
        
    }
    
}