src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Agreement_Category__c</fullName>
        <description>Used to categorize agreement types.  When setting up a new agreement type make sure to seect approrpiate values for that agreement type and to set the right default</description>
        <label>Agreement Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard Deal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__PriceList__c.object
<CustomObject>
    <description>Represents a price list that contains the list of products the organization sells</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APTS_LegalEntityChangeBatchTest.cls
/*************************************************************
@Name: APTS_LegalEntityChangeBatchTest
@Author: Pranjal Mittal
@CreateDate: 04-06-2018
@Description: Test clas for APTS_LegalEntityChangeBatch
@UsedBy: APTS_LegalEntityChangeBatch
******************************************************************/
@isTest
private class APTS_LegalEntityChangeBatchTest{

    @isTest
    static void testLegalEntityBatch(){
        Contact contact = APTS_TestUtils.createContact();
        Database.insert(contact,false);
        
        Apttus_Config2__PriceList__c priceList = APTS_TestUtils.createPriceList();
        Database.insert(priceList,false);
        
        Account account = APTS_TestUtils.createaccount();
        Database.insert(account,false);
        
        Apttus__APTS_Agreement__c agreement = APTS_TestUtils.createAgreement(contact.Id, null, priceList.Id, account.Id);
        Database.insert(agreement,false);
 
        Map<Id, Id> agreementMap = new Map<Id, Id>();
        agreementMap.put(agreement.Id, agreement.Id);
        
        Test.startTest();
            APTS_LegalEntityChangeBatch batch = new APTS_LegalEntityChangeBatch(agreementMap);
            Database.executeBatch(batch, 200);
        Test.stopTest();
        
        Apttus__APTS_Agreement__c agr=[SELECT Id,Name,Apttus__Agreement_Category__c FROM Apttus__APTS_Agreement__c WHERE Id =:agreement.Id];
        System.assertEquals('Agreement',agr.Name);
        System.assertEquals('Standard',agr.Apttus__Agreement_Category__c);
    }
}