src/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Add email from customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
                <value>
                    <fullName>In Termination</fullName>
                </value>
                <value>
                    <fullName>Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement</fullName>
                </value>
                <value>
                    <fullName>Initial Agreement Activated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Apttus_Config2__AssetLineItem__c.object
<CustomObject>
    <description>Represents a product or service asset line item.</description>
    <fields>
        <fullName>APTS_Is_Primary_L1_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Primary L1 Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APTS_Manual_Activation_Date__c</fullName>
        <description>Manual Activation Date of Asset</description>
        <inlineHelpText>Manual Activation Date</inlineHelpText>
        <label>Manual Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>APTS_Type_Of_Contract__c</fullName>
        <label>Type Of Contract</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>RentBuy</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Free On Loan</fullName>
                </value>
                <value>
                    <fullName>Consumption</fullName>
                    <label>Consumption Model</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_CMConfig__AgreementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the associated agreement</description>
        <inlineHelpText>ID of the associated agreement</inlineHelpText>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Asset Line Items</relationshipLabel>
        <relationshipName>AssetLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__AssetStatus__c</fullName>
        <description>The asset status</description>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Pending Re-activation</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Renewal</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending Change</fullName>
                </value>
                <value>
                    <fullName>Pending Suspension</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Incremented</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Changed Configuration</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__BillingStartDate__c</fullName>
        <description>The billing start date. Also known as the first billing period end date.</description>
        <inlineHelpText>The billing start date. Also known as the first billing period end date.</inlineHelpText>
        <label>Billing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__ChargeType__c</fullName>
        <description>The charge type  associated with the product or service</description>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Rental Fee</fullName>
                </value>
                <value>
                    <fullName>Usage Fee</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Additional Service Fee</fullName>
                </value>
                <value>
                    <fullName>Sales Price</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__HasOptions__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the product has options.</description>
        <label>Has Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__LineType__c</fullName>
        <description>The line type.</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Service</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus_Config2__NetPrice__c</fullName>
        <description>The net price for the product or service is the Adjusted Price after applying the Group Adjustment %</description>
        <label>Net Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Apttus_Config2__NetUnitPrice__c</fullName>
        <description>The net unit price for the product or service is the Unit Adjusted Price after applying the Group Adjustment %</description>
        <inlineHelpText>The net unit price for the product or service is the Unit Adjusted Price after applying the Group Adjustment %</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <label>Asset Line Item</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RTR_LAE_Transaction_Data__c.object
<CustomObject>
    <fields>
        <fullName>APTS_Asset_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset Line Item</label>
        <referenceTo>Apttus_Config2__AssetLineItem__c</referenceTo>
        <relationshipName>Apttus_Transaction_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RTR-LAE Transaction Data</label>
    <nameField>
        <displayFormat>ATL-{00000000}</displayFormat>
        <label>RTR-LAE Transaction Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTR-LAE Transaction Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>LAETransaction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LAETransaction</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/APTS_LaeTransactionHandlerTest.cls
/*************************************************************
@Name: APTS_LaeTransactionHandlerTest
@Author: Shahul
@CreateDate: 11-08-2020
@Description: Test class for laetransaction trigger handler
@UsedBy: APTS_LaeTransactionHandler
******************************************************************/
@isTest
public class APTS_LaeTransactionHandlerTest{

    public static testMethod void insertTransactionRecord()
    {
    TriggerSettings__c settings = new TriggerSettings__c();
        settings.LAETransaction__c = true;
        Database.insert(settings, false);
        List<RTR_LAE_Transaction_Data__c> lstlaecount =new List<RTR_LAE_Transaction_Data__c>();
        List<RTR_LAE_Transaction_Data__c> lstlaecountupdate =new List<RTR_LAE_Transaction_Data__c>();
        Map<Id, RTR_LAE_Transaction_Data__c > newItems =new Map<Id, RTR_LAE_Transaction_Data__c >();
        List<RTR_LAE_Transaction_Data__c > oldList =new List<RTR_LAE_Transaction_Data__c >();
        Map<Id, RTR_LAE_Transaction_Data__c > oldItems =new Map<Id, RTR_LAE_Transaction_Data__c >();
        List<Apttus__APTS_Agreement__c> agrlst = new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c aggr = new Apttus__APTS_Agreement__c();
        aggr.Apttus__Status__c = 'In Effect';
        aggr.Apttus__Status_Category__c = 'Activated';
        agrlst.add(aggr);
        Apttus__APTS_Agreement__c aggr1 = new Apttus__APTS_Agreement__c();
        aggr1.Apttus__Status__c = 'In Effect';
        aggr1.Apttus__Status_Category__c = 'Activated';
        agrlst.add(aggr1);
        Database.insert(agrlst,false);
        
        List<Apttus_Config2__AssetLineItem__c> assetLI = new List<Apttus_Config2__AssetLineItem__c>();
        Apttus_Config2__AssetLineItem__c tstAsset= new Apttus_Config2__AssetLineItem__c();
        tstAsset.Apttus_Config2__BillingStartDate__c = Date.today().addDays(1);
        tstAsset.Name = 'tstAsset';
        tstAsset.Apttus_Config2__NetPrice__c = 100;
        tstAsset.Apttus_Config2__NetUnitPrice__c=10;
        tstAsset.Apttus_Config2__AssetStatus__c = 'Activated';
        tstAsset.APTS_Manual_Activation_Date__c = Date.today();
        tstAsset.Apttus_Config2__HasOptions__c = true;
        tstAsset.Apttus_CMConfig__AgreementId__c =  agrlst[0].Id;
        tstAsset.Apttus_Config2__LineType__c = 'Product/Service';
        tstAsset.APTS_Is_Primary_L1_Line__c = true;
        tstAsset.APTS_Type_Of_Contract__c = 'Sales';
        tstAsset.Apttus_Config2__ChargeType__c = 'Service Fee';
        insert tstAsset;
        
        RTR_LAE_Transaction_Data__c lae=new RTR_LAE_Transaction_Data__c();
        lae.APTS_Asset_Line_Item__c=tstAsset.Id;
        lae.APTS_Business_Transaction_Type__c='0001';
        lae.APTS_Contract_Effective_Date__c=system.today();
        lstlaecount.add(lae);
        
        RTR_LAE_Transaction_Data__c lae1=new RTR_LAE_Transaction_Data__c();
        lae1.APTS_Asset_Line_Item__c=tstAsset.Id;
        lae1.APTS_Business_Transaction_Type__c='0001';
        lae1.APTS_Contract_Effective_Date__c=system.today();
        lstlaecount.add(lae1);
        
        RTR_LAE_Transaction_Data__c lae2=new RTR_LAE_Transaction_Data__c();
        lae2.APTS_Asset_Line_Item__c=tstAsset.Id;
        lae2.APTS_Business_Transaction_Type__c='A005';
        lae2.APTS_Contract_Effective_Date__c=system.today();
        lstlaecount.add(lae2);
        
        RTR_LAE_Transaction_Data__c lae3=new RTR_LAE_Transaction_Data__c();
        lae3.APTS_Asset_Line_Item__c=tstAsset.Id;
        lae3.APTS_Business_Transaction_Type__c='A005';
        lae3.APTS_Contract_Effective_Date__c=null;
        lstlaecount.add(lae3); 
        if(lstlaecount.size()>0){
        Database.insert(lstlaecount,false);}
        
    //APTS_LaeTransactionHandler laeins=new APTS_LaeTransactionHandler();
    // laeins.BeforeInsert(lstlaecount);
    
    RTR_LAE_Transaction_Data__c laaupdate1=[select id,APTS_Contract_Effective_Date__c,APTS_Business_Transaction_Type__c,APTS_Asset_Line_Item__c from RTR_LAE_Transaction_Data__c where APTS_Contract_Effective_Date__c=null];
    system.debug('++++laaupdate1+++++'+laaupdate1);
    laaupdate1.APTS_Contract_Effective_Date__c=Date.today().addDays(1);
    lstlaecountupdate.add(laaupdate1);
    if(lstlaecountupdate.size()>0){
    Database.update(lstlaecountupdate,false);}
    //laeins.BeforeUpdate(lstlaecountupdate,newItems,oldList,oldItems);
    RTR_LAE_Transaction_Data__c lae4=new RTR_LAE_Transaction_Data__c();
    lae4.APTS_Asset_Line_Item__c=tstAsset.Id;
    lae4.APTS_Business_Transaction_Type__c='0001';
    lae4.APTS_Contract_Effective_Date__c=system.today();
    insert lae4;
    delete lae4;
    RTR_LAE_Transaction_Data__c lae5=new RTR_LAE_Transaction_Data__c();
    lae5.APTS_Asset_Line_Item__c=tstAsset.Id;
    lae5.APTS_Business_Transaction_Type__c='0004';
    lae5.APTS_Asset_Processed__c=false;
    lae5.APTS_Contract_Effective_Date__c=system.today();
    insert lae5;
    System.assert(lae5.APTS_Asset_Processed__c!=null);
    }
}