src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Country codes</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CaseClosureNotification__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When opt-in, the customer will get a notification when the case is closed.</description>
        <label>Case Closure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Communication_Preference__c</fullName>
        <label>Communication Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>ExecutingEngineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executing Engineer</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>WorkOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>RouteSales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to case object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>WorkOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExecutingEngineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to indicated by Click which engineer has executed the Task or which engineeers Parts have been used, missing, required.</description>
        <inlineHelpText>Engineer that performed the job.</inlineHelpText>
        <label>Executing Engineer</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Work Order Line Items (Executing Engineer)</relationshipLabel>
        <relationshipName>ExecutingEngineerWorkOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrderSAP__c</fullName>
        <description>FD 1237 Internal order number coming from SAP</description>
        <externalId>true</externalId>
        <label>Internal Order SAP</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JDELineItemNumber__c</fullName>
        <externalId>true</externalId>
        <label>JDE Line Item Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkOrderLineItemType__c</fullName>
        <description>Defines the type of work order line</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UsedSpareParts</fullName>
                    <label>Used parts</label>
                </value>
                <value>
                    <fullName>MissingSpareParts</fullName>
                    <label>Missing parts</label>
                </value>
                <value>
                    <fullName>RequiredSpareparts</fullName>
                    <label>Required parts</label>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Service Materials</fullName>
                </value>
                <value>
                    <fullName>MachineActions</fullName>
                    <label>Machine Actions</label>
                </value>
                <value>
                    <fullName>Counter Reading</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Cups</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                    <label>Counter Reading Task</label>
                </value>
                <value>
                    <fullName>Rinse</fullName>
                </value>
                <value>
                    <fullName>Preventive Maintenance</fullName>
                </value>
                <value>
                    <fullName>Waterfilter</fullName>
                </value>
                <value>
                    <fullName>Descaling</fullName>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Ingredients</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>LW</fullName>
                </value>
                <value>
                    <fullName>LD</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LI</fullName>
                </value>
                <value>
                    <fullName>PW</fullName>
                </value>
                <value>
                    <fullName>PD</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>WD</fullName>
                </value>
                <value>
                    <fullName>WB</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>DB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S44</fullName>
                    <label>Workshop</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>Routesales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_PDFContentEmailLink_Controller_Test.cls
/**
* @author        Abram Vixen Reyes
* @date          July 30, 2019
* @description   Test class for TS_PDFContentEmailLink_Controller
* @revision(s)
*/

@isTest
public class TS_PDFContentEmailLink_Controller_Test {
    
    static Contact con;
    static Case c;
    static WorkOrder wo;
    static Resource__c resource;
    static WorkOrderLineItem parentWOLI;
    static List<WorkOrderLineItem> workOrderLineItems;
    
    static void setupTestData() {
        con = TS_TestDataFactory.createContact();
        con.Preferred_Language__c = 'SAP_NL';
        con.CaseClosureNotification__c = true;
        con.Communication_Preference__c = 'Email';
        con.Email = 'test@jde.com';
        insert con;
        
        c = TS_TestDataFactory.createFieldServiceCase();
        c.ContactId = con.Id;
        insert c;
        
        wo = TS_TestDataFactory.createWorkOrder();
        wo.ContactId = con.Id;
        wo.CaseId = c.Id;
        wo.WorkOrderType__c = Label.TS_Case_SubType_CorrectMaint;
        insert wo;
        
        resource = TS_TestDataFactory.createResourceSingle('Test Resource');
        insert resource;
        
        parentWOLI = TS_TestDataFactory.createWorkOrderLineItem(wo.Id);
        parentWOLI.ExecutingEngineer__c = resource.Id;
        parentWOLI.Status = Label.TS_WOLI_Status_Completed;
        parentWOLI.InternalOrderSAP__c = '123';
        parentWOLI.WorkOrderLineItemType__c = Label.TS_Type_Task;
        parentWOLI.Case__c = c.Id;
        parentWOLI.WorkOrderId = wo.Id;
        parentWOLI.WorkOrderType__c = 'S10';
        insert parentWOLI;
        
        parentWOLI = [SELECT Id,Case__r.ContactId,Case__r.SalesOrganization__c,Case__r.Contact.Preferred_Language__c,Case__c,JDELineItemNumber__c FROM WorkOrderLineItem WHERE Id =: parentWOLI.Id LIMIT 1];
        
        workOrderLineItems = new List<WorkOrderLineItem>();
        WorkOrderLineItem serviceMaterial = TS_TestDataFactory.createWorkOrderLineItem(wo.Id);
        serviceMaterial.Status = Label.TS_WOLI_Status_Completed;
        serviceMaterial.WorkOrderLineItemType__c = Label.TS_Type_Service;
        serviceMaterial.Case__c = c.Id;
        serviceMaterial.ParentWorkOrderLineItemId = parentWOLI.Id;
        workOrderLineItems.add(serviceMaterial);
        
	}
    
	static testMethod void test_getContent(){
        
        setupTestData();
        Test.startTest();
            ContentVersion testFile = new ContentVersion();
            Blob b = Blob.valueOf('UNIT.Test');
            testFile.VersionData = b;
            testFile.Title = 'Test Title';
            testFile.PathOnClient = 'Test.pdf';
            testFile.ContentLocation='S';
            testFile.Description  = parentWOLI.Case__c;
            testFile.ObjectReferenceID__c = parentWOLI.Id;
            insert testFile;
        
        	List<ContentVersion> CONTENT_LIST = [SELECT ContentDocumentId, Description, PathOnClient, ObjectReferenceID__c FROM ContentVersion WHERE Id =: testFile.Id];
            
            ContentDocumentLink contDoc = new ContentDocumentLink();
            contDoc.ContentDocumentId = CONTENT_LIST[0].ContentDocumentId;
            contDoc.LinkedEntityId = CONTENT_LIST[0].ObjectReferenceID__c;
            contDoc.ShareType = 'V';
            insert contDoc;
               	
            ContentDistribution cd = new ContentDistribution();
            cd.PreferencesAllowPDFDownload = true;
            cd.Name = testFile.PathOnClient;
            cd.ContentVersionId = testFile.Id;
            cd.RelatedRecordId = testFile.Description;
            cd.PreferencesAllowOriginalDownload = false;
            cd.PreferencesAllowViewInBrowser = true;
            insert cd;
            
            TS_PDFContentEmailLink_Controller PDF_CONTENT = new TS_PDFContentEmailLink_Controller();
            PDF_CONTENT.WoliID = parentWOLI.Id;
            PDF_CONTENT.fileName = 'Test.pdf';
            PDF_CONTENT.getcontent();
        Test.stopTest();
    }
}