src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ActualDeliveryDate__c</fullName>
        <label>Actual Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ActualPickUpDate__c</fullName>
        <label>Actual Pick-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CustomerScheduleDate__c</fullName>
        <label>Customer Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EarliestAppointmentTime__c</fullName>
        <description>Indicates the start date/time the service can be executed in collaboration with the customer or determined by planning.</description>
        <label>Earliest Appointment Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EarlyStartDate__c</fullName>
        <description>Indicates the earliest date/time the service can be executed if the case needs to be managed within the SLA.</description>
        <label>Early Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LSPScheduleDate__c</fullName>
        <label>LSP Schedule Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PickingDate__c</fullName>
        <description>Ultimate time the job has to be scheduled on.</description>
        <inlineHelpText>Ultimate time the job has to be scheduled on.</inlineHelpText>
        <label>Picking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlannedDeliveryDate__c</fullName>
        <label>Planned Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlannedPickUpDate__c</fullName>
        <label>Planned Pick-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLADate__c</fullName>
        <description>Indicates the SLA time to resolve the case and will be automatically calculated.</description>
        <label>SLA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Country codes</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduleManually__c</fullName>
        <defaultValue>false</defaultValue>
        <description>KTS - 369: Quickly Escalate a Case. Field responsible for identifying case records tagged for manual schedule</description>
        <label>Schedule Manually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is a picklist describing the type of case in more detail.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Generic question</fullName>
                </value>
                <value>
                    <fullName>Field Service Tips</fullName>
                </value>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water-Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>Not assigned</fullName>
                </value>
                <value>
                    <fullName>Quality Ingredients</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Machines</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>S44</fullName>
                    <label>Workshop</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop-off</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>Contract question/change</fullName>
                </value>
                <value>
                    <fullName>CMD question/change</fullName>
                </value>
                <value>
                    <fullName>Invoice question/change</fullName>
                </value>
                <value>
                    <fullName>Report question/request</fullName>
                </value>
                <value>
                    <fullName>Product information request</fullName>
                </value>
                <value>
                    <fullName>Movement</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CountrySetting__c.object
<CustomObject>
    <description>Records containing country specified settings (e.g. country specific SLAs)</description>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Country_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LSPScheduleTimeOffset__c</fullName>
        <inlineHelpText>Determine the hour in the 24 hour clock.</inlineHelpText>
        <label>LSP Schedule Time Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Settings</pluralLabel>
    <recordTypes>
        <fullName>CountryDefaultBusinessHours</fullName>
        <active>true</active>
        <label>Country Default Business Hours</label>
    </recordTypes>
    <recordTypes>
        <fullName>CountryScheduleDateTimeSettings</fullName>
        <active>true</active>
        <label>Country Schedule Date/Time Settings</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RescheduleRequest__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reschedule Requests</relationshipLabel>
        <relationshipName>Reschedule_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpectedDeliveryDate__c</fullName>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PickingDate__c</fullName>
        <label>Picking Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RequestedActivityDate__c</fullName>
        <label>Requested Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RescheduleSource__c</fullName>
        <label>Reschedule Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reschedule Request</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Reschedule Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reschedule Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>RescheduleRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RescheduleRequest</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to case object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>WorkOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EarliestAppointmentTime__c</fullName>
        <description>Appointment Finish agreed with customer</description>
        <label>Earliest Appointment Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EarlyStart__c</fullName>
        <label>Early Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LatestAppointmentTime__c</fullName>
        <description>Appointment Start agreed with customer</description>
        <label>Latest Appointment Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reschedule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reschedule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLADate__c</fullName>
        <description>TS: Indicates the SLA date for the line item.</description>
        <label>SLA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ScheduleManually__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines is a task is not to schedule automatically.</description>
        <label>Schedule Manually</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RescheduleRequestTriggerHandler.cls
/**
* @author        Adrian Reyes
* @date          02.26.2018           
* @description   Class responsible for the trigger business logic of Reschedule Request
* @revision(s)   7.13.2018 Paul Aguiling: KTS-1935 Updated updateCase()
*/
public without sharing class RescheduleRequestTriggerHandler implements ITriggerHandler {
    public static Boolean isTriggerDisabled = true;
    
    public void BeforeInsert(List<SObject> newItems) {
    }
    
    public void BeforeUpdate(List<SObject> newList, Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems) {
    }
    
    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems) {
    }
    
    public void AfterInsert(List<SObject> newList, Map<Id, SObject> newMapItems) {
        updateCase(newList);
    }
    
    public void AfterUpdate(List<SObject> newList , Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems){
    }
    
    public void AfterDelete(List<SObject> oldList, Map<Id, SObject> oldMapItems) {
    }
    
    public void AfterUndelete(List<SObject> newList, Map<Id, SObject> newMapItems) {
    }
    
    public Boolean IsDisabled() {
        if (TriggerSettings__c.getInstance().RescheduleRequest__c) {
            return false;
        } else {
            return isTriggerDisabled;
        }
    }
    
    /**
    * @author        Adrian Reyes
    * @date          02.26.2018          
    * @description   Method to update case's early start and SLA dates and reschedule related work order line items
    * @revision(s)
    */
    void updateCase(List<SObject> newList) {
        CustomLogging.push('updateCase', 'RescheduleRequestTriggerHandler');
        Set<Id> caseIDs = new Set<Id>();
        List<RescheduleRequest__c> rescheduleRequests = new List<RescheduleRequest__c>();
        for(RescheduleRequest__c rescheduleRequest: (List<RescheduleRequest__c>) newList){
            if(rescheduleRequest.RescheduleSource__c == Label.TS_RescheduleSourceOrder && rescheduleRequest.Case__c != null && rescheduleRequest.PickingDate__c != null){
                caseIDs.add(rescheduleRequest.Case__c);
                rescheduleRequests.add(rescheduleRequest);
            }
        }
        
        if(!rescheduleRequests.isEmpty()){
            Map<Id,Case> caseMap = new Map<Id,Case>([SELECT SalesOrganization__c, SubType__c, EarlyStartDate__c, SLADate__c, ActualDeliveryDate__c, ActualPickUpDate__c, (SELECT Id FROM WorkOrderLineItems__r WHERE Status !=: Label.TS_WOLI_Status_Completed) FROM Case WHERE Id IN: caseIDs]);
            Map<String,CountrySetting__c> countryScheduleDateTimeSettingsMap = TS_SalesTriggerController.getCountryScheduleDateTimeSettingsMap();
            Map<String,CountrySetting__c> countryDefaultBusinessHoursMap = TS_SalesTriggerController.getCountryDefaultBusinessHoursMap();
            Map<String,String> orderTypeMap = new Map<String,String>{Label.TS_Order_S40 => Label.TS_Order_Instype_Installation, Label.TS_Order_S41 => Label.TS_Order_Instype_DeInstallation, Label.TS_Case_SubType_Swap => Label.TS_Case_SubType_Swap, Label.TS_Order_Instype_Movement => Label.TS_Order_Instype_Movement, Label.TS_WOTOrderType_Conversion => Label.TS_WOTOrderType_Conversion};
            List<WorkOrderLineItem> workOrderLineItems = new List<WorkOrderLineItem>();
            for(RescheduleRequest__c rescheduleRequest: rescheduleRequests){
                Case c = caseMap.get(rescheduleRequest.Case__c);
                CountrySetting__c countryScheduleDateTimeSettings = countryScheduleDateTimeSettingsMap.get(c.SalesOrganization__c + '-' + orderTypeMap.get(c.SubType__c));
                CountrySetting__c countryDefaultBusinessHours = countryDefaultBusinessHoursMap.get(c.SalesOrganization__c);
                
                //Update case dates
                //JAN 24, 2019 XEN REYES
                if(c.ActualDeliveryDate__c == null){
                    c.PlannedDeliveryDate__c = null;    
                }

                if(c.ActualPickUpDate__c == null){
                    c.PlannedPickUpDate__c = null;    
                }
                
                c.PickingDate__c = rescheduleRequest.PickingDate__c;
                c.EarlyStartDate__c = rescheduleRequest.RequestedActivityDate__c != null ? DateTime.newInstance(rescheduleRequest.RequestedActivityDate__c.year(), rescheduleRequest.RequestedActivityDate__c.month(), rescheduleRequest.RequestedActivityDate__c.day(), 8, 0, 0) : c.EarlyStartDate__c;
                c.SLADate__c = rescheduleRequest.RequestedActivityDate__c != null ? DateTime.newInstance(rescheduleRequest.RequestedActivityDate__c.addDays(4), Time.newInstance(17, 0, 0, 0)) : c.SLADate__c;
                c.LSPScheduleDate__c = TS_SalesTriggerController.getLSPScheduleDate(c, countryScheduleDateTimeSettings, countryDefaultBusinessHours);
				
                if(rescheduleRequest.RequestedActivityDate__c != null){ //XEN REYES Nov 1 2018
                    c.CustomerScheduleDate__c = TS_SalesTriggerController.getCustomerScheduleDate(c, countryScheduleDateTimeSettings, countryDefaultBusinessHours);

                    //KTS-1935: Change the customer schedule and lsp date to today if calculated date is in the past - START
                    //KTS-2257: Include equal to today in the criteria, not just greater than. XEN REYES Feb 11, 2019
                    if (Date.today() >= c.CustomerScheduleDate__c) {
                        c.ScheduleManually__c = true;
                        c.CustomerScheduleDate__c = TS_UtilityClass.getWorkingDate(countryDefaultBusinessHours.Business_Hours__c, Date.today());
                    }
                }

                c.ActualDeliveryDate__c = rescheduleRequest.ExpectedDeliveryDate__c != null ? rescheduleRequest.ExpectedDeliveryDate__c : c.ActualDeliveryDate__c;

                //KTS-2257: Include equal to today in the criteria, not just greater than. XEN REYES Feb 11, 2019
                if (Date.today() >= c.LSPScheduleDate__c) {
                    Time lspScheduleTime = Time.newInstance(Integer.valueOf(countryScheduleDateTimeSettings.LSPScheduleTimeOffset__c), 0, 0, 0);
                    Date lspSched = TS_UtilityClass.getWorkingDate(countryDefaultBusinessHours.Business_Hours__c, Date.today());
                    c.LSPScheduleDate__c = DateTime.newInstance(lspSched, lspScheduleTime);
                }
                //KTS-1935: Change the customer schedule and lsp date to today if calculated date is in the past - END

                //Update work order line items
                if(rescheduleRequest.RequestedActivityDate__c != null){
                    for(WorkOrderLineItem workOrderLineItem: c.WorkOrderLineItems__r){
                        workOrderLineItem.EarlyStart__c = c.EarlyStartDate__c;
                        workOrderLineItem.SLADate__c = c.SLADate__c;
                        workOrderLineItem.EarliestAppointmentTime__c = null;
                        workOrderLineItem.LatestAppointmentTime__c = null;
                        workOrderLineItem.Reschedule__c = true;
                        workOrderLineItems.add(workOrderLineItem);
                    }
                }
            }
            
            if(Schema.sObjectType.Case.isUpdateable())
            	update caseMap.values();
            
            if(Schema.sObjectType.WorkOrderLineItem.isUpdateable())
            	update workOrderLineItems;
        }
        
        CustomLogging.pop();
    }
}