src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>PlannedDeliveryDate__c</fullName>
        <label>Planned Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlannedMovementDate__c</fullName>
        <label>Planned Movement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlannedPickUpDate__c</fullName>
        <label>Planned Pick-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Country codes</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>This is a picklist describing the type of case in more detail.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Generic question</fullName>
                </value>
                <value>
                    <fullName>Field Service Tips</fullName>
                </value>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water-Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>Not assigned</fullName>
                </value>
                <value>
                    <fullName>Quality Ingredients</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Machines</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>S44</fullName>
                    <label>Workshop</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop-off</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>Contract question/change</fullName>
                </value>
                <value>
                    <fullName>CMD question/change</fullName>
                </value>
                <value>
                    <fullName>Invoice question/change</fullName>
                </value>
                <value>
                    <fullName>Report question/request</fullName>
                </value>
                <value>
                    <fullName>Product information request</fullName>
                </value>
                <value>
                    <fullName>Movement</fullName>
                </value>
                <value>
                    <fullName>Replacement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CountrySetting__c.object
<CustomObject>
    <description>Records containing country specified settings (e.g. country specific SLAs)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Country_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for which this record is applicable</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeliveryOffset__c</fullName>
        <label>Delivery Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PickupOffset__c</fullName>
        <label>Pick-up Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Round Trip</label>
        <type>Checkbox</type>
    </fields>
    <label>Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Settings</pluralLabel>
    <recordTypes>
        <fullName>CountryDefaultBusinessHours</fullName>
        <active>true</active>
        <label>Country Default Business Hours</label>
    </recordTypes>
    <recordTypes>
        <fullName>Country_Scheduling_Rules</fullName>
        <active>true</active>
        <description>This record type is used to define schedule offset per country.</description>
        <label>Country Scheduling Rules</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Includes_Round_Trip__c</fullName>
        <description>Indicates if the work order contains a plug and play or workshop activity</description>
        <formula>S40TotalCount__c + S41TotalCount__c + S43TotalCount__c = PlannedRoundTripCount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Planned Round Trip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>S40_Scheduled_Date__c</fullName>
        <label>S40 Scheduled Date</label>
        <summarizedField>WorkOrderLineItem.Installation_Date_S40__c</summarizedField>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderLineItemType__c</field>
            <operation>equals</operation>
            <value>Task</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderType__c</field>
            <operation>equals</operation>
            <value>Installation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.Installation_Date_S40__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.Status</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>S41ScheduledDate__c</fullName>
        <label>S41 Scheduled Date</label>
        <summarizedField>WorkOrderLineItem.DeInstallationDateS41__c</summarizedField>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderLineItemType__c</field>
            <operation>equals</operation>
            <value>Task</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderType__c</field>
            <operation>equals</operation>
            <value>De-Installation</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.DeInstallationDateS41__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.Status</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>S43ScheduledDate__c</fullName>
        <label>S43 Scheduled Date</label>
        <summarizedField>WorkOrderLineItem.ConfigurationDateS43__c</summarizedField>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderLineItemType__c</field>
            <operation>equals</operation>
            <value>Task</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.WorkOrderType__c</field>
            <operation>equals</operation>
            <value>Configuration Change</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.ConfigurationDateS43__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>WorkOrderLineItem.Status</field>
            <operation>notEqual</operation>
            <value>Canceled</value>
        </summaryFilterItems>
        <summaryForeignKey>WorkOrderLineItem.WorkOrderId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TS_LSPDatesCalculator.cls
/**
* @author        Adrian Reyes
* @date          02.07.2018
* @description   Class used to calculate LSP dates on case when all related work order line items are scheduled
* @revision(s)
*/

global with sharing class TS_LSPDatesCalculator {
    /**
    * @author        Adrian Reyes
    * @date          02.07.2018           
    * @description   Method used to calculate LSP dates on case when all related work order line items are scheduled
    * @revision(s)
    */
    @InvocableMethod
    global static void calculateLSPDates(List<Id> workOrderIDs) {
        CustomLogging.push('calculateLSPDates', 'TS_LSPDatesCalculator');

        try {
            //Retrieve country scheduling rules and default business hours
            Map<String,CountrySetting__c> countrySchedulingRuleMap = new Map<String,CountrySetting__c>();
            for(CountrySetting__c countrySetting: [SELECT Country__c, RoundTrip__c, DeliveryOffset__c, PickupOffset__c FROM CountrySetting__c WHERE RecordType.DeveloperName = 'Country_Scheduling_Rules' AND Active__c = true])
                countrySchedulingRuleMap.put(countrySetting.Country__c + '-' + countrySetting.RoundTrip__c, countrySetting);
            
            Map<String,CountrySetting__c> countryDefaultBusinessHoursMap = new Map<String,CountrySetting__c>();
            for(CountrySetting__c countrySetting: [SELECT Country__c, Business_Hours__c FROM CountrySetting__c WHERE RecordType.DeveloperName = 'CountryDefaultBusinessHours' AND Active__c = true])
                countryDefaultBusinessHoursMap.put(countrySetting.Country__c, countrySetting);
            
            List<WorkOrder> workOrders = [SELECT CaseId, S40_Scheduled_Date__c, S41ScheduledDate__c, S43ScheduledDate__c, Includes_Round_Trip__c FROM WorkOrder WHERE Id IN: workOrderIDs];
            Set<Id> caseIDs = new Set<Id>();
            for(WorkOrder workOrder: workOrders)
                caseIDs.add(workOrder.CaseId);
            
            Map<Id,Case> caseMap = new Map<Id,Case>([SELECT SalesOrganization__c, SubType__c FROM Case WHERE Id IN: caseIDs]);
            for(WorkOrder workOrder: workOrders){
                Case c = caseMap.get(workOrder.CaseId);
                CountrySetting__c countrySchedulingRule = countrySchedulingRuleMap.get(c.SalesOrganization__c + '-' + workOrder.Includes_Round_Trip__c);
                CountrySetting__c countryDefaultBusinessHours = countryDefaultBusinessHoursMap.get(c.SalesOrganization__c);
                
                //Calculate LSP dates
                c.PlannedDeliveryDate__c = getDeliveryDate(workOrder, c, countrySchedulingRule, countryDefaultBusinessHours);
                c.PlannedPickUpDate__c = getPickUpDate(workOrder, c, countrySchedulingRule, countryDefaultBusinessHours);
                c.PlannedMovementDate__c = getMovementDate(workOrder, c, countrySchedulingRule, countryDefaultBusinessHours);
            }

            //Update cases
            if(Schema.sObjectType.Case.isUpdateable())
                update caseMap.values();
                
        } catch (Exception ex) {
            CustomLogging.debugException(ex);
            CustomLogging.pop();
            System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());
        }
        
        CustomLogging.pop();
    }
    
    /**
    * @author        Adrian Reyes
    * @date          02.07.2018           
    * @description   Method used to calculate Delivery Date
    * @revision(s)
    */
    static Date getDeliveryDate(WorkOrder workOrder, Case c, CountrySetting__c countrySchedulingRule, CountrySetting__c countryDefaultBusinessHours) {
        CustomLogging.push('getDeliveryDate', 'TS_LSPDatesCalculator');
        DateTime deliveryDate;
        //Integer deliveryOffset = Integer.valueOf(countrySchedulingRule.DeliveryOffset__c * -1);
        Integer deliveryOffset = Integer.valueOf(countrySchedulingRule.DeliveryOffset__c);
        if (c.SubType__c == Label.TS_Order_S40 || c.SubType__c == Label.TS_Case_SubType_Swap) {
            //deliveryDate = workOrder.S40_Scheduled_Date__c.addDays(deliveryOffset);
            deliveryDate = workOrder.S40_Scheduled_Date__c;
        } else if (c.SubType__c == Label.TS_WOTOrderType_Conversion) {
            //deliveryDate = workOrder.S43ScheduledDate__c.addDays(deliveryOffset);
            deliveryDate = workOrder.S43ScheduledDate__c;
        } else {
            return null;
        }
        
        DateTime nextStartDate = BusinessHours.nextStartDate(countryDefaultBusinessHours.Business_Hours__c, deliveryDate);
        deliveryDate = deliveryDate.date() != nextStartDate.date() ? BusinessHours.add(countryDefaultBusinessHours.Business_Hours__c, nextStartDate, -1000) : nextStartDate;
        deliveryDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, deliveryDate, deliveryOffset, false);
        //deliveryDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, deliveryDate, -1);
        CustomLogging.pop();
        return deliveryDate.date();
    }
    
    /**
    * @author        Adrian Reyes
    * @date          02.07.2018           
    * @description   Method used to calculate Pick-Up Date
    * @revision(s)
    */
    static Date getPickUpDate(WorkOrder workOrder, Case c, CountrySetting__c countrySchedulingRule, CountrySetting__c countryDefaultBusinessHours) {
        CustomLogging.push('getPickUpDate', 'TS_LSPDatesCalculator');
        DateTime pickUpDate;
        Integer pickUpOffset = Integer.valueOf(countrySchedulingRule.PickupOffset__c);
        if(c.SubType__c == Label.TS_Order_S41 || c.SubType__c == Label.TS_Case_SubType_Swap) {
            //pickUpDate = workOrder.S41ScheduledDate__c.addDays(pickUpOffset);
            pickUpDate = workOrder.S41ScheduledDate__c;
        } else {
            return null;
        }
        
        pickUpDate = BusinessHours.nextStartDate(countryDefaultBusinessHours.Business_Hours__c, pickUpDate);
        pickUpDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, pickUpDate, pickUpOffset, true);
        //pickUpDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, pickUpDate, 1);
        CustomLogging.pop();
        return pickUpDate.date();
    }
    
    /**
    * @author        Adrian Reyes
    * @date          02.07.2018           
    * @description   Method used to calculate Movement Date
    * @revision(s)
    */
    static Date getMovementDate(WorkOrder workOrder, Case c, CountrySetting__c countrySchedulingRule, CountrySetting__c countryDefaultBusinessHours) {
        CustomLogging.push('getMovementDate', 'TS_LSPDatesCalculator');
        DateTime movementDate;
        Integer pickUpOffset = Integer.valueOf(countrySchedulingRule.PickupOffset__c);
        if(c.SubType__c == Label.TS_Order_Instype_Movement) {
            //movementDate = workOrder.S41ScheduledDate__c.addDays(pickUpOffset);
            movementDate = workOrder.S41ScheduledDate__c;
        } else {
            return null;
        }
        
        movementDate = BusinessHours.nextStartDate(countryDefaultBusinessHours.Business_Hours__c, movementDate);
        movementDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, movementDate, pickUpOffset, true);
        //movementDate = getNextBusinessDay(countryDefaultBusinessHours.Business_Hours__c, movementDate, 1);
        CustomLogging.pop();
        return movementDate.date();
    }
    
    ///**
    //* @author        Adrian Reyes
    //* @date          02.07.2018           
    //* @description   Method used to get next business day
    //* @revision(s)
    //*/
    //static DateTime getNextBusinessDay(Id businessHoursId, DateTime targetDate, Integer numberOfDays) {
    //    CustomLogging.push('getNextBusinessDay', 'TS_LSPDatesCalculator');
    //    while(!BusinessHours.isWithin(businessHoursId, targetDate))
    //        targetDate = targetDate.addDays(numberOfDays);
        
    //    CustomLogging.pop();
    //    return targetDate;
    //}

    /**
    * @author        Paul Jarred Aguiling
    * @date          3.27.2018           
    * @description   Method used to get business day
    * @revision(s)
    */
    public static DateTime getNextBusinessDay(Id businessHoursId, DateTime targetDate, Integer offSet, Boolean isNextDay) {
        CustomLogging.push('getNextBusinessDay', 'TS_LSPDatesCalculator');

        Integer num1 = isNextDay? 1 : -1; //Add additional day when isNextDay is true. Otherwise, subtract.
        Integer num2 = isNextDay? 2 : -2; //Add additional day when isNextDay is true. Otherwise, subtract.
        Integer newOffSet = offSet != null? offSet : 0;
        DateTime newTargetDate = targetDate;

        //Use offset param to indicate the loop count
        for (Integer i = 1; i <= newOffSet; i++) {
            newTargetDate = newTargetDate.addDays(num1); //Deduct or add 1 day before calculating business day

            //Check for days falling on weekends in 24/7 business hours 
            if (Label.TS_SLA_Saturday.equals(TS_UtilityClass.getReadableDay(newTargetDate.date()))) {
                newTargetDate = newTargetDate.addDays(num1);
            } else if (Label.TS_SLA_Sunday.equals(TS_UtilityClass.getReadableDay(newTargetDate.date()))) {
                newTargetDate = newTargetDate.addDays(num2);
            } 

            //Check the working day after validating weekend dates
            while(!BusinessHours.isWithin(businessHoursId, newTargetDate)) {
                newTargetDate = newTargetDate.addDays(num1);
            }
        }

        CustomLogging.pop();
        return newTargetDate;
    }

}