src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the machine for which the case is logged.</description>
        <inlineHelpText>Please indicate the machine for which you want to log a case.</inlineHelpText>
        <label>Physical Asset</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PhysicalAsset__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Machine</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrderTrigger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Header work order trigger records</description>
        <label>Work Order Trigger</label>
        <referenceTo>WorkOrderTrigger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IntegrationTriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>IntegrationTriggerSettings</label>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>UniqueNumber__c</fullName>
        <externalId>true</externalId>
        <label>Unique Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProcessBuilderSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ProcessBuilderTrigger__c) and create a CheckBox field per Object to turn the sets of trigger off/on</description>
    <fields>
        <fullName>CasePBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CasePBFlows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderPBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkOrderPBFlows</label>
        <type>Checkbox</type>
    </fields>
    <label>ProcessBuilderSettings</label>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderLineItemTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkOrderLineItemTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkOrderTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>RouteSales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderTrigger__c.object
<CustomObject>
    <description>Line Item that will be used for Installation Orders</description>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the physical asset.</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Work Order Triggers</relationshipLabel>
        <relationshipName>WorkOrderTriggers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order Trigger</label>
    <nameField>
        <displayFormat>WOT-{000000}</displayFormat>
        <label>Work Order Trigger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Triggers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TS_UpdateRelatedWorkOrder_Test.cls
/**
* @author        Marvin Gatchalian
* @date          03.26.2018        
* @description   Test class for TS_UpdateRelatedWorkOrder
* @revision(s)
*/
    
@isTest
public with sharing class TS_UpdateRelatedWorkOrder_Test {
	
	static Account acct;
    static Contact con;
    static Case c;
    static WorkOrder wo;
    static PhysicalAsset__c pa;
    static User u;
    
    
    @testSetup
    static void dataSetup() {
        //Custom settings is being shared by all test class, if another test class has already inserted the record 
        //this test class will throw "UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record"
        try {
            TriggerSettings__c trg = TriggerSettings__c.getOrgDefaults();
            trg.CaseTrigger__c = true;
            trg.WorkOrderTrigger__c = true;
            trg.WorkOrderLineItemTrigger__c = true;
            upsert trg;      
            system.debug('trg is:'+trg);
        } catch(Exception ex) {
            system.debug(ex);
        }

         try {
            IntegrationTriggerSettings__c trg1 = IntegrationTriggerSettings__c.getOrgDefaults();
            trg1.IntegrationLogTrigger__c = true;
            upsert trg1; 
        } catch(Exception ex) {
            system.debug(ex);
        }

        ProcessBuilderSettings__c pb = new ProcessBuilderSettings__c();
        pb.WorkOrderPBFlows__c = true;
        pb.CasePBFlows__c = true;
        insert pb;
    }
    
	/**
    * @author        Marvin Gatchalian
    * @date          03.26.2018            
    * @description   Method responsible for creating test data
    * @revision(s)
    */
    static void setupTestData() {
        
        
        pa = new PhysicalAsset__c(Name='Test', 
                                  UniqueNumber__c='1234567-TestMachine', 
                                  RecordTypeId = Schema.SObjectType.PhysicalAsset__c.getRecordTypeInfosByName().get('Machine').getRecordTypeId());
        insert pa;
		
        acct = new Account(Name='Account', Phone='+31302979111');
        insert acct;
        
        con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        Insert con;
        
        c = TS_TestDataFactory.createFieldServiceCase();
        c.ContactId = con.Id;
        c.Status = Label.TS_Status_InProgress;
        c.OwnerId = userinfo.getUserId();
        insert c;
        
        wo = TS_TestDataFactory.createWorkOrder();
        wo.CaseId = c.Id;
        wo.WorkOrderType__c = Label.TS_Case_SubType_CorrectMaint;
        wo.ContactId = con.Id;
        insert wo;
        
    }
    
     static testMethod void testChangeCaseOwnerId() {
         
	    setupTestData();
		u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        
         System.runAs(u) {
			 
			 Test.startTest();
				 System.debug ('Marvin >>> c.OwnerId' + c.OwnerId);
				 Case cse = [Select id, OwnerId From Case where id = :c.id];
				 cse.OwnerId = u.id;
				 update cse;
				 
	             WorkOrder wo = [Select Id, OwnerId, Case.OwnerId from WorkOrder where CaseId = :cse.id];
	             System.debug ('Marvin After Change >>> c.OwnerId' + wo.Case.OwnerId);
                 System.assertEquals(wo.Case.OwnerId, wo.OwnerId);
                 
             Test.stopTest();
         }
     }
    
    
    
}