src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the account location of the  Physical Asset</description>
        <inlineHelpText>Indicates the account location of the  Physical Asset</inlineHelpText>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Country codes</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IntegrationTriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>IntegrationTriggerSettings</label>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Is_Country_Standard_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It is true for (custom pricebook) that defines Standard Price for a Country.
It is false for nonstandard price</description>
        <label>Is Country Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Is_Country_Standard_Price__c</fullName>
        <formula>Pricebook2.Is_Country_Standard_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Country Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OldStandardPrice__c</fullName>
        <label>Old Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/ProcessBuilderSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ProcessBuilderTrigger__c) and create a CheckBox field per Object to turn the sets of trigger off/on</description>
    <fields>
        <fullName>CasePBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CasePBFlows</label>
        <type>Checkbox</type>
    </fields>
    <label>ProcessBuilderSettings</label>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderLineItemTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkOrderLineItemTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty__c</fullName>
        <label>Billing Information</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>K1</fullName>
                    <label>Under Warranty</label>
                </value>
                <value>
                    <fullName>YR</fullName>
                    <label>Covered By Contract</label>
                </value>
                <value>
                    <fullName>Z1</fullName>
                    <label>Coulance (Goodwill)</label>
                </value>
                <value>
                    <fullName>C1</fullName>
                    <label>To be paid by Customer</label>
                </value>
                <value>
                    <fullName>None</fullName>
                    <label>Not Covered</label>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_CreateOrderSvcPartsController_Test.cls
/**
* @author        Paul Jarred Aguiling
* @date          06.03.2018
* @description   Test class for TS_CreateOrderSvcPartsController
* @revision(s)
*/
@isTest
private class TS_CreateOrderSvcPartsController_Test {
	
    static Account acct;
    static Contact con;
    static Case c;

   /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018         
    * @description   Method responsible for creating custom setting records
    * @revision(s)
    */
    @testSetup
    static void dataSetup() {
        TriggerSettings__c trg = TriggerSettings__c.getOrgDefaults();
        trg.WorkOrderLineItemTrigger__c = true;
        upsert trg;
        
        IntegrationTriggerSettings__c trg1 = IntegrationTriggerSettings__c.getOrgDefaults();
        trg1.IntegrationLogTrigger__c = true;
        upsert trg1;
        
        ProcessBuilderSettings__c pb = new ProcessBuilderSettings__c();
        pb.CasePBFlows__c = true;
        insert pb;  
    }
    
    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Method responsible for creating test data
    * @revision(s)
    */
    static void setupTestData() {
        acct = new Account(Name='Account', Phone='+31302979111');
        //acct.Segment__c = 'SAP_A';
        //acct.High_Segment__c = 'Business';
        insert acct;
        
        con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        Insert con;
        
        Apttus_Config2__AccountLocation__c accLoc = new Apttus_Config2__AccountLocation__c();
        accLoc.Name = 'Test Loc';
        accLoc.Apttus_Config2__AccountId__c = acct.id;
        accLoc.Customer_calendar_key__c = 'SAP_01';
        insert accLoc; 

        c = TS_TestDataFactory.createFieldServiceCase();
        c.ContactId = con.Id;
        c.SalesOrganization__c = 'SAP_0333';
        c.AccountLocation__c = accLoc.Id;
        insert c;
    }
	
    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for fetchPicklistValues
    * @revision(s)
    */
	static testmethod void test_fetchPicklistValues() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
            Test.startTest();
	            List<String> result = TS_CreateOrderSvcPartsController.fetchPicklistValues('WorkOrderLineItem', 'Warranty__c');
	            System.assert(result != null);
            Test.stopTest();
        }
	}

    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for convertOrderServer Required Parts Scenario
    * @revision(s)
    */
	static testmethod void test_convertOrderServer() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
        	setupTestData();
	        Product2 prod = new Product2(Name = 'Laptop X200', 
	            Family = 'Hardware');
	        insert prod;
	        
	        Id pricebookId = Test.getStandardPricebookId();
	        
	        PricebookEntry standardPrice = new PricebookEntry(
	            Pricebook2Id = pricebookId, Product2Id = prod.Id,
	            UnitPrice = 10000, IsActive = true);
	        insert standardPrice;

	        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', 
	        	isActive=true, 
	        	Is_Country_Standard_Price__c = true,
	        	Sales_Organization__c = 'SAP_0333');
	        insert customPB;
	        
	        PricebookEntry customPrice = new PricebookEntry(
	            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
	            UnitPrice = 12000, OldStandardPrice__c=100.0, IsActive = true);
	        insert customPrice;

        	TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass wrapper = new TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass();
        	wrapper.partType = 'RequiredSpareparts';
        	wrapper.existing = true;
        	wrapper.directTo = false;
        	wrapper.woPBId = pricebookId;
        	wrapper.taskpbEntryId = standardPrice.Id;
        	wrapper.matType = 'ZSPR';
        	wrapper.quantity = 1;
        	wrapper.wolipbEntry = standardPrice;
        	wrapper.billingInfo = 'K1';

			List<Object> addList = new List<Object>();
			addList.add(wrapper);
	        String jSONClass = JSON.serialize(addList);

        	Test.startTest();
        		String result = TS_CreateOrderSvcPartsController.convertOrderServer(c.Id, jSONClass);
        		System.assert(result != null);
        	Test.stopTest();
        }
    }

   /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for convertOrderServer Service Materials Scenario
    * @revision(s)
    */
	static testmethod void test_convertOrderServer2() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
        	setupTestData();
	        Product2 prod = new Product2(Name = 'Laptop X200', 
	            Family = 'Hardware');
	        insert prod;
	        
	        Id pricebookId = Test.getStandardPricebookId();
	        
	        PricebookEntry standardPrice = new PricebookEntry(
	            Pricebook2Id = pricebookId, Product2Id = prod.Id,
	            UnitPrice = 10000, IsActive = true);
	        insert standardPrice;

	        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', 
	        	isActive=true, 
	        	Is_Country_Standard_Price__c = true,
	        	Sales_Organization__c = 'SAP_0333');
	        insert customPB;
	        
	        PricebookEntry customPrice = new PricebookEntry(
	            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
	            UnitPrice = 12000, OldStandardPrice__c=100.0, IsActive = true);
	        insert customPrice;

        	TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass wrapper = new TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass();
        	wrapper.partType = 'Service Materials';
        	wrapper.existing = true;
        	wrapper.directTo = false;
        	wrapper.woPBId = pricebookId;
        	wrapper.taskpbEntryId = standardPrice.Id;
        	wrapper.matType = 'ZSPR';
        	wrapper.quantity = 1;
        	wrapper.wolipbEntry = standardPrice;
        	wrapper.billingInfo = 'K1';

			List<Object> addList = new List<Object>();
			addList.add(wrapper);
	        String jSONClass = JSON.serialize(addList);

        	Test.startTest();
        		String result = TS_CreateOrderSvcPartsController.convertOrderServer(c.Id, jSONClass);
        		System.assert(result != null);
        	Test.stopTest();
        }
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for convertOrderServer Exception
    * @revision(s)
    */
	static testmethod void test_convertOrderServerException() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
	        Test.startTest();

	        	TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass wrapper = new TS_CreateOrderSvcPartsController.WorkOrderLineItemWrapperClass();
	        	wrapper.partType = 'Service Materials';
	        	wrapper.existing = true;
	        	wrapper.directTo = false;
	        	wrapper.woPBId = null;
	        	wrapper.taskpbEntryId = null;
	        	wrapper.matType = 'ZSPR';
	        	wrapper.quantity = 1;
	        	wrapper.wolipbEntry = null;
	        	wrapper.billingInfo = 'K1';

				List<Object> addList = new List<Object>();
				addList.add(wrapper);
		        String jSONClass = JSON.serialize(addList);
	        	String result;

	        	try {
		        	result = TS_CreateOrderSvcPartsController.convertOrderServer(null, jSONClass);
		        } catch(Exception e) {
			        System.assert(result != null);
		        }
	        Test.stopTest();
        }
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for retrievePricebookEntry
    * @revision(s)
    */
	static testmethod void test_retrievePricebookEntry() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
        	Product2 prod = new Product2(Name = 'Laptop X200', 
	        Family = 'Hardware');
	        insert prod;
	        
	        Id pricebookId = Test.getStandardPricebookId();
	        
	        PricebookEntry standardPrice = new PricebookEntry(
	            Pricebook2Id = pricebookId, Product2Id = prod.Id,
	            UnitPrice = 10000, IsActive = true);
	        insert standardPrice;

	        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', 
	        	isActive=true, 
	        	Is_Country_Standard_Price__c = true,
	        	Sales_Organization__c = 'SAP_0333');
	        insert customPB;
	        
	        PricebookEntry customPrice = new PricebookEntry(
	            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
	            UnitPrice = 12000, OldStandardPrice__c=100.0, IsActive = true);
	        insert customPrice;

	        Test.startTest();
		        Object obj = TS_CreateOrderSvcPartsController.retrievePricebookEntry('SAP_0333', prod.Id);
		        System.assert(obj != null);
	        Test.stopTest();
        }
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          06.03.2018        
    * @description   Test method for retrievePricebookEntry
    * @revision(s)
    */
	static testmethod void test_retrievePricebookEntryException() {
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
	        Test.startTest();
	        	Object obj;
	        	try {
		        	obj = TS_CreateOrderSvcPartsController.retrievePricebookEntry(null, null);
		        } catch(Exception e) {
			        System.assert(obj == null);
		        }
	        Test.stopTest();
        }
    }
}