src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the account location of the  Physical Asset</description>
        <inlineHelpText>Indicates the account location of the  Physical Asset</inlineHelpText>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseSubStatus__c</fullName>
        <description>More Detailed status</description>
        <inlineHelpText>More Detailed status for case records</inlineHelpText>
        <label>Case Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Order Open</fullName>
                </value>
                <value>
                    <fullName>Order Sent to Planning</fullName>
                </value>
                <value>
                    <fullName>Order Sent to Field</fullName>
                </value>
                <value>
                    <fullName>Review Needed</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Feedback</fullName>
                </value>
                <value>
                    <fullName>Awaiting Customer Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Feedback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreatedOrderedManually__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Order Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the machine for which the case is logged.</description>
        <inlineHelpText>Please indicate the machine for which you want to log a case.</inlineHelpText>
        <label>Physical Asset</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>PhysicalAsset__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Machine</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLADate__c</fullName>
        <description>Indicates the SLA time to resolve the case and will be automatically calculated.</description>
        <label>SLA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Country codes</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>CaseRegistration</fullName>
        <active>true</active>
        <businessProcess>Case Registration</businessProcess>
        <description>Record type that will serve as default for all case records</description>
        <label>Case Registration</label>
    </recordTypes>
    <recordTypes>
        <fullName>FieldService</fullName>
        <active>true</active>
        <businessProcess>Field Service Process</businessProcess>
        <description>All cases where a visit by an engineer is required</description>
        <label>Field Service Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the account location where the asset is located at.</description>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>This indicates the sales organization / region to which the machine is sold to.</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UniqueNumber__c</fullName>
        <externalId>true</externalId>
        <label>Unique Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/ProcessBuilderSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ProcessBuilderTrigger__c) and create a CheckBox field per Object to turn the sets of trigger off/on</description>
    <fields>
        <fullName>CasePBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CasePBFlows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Enable process builder on Resource__c object</description>
        <label>Resource</label>
        <type>Checkbox</type>
    </fields>
    <label>ProcessBuilderSettings</label>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>This object collects the information  that is needed for linking Engineer information to Work Orders for reporting purposes.</description>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>SAP Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>CaseTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CaseTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to case object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>WorkOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JDELineItemNumber__c</fullName>
        <externalId>true</externalId>
        <label>JDE Line Item Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the physical asset applicable for the work.</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Service Jobs</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLADate__c</fullName>
        <description>TS: Indicates the SLA date for the line item.</description>
        <label>SLA Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_RecordHeaderControllerTest.cls
/**
* @author        Rey Austral
* @date          10.2.2017           
* @description   Test Class for TS_RecordHeaderController
* @revision(s)
*/
@isTest
public class TS_RecordHeaderControllerTest {
    
    @testSetup static void dataSetup() {        
        Contact con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        Insert con;
        
        Resource__c testResource = TS_TestDataFactory.createResourceSingle('Test Resource Number');
        insert testResource;
        
        List<Account> accountList = TS_TestDataFactory.createAccounts(1);
        accountList.get(0).Name = 'SendToClick_Test Name';
        insert accountList;
        
        Apttus_Config2__AccountLocation__c alocation = TS_TestDataFactory.createAccountLocation( accountList.get(0).Id );
        alocation.Apttus_Config2__PostalCode__c   = '123';
        alocation.Shipping_Country_ISO__c = 'NL';
        alocation.Shipping_Street_Only__c = '1';
        alocation.Apttus_Config2__City__c = 'city';
        insert alocation;
        
        // Instantiate the Pricebook2 record first, setting the Id
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        
        // Run an update DML on the Pricebook2 record
        // This is the weird workaround that enables IsStandard to become true
        // on the PricebookEntry record
        update standardPricebook;
        
        Pricebook2 standardPB = [SELECT Id FROM Pricebook2 WHERE isStandard = true];
        
        Product2 prod = TS_TestDataFactory.createProduct('name','family');
        prod.ProductCode = 'prod';
        insert prod;
        
        Pricebook2 pb = new pricebook2(Name='test', IsActive = true, Sales_Organization__c = 'SAP_0333');
        insert pb;
        
        Pricebook2 pb2 = new pricebook2(Name='test2', IsActive = true, Sales_Organization__c = 'SAP_0111');
        insert pb2;
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 10000, IsActive = true, UseStandardPrice = false);
        insert standardPrice;
        
        PricebookEntry newProduct = new PricebookEntry (Pricebook2Id = pb2.id, Product2Id = prod.id, IsActive=true, UseStandardPrice = false, UnitPrice=100.0);
        insert newProduct;
        
        PhysicalAsset__c testAsset = new PhysicalAsset__c();
        testAsset.RecordTypeId = TS_UtilityClass.getRecordTypeIdByName('PhysicalAsset__c', 'Machine');
        testAsset.Name = 'Test Asset';
        testAsset.UniqueNumber__c = '1234567890';
        testAsset.AccountLocation__c = alocation.Id;
        insert testAsset;
        
        ProcessBuilderSettings__c pbTest = new ProcessBuilderSettings__c();
        pbTest.CasePBFlows__c = true;
        insert pbTest;
        
        Case cseData = TS_TestDataFactory.createFieldServiceCase();
        cseData.AccountId = accountList[0].Id;
        cseData.ContactId = con.Id;       
        cseData.SalesOrganization__c = 'SAP_0111';
        cseData.Subject = 'Bas';
        cseData.Description = 'Bas';
        cseData.Priority = 'Medium';
        cseData.PhysicalAsset__c = testAsset.Id;
        cseData.SLADate__c = System.now() + 7;
        insert cseData;
    }
    
    @isTest static void test_FollowFunction() {
        
        Case cse = [SELECT Id, Subject FROM Case WHERE Subject = 'Bas' LIMIT 1];
        Test.startTest();
        
        TS_RecordHeaderController.hasException = true;
        
        Boolean checkIfFollowing = TS_RecordHeaderController.isFollowingCheck(cse.Id);
        System.assertEquals(false, checkIfFollowing);
        
        TS_RecordHeaderController.followRecord(cse.Id);
        checkIfFollowing = TS_RecordHeaderController.isFollowingCheck(cse.Id);
        System.assertEquals(true, checkIfFollowing);
        
        TS_RecordHeaderController.unfollowRecord(cse.Id);
        checkIfFollowing = TS_RecordHeaderController.isFollowingCheck(cse.Id);
        System.assertEquals(false, checkIfFollowing);
        
        TS_RecordHeaderController.getCaseAccess(cse.Id);
        
        Test.stopTest();
    }
    
    @isTest static void test_InsertComment() {
        
        Case cse = [SELECT Id, Subject FROM Case WHERE Subject = 'Bas' LIMIT 1];
        Test.startTest();
        TS_RecordHeaderController.insertComments(cse.Id, 'Test Comment');
        Test.stopTest();
        
        List<CaseComment> ccList = [Select id from CaseComment where ParentId =: cse.Id];
        System.assertEquals(1, ccList.size());
    }
    
    @isTest static void test_getRecordTypeAndUser() {
        
        Case cse = [SELECT Id, Subject FROM Case WHERE Subject = 'Bas' LIMIT 1];
        Test.startTest();		
        String recordName = TS_RecordHeaderController.getRecordType(cse.Id);
        String loginName = TS_RecordHeaderController.currentUserId();
        String accessCheck = TS_RecordHeaderController.checkButtonAccess();
        Test.stopTest();
        System.assertNotEquals('', recordName);
        System.assertNotEquals('', loginName);
        System.assertNotEquals('', accessCheck);
    }
    
    @isTest static void test_getRecordTypeIds() {
        Test.startTest();		
        String fieldService = TS_RecordHeaderController.getRecordTypeFS();
        String caseRegistration = TS_RecordHeaderController.getRecordTypeCR();
        String serviceJob = TS_RecordHeaderController.getRecordTypeAS();
        String inboundTask = TS_RecordHeaderController.getRecordTypeInboundTask();
        String addServiceJob = TS_RecordHeaderController.getRecordTypeGeneric('WorkOrderLineItem', 'Register Task');
        Test.stopTest();
        
        System.assertNotEquals('', fieldService);
        System.assertNotEquals('', caseRegistration);
        System.assertNotEquals('', serviceJob);
        System.assertNotEquals('', inboundTask);
        System.assertNotEquals('', addServiceJob);
    }
    
    @isTest static void test_createOrderClass() {
        
        Id taskId = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByName().get('Register Task').getRecordTypeId();
        Id partsId = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByName().get('Register Required Part').getRecordTypeId();
        
        Case cse = [SELECT Id, Subject, Status, CaseSubStatus__c, CreatedOrderedManually__c, RecordTypeId FROM Case WHERE Subject = 'Bas' LIMIT 1];
        
        TriggerSettings__c trg = TriggerSettings__c.getOrgDefaults();
        trg.CaseTrigger__c = true;
        upsert trg; 
        
        Case qCase = TS_RecordHeaderController.queryCase(cse.Id);
        
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        TS_RecordHeaderController.executeTakeOwnership(cse.Id, u.Id, 'New');
        TS_RecordHeaderController.changeOwner(cse.Id, u.Id);
        
        String orderResult = TS_RecordHeaderController.createOrderClass(cse.Id);
        System.assertEquals('SUCCESS', orderResult);
        
        Case cseUpdated = [SELECT Id, Subject, Status, CaseSubStatus__c, CreatedOrderedManually__c, SLADate__c, RecordTypeId FROM Case WHERE Id =: cse.Id LIMIT 1];
        System.assertEquals('In progress', cseUpdated.Status);
        System.assertEquals('Order Open', cseUpdated.CaseSubStatus__c);
        System.assertEquals(true, cseUpdated.CreatedOrderedManually__c);
        
        TS_RecordHeaderController.counters(cseUpdated.Id);
        //System.assertEquals(1, count);
        
        Test.startTest();
        
        WorkOrder wo = TS_RecordHeaderController.getFirstWOinCase(cseUpdated.Id);
        
        String getSLADate = TS_RecordHeaderController.getCorrectSLADate(cseUpdated);
        
        List<WorkOrderLineItem> openTaskList = TS_RecordHeaderController.getOpenTasks(cseUpdated.Id);
        TS_RecordHeaderController.getScheduledAndOpenTasks(cseUpdated.Id, false);
        
        //Test Search WOLI via JDELineItemNumber__c - Jan. 21, 2019 Xen Reyes
        List<WorkOrderLineItem> searchRes = TS_RecordHeaderController.getWorkOrderLineItemSearch(openTaskList[0].JDELineItemNumber__c);
        String getInfo = TS_RecordHeaderController.getInfoForTask();
        String inboundRecordTypeId = TS_RecordHeaderController.getRecordTypeInboundTask();
        
        WorkOrderLineItem toBeScheduled = openTaskList[0];
        toBeScheduled.Status = 'Scheduled';
        update toBeScheduled;
        
        List<WorkOrderLineItem> scheduled = TS_RecordHeaderController.getScheduledTasks(cseUpdated.Id, false);
        System.assertEquals(1, scheduled.size());
        
        Product2 prod = [SELECT Id FROM Product2 WHERE ProductCode = 'prod'];
        Pricebook2 pbook = [SELECT Id FROM Pricebook2 WHERE Name = 'test2'];
        PricebookEntry prodAsset = [SELECT Id FROM PricebookEntry WHERE Pricebook2Id =: pbook.Id AND Product2Id =: prod.Id];
        
        WorkOrderLineItem newRequiredPart = new WorkOrderLineItem();
        newRequiredPart.RecordTypeId = partsId;
        newRequiredPart.WorkOrderId = wo.Id;
        newRequiredPart.Case__c = cseUpdated.Id;
        newRequiredPart.WorkOrderLineItemType__c = 'RequiredSpareparts';
        newRequiredPart.ParentWorkOrderLineItemId = toBeScheduled.Id;
        newRequiredPart.Quantity = 1;
        newRequiredPart.PricebookEntryId = prodAsset.Id;
        insert newRequiredPart;
        
        String updateParts = TS_RecordHeaderController.updateRequiredParts(new List<String>{newRequiredPart.Id});
        System.assertEquals('SUCCESS', updateParts);
        
        List<WorkOrderLineItem> getReqs = TS_RecordHeaderController.getReqParts(cseUpdated.Id);
        
        TS_RecordHeaderController.AddServiceWrapper add = TS_RecordHeaderController.queryAddService(cseUpdated.Id, prod.Id);
        
        WorkOrderLineItem schTask = scheduled[0];
        String reschedule = TS_RecordHeaderController.rescheduleApppointment(cseUpdated.Id, new List<String>{schTask.Id}, System.now() + 1 , System.now() + 3);
        
        schTask.Status = 'Open';
        update schTask;
        
        Resource__c res = [SELECT Id FROM Resource__c WHERE Name = 'Test Resource Number' LIMIT 1];
        String schedOpen = TS_RecordHeaderController.scheduleOpenTask(System.now() + 1, System.now() + 5, res.Id, false, new List<String>{schTask.Id});
        //System.assertEquals('SUCCESS', schedOpen);
        
        Test.stopTest();
    }
    
    @isTest static void test_getCaseRecord() {
        
        Case cse = [SELECT Id, Subject FROM Case WHERE Subject = 'Bas' LIMIT 1];
        Test.startTest();
        Case cse2 = TS_RecordHeaderController.getCaseRecord(cse.Id);
        System.assertEquals(cse.Id, cse2.Id);
        Test.stopTest();
    }
    
    @isTest static void test_getObjectTypeOfRecord() {
        
        Case cse = [SELECT Id, Subject FROM Case WHERE Subject = 'Bas' LIMIT 1];
        Test.startTest();
        String objType = TS_RecordHeaderController.getObjectTypeOfRecord(cse.Id);
        System.assertEquals('Case', objType);
        Test.stopTest();
    }
    
    @isTest static void test_picklistValues() {
        
        Test.startTest();
        Map<String, String> getMapPL = TS_RecordHeaderController.getPicklistValuesMap('Case', 'Type');
        Map<String, List<String>> getMapListPL = TS_RecordHeaderController.getPLvalueOption2('Case', 'Type', 'SubType__c');
        Map<String,TS_PicklistEntryWrapper> getMapListPL2 = TS_RecordHeaderController.getPLvalueOption3('Case', 'Type', 'SubType__c');
        Map<String, TS_PicklistEntryWrapper> getValues = TS_RecordHeaderController.getDependentValue('Case', 'Type', 'SubType__c');
        Test.stopTest();
    }
    
    @isTest static void test_Exception() {
        
        Case cse = [SELECT Id, Subject, Status, CaseSubStatus__c, CreatedOrderedManually__c, RecordTypeId FROM Case WHERE Subject = 'Bas' LIMIT 1];
        
        Test.startTest();
        
        TS_RecordHeaderController.hasException = true;
        
        String orderResult = TS_RecordHeaderController.createOrderClass(cse.Id);
        String recordName = TS_RecordHeaderController.getRecordType(cse.Id);
        Case csTest = TS_RecordHeaderController.getCaseRecord(cse.Id);
        
        //System.assertEquals('Force to throw an exception', orderResult);
        
        /* String recordName = TS_RecordHeaderController.getRecordType(cse.Id);
		System.assertEquals('Force to throw an exception', recordName); */
        
        Test.stopTest();
    }
    
}