src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Disaster_Recovery__c.object
<CustomObject>
    <description>This object is used as a staging table to generate disaster recovery records.</description>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the Account Location for which the case was logged.</description>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Disaster Recovery</relationshipLabel>
        <relationshipName>Disaster_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Already_Processed__c</fullName>
        <formula>(TS_Case_Reference__c != null &amp;&amp; TS_Work_Order_Reference__c != null &amp;&amp; TS_Work_Order_Line_Item_Reference__c != null)
||
(TS_Case_Reference__c != null &amp;&amp; TS_Work_Order_Reference__c == null &amp;&amp; TS_Work_Order_Line_Item_Reference__c == null &amp;&amp; !WorkOrderRequired__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Already Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CoffeeIsRunning__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This indicates whether the customer indicated whether the customer was running during call intake.</description>
        <label>Coffee Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the contact for who the case needs to be registered for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Disaster Recovery</relationshipLabel>
        <relationshipName>Disaster_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This indicates the description.</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Physical_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the machine for which you want to create a case for.</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Disaster Recovery</relationshipLabel>
        <relationshipName>Disaster_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the product for which the case was logged.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Disaster Recovery</relationshipLabel>
        <relationshipName>Disaster_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>This indicates the subject of the case.</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkOrderRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This indicates whether a work order is required.</description>
        <label>Work Order Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <description>This indicates the type of order which needs to be created.</description>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Disaster Recovery</label>
    <nameField>
        <displayFormat>DR-{0}</displayFormat>
        <label>Disaster Recovery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disaster Recovery</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the account location where the asset is located at.</description>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActiveContract__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AssetStatus__c</fullName>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                    <default>true</default>
                    <label>Pending Activation</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Machine_Care__c</fullName>
        <description>Global Picklist used on other objects as well ( Operating Tasks)</description>
        <label>Machine Care</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_MachineCare</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the product used for the asset.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>This indicates the sales organization / region to which the machine is sold to.</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TypeOfContract__c</fullName>
        <label>Type Of Contract</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Consumption</fullName>
                    <label>Consumption Model</label>
                </value>
                <value>
                    <fullName>Free On Loan</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>RentBuy</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TS_Load_Id__c</fullName>
        <externalId>true</externalId>
        <label>Load Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>APTS_Material_Type__c</fullName>
        <description>SAP Material Type, Used in EPI Integration
/ZMATMAS03I/IDOC/E1MARAM/MTART</description>
        <label>Material_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TS_DisasterRecoveryBatch_Test.cls
/**
* @author        Marvin Gatchalian
* @date          19.April.2018
* @description   Test class for TS_DisasterRecoveryBatch.
* @revision(s)
*/

@isTest
public with sharing class TS_DisasterRecoveryBatch_Test {
    
    
    
    public static void dataSetup() {
		List <Disaster_Recovery__c> drToInsert = new List <Disaster_Recovery__c> ();
        id rtpa = TS_UtilityClass.getRecordTypeIdByName('PhysicalAsset__c', 'Machine');
        Id caseRecTypeId = TS_UtilityClass.getRecordTypeIdByName(Label.TS_Obj_API_Name_DR, Label.TS_Obj_API_Name_Case);
        
        Account acct = new Account ();
        Contact con = new Contact();
        
        Apttus_Config2__AccountLocation__c acctLocSingle = new  Apttus_Config2__AccountLocation__c();
        for(Apttus_Config2__AccountLocation__c acctLoc : TestDataFactory.createAccountLocation(1)){
            acctLocSingle = acctLoc;
        }
        insert acctLocSingle;    
        
        product2 prod = new product2();
        prod.Name = 'Operating Sched Product Test';
        prod.APTS_Material_Type__c = 'ZSPR';
        insert prod;
        
        //Create sales org pricebook
        pricebook2 orgPB = new pricebook2();
        orgPB.name = 'BE Price Book';
        orgPB.IsActive = true;
        orgPB.Sales_Organization__c = 'SAP_0333';
        insert orgPB;
        
        //Create Pricebookentry with standard and sales org pricebook
        pricebookentry pbe = new pricebookentry();
        pbe.product2id = prod.id;
        pbe.pricebook2id = Test.getStandardPricebookId();
        pbe.UnitPrice = 1;
        pbe.IsActive = true;
        //pbe.TS_Load_Id__c = String.valueOf(p.id) + String.valueOf(Test.getStandardPricebookId());
        insert pbe;
        
        pbe = new pricebookentry();
        pbe.product2id = prod.id;
        pbe.pricebook2id = orgPB.id;
        pbe.UnitPrice = 11;
        pbe.IsActive = true;
        insert pbe;
        
        PhysicalAsset__c pa = TS_TestDataFactory.createPhysicalAsset();
        pa.RecordTypeId = rtpa;
        pa.Machine_Care__c = 'Full Operating';
        pa.StartDate__c = date.today().addDays(-365);
        pa.EndDate__c = date.today().addDays(365);
        pa.TypeOfContract__c = 'Sales';
        pa.AssetStatus__c = 'Activated';
        pa.ActiveContract__c = true;
        pa.SalesOrganization__c = 'SAP_0333';
        pa.Product__c = prod.id;
        pa.AccountLocation__c = acctLocSingle.id;
        insert pa;
        
        acct = new Account(Name='Account', Phone='+31302979111');
        //acct.Segment__c = 'SAP_A';
        //acct.High_Segment__c = 'Business';
        insert acct;
        
        con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        con.AccountId = acct.id;
        Insert con;
        
        for (Integer i = 0; i < 20; i++) {
            Disaster_Recovery__c newDr = new Disaster_Recovery__c();
            newDr.Subject__c = 'Test' + i;
            newDR.Description__c = 'Test' + i;
            newDR.Contact__c = con.id;
            newDR.Physical_Asset__c = pa.id;
            newDR.CoffeeIsRunning__c = true;
            newDR.WorkOrderRequired__c = true;
            newDR.WorkOrderType__c = 'S10';
            newDR.RecordTypeId = caseRecTypeId;
            newDR.SalesOrganization__c = 'SAP_0333';
            drToInsert.add(newDr);
        }
        insert drToInsert;
		
    }

    private static testMethod void TS_DisasterRecovery_Batch() {
		dataSetup();
		
		Test.startTest();
			TS_DisasterRecoveryBatch  dr = new TS_DisasterRecoveryBatch ();
        	Database.executeBatch(dr, 20);
		Test.stopTest();
		System.assertEquals(20, [Select id from Disaster_Recovery__c where Already_Processed__c = true].size());
	    	
    }
			
}