src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Archiving_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archiving Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buyer All</fullName>
                </value>
                <value>
                    <fullName>Buyer Ingredients</fullName>
                </value>
                <value>
                    <fullName>Buyer Machines</fullName>
                </value>
                <value>
                    <fullName>Service Contact</fullName>
                </value>
                <value>
                    <fullName>Payment Responsible</fullName>
                </value>
                <value>
                    <fullName>Invoices Responsible</fullName>
                </value>
                <value>
                    <fullName>Digital Invoices Responsible</fullName>
                </value>
                <value>
                    <fullName>Catering Responsible</fullName>
                </value>
                <value>
                    <fullName>Goods Recipient Contact</fullName>
                </value>
                <value>
                    <fullName>Administrative Contact</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Personnel</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Head of Purchasing</fullName>
                </value>
                <value>
                    <fullName>Head of Sales</fullName>
                </value>
                <value>
                    <fullName>Head of Personnel</fullName>
                </value>
                <value>
                    <fullName>Janitor</fullName>
                </value>
                <value>
                    <fullName>Head of Canteen</fullName>
                </value>
                <value>
                    <fullName>Secretary</fullName>
                </value>
                <value>
                    <fullName>Route Sales Responsible</fullName>
                </value>
                <value>
                    <fullName>Fin. Acc. Manager</fullName>
                </value>
                <value>
                    <fullName>Marketing Manager</fullName>
                </value>
                <value>
                    <fullName>Charges Responsible</fullName>
                </value>
                <value>
                    <fullName>Purchasing Responsible</fullName>
                </value>
                <value>
                    <fullName>Head of Section</fullName>
                </value>
                <value>
                    <fullName>Merchandise Recept.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DK</fullName>
                </value>
                <value>
                    <fullName>EN</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Relevant_Activity_Date__c</fullName>
        <label>Last Relevant Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Lifecycle__c</fullName>
        <label>Account Lifecycle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_AccountLifecycle</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <formula>TEXT(Partner_Contact__r.Function__c)</formula>
        <label>Function</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Account Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Segment</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProcessBuilderSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ProcessBuilderTrigger__c) and create a CheckBox field per Object to turn the sets of trigger off/on</description>
    <fields>
        <fullName>OpportunityPBFlows__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OpportunityPBFlows</label>
        <type>Checkbox</type>
    </fields>
    <label>ProcessBuilderSettings</label>
</CustomObject>

src/classes/UpdateOpportunityContactsTest.cls
/**
    * @author        Alvin Lomod
    * @date          02.02.2018 - Alvin Lomod KASM-1017         
    * @description   Test Class of UpdateOpportunityContacts
    * @revision(s)   
    */
@isTest
private class UpdateOpportunityContactsTest{
    
    private static testMethod void UpdateOpportunityContactRoles(){
        
        insert new ProcessBuilderSettings__c(SetupOwnerId = UserInfo.getOrganizationId(), OpportunityPBFlows__c = true);
        
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        acc1.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.Customer).getRecordTypeId();
        acc1.Main_Street_Only__c = 'Test Street';
        acc1.Main_Postal_Code__c = '1000';
        acc1.Industry_Code__c = '100';
        acc1.Phone = '+1234567890';
        acc1.CurrencyIsoCode = 'EUR';
        acc1.Language__c = 'SAP_EN';
        acc1.Sales_Organization__c = 'SAP_0333';
        acc1.Account_Type__c = 'Customer';
        acc1.Segment__c = 'SAP_A'; //Indicator for change of rule
        acc1.of_Beds__c = 10;
        acc1.of_drinks__c = 10;        
        acc1.of_Employees_FTE__c = 10;
        acc1.Exclude_from_Territory_Assignment__c = false;
        acc1.of_Seats__c = 10;
        acc1.Account_Lifecycle__c = 'Active Customer';
        
        insert acc1;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'Test Opp1';
        opp1.AccountId = acc1.Id;
        opp1.CloseDate = Date.Today().addDays(10);
        opp1.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(SM_Constants.OpptRecTypeStandard).getRecordTypeId();
        opp1.StageName = 'Open';
        
        insert opp1;
        
        List<Contact> conList = new List<Contact>();
        Contact con;
        for(Integer i = 0; i < 3; i++){
            
            con = new Contact();
            con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(SM_Constants.ContactStandard).getRecordTypeId();
            con.AccountId = acc1.Id;
            con.Function__c = 'Director';
            con.Preferred_Language__c = 'SAP_EN';
            con.Email = 'test'+ String.valueOf(i)+ '@test.com';
            con.FirstName = 'FirstTest' + i;
            con.LastName = 'LastTest' + i;
            conList.add(con);
            
        }
        
        conList[0].Phone = '+02139141203';
        conList[0].Last_Relevant_Activity_Date__c = Date.Today().addDays(-1);
        conList[1].Phone = '+02139141432';
        conList[1].Last_Relevant_Activity_Date__c = Date.Today().addDays(-2);
        conList[1].IsActive__c = false;
        conList[1].Archiving_Flag__c = true;
        conList[2].Phone = '+02139141598';
        conList[2].Last_Relevant_Activity_Date__c = Date.Today().addDays(4);
        
        insert conList;
        
        List<OpportunityContactRole> ocrList = new List<OpportunityContactRole>();
        OpportunityContactRole ocr;
        for(Integer i = 0; i < 3; i++){
            
            ocr = new OpportunityContactRole();
            ocr.ContactId = conList[i].Id;
            ocr.OpportunityId = opp1.Id;
            ocr.Role = 'Decision Maker';
            
            ocrList.add(ocr);
        }
        
        insert ocrList;
        
        System.debug('ocrList: ' + ocrList);
        opp1.Comments__c = 'test';
        
        update opp1;
        System.debug('opp1: ' + opp1);
        
        List<Contact> updatedConList = [SELECT Id, Last_Relevant_Activity_Date__c, IsActive__c, Archiving_Flag__c FROM Contact];
        system.assertEquals(updatedConList[0].Last_Relevant_Activity_Date__c, Date.Today());
        system.assertEquals(updatedConList[1].Last_Relevant_Activity_Date__c, Date.Today());
        system.assertEquals(updatedConList[1].IsActive__c, true);
        system.assertEquals(updatedConList[1].Archiving_Flag__c, false);
        system.assertEquals(updatedConList[2].Last_Relevant_Activity_Date__c, Date.Today().addDays(4));
        
        
    }

}