src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IntegrationTriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>IntegrationTriggerSettings</label>
</CustomObject>

src/objects/ProcessBuilderSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (ProcessBuilderTrigger__c) and create a CheckBox field per Object to turn the sets of trigger off/on</description>
    <fields>
        <fullName>CasePBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CasePBFlows</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Enable process builder on Resource__c object</description>
        <label>Resource</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderPBFlows__c</fullName>
        <defaultValue>true</defaultValue>
        <label>WorkOrderPBFlows</label>
        <type>Checkbox</type>
    </fields>
    <label>ProcessBuilderSettings</label>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>This object collects the information  that is needed for linking Engineer information to Work Orders for reporting purposes.</description>
    <fields>
        <fullName>ActiveUser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates that a user is active or not.</description>
        <label>Active User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>Email Address</label>
        <length>241</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeFirstName__c</fullName>
        <label>Employee First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeLastName__c</fullName>
        <label>Employee Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <description>This field is used to specify the nickname of the user.</description>
        <label>Nickname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a relationship to the contact required for a third party user (customer community user) being created in the system.</description>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Resources</relationshipLabel>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequiresClickUser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates whether the user needs to have a click user.</description>
        <label>Requires Click User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TeamNumber__c</fullName>
        <description>CR- 1609 Adding Team and Team Number to Interface 1374-1609-447</description>
        <label>Team Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserProfile__c</fullName>
        <description>This field indicates the user profile required.</description>
        <label>User Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Third Party Capacity</fullName>
                </value>
                <value>
                    <fullName>Planner</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>BI Analyst</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>TS Resource</fullName>
                </value>
                <value>
                    <fullName>Operator</fullName>
                </value>
                <value>
                    <fullName>Routesales Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>SAP Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>IntegrationLogTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IntegrationLogTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResourceTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>KTS-1931: Field used as flagging to enable or disable a trigger for Resource Object</description>
        <label>ResourceTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/TS_AsyncUserCreateOrUpdate_Test.cls
/**
* @author        Paul Jarred Aguiling
* @date          07.12.2018          
* @description   Test class for TS_AsyncUserCreateOrUpdate
* @revision(s)
*/
@isTest
public class TS_AsyncUserCreateOrUpdate_Test {
    static Account acct;
    static Contact con;
    static Resource__c  testResource;

    @testSetup
    static void dataSetup() {
        //Custom settings is being shared by all test class, if another test class has already inserted the record 
        //this test class will throw "UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record"
        try {
            TriggerSettings__c trg = TriggerSettings__c.getOrgDefaults();
            trg.ResourceTrigger__c = true;
            upsert trg;      
            system.debug('trg is:'+trg);
        } catch(Exception ex) {
            system.debug(ex);
        }

         try {
            IntegrationTriggerSettings__c trg1 = IntegrationTriggerSettings__c.getOrgDefaults();
            trg1.IntegrationLogTrigger__c = true;
            upsert trg1; 
        } catch(Exception ex) {
            system.debug(ex);
        }

        ProcessBuilderSettings__c pb = new ProcessBuilderSettings__c();
        pb.WorkOrderPBFlows__c = true;
        pb.CasePBFlows__c = true;
        insert pb;
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          07.12.2018             
    * @description   Method responsible for creating test data
    * @revision(s)
    */
    static void setupTestData() {
        acct = new Account(Name='Account', Phone='+31302979111');
        insert acct;
        
        con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        con.AccountId = acct.Id;
        insert con;

		testResource = TS_TestDataFactory.createResourceSingle('TestRSONumber');
		testResource.EmailAddress__c = 'testRSO@JDECoffee.com';
		testResource.RelatedContact__c = con.Id;
		testResource.EmployeeLastName__c = 'Skywalker';
		testResource.EmployeeFirstName__c = 'Anakin';
		testResource.CompanyCode__c = '6864';
		testResource.TeamNumber__c = '619';
        testResource.Username__c = 'testuser@salesforce.com';
        testResource.NickName__c = 'Anakin001';
		testResource.RequiresClickUser__c = true;
		testResource.UserProfile__c = Label.TS_ResourceUsrProf_ThirdParty;
		testResource.ActiveUser__c = true;
		
		insert testResource;
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          07.12.2018            
    * @description   Test class for TS_AsyncUserCreateOrUpdate execute method
    * @revision(s)
    */
    static testMethod void testExecute1() {
    	UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        u.UserRoleId = portalRole.Id;
        update u;

        System.runAs(u) {
			setupTestData();
			acct.OwnerId = u.Id;
			update acct;

			Set<Id> resList = new Set<Id>();
			resList.add(testResource.Id);

			ResourceTriggerHandler resTrig = new ResourceTriggerHandler();
	        TS_AsyncUserCreateOrUpdate userRes = new TS_AsyncUserCreateOrUpdate();
            userRes.resourceList = resList;
            userRes.map_profile = resTrig.getProfile();
            System.enqueueJob(userRes);

            Test.startTest();
            		System.assert(userRes.map_profile != null);
            Test.stopTest();
        }
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          07.12.2018            
    * @description   Test class for TS_AsyncUserCreateOrUpdate execute method
    * @revision(s)
    */
    static testMethod void testExecute2() {
    	UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        u.UserRoleId = portalRole.Id;
        update u;

        System.runAs(u) {
			setupTestData();
			acct.OwnerId = u.Id;
			update acct;

			testResource.UserProfile__c = Label.TS_ResourceUsrProf_Operator;
			update testResource;

			Set<Id> resList = new Set<Id>();
			resList.add(testResource.Id);

			ResourceTriggerHandler resTrig = new ResourceTriggerHandler();
	        TS_AsyncUserCreateOrUpdate userRes = new TS_AsyncUserCreateOrUpdate();
            userRes.resourceList = resList;
            userRes.map_profile = resTrig.getProfile();
            System.enqueueJob(userRes);

            Test.startTest();
            		System.assert(userRes.map_profile != null);
            Test.stopTest();
        }
    }

    /**
	* @author        Paul Jarred Aguiling
	* @date          07.12.2018            
    * @description   Test class for TS_AsyncUserCreateOrUpdate execute method
    * @revision(s)
    */
    static testMethod void testExecute3() {
    	UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        u.UserRoleId = portalRole.Id;
        update u;

        System.runAs(u) {
			setupTestData();
			acct.OwnerId = u.Id;
			update acct;

			testResource.UserProfile__c = Label.TS_ResourceUsrProf_Planner;
			update testResource;

			Set<Id> resList = new Set<Id>();
			resList.add(testResource.Id);

			ResourceTriggerHandler resTrig = new ResourceTriggerHandler();
	        TS_AsyncUserCreateOrUpdate userRes = new TS_AsyncUserCreateOrUpdate();
            userRes.resourceList = resList;
            userRes.map_profile = resTrig.getProfile();
            System.enqueueJob(userRes);

            Test.startTest();
            		System.assert(userRes.map_profile != null);
            Test.stopTest();
        }
    }
    /**
	* @author        Karen Hung
	* @date          01.15.19           
    * @description   Test class for TS_AsyncUserCreateOrUpdate execute method
    * @revision(s)
    */
    static testMethod void testExecute4() {
    	UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);
        u.UserRoleId = portalRole.Id;
        update u;

        System.runAs(u) {
			setupTestData();
			acct.OwnerId = u.Id;
			update acct;

			testResource.UserProfile__c = Label.TS_ResourceUsrProf_TSRes;
            testResource.RequiresClickUser__c = false;
			update testResource;

			Set<Id> resList = new Set<Id>();
			resList.add(testResource.Id);

			ResourceTriggerHandler resTrig = new ResourceTriggerHandler();
	        TS_AsyncUserCreateOrUpdate userRes = new TS_AsyncUserCreateOrUpdate();
            userRes.resourceList = resList;
            userRes.map_profile = resTrig.getProfile();
            System.enqueueJob(userRes);

            Test.startTest();
            		System.assert(userRes.map_profile != null);
            Test.stopTest();
        }
    }
}