src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <defaultValue>CASE($User.Sales_Organization__c, 
&quot;SAP_0111&quot;, &quot;SAP_NL&quot;,
&quot;SAP_0975&quot;, &quot;SAP_DA&quot;,
&quot;SAP_0976&quot;, &quot;SAP_SV&quot;,
&quot;SAP_6712&quot;, &quot;SAP_DE&quot;,
&quot;SAP_6750&quot;, &quot;SAP_EN&quot;,
&quot;SAP_6864&quot;, &quot;SAP_NO&quot;,
&quot;SAP_6749&quot;, &quot;SAP_ES&quot;, &quot;&quot;)</defaultValue>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the account location where the asset is located at.</description>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IncludesPreventiveMaintenanceCoverage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes Preventive Maintenance Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludesWTSCoverage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Includes WTS Coverage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NextWTSDate__c</fullName>
        <label>Next WTS Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the product used for the asset.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TS_CustomLookUpControllerTest.cls
/**
* @author        Rey Austral
* @date          9.29.2017           
* @description   Test Class for TS_CustomLookUpController
* @revision(s)
*/
@isTest
private class TS_CustomLookUpControllerTest {
    static Account acc;
    static Apttus_Config2__AccountLocation__c accLoc;
    static Contact con;
    static PhysicalAsset__c pAsset;
        
    
	@testSetup
    static void dataSetup() {
        acc = new Account(Name='Account 1', Phone='+31302979111');   
        insert acc;                
                
        Product2 prod_ZCMA = TS_TestDataFactory.createProductTest('ProductTest','ZCMA');
        insert prod_ZCMA;
                
        con = TS_TestDataFactory.createContact();  
        con.Preferred_Language__c = 'SAP_EN';
        con.AccountId = acc.Id;
        insert con;
        
        accLoc = TS_TestDataFactory.createAccountLocationTest('123456753', acc.Id);
        accLoc.Apttus_Config2__AccountId__c = acc.Id;               
        insert accLoc;
        
		pAsset = TS_TestDataFactory.createPhysicalAsset();
        pAsset.NextWTSDate__c = Date.Today().addDays(5);
        pAsset.Product__c = prod_ZCMA.Id;
        pAsset.IncludesWTSCoverage__c = true;
        pAsset.IncludesPreventiveMaintenanceCoverage__c = true;
        pAsset.EndDate__c = Date.today().addDays(1);        
        pAsset.AccountLocation__c = accLoc.Id;
        insert pAsset;
    }
    
    static void setupTestData() {
        pAsset = [SELECT Id FROM PhysicalAsset__c LIMIT 1];
        acc = [SELECT Id FROM Account LIMIT 1];        
    }
    	
	@isTest static void test_fetchLookUpValues() {
		User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);        
        System.runAs(u) {
            setupTestData();
            Test.startTest();
            List < sObject > sObjectList = TS_CustomLookUpController.fetchLookUpValues('Acc','Account','', false, '', '', '', '', '',
                                                                                       false, null, null, null, null, 
                                                                                       false, false, false);        
            Test.stopTest();
    
            System.assertEquals(1, sObjectList.size());
        }
	}
    
    @isTest static void test_fetchLookUpValuesFiltered() {
		User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);        
        System.runAs(u) {
            setupTestData();
            Test.startTest();
            List < sObject > sObjectList = TS_CustomLookUpController.fetchLookUpValues('Acc','Account','', true, '', '', '', '', '',
                                                                                       false, null, null, null, null, 
                                                                                       false, false, false);        
            Test.stopTest();
    
            System.assertEquals(1, sObjectList.size());
        }
	}
    
    @isTest static void test_fetchLookUpValuesNested() {
		User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);        
        System.runAs(u) {
            setupTestData();
            Test.startTest();            
            List < sObject > sObjectList = TS_CustomLookUpController.fetchLookUpValues(null,'Contact','', false, 'AccountId IN', '', '', '', '',
                                                                                       true, 'AccountLocation__r.Apttus_Config2__AccountId__c', 'PhysicalAsset__c', 'Id IN', pAsset.Id,
                                                                                       true, true, true);              
            Test.stopTest();                
        }            
	}  
    
    @isTest static void test_fetchLookUpValuesExact() {
		User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);        
        System.runAs(u) {
            setupTestData();
            Test.startTest();            
            List < sObject > sObjectList = TS_CustomLookUpController.fetchLookUpValues(acc.Id,'Account','', false, 'AccountId IN', '', '', '', 'Exact',
                                                                                       false, '', '', '', '',
                                                                                       true, true, true);              
            Test.stopTest();                
        }            
	}  
       	
	@isTest static void test_exception() {
		User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);        
        System.runAs(u) {                
            setupTestData();
            Test.startTest();
            TS_CustomLookUpController.hasException = true;
            List < sObject > sObjectList = TS_CustomLookUpController.fetchLookUpValues('Acc','Account','', false, '', '', '', '', '',
                                                                                       false, null, null, null, null, 
                                                                                       false, false, false);        
            Test.stopTest();
    
            System.assertEquals(1, sObjectList.size());
        }            
	}            
}