src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <defaultValue>CASE( $User.Sales_Organization__c, &apos;SAP_0333&apos;, &apos;SAP_0333&apos;, &apos;SAP_0975&apos;, &apos;SAP_0975&apos;, &apos;SAP_0976&apos;, &apos;SAP_0976&apos;, &apos;SAP_6864&apos;, &apos;SAP_6864&apos;, &apos;SAP_6706&apos;, &apos;SAP_6706&apos;, &apos;SAP_0080&apos;, &apos;SAP_0080&apos;, &apos;SAP_0111&apos;, &apos;SAP_0111&apos;, &apos;SAP_6709&apos;, &apos;SAP_6709&apos;, &apos;SAP_6712&apos;, &apos;SAP_6712&apos;, &apos;SAP_6750&apos;, &apos;SAP_6750&apos;, &apos;&apos;)</defaultValue>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Operational_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Task Record</relationshipLabel>
        <relationshipName>Operational_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Task Record</relationshipLabel>
        <relationshipName>Operational_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_Closed__c</fullName>
        <label>Date/Time Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect visit</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Stopped by Customer</fullName>
                </value>
                <value>
                    <fullName>Wrong Solution</fullName>
                </value>
                <value>
                    <fullName>Sales Process</fullName>
                </value>
                <value>
                    <fullName>No Fit For JDE</fullName>
                </value>
                <value>
                    <fullName>Credit Check</fullName>
                </value>
                <value>
                    <fullName>Future Follow Up &gt; 1 year</fullName>
                </value>
                <value>
                    <fullName>Converted to Quote</fullName>
                </value>
                <value>
                    <fullName>Converted to Event</fullName>
                </value>
                <value>
                    <fullName>Converted to Opportunity</fullName>
                </value>
                <value>
                    <fullName>No Interest</fullName>
                </value>
                <value>
                    <fullName>Unreachable</fullName>
                </value>
                <value>
                    <fullName>Recent contact (&lt; 3 mo)</fullName>
                </value>
                <value>
                    <fullName>Company not active</fullName>
                </value>
                <value>
                    <fullName>Conversation was rejected</fullName>
                </value>
                <value>
                    <fullName>Active customer</fullName>
                </value>
                <value>
                    <fullName>Company is not DMU</fullName>
                </value>
                <value>
                    <fullName>Current contract expiration &gt; 6 mo</fullName>
                </value>
                <value>
                    <fullName>Company too small</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Converter to Case</fullName>
                </value>
                <value>
                    <fullName>No Follow Up Needed</fullName>
                </value>
                <value>
                    <fullName>Follow Up &gt; 1 yr</fullName>
                </value>
                <value>
                    <fullName>Follow Up Order Survey Email</fullName>
                </value>
                <value>
                    <fullName>Lost Customer to Competitor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Task_Source__c</fullName>
        <label>Task Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP HANA</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                    <label>MANUAL</label>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>SFDC</fullName>
                </value>
                <value>
                    <fullName>APTTUS</fullName>
                </value>
                <value>
                    <fullName>EPI</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Offerte.nl</fullName>
                </value>
                <value>
                    <fullName>Companeo</fullName>
                </value>
                <value>
                    <fullName>KonceptM</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Cold Acquisition</fullName>
                    <isActive>false</isActive>
                    <label>COLD AQCUISITION</label>
                </value>
                <value>
                    <fullName>End Warranty MC</fullName>
                    <isActive>false</isActive>
                    <label>END WARR MC CAMP</label>
                </value>
                <value>
                    <fullName>Expiration</fullName>
                    <isActive>false</isActive>
                    <label>Expiration</label>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                    <isActive>false</isActive>
                    <label>Follow Up</label>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                    <isActive>false</isActive>
                    <label>INBOUND CALL</label>
                </value>
                <value>
                    <fullName>Installation Case SFDC</fullName>
                    <isActive>false</isActive>
                    <label>INSTAL CASE SFDC</label>
                </value>
                <value>
                    <fullName>Movement Case SFDC</fullName>
                    <isActive>false</isActive>
                    <label>MOVEMNT CASE SFDC</label>
                </value>
                <value>
                    <fullName>MPV SAP HANA</fullName>
                    <isActive>false</isActive>
                    <label>MPV SAP HANA</label>
                </value>
                <value>
                    <fullName>NPS Detail SFDC</fullName>
                    <isActive>false</isActive>
                    <label>NPS DETAIL SFDC</label>
                </value>
                <value>
                    <fullName>Online MC</fullName>
                    <isActive>false</isActive>
                    <label>ONLINE MC</label>
                </value>
                <value>
                    <fullName>Online OTH</fullName>
                    <isActive>false</isActive>
                    <label>ONLINE OTH</label>
                </value>
                <value>
                    <fullName>Prospect List</fullName>
                    <isActive>false</isActive>
                    <label>PROSPECT LIST</label>
                </value>
                <value>
                    <fullName>Referral Customer</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL CUSTOMER</label>
                </value>
                <value>
                    <fullName>Referral Employee</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL EMPLOYEE</label>
                </value>
                <value>
                    <fullName>Referral Partner</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL PARTNER</label>
                </value>
                <value>
                    <fullName>Referral Route Sales</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL ROUTESALES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Updated_by_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated by Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Task Record</label>
    <nameField>
        <label>Operational Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MirrorTaskRecordDetailController.cls
//-------------------------------------------------------------------------------------------//
// Author       :   Catherine Aragon - Accenture
// Created Date :   September 22, 2017
// Usage        :   Class for lightning component that will return task details
//-------------------------------------------------------------------------------------------//
public without sharing class MirrorTaskRecordDetailController {
    @AuraEnabled
    public static Task getTask(String OTrecordId) {
        CustomLogging.push('getTask', 'MirrorTaskRecordDetailController');
        Task taskRec = new Task();
        try {
            Operational_Tasks__c otRec = new Operational_Tasks__c();
            otRec = [Select Id, Name, Updated_by_Trigger__c, Task_ID__c, OwnerId
                      FROM Operational_Tasks__c 
                      WHERE Id = : OTrecordId];
        
            
            if(otRec.Task_ID__c <> Null || otRec.Task_ID__c <> ''){
                 taskRec = [Select Id, OwnerId, Subject, Updated_by_Trigger__c, Operational_Tasks__c,
                                   ActivityDate, WhoId, WhatId, Priority, Type, Status,
                                   Description, Task_Source__c, Campaign__c, Contact__c, 
                                   Reason__c, Start_DateCS__c, Sales_Organization__c,
                                   DurationInMin__c, Role_Id__c, Date_Time_Closed__c, Owner.Name, What.Name,
                                   Who.Name, Operational_Tasks__r.Name, Campaign__r.Name, Contact__r.Name
                            FROM Task 
                            WHERE ID = : otRec.Task_ID__c]; 
            }
           
            
        } catch (Exception e) {
            CustomLogging.debugException(e);
            CustomLogging.pop();      
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());
        }
        
        return taskRec;
    }
    
    @AuraEnabled
    public static Task saveTask(Task OTrecord) {
        CustomLogging.push('saveTask', 'MirrorTaskRecordDetailController');
        Task taskRec = new Task();
        
        try {
        update OTrecord;
        
            taskRec = [Select Id, OwnerId, Subject, Updated_by_Trigger__c, Operational_Tasks__c,
                                   ActivityDate, WhoId, WhatId, Priority, Type, Status,
                                   Description, Task_Source__c, Campaign__c, Contact__c, 
                                   Reason__c, Start_DateCS__c, Sales_Organization__c,
                                   DurationInMin__c, Role_Id__c, Date_Time_Closed__c, Owner.Name, What.Name,
                                   Who.Name, Operational_Tasks__r.Name, Campaign__r.Name, Contact__r.Name
                            FROM Task 
                            WHERE ID = : OTrecord.Id];
            
            System.debug('OTrecord: ' + OTrecord);
                
        } catch (Exception e) {
            CustomLogging.debugException(e);
            CustomLogging.pop();      
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());
        }

        return taskRec;
        
    }
}