src/objects/CountrySetting__c.object
<CustomObject>
    <description>Records containing country specified settings (e.g. country specific SLAs)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Request</label>
        <referenceTo>Part_Request__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Part_Request__c.object
<CustomObject>
    <fields>
        <fullName>Company_Code__c</fullName>
        <formula>Resource__r.CompanyCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Part Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>PartRequestTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PartRequestTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/classes/PartRequestTriggerHandler.cls
/**
* @author        Karen Hung
* @date          13.11.2019
* @description   Class responsible for the trigger business logic of Part Request, part of DOO-2196
* @revision(s)   
*/
public without sharing class PartRequestTriggerHandler implements ITriggerHandler {
    
    public static Boolean isTriggerDisabled = true;
    
    public class PartRequestTriggerHandlerException extends Exception {}
    
    public static boolean hasException = false;
    
    public void BeforeInsert(List<SObject> newList) {
        validateItem(newList,null,null);
        
    }
    
    public void BeforeUpdate(List<SObject> newList, Map<Id, SObject> newItems, List<SObject> oldList, Map<Id, SObject> oldMap) {
        validateItem(newList,oldMap,newItems);	
    }
    
    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems) {
        
    }
    
    public void AfterInsert(List<SObject> newList, Map<Id, SObject> newItems) {
        
    }
    
    public void AfterUpdate(List<SObject> newList, Map<Id, SObject> newItems, List<SObject> oldList, Map<Id, SObject> oldItems) {
        Map<Id, Part_Request__c> newMapItems = (Map<Id, Part_Request__c>) newItems;
        Map<Id, Part_Request__c> oldMapItems = (Map<Id, Part_Request__c>) oldItems;
        createIntegrationLogs(newList, oldMapItems, newMapItems);
    }
    
    public void AfterDelete(List<SObject> oldList, Map <Id, SObject> oldItems) {
        
    }
    
    public void AfterUndelete(List<SObject> newList, Map <Id, SObject> newItems) {
        
    }
    
    public Boolean IsDisabled() {
        if (TriggerSettings__c.getInstance().PartRequestTrigger__c == true) {
            return false;
        } else {
            return isTriggerDisabled;
        }
    }
    
    /****Method for custom validation***/
    public void validateItem(List<SObject> newItems, Map<Id, SObject> oldMapItems, Map<Id, SObject> newMapItems){
        CustomLogging.push('validateItem', 'PartRequestTriggerHandler');
        
        List<Part_Request__c> newList = (List<Part_Request__c>) newItems;
        Map<Id,Part_Request__c> newMap = (Map<Id,Part_Request__c>) newMapItems;
        Map<Id,Part_Request__c> oldMap = (Map<Id,Part_Request__c>) oldMapItems;
        
        try{
            if (Test.isRunningTest() && hasException) {
                throw new PartRequestTriggerHandlerException(TS_Constants.FORCE_EXCEPTION);
            }
            
            /**Validation : You can only create a part request if there is an active country setting for the related resource company code**/
            
            //get company codes in country settings - Country Purchasing Setting Recordtype
            Set<String> companyCodes = new Set<String>();
            for(CountrySetting__c cset : [SELECT Id, Company_Code__c FROM CountrySetting__c WHERE Active__c = true AND RecordType.Name = :TS_Constants.TS_COUNTRYSETTING_RECORDTYPE_COUNTRYPURCHASING]){
                companyCodes.add(cset.Company_Code__c);    
            }
            
            //put errors
            for(Part_Request__c partR : newList){
                if(!companyCodes.contains(partR.Company_Code__c)){
                    //put error on insert and status change
                    if(oldMapItems == null || (oldMap.get(partR.Id).Status__c != newMap.get(partR.Id).Status__c && newMap.get(partR.Id).Status__c == TS_Constants.STATUS_COMPLETED)){
                   		partR.addError(TS_Constants.ERRORMESSAGE_NOCOUNTRYSETTING); // Please contact your administrator to activate the purchasing settings for your company.     
                    }                     
                }	    
            }
                        
        }catch(Exception e){
            CustomLogging.debugException(e);
            CustomLogging.pop();
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());           
        }        
        
        CustomLogging.pop(); 
    }
    
    /*Method to create Integration Logs*/
    public void createIntegrationLogs(List<Part_Request__c> newList, Map<Id, Part_Request__c> oldRecordMap, Map<Id, Part_Request__c> newRecordMap) {
        CustomLogging.push('createIntegrationLogs', 'PartRequestTriggerHandler');
        try{
            
            if (Test.isRunningTest() && hasException) {
                throw new PartRequestTriggerHandlerException(TS_Constants.FORCE_EXCEPTION);
            }
            
            List<Integration_Log__c> integLogsToInsertList = new List<Integration_Log__c>();
            for(Part_Request__c pReq : newList){
                //when request is updated to Completed
                if(oldRecordMap.get(pReq.Id).Status__c != newRecordMap.get(pReq.Id).Status__c && newRecordMap.get(pReq.Id).Status__c == TS_Constants.STATUS_COMPLETED){
                    integLogsToInsertList.addAll(validatePartRequest(pReq));	      
                }
            }
            //check if integLogsToInsertList is not empty and proceed to insertion
            if(integLogsToInsertList != null && !integLogsToInsertList.isEmpty()  && Schema.sObjectType.Integration_Log__c.isCreateable()) {
                insert integLogsToInsertList;    
            }
            
        }catch(Exception e){
            CustomLogging.debugException(e);
            CustomLogging.pop();
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());            
        }
        CustomLogging.pop();      
    }
    
    /*integration log creation*/
    public List<Integration_Log__c> validatePartRequest(Part_Request__c pRequest){
        CustomLogging.push('validatePartRequest', 'PartRequestTriggerHandler');
        List<Integration_Log__c> integLogsList = new List<Integration_Log__c>();
        
        //CREATE INTEGRATION LOGS
        integLogsList.add(new Integration_Log__c(Object_Id__c = pRequest.Id,
                                                 Object__c = 'Part Request - Car Stock Replenishment',
                                                 Integration_Status__c = INT_Constants.INITIAL,
                                                 Part_Request__c = pRequest.Id));  
        
        CustomLogging.pop(); 
        return integLogsList; 
        
    }
    
}