src/objects/Country_Super_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Country Super Users</label>
</CustomObject>

src/objects/Operational_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Task Record</relationshipLabel>
        <relationshipName>Operational_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Task Record</relationshipLabel>
        <relationshipName>Operational_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                    <default>true</default>
                    <label>Medium</label>
                </value>
                <value>
                    <fullName>High Priority</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect visit</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Price</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Stopped by Customer</fullName>
                </value>
                <value>
                    <fullName>Wrong Solution</fullName>
                </value>
                <value>
                    <fullName>Sales Process</fullName>
                </value>
                <value>
                    <fullName>No Fit For JDE</fullName>
                </value>
                <value>
                    <fullName>Credit Check</fullName>
                </value>
                <value>
                    <fullName>Future Follow Up &gt; 1 year</fullName>
                </value>
                <value>
                    <fullName>Converted to Quote</fullName>
                </value>
                <value>
                    <fullName>Converted to Event</fullName>
                </value>
                <value>
                    <fullName>Converted to Opportunity</fullName>
                </value>
                <value>
                    <fullName>No Interest</fullName>
                </value>
                <value>
                    <fullName>Unreachable</fullName>
                </value>
                <value>
                    <fullName>Recent contact (&lt; 3 mo)</fullName>
                </value>
                <value>
                    <fullName>Company not active</fullName>
                </value>
                <value>
                    <fullName>Conversation was rejected</fullName>
                </value>
                <value>
                    <fullName>Active customer</fullName>
                </value>
                <value>
                    <fullName>Company is not DMU</fullName>
                </value>
                <value>
                    <fullName>Current contract expiration &gt; 6 mo</fullName>
                </value>
                <value>
                    <fullName>Company too small</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Converter to Case</fullName>
                </value>
                <value>
                    <fullName>No Follow Up Needed</fullName>
                </value>
                <value>
                    <fullName>Follow Up &gt; 1 yr</fullName>
                </value>
                <value>
                    <fullName>Follow Up Order Survey Email</fullName>
                </value>
                <value>
                    <fullName>Lost Customer to Competitor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReminderSet__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ReminderSet</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed Effective</fullName>
                </value>
                <value>
                    <fullName>Completed Non-Effective</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Redial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Source__c</fullName>
        <label>Task Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP HANA</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                    <label>MANUAL</label>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>SFDC</fullName>
                </value>
                <value>
                    <fullName>APTTUS</fullName>
                </value>
                <value>
                    <fullName>EPI</fullName>
                </value>
                <value>
                    <fullName>CTI</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Offerte.nl</fullName>
                </value>
                <value>
                    <fullName>Companeo</fullName>
                </value>
                <value>
                    <fullName>KonceptM</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Cold Acquisition</fullName>
                    <isActive>false</isActive>
                    <label>COLD AQCUISITION</label>
                </value>
                <value>
                    <fullName>End Warranty MC</fullName>
                    <isActive>false</isActive>
                    <label>END WARR MC CAMP</label>
                </value>
                <value>
                    <fullName>Expiration</fullName>
                    <isActive>false</isActive>
                    <label>Expiration</label>
                </value>
                <value>
                    <fullName>Follow Up</fullName>
                    <isActive>false</isActive>
                    <label>Follow Up</label>
                </value>
                <value>
                    <fullName>Inbound Call</fullName>
                    <isActive>false</isActive>
                    <label>INBOUND CALL</label>
                </value>
                <value>
                    <fullName>Installation Case SFDC</fullName>
                    <isActive>false</isActive>
                    <label>INSTAL CASE SFDC</label>
                </value>
                <value>
                    <fullName>Movement Case SFDC</fullName>
                    <isActive>false</isActive>
                    <label>MOVEMNT CASE SFDC</label>
                </value>
                <value>
                    <fullName>MPV SAP HANA</fullName>
                    <isActive>false</isActive>
                    <label>MPV SAP HANA</label>
                </value>
                <value>
                    <fullName>NPS Detail SFDC</fullName>
                    <isActive>false</isActive>
                    <label>NPS DETAIL SFDC</label>
                </value>
                <value>
                    <fullName>Online MC</fullName>
                    <isActive>false</isActive>
                    <label>ONLINE MC</label>
                </value>
                <value>
                    <fullName>Online OTH</fullName>
                    <isActive>false</isActive>
                    <label>ONLINE OTH</label>
                </value>
                <value>
                    <fullName>Prospect List</fullName>
                    <isActive>false</isActive>
                    <label>PROSPECT LIST</label>
                </value>
                <value>
                    <fullName>Referral Customer</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL CUSTOMER</label>
                </value>
                <value>
                    <fullName>Referral Employee</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL EMPLOYEE</label>
                </value>
                <value>
                    <fullName>Referral Partner</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL PARTNER</label>
                </value>
                <value>
                    <fullName>Referral Route Sales</fullName>
                    <isActive>false</isActive>
                    <label>REFERRAL ROUTESALES</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outbound Commercial</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Agreement Compliance</fullName>
                </value>
                <value>
                    <fullName>Outbound Non-commercial</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Agreement Amendment</fullName>
                </value>
                <value>
                    <fullName>Indexation</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Contract Compliance Task</fullName>
                    <isActive>false</isActive>
                    <label>Contract Compliance Task</label>
                </value>
                <value>
                    <fullName>Internal</fullName>
                    <isActive>false</isActive>
                    <label>Internal</label>
                </value>
                <value>
                    <fullName>Outbound Commercial Other</fullName>
                    <isActive>false</isActive>
                    <label>Outbound Commercial Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task Record</label>
    <nameField>
        <label>Operational Tasks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QueueGateKeepers__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sales_Org_ID__c</fullName>
        <label>Sales Org ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Queue Gate Keepers</label>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>OperationalTaskTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OperationalTaskTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OperationalTaskTriggerHandler.cls
public without sharing class OperationalTaskTriggerHandler implements ITriggerHandler{
    public static Boolean isTriggerDisabled = true;
    
    public void beforeInsert(List<SObject> newListTask){
        
    } 
 
    public void beforeUpdate(List<SObject> newListTask, Map<Id, SObject> newItems, List<SObject> oldList, Map<Id, SObject> oldMapTask){
        validationforqueueanduser((List<Operational_Tasks__c>) newListTask, oldMapTask);
    }
 
    public void beforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){
        preventDeletion((List<Operational_Tasks__c>) oldList);
    }
 
    public void afterInsert(List<SObject> newListTask, Map<Id, SObject> newItems){
        
    }
 
    public void afterUpdate(List<SObject> newListTask , Map<Id, SObject> newItems, List<SObject> oldList, Map<Id, SObject> oldMapTask){
        if(SM_CheckRecursive.run == True){
            updateTaskRecordRelatedToOT((List<Operational_Tasks__c>) newListTask, oldMapTask);
        }
    }
 
    public void afterDelete(List<SObject> oldList, Map<Id, SObject> oldItems){
        
    }
 
    public void afterUndelete(List<SObject> newList, Map<Id, SObject> newItems){
        
    }
    
    public Boolean IsDisabled(){
        if (TriggerSettings__c.getInstance().OperationalTaskTrigger__c == true) {
            return false;
        } else {
            return isTriggerDisabled;
        }
    }
    
    public static void preventDeletion(List<Operational_Tasks__c> oldList) {
       CustomLogging.push('preventDeletion', 'OperationalTaskTriggerHandler');
       try {    
           String UserID = UserInfo.getUserId(); 
           User currentUser = new User();
           currentUser = [Select Id, Name, Sales_Organization__c, Profile.Name FROM User WHERE ID = :UserID];
           
           Country_Super_Users__c csu = Country_Super_Users__c.getInstance(UserID);
           if (currentUser != null){
                for(Operational_Tasks__c ot : oldList){
                    if (csu != null){
                        if (currentUser.Id != csu.Name && currentUser.Sales_Organization__c != csu.Sales_Organization__c && currentUser.Profile.Name != SM_Constants.SystemAdmin) {
                            ot.addError('You cannot delete this record. Insufficient Privilege');
                        }
                    }
                    else {
                        if (currentUser.Profile.Name != SM_Constants.SystemAdmin){
                            ot.addError('You cannot delete this record. Insufficient Privilege');
                        }
                    }
                }
           }
          
       } catch (Exception e) {
           CustomLogging.debugException(e);
           CustomLogging.pop();      
           System.debug(e.getMessage() + '\n' + e.getStackTraceString());
       }
           
    }
    
    public static void validationforqueueanduser(List<Operational_Tasks__c> newListTask,  Map<Id, SObject> oldMapTask){
        CustomLogging.push('updateTaskRecordRelatedToOT', 'OperationalTaskTriggerHandler');
        try {
            String UserID = UserInfo.getUserId(); 
            User currentUser = new User();
            if(UserID != null){
                currentUser = [Select Id, Name, Sales_Organization__c FROM User WHERE ID = :UserID];
            }
            if (oldMapTask != null){
                for(Operational_Tasks__c OT : newListTask){
                    Operational_Tasks__c oldOT = (Operational_Tasks__c) oldMapTask.get(OT.Id);
                    if (OT.OwnerId != oldOT.OwnerId){
                        if (OT.OwnerId != null && String.valueOf(OT.OwnerId).left(3) == SM_Constants.queuePrefix) {
                            QueueGateKeepers__c gatekeeper = QueueGateKeepers__c.getInstance(OT.OwnerId);
                            if (gatekeeper != null) {
                                if (currentUser.Sales_Organization__c != gatekeeper.Sales_Org_ID__c){
                                    OT.addError('Country of the Queue and your Sales Organization does not match, you can not add this to the queue');
                                }
                            }
                           
                        }
                    }
                }
            }
    
           
        } catch (Exception e) {
           CustomLogging.debugException(e);
           CustomLogging.pop();      
           System.debug(e.getMessage() + '\n' + e.getStackTraceString());
       }
    }
    public static void updateTaskRecordRelatedToOT(List<Operational_Tasks__c> newListTask,  Map<Id, SObject> oldMapTask){
        CustomLogging.push('updateTaskRecordRelatedToOT', 'OperationalTaskTriggerHandler');
        try {
            List<Task> taskRecs = new List<Task>();
            List<Task> updateTaskList = new List<Task>();
            Set<Id> TaskID = new Set<Id>();
            Map<Id, Operational_Tasks__c> otrecsMap = new Map<Id, Operational_Tasks__c>();
            if (!oldMapTask.isEmpty()){
                for (Operational_Tasks__c otrecs : newListTask){
                    Operational_Tasks__c oldtask = (Operational_Tasks__c) oldMapTask.get(otrecs.Id);
                    if (otrecs.OwnerId != oldTask.OwnerId || otrecs.Due_Date__c != oldTask.Due_Date__c || otrecs.Status__c != oldTask.Status__c || otrecs.Task_Source__c != oldTask.Task_Source__c ||
                            otrecs.Comments__c != oldTask.Comments__c || otrecs.Priority__c != oldTask.Priority__c || otrecs.Type__c != oldTask.Type__c || otrecs.Contact__c != oldTask.Contact__c ||
                            otrecs.Campaign__c != oldTask.Campaign__c || otrecs.Reason__c != oldTask.Reason__c || otrecs.Start_Date__c != oldTask.Start_Date__c || otrecs.ReminderSet__c != oldTask.ReminderSet__c ||
                            otrecs.ReminderDateTime__c != oldTask.ReminderDateTime__c){
                                TaskID.add(otrecs.Task_ID__c);
                                otrecsMap.put(otrecs.Task_ID__c, otrecs);
                    }
                }
            }
            
            if (!otrecsMap.isEmpty()){
                taskRecs = [Select Id, OwnerId, Subject, Updated_by_Trigger__c, Operational_Tasks__c, ActivityDate, Status, 
                            Task_Source__c, Priority, Type, Reason__c, WhatId, WhoId, Start_DateCS__c,
                            Date_Time_Closed__c, IsReminderSet, ReminderDateTime
                            FROM Task 
                            WHERE ID in : TaskID];
                
                if (!taskRecs.isEmpty()){
                    for (Task taskrec : taskRecs){
                        if (String.valueOf(otrecsMap.get(taskrec.Id).OwnerID).left(3) == '00G'){
                            QueueGateKeepers__c gatekeeper = QueueGateKeepers__c.getInstance(otrecsMap.get(taskrec.Id).OwnerId);
                            taskRec.OwnerId = gatekeeper.User_Keeper__c;
                        }
                        else {
                            taskRec.OwnerId = otrecsMap.get(taskrec.Id).OwnerId; 
                        }
                        taskRec.ActivityDate = otrecsMap.get(taskrec.Id).Due_Date__c;
                        taskRec.Status = otrecsMap.get(taskrec.Id).Status__c;
                        taskRec.Updated_by_Trigger__c = true;
                        taskRec.Task_Source__c = otrecsMap.get(taskrec.Id).Task_Source__c;
                        taskRec.Description = otrecsMap.get(taskrec.Id).Comments__c;
                        taskRec.Priority = otrecsMap.get(taskrec.Id).Priority__c;
                        taskRec.Type = otrecsMap.get(taskrec.Id).Type__c;
                        if (otrecsMap.get(taskrec.Id).Contact__c != Null) {
                            taskRec.WhoId = otrecsMap.get(taskrec.Id).Contact__c;  
                        }
                        if (otrecsMap.get(taskrec.Id).Campaign__c != Null) {
                            taskRec.Campaign__c = otrecsMap.get(taskrec.Id).Campaign__c;  
                        }
                        taskRec.Reason__c = otrecsMap.get(taskrec.Id).Reason__c;
                        taskRec.Start_DateCS__c = otrecsMap.get(taskrec.Id).Start_Date__c;
                        taskRec.IsReminderSet = otrecsMap.get(taskrec.Id).ReminderSet__c;
                        taskRec.ReminderDateTime = otrecsMap.get(taskrec.Id).ReminderDateTime__c;
                        updateTaskList.add(taskrec);
                    }
                }
                if (!updateTaskList.isEmpty()){
                    SM_CheckRecursive.run = false;
                    update updateTaskList;
                }
            }
            
       } catch (Exception e) {
           CustomLogging.debugException(e);
           CustomLogging.pop();      
           System.debug(e.getMessage() + '\n' + e.getStackTraceString());
       }
    
    }
}