src/objects/CountrySetting__c.object
<CustomObject>
    <description>Records containing country specified settings (e.g. country specific SLAs)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Line Item</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IntegrationUserAndProfile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Click_Integration_Name__c</fullName>
        <label>Click Integration Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>IntegrationUserAndProfile</label>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>This object collects the information  that is needed for linking Engineer information to Work Orders for reporting purposes.</description>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <label>Company Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAPStorageLocation__c</fullName>
        <label>SAP Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>SAP Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TS_Feature_Flag__mdt.object
<CustomObject>
    <fields>
        <fullName>Enable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable?</label>
        <type>Checkbox</type>
    </fields>
    <label>TS Feature Flag</label>
    <pluralLabel>TS Feature Flags</pluralLabel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_CompanyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_ID__c</fullName>
        <description>Azure ID reference</description>
        <label>Azure Object ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>DirectToCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct To Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExecutingEngineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to indicated by Click which engineer has executed the Task or which engineeers Parts have been used, missing, required.</description>
        <inlineHelpText>Engineer that performed the job.</inlineHelpText>
        <label>Executing Engineer</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Work Order Line Items (Executing Engineer)</relationshipLabel>
        <relationshipName>ExecutingEngineerWorkOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalOrderSAP__c</fullName>
        <description>FD 1237 Internal order number coming from SAP</description>
        <externalId>true</externalId>
        <label>Internal Order SAP</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsReadyToSummarize__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag when a dummy service material is received from click, to start a generation of task summary and link to case (see TS_CreateCaseReportFile_2)</description>
        <inlineHelpText>Used to flag if all task information from Click has been completely received. (Used by PB TS_SendEmailOnCompletedTask, and APEX TS_CreateCaseReportFile_2 )</inlineHelpText>
        <label>IsReadyToSummarize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_WorkOrder_Billling_Required__c</fullName>
        <formula>ISPICKVAL(WorkOrderLineItemType__c, &apos;Task&apos;) &amp;&amp;
(ISPICKVAL(WorkOrderType__c , &apos;S10&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S30&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S31&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S32&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S42&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S52&apos;) ||
 ISPICKVAL(WorkOrderType__c , &apos;S53&apos;)
) &amp;&amp;
ISBLANK(OrderHeaderSAPId__c) 

/* Removed S40 &amp; S51 ALM 5297
Feb. 22, 2019 */</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is WorkOrder Billling Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderHeaderSAPId__c</fullName>
        <description>TS used to received the  SAP Order header wrt the Work Order Billing Interface.  KTS-384</description>
        <label>Order Header SAP Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_used_from_own_storage_location__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Part used from own car stock?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderLineItemType__c</fullName>
        <description>Defines the type of work order line</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UsedSpareParts</fullName>
                    <label>Used parts</label>
                </value>
                <value>
                    <fullName>MissingSpareParts</fullName>
                    <label>Missing parts</label>
                </value>
                <value>
                    <fullName>RequiredSpareparts</fullName>
                    <label>Required parts</label>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Service Materials</fullName>
                </value>
                <value>
                    <fullName>MachineActions</fullName>
                    <label>Machine Actions</label>
                </value>
                <value>
                    <fullName>Counter Reading</fullName>
                </value>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Cups</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                    <label>Counter Reading Task</label>
                </value>
                <value>
                    <fullName>Rinse</fullName>
                </value>
                <value>
                    <fullName>Preventive Maintenance</fullName>
                </value>
                <value>
                    <fullName>Waterfilter</fullName>
                </value>
                <value>
                    <fullName>Descaling</fullName>
                </value>
                <value>
                    <fullName>Bottle</fullName>
                </value>
                <value>
                    <fullName>Ingredients</fullName>
                </value>
                <value>
                    <fullName>LP</fullName>
                </value>
                <value>
                    <fullName>LW</fullName>
                </value>
                <value>
                    <fullName>LD</fullName>
                </value>
                <value>
                    <fullName>LB</fullName>
                </value>
                <value>
                    <fullName>LI</fullName>
                </value>
                <value>
                    <fullName>PW</fullName>
                </value>
                <value>
                    <fullName>PD</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>WD</fullName>
                </value>
                <value>
                    <fullName>WB</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>DB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_WorkOrderBillingQueuable.cls
//-------------------------------------------------------------------------------------------//
// Author       :   Abram Vixen Reyes
// Created Date :   Sept 26, 2018
// Usage        :   Queuable Interface to Trigger Work Order Billing
//-------------------------------------------------------------------------------------------//
public without sharing class TS_WorkOrderBillingQueuable implements Queueable , Database.AllowsCallouts{

	public List<WorkOrderLineItem> newList {get; set;}
	public Set<Id> parentWOLI {get; set;}
	public List<WorkOrderLineItem> updateList = new List<WorkOrderLineItem>();
	public static Map<String, CountrySetting__c> COUNTRYSETTING_PURCHASING_COMPANYCODE_MAP = new Map<String, CountrySetting__c>();
    //Karen Hung 25/11/2020 DOO-5035
    public static String clickName = IntegrationUserAndProfile__c.getInstance().Click_Integration_Name__c;

	public void execute(QueueableContext context) {
		CustomLogging.push('execute', 'TS_WorkOrderBillingQueuable');

		//System.debug('XEN 10/2 getUiThemeDisplayed: ' + UserInfo.getUiThemeDisplayed());
		//System.debug('XEN 10/2 getUiTheme: ' + UserInfo.getUiTheme());

		List<Integration_Log__c> integLogsList = new List<Integration_Log__c>();

		try{
			if(!parentWOLI.isEmpty()){
				Map<Id, WorkOrderLineItem> parentTaskMap = new Map<Id, WorkOrderLineItem>([SELECT Id, Status, Is_WorkOrder_Billling_Required__c, LastModifiedById, CreatedById, InternalOrderSAP__c FROM WorkOrderLineItem WHERE Id IN: parentWOLI]);
				
                //Karen Hung 21/11/2020 DOO-5035 to query createdby.name
                Map<Id, WorkOrderLineItem> extnewList = new Map<Id,WorkOrderLineItem>([SELECT Id, Createdby.Name FROM WorkOrderLineItem WHERE Id in :newList]);
                
				//SCENARIO 1: Work Order Billing Queueable
				for(WorkOrderLineItem wo : newList){
					WorkOrderLineItem parentTask = parentTaskMap.get(wo.ParentWorkOrderLineItemId);

					System.debug('XEN Jan. 11 parentTask: ' + parentTask);

					//SCENARIO 1: When Click User closed a non-review needed task, but review needed in SF. (e.g internal order sap is missing)
					Boolean isClickCreated = extnewList.get(wo.Id).CreatedBy.Name == clickName && parentTask.InternalOrderSAP__c != null;

					//SCENARIO 2: Non-Click User task completion
					Boolean isNonClickCreated = extnewList.get(wo.Id).CreatedBy.Name != clickName;

					if((isClickCreated || isNonClickCreated) && parentTask.Is_WorkOrder_Billling_Required__c == true){
						integLogsList.add(new Integration_Log__c(Object_Id__c = parentTask.Id,
                                                  Object__c = TS_Constants.WO_BILLING,
                                                  Integration_Status__c = INT_Constants.INITIAL,
                                                  Work_Order_Line_Item__c = parentTask.Id));
					}					
				}
				
				//Check the feature flag AND query child parts for Goods Movement & Car Stock Replenishment
				List<TS_Feature_Flag__mdt> featureflagList = [SELECT Id, QualifiedApiName, Enable__c FROM TS_Feature_Flag__mdt WHERE QualifiedApiName = 'DOO_5026_SF_Change_trigger_Used_Part_G' LIMIT 1];
				if((!featureflagList.isEmpty() && featureflagList[0].Enable__c) || Test.isRunningTest()){

					List<WorkOrderLineItem> childWorkOrderLineItems = [SELECT Id,
																			Status,
																			WorkOrderLineItemType__c,
																			Part_used_from_own_storage_location__c,
																			ParentWorkOrderLineItemId,
																			ParentWorkOrderLineItem.OrderHeaderSAPId__c,
																			ParentWorkOrderLineItem.ExecutingEngineer__c,
																			ParentWorkOrderLineItem.ExecutingEngineer__r.SAPStorageLocation__c,
																			ParentWorkOrderLineItem.ExecutingEngineer__r.CompanyCode__c,
																			DirectToCustomer__c
																			FROM WorkOrderLineItem WHERE ParentWorkOrderLineItemId IN:parentWOLI 
																			AND IsReadyToSummarize__c = false
																			AND (WorkOrderLineItemType__c =: TS_Constants.TYPE_API_USEDPARTS OR WorkOrderLineItemType__c =: TS_Constants.WOLI_STATUS_MISSING)
																			AND Id NOT IN (SELECT Work_Order_Line_Item__c FROM Integration_Log__c WHERE Work_Order_Line_Item__r.ParentWorkOrderLineItemId IN: parentWOLI AND (Object__c =: INT_Constants.WOLI_GOODS_MVMT OR Object__c =: INT_Constants.WOLI_CARSTOCK))];

					if(!childWorkOrderLineItems.isEmpty()){

						if(COUNTRYSETTING_PURCHASING_COMPANYCODE_MAP.isEmpty()){    
							List<CountrySetting__c> GET_COUNTRYPURCHASING_LIST = [SELECT Id, Name, Company_Code__c, Active__c FROM CountrySetting__c    
																				WHERE Active__c = true  
																				AND RecordType.Name =: TS_Constants.TS_COUNTRYSETTING_RECORDTYPE_COUNTRYPURCHASING];    
							if(!GET_COUNTRYPURCHASING_LIST.isEmpty()){  
								for(CountrySetting__c CS_VAR : GET_COUNTRYPURCHASING_LIST){ 
									COUNTRYSETTING_PURCHASING_COMPANYCODE_MAP.put(CS_VAR.Company_Code__c, CS_VAR);  
								}   
							}   
						}

						for(WorkOrderLineItem woli : childWorkOrderLineItems){

							//SCENARIO 2: Goods Movement
							if (woli.Status == TS_Constants.STATUS_COMPLETED &&
								woli.WorkOrderLineItemType__c == TS_Constants.TYPE_API_USEDPARTS &&
								woli.Part_used_from_own_storage_location__c == true && 
								woli.ParentWorkOrderLineItem.OrderHeaderSAPId__c == null &&
								woli.ParentWorkOrderLineItem.ExecutingEngineer__c != null &&
								woli.ParentWorkOrderLineItem.ExecutingEngineer__r.SAPStorageLocation__c != null
								){

								integLogsList.add(new Integration_Log__c(Object_Id__c = woli.Id,
										Object__c = INT_Constants.WOLI_GOODS_MVMT,
										Integration_Status__c = INT_Constants.INITIAL,
										Work_Order_Line_Item__c = woli.Id));
							}
							
							//SCENARIO 3: Missing Parts Car Stock Replenishment
							if (woli.DirectToCustomer__c == false &&
								woli.WorkOrderLineItemType__c == TS_Constants.WOLI_STATUS_MISSING &&
								woli.ParentWorkOrderLineItem.ExecutingEngineer__c != null &&
								woli.ParentWorkOrderLineItem.ExecutingEngineer__r.CompanyCode__c != null &&
								COUNTRYSETTING_PURCHASING_COMPANYCODE_MAP.containsKey(woli.ParentWorkOrderLineItem.ExecutingEngineer__r.CompanyCode__c)
								){
								
								integLogsList.add(new Integration_Log__c(Object_Id__c = woli.Id,
										Object__c = INT_Constants.WOLI_CARSTOCK,
										Integration_Status__c = INT_Constants.INITIAL,
										Work_Order_Line_Item__c = woli.Id));
							}				
						}
					}
				}

				if(!integLogsList.isEmpty()){
					insert integLogsList;
				}
				
			}	
		} catch (Exception e){
			System.debug(e);
		}

		CustomLogging.pop();
	}
}