src/objects/CountrySetting__c.object
<CustomObject>
    <description>Records containing country specified settings (e.g. country specific SLAs)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Country_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for which this record is applicable</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DefaultEndTime__c</fullName>
        <defaultValue>17</defaultValue>
        <description>Define default end time (hour) to plan operating task (fill between 1 - 24)</description>
        <inlineHelpText>Define default end time (hour) to plan operating task (fill between 1 - 24)</inlineHelpText>
        <label>DefaultEndTime</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DefaultStartTime__c</fullName>
        <defaultValue>5</defaultValue>
        <description>Define default start time (hour) to plan operating task (fill between 1 - 24)</description>
        <inlineHelpText>Define default start time (hour) to plan operating task (fill between 1 - 24)</inlineHelpText>
        <label>DefaultStartTime</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberDayToLookup__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Number of days to lookup (in day), is used for Operating Batch to build a map/list to describe if the last or future days have non business day</description>
        <label>NumberDayToLookup</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Country Setting</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OperatingSchedule__c.object
<CustomObject>
    <description>KTS-1103  Operating Work Orders in  Salesforce:   this Objects stores the  Operating Schedules for each Coffee Machine. These schedules defines which Jobs( Work Order Line Items) will be generated and send to ClickSoftware as Tasks.  The operator will pick them up and  executes them in his route for the day.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Operating:  indicates whether the Schedule is active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval_in_Weeks__c</fullName>
        <inlineHelpText>Please determine the interval per weeks for which an operating task should be executed.</inlineHelpText>
        <label>Interval in Weeks</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OP_Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To map the holidays of the respective country to the record. Automatically filled upon creation</description>
        <inlineHelpText>Filled automatically</inlineHelpText>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Operating_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <description>TS Operating, used to link an operating schedule to a Physical Asset record. via this  relationship  further information can be pulled onto the Schedule object</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Operating Schedules</relationshipLabel>
        <relationshipName>Operating_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <description>Defines the country  in which this record resides</description>
        <inlineHelpText>Country of record creator.</inlineHelpText>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Schedule_Tasks_for_Holiday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Schedule Tasks for Holiday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specific_Days_in_Week__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicate whether a one or multiple operating tasks should be executed on an exact day.</inlineHelpText>
        <label>Specific Days in Week</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Operating: indicates the start date the schedule should start</description>
        <inlineHelpText>Please enter a Monday (can be in the past) for Daily batch executions and Sunday for Weekly batch executions. For Daily (NL): Create MON = First task THUR; Create TUE = First task FRI; Create WED = First task MON; Create THUR/FRI = First task WED</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Operating Schedule</label>
    <nameField>
        <displayFormat>Schedule-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Schedules</pluralLabel>
    <recordTypes>
        <fullName>Daily</fullName>
        <active>true</active>
        <description>This is the default template for daily executed operating batches.</description>
        <label>Daily</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>This object collects the information  that is needed for linking Engineer information to Work Orders for reporting purposes.</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>SAP Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TS_CreateTask_Batch_Test.cls
/*
* @author        Karen Hung
* @date          6.Sep.2018          
* @description   Test class for TS_CreateTask_Batch
* @revision(s)
*/
@isTest
public class TS_CreateTask_Batch_Test {
    
    public static void dataSetup(){
        
        BusinessHours  bs = [select id from BusinessHours where Name = 'Default'];
        Id bsId = bs.id;
        
        Id rtCs = TS_UtilityClass.getRecordTypeIdByName('CountrySetting__c', 'Operating Task');
        CountrySetting__c testCS = TS_TestDataFactory.createCountrySettings ();      
        testCS.Business_Hours__c = bsId;
        testCS.RecordTypeId = rtCs;
        testCS.NumberDayToLookup__c  = 10;
        testCS.Active__c = true;
        testCS.Country__c = 'SAP_0333';
        Insert testCS;
    }
    

    /*
	* @author        Ritesh Kumar
	* @date          6.Sep.2018          
	* @description   Test class for TS_CreateTask_Batch (1. weekly task -Scenario 1, 1 wo and 1 woli for the whole week ---- Specific_Days_in_Week__c == false)
	* @revision(s)
	*/
    @isTest
    public static void  scenarioOneTest(){
        
        dataSetup();
        
        Date startOfWeek = Date.today().toStartOfWeek();
        DateTime dt = DateTime.newInstance(startOfWeek, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dt.format('EEEE');
        Date sundayStartDate = dayOfWeek == 'Sunday' ? startOfWeek : startOfWeek.addDays(-1);

        List<Account> account_List = TS_TestDataFactory.createAccounts(1);
        Insert account_List;
        
        product2 pd = TS_TestDataFactory.createProductTest('ProductTest','ZSPR');
        Insert pd;
        
        Apttus_Config2__AccountLocation__c accLocation = TS_TestDataFactory.createAccountLocationTest('454545577868',account_List[0].Id );
        Insert accLocation;

        List <BusinessHours> businessHours_List = [SELECT Id, Name FROM BusinessHours WHERE Name = 'Default' LIMIT 1];

        Resource__c resource_obj = TS_TestDataFactory.createResourceTest('ResourceTest');
        Insert resource_obj;	
        
        Id recordType =  TS_UtilityClass.getRecordTypeIdByName('PhysicalAsset__c', 'Machine');
        PhysicalAsset__c physicalAsset = TS_TestDataFactory.createPhysicalAssetTest(recordType, pd.Id,'SAP_0333', account_List[0].Id, accLocation.Id, 'building', 'floor', resource_obj.Id, 'Full Operating');
        Insert physicalAsset;
        
        Id opsRecordType = TS_UtilityClass.getRecordTypeIdByName('OperatingSchedule__c', Label.APTS_Weekly);
        List<OperatingSchedule__c> operatingScheduleList = new List<OperatingSchedule__c>();  
        
        OperatingSchedule__c operatingSchedule = TS_TestDataFactory.createOperatingScheduleTest(false, false, 'PM', '0', '0', '0', 'PM', '0', '0');
        operatingSchedule.Start_Date__c = sundayStartDate;//Date.newInstance(2018,08,06);
        operatingSchedule.OP_Business_Hours__c = businessHours_List[0].Id;
        operatingSchedule.Sales_Organization__c = 'SAP_0333';
        operatingSchedule.PhysicalAsset__c= physicalAsset.Id;
        operatingSchedule.recordTypeId = opsRecordType;
        operatingSchedule.Interval_in_Weeks__c = '1';
  
        operatingScheduleList.add(operatingSchedule);
        Insert operatingScheduleList;

        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntrySTD= TS_TestDataFactory.createPricebookEntryTest(pd.Id,pricebookId);
        Insert pbEntrySTD;

        Pricebook2 Pricebook = new Pricebook2(Name=' Pricebook', isActive=true, Sales_Organization__c ='SAP_0333');
        insert Pricebook;

        PricebookEntry pbEntry= TS_TestDataFactory.createPricebookEntryTest(pd.Id,Pricebook.Id);
        Insert pbEntry;
        
        Test.startTest();
		TS_CreateTask_Batch createTaskBatch = new TS_CreateTask_Batch(sundayStartDate);
		Database.QueryLocator  queryLocator = createTaskBatch.start(null);
		Database.executeBatch(createTaskBatch);
		createTaskBatch.Finish(null);

        Test.stopTest();
		System.assertEquals(operatingSchedule.Sales_Organization__c, 'SAP_0333');
        
        
    }

    /*
	* @author        Ritesh Kumar
	* @date          7.Sep.2018          
	* @description   Test class for TS_CreateTask_Batch (daily task - scenario 2 daily workorders with woli---Specific_Days_in_Week__c == true AND Schedule_Tasks_for_Holiday__c == true)
	* @revision(s)
	*/
    @isTest
    public static void  scenarioTwoTest(){
        dataSetup();
        
        Date startOfWeek = Date.today().toStartOfWeek();
        DateTime dt = DateTime.newInstance(startOfWeek, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dt.format('EEEE');
        Date sundayStartDate = dayOfWeek == 'Sunday' ? startOfWeek : startOfWeek.addDays(-1);

        List<Account> account_List = TS_TestDataFactory.createAccounts(1);
        Insert account_List;
        
        product2 pd = TS_TestDataFactory.createProductTest('ProductTest','ZSPR');
        Insert pd;
        
        Apttus_Config2__AccountLocation__c accLocation = TS_TestDataFactory.createAccountLocationTest('123456789013',account_List[0].Id );
        Insert accLocation;
        
        Resource__c resource_obj = TS_TestDataFactory.createResourceTest('ResourceTest');
        Insert resource_obj;

        List<BusinessHours> businessHours_list = [SELECT Id, Name FROM BusinessHours WHERE Name = 'Default' LIMIT 1];
        String recordTypeId = Schema.SObjectType.CountrySetting__c.getRecordTypeInfosByName().get('Operating Task').getRecordTypeId(); 
        List<CountrySetting__c> cList = [SELECT Country__c, DefaultStartTime__c, DefaultEndTime__c, Business_Hours__c FROM CountrySetting__c WHERE Active__c = true AND RecordTypeId =: recordTypeId];
        
        Id recordType =  TS_UtilityClass.getRecordTypeIdByName('PhysicalAsset__c', 'Machine');
        PhysicalAsset__c physicalAsset = TS_TestDataFactory.createPhysicalAssetTest(recordType, pd.Id,'SAP_0333', account_List[0].Id, accLocation.Id, 'building', 'floor', resource_obj.Id, 'Full Operating');
        Insert physicalAsset;
        
        Id opsRecordType = TS_UtilityClass.getRecordTypeIdByName('OperatingSchedule__c', Label.APTS_Weekly);
        List<OperatingSchedule__c> operatingScheduleList = new List<OperatingSchedule__c>();  
        
        OperatingSchedule__c operatingSchedule = TS_TestDataFactory.createOperatingScheduleTest(true, true, 'PM', '1', '1', '1', 'PM', '0', '0');
        operatingSchedule.Start_Date__c = sundayStartDate; //Date.newInstance(2018,09,07);
        operatingSchedule.OP_Business_Hours__c = businessHours_List[0].Id;
        operatingSchedule.Sales_Organization__c = 'SAP_0333';
        operatingSchedule.PhysicalAsset__c= physicalAsset.Id;
        operatingSchedule.recordTypeId = opsRecordType;
        operatingSchedule.Interval_in_Weeks__c = '1';
  
        operatingScheduleList.add(operatingSchedule);
        Insert operatingScheduleList;

        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntrySTD= TS_TestDataFactory.createPricebookEntryTest(pd.Id,pricebookId);
        Insert pbEntrySTD;

        Pricebook2 Pricebook = new Pricebook2(Name=' Pricebook', isActive=true, Sales_Organization__c ='SAP_0333');
        insert Pricebook;

        PricebookEntry pbEntry= TS_TestDataFactory.createPricebookEntryTest(pd.Id,Pricebook.Id);
        Insert pbEntry;
        
		Test.startTest();

		TS_CreateTask_Batch createTaskBatch = new TS_CreateTask_Batch(sundayStartDate);
		Database.QueryLocator  queryLocator = createTaskBatch.start(null);
		Database.executeBatch(createTaskBatch);
		createTaskBatch.Finish(null);

        Test.stopTest(); 
        System.assertEquals(operatingSchedule.Sales_Organization__c, 'SAP_0333');
    }

    /*
	* @author        Ritesh Kumar
	* @date          7.Sep.2018          
	* @description   Test class for TS_CreateTask_Batch (daily without holiday - scenario 3 daily workorders with woli except holiday---Specific_Days_in_Week__c == true AND Schedule_Tasks_for_Holiday__c == FALSE)
	* @revision(s)
	*/
   @isTest
    public static void  scenarioThreeTest(){
        dataSetup();
        Date startOfWeek = Date.today().toStartOfWeek();
        DateTime dt = DateTime.newInstance(startOfWeek, Time.newInstance(0, 0, 0, 0));
        String dayOfWeek = dt.format('EEEE');
        Date sundayStartDate = dayOfWeek == 'Sunday' ? startOfWeek : startOfWeek.addDays(-1);

        List<Account> account_List = TS_TestDataFactory.createAccounts(1);
        Insert account_List;
        
        product2 pd = TS_TestDataFactory.createProductTest('ProductTest','ZSPR');
        Insert pd;
        
        Apttus_Config2__AccountLocation__c accLocation = TS_TestDataFactory.createAccountLocationTest('123456789013',account_List[0].Id );
        Insert accLocation;
        
        Resource__c resource_obj = TS_TestDataFactory.createResourceTest('ResourceTest');
        Insert resource_obj;

        List<BusinessHours> businessHours_list = [SELECT Id, Name FROM BusinessHours WHERE Name = 'BE - Default' LIMIT 1];
        String recordTypeId = Schema.SObjectType.CountrySetting__c.getRecordTypeInfosByName().get('Operating Task').getRecordTypeId(); 
        List<CountrySetting__c> cList = [SELECT Country__c, DefaultStartTime__c, DefaultEndTime__c, Business_Hours__c FROM CountrySetting__c WHERE Active__c = true AND RecordTypeId =: recordTypeId];
        
        Id recordType =  TS_UtilityClass.getRecordTypeIdByName('PhysicalAsset__c', 'Machine');
        PhysicalAsset__c physicalAsset = TS_TestDataFactory.createPhysicalAssetTest(recordType, pd.Id,'SAP_0333', account_List[0].Id, accLocation.Id, 'building', 'floor', resource_obj.Id, 'Full Operating');
        Insert physicalAsset;
        
        Id opsRecordType = TS_UtilityClass.getRecordTypeIdByName('OperatingSchedule__c', Label.APTS_Weekly);
        List<OperatingSchedule__c> operatingScheduleList = new List<OperatingSchedule__c>();  
        
        OperatingSchedule__c operatingSchedule = TS_TestDataFactory.createOperatingScheduleTest(true, false, 'PM', '1', '1', '0', 'PM', '0', '1');
        operatingSchedule.Start_Date__c = sundayStartDate;
        operatingSchedule.OP_Business_Hours__c = businessHours_List[0].Id;
        operatingSchedule.Sales_Organization__c = 'SAP_0333';
        operatingSchedule.PhysicalAsset__c= physicalAsset.Id;
        operatingSchedule.recordTypeId = opsRecordType;
        operatingSchedule.Interval_in_Weeks__c = '1';
  
        operatingScheduleList.add(operatingSchedule);
        Insert operatingScheduleList;

        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntrySTD= TS_TestDataFactory.createPricebookEntryTest(pd.Id,pricebookId);
        Insert pbEntrySTD;

        Pricebook2 Pricebook = new Pricebook2(Name=' Pricebook', isActive=true, Sales_Organization__c ='SAP_0333');
        insert Pricebook;

        PricebookEntry pbEntry= TS_TestDataFactory.createPricebookEntryTest(pd.Id,Pricebook.Id);
        Insert pbEntry;
        
		Test.startTest();

		TS_CreateTask_Batch createTaskBatch = new TS_CreateTask_Batch(sundayStartDate);
		Database.QueryLocator  queryLocator = createTaskBatch.start(null);
		Database.executeBatch(createTaskBatch,10);
		createTaskBatch.Finish(null);

        Test.stopTest(); 
        System.assertEquals(operatingSchedule.Sales_Organization__c, 'SAP_0333');
    }

}