src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Triggered_Timestamp__c</fullName>
        <description>Trigger date time from Salesforce.</description>
        <inlineHelpText>Trigger date time from Salesforce.</inlineHelpText>
        <label>Triggered Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>TS_Click_Synchronized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to know if this record were already synchronized with Click.</description>
        <inlineHelpText>Indicator to know if this record were already synchronized with Click.</inlineHelpText>
        <label>Click Synchronized</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/TS_PricebookEntry_SyncToClick_Execute.cls
/**
* @author        Marvin Gatchalian
* @date          5.mar.2018
* @description   Apex class used to execute Pricebook Entry SyncToClick batch by creating Integration Log 
* @revision(s)
*/
public with sharing class TS_PricebookEntry_SyncToClick_Execute {
	
	public Map <pricebookentry, Integration_Log__c> createIntegrationLogPerPriceBookEntry (List<pricebookentry> priceBookEntries) {
        CustomLogging.push('createIntegrationLogPerPriceBookEntry', 'TS_PricebookEntry_SyncToClick_Execute');
		Map <pricebookentry, Integration_Log__c> priceBookEntryIntegrationLogMap  = new
		Map <pricebookentry, Integration_Log__c>();
		
        try {
            
            for(PricebookEntry eachPriceBookEntry :priceBookEntries) {
                if (!eachPriceBookEntry.TS_Click_Synchronized__c) {
                	
                	Integration_Log__c integLog = new Integration_Log__c();
                	
                    integLog.Object_Id__c = eachPriceBookEntry.Id;
                    integLog.Object__c = INT_Constants.CLICK_SYNCMASTERPRODUCT;
                    integLog.Integration_Status__c = INT_Constants.INITIAL;
                    integLog.Triggered_Timestamp__c = Datetime.now();
                    
                    eachPriceBookEntry.TS_Click_Synchronized__c = true;
                    
                    priceBookEntryIntegrationLogMap.put(eachPriceBookEntry, integLog);
                }
            }

        } catch (Exception ex) {
            CustomLogging.debugException(ex);
            CustomLogging.pop();
            System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());
        }
        
        CustomLogging.pop();
		return priceBookEntryIntegrationLogMap;
	}
    
}