src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Message__c</fullName>
        <description>Any messages sent from SAP PI to Salesforce (error and success messages).</description>
        <inlineHelpText>Any messages sent from SAP PI to Salesforce (error and success messages).</inlineHelpText>
        <label>Integration Message</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object triggering the transaction</description>
        <inlineHelpText>Object triggering the transaction</inlineHelpText>
        <label>Object</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SessionID__c</fullName>
        <label>Session ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Target_System_Processed_TimeStamp__c</fullName>
        <description>Date Time when the transaction was processed by SAP (success message from SAP to SAP PI).</description>
        <inlineHelpText>Date Time when the transaction was processed by SAP (success message from SAP to SAP PI).</inlineHelpText>
        <label>Target System Processed TimeStamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Line Item</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IntegrationUserAndProfile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Click_Product_Batch_Limit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Click Product Batch Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IntegrationUserAndProfile</label>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Country_ISO__c</fullName>
        <description>Define the country for (custom) pricebook</description>
        <label>Country (ISO)</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Country_ISO__c</fullName>
        <formula>Pricebook2.Country_ISO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country (ISO)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Service_Material__c</fullName>
        <description>To check if the product is service material</description>
        <formula>ISPICKVAL(Product2.Family, &apos;SE&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Service Material</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OldStandardPrice__c</fullName>
        <label>Old Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/TS_ClickSyncMasterData.cls
//-------------------------------------------------------------------------------------------//
// Author       :   Rey Austral - Accenture
// Created Date :   March 21, 2017
// Usage        :   
//-------------------------------------------------------------------------------------------//
public without sharing class TS_ClickSyncMasterData {
        
    //Added by Ritesh Kumar to throw custome exception.
    public class TS_ClickSyncMasterDataException extends Exception{
    }
    
    public void executeSessionId(List<Integration_Log__c> updatableIlogList) {
        CustomLogging.push('executeSessionId', 'TS_ClickSyncMasterData');

        for (Integration_Log__c iLog : updatableIlogList) {
            JDEServicesCallout.JDEServiceOptimizationPort port = new JDEServicesCallout.JDEServiceOptimizationPort();
            JDEServicesCallout.Sessions[] elem = new List<JDEServicesCallout.Sessions>();
            JDEServicesCallout.Sessions session = new JDEServicesCallout.Sessions();
            session.SessionID = iLog.SessionID__c;
            elem.add(session);
 
            try {
                port.SyncMasterData(null,elem);
                iLog.Integration_Status__c = INT_Constants.TARGET_SYSTEM_SUCCESS;
                iLog.Target_System_Processed_TimeStamp__c = Datetime.now();
                
            } catch(Exception ex) {
                iLog.Integration_Status__c = INT_Constants.TARGET_SYSTEM_ERROR;
                iLog.Integration_Message__c = ex.getMessage();
                CustomLogging.debugException(ex);
                CustomLogging.pop();
            }              
        }

        try {
            update updatableIlogList;
            //Exception for test class purposes
            if (Test.isRunningTest()) {
                throw new TS_ClickSyncMasterDataException('Force to throw an exception');
            }
        } catch(Exception ex) {          
            CustomLogging.debugException(ex);
            CustomLogging.pop();
        }

        CustomLogging.pop();       
    }

    //### Commented due to test class coverage. Method seems not used anymore. ###
    /*public void executeSendPartType(List<Integration_Log__c> currentILogList) {
        CustomLogging.push('SyncMasterProduct', 'TS_ClickSyncMasterData');
        
        List<Integration_Log__c> updatedIlogList = [Select Id, Integration_Status__c, Work_Order_Line_Item__c ,Object__c, Object_Id__c
                                                        from Integration_Log__c where Id IN: currentILogList];
        List<Integration_Log__c> updatableIlogList = new List<Integration_Log__c>();
        Set<Id> psId = new Set<Id>();
        
        Map<Id,Integration_Log__c> iLogMap = new Map<Id,Integration_Log__c>();
        for (Integration_Log__c ilog : updatedIlogList) {
            psId.add(ilog.Object_Id__c);      
            iLogMap.put(ilog.Object_Id__c,ilog);      
        }

        List<PricebookEntry> psList = [Select Id,PriceBook2.Name,Country_ISO__c, Product2.Id, Product2.Name, UnitPrice, 
                                        Product2.Description,OldStandardPrice__c, Name,Product2.IsActive ,Is_Service_Material__c
                                        From PricebookEntry where Id in: psId];
        JDEServicesCallout.JDEServiceOptimizationPort port = new JDEServicesCallout.JDEServiceOptimizationPort();
        JDEServicesCallout.PartTypes[] elem = new List<JDEServicesCallout.PartTypes>();
        
        Integer ctr = 0;
     
        for(PricebookEntry ps : psList) {
            JDEServicesCallout.PartTypes partType = new JDEServicesCallout.PartTypes();
            partType.Name = ps.Product2.Name;
            //if (!String.isBlank(ps.Sales_Office__c)) {
            partType.Country = ps.Country_ISO__c;//Integer.valueOf( ps.Sales_Office__c );
            //}
            partType.Description = ps.Product2.Description;             
            partType.Cost = Integer.valueOf( ps.UnitPrice );            
            partType.Active = ps.Product2.IsActive;
            partType.PartID = ps.Id;
            partType.IsServiceMaterial =  ps.Is_Service_Material__c ? 1 : 0;
            elem.add(partType);           
            updatableIlogList.add( iLogMap.get(ps.Id) );
            ctr++;
            //if the records exceeds the maximum number of records that can be send to click
            //immediately send the list of records and create a new set of list
            if (ctr == IntegrationUserAndProfile__c.getInstance().Click_Product_Batch_Limit__c && IntegrationUserAndProfile__c.getInstance().Click_Product_Batch_Limit__c !=0 ) {
                ExecuteQueueableCallOut eqc = new ExecuteQueueableCallOut();
                eqc.iLogList = updatableIlogList;
                eqc.elem = elem;            
                System.enqueueJob(eqc);

                elem = new List<JDEServicesCallout.PartTypes>();
                ctr = 0;
                
            }
        }        
        if (!elem.isEmpty()) {
            ExecuteQueueableCallOut eqc = new ExecuteQueueableCallOut();
            eqc.iLogList = updatableIlogList;
            eqc.elem = elem;            
            System.enqueueJob(eqc);
       
        }
    
        CustomLogging.pop();       
    }*/

}