src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <description>Status of the triggered transaction.</description>
        <inlineHelpText>Status of the triggered transaction.</inlineHelpText>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                    <default>true</default>
                    <label>Initial</label>
                </value>
                <value>
                    <fullName>Waiting on Parent Integration</fullName>
                </value>
                <value>
                    <fullName>Outbound Message Triggered</fullName>
                </value>
                <value>
                    <fullName>Target System Success</fullName>
                </value>
                <value>
                    <fullName>Target System Error</fullName>
                </value>
                <value>
                    <fullName>Paused</fullName>
                </value>
                <value>
                    <fullName>Product Batch Upsert Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is a generic field that will be used to store the record ID (Account, Order, etc.) and is used by SAP PI. This avoids the use of lookup fields in the interface and the need to change the WSDL per new Salesforce object that needs to be integrated and therefore impacting SAP PI.</description>
        <externalId>true</externalId>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ResetAccount.cls
global without sharing class ResetAccount {
    webservice static String resetAccountRelatedToIntegrationLog(Id integID) {
        String retString = 'Success';
        Id recordTypeIdCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.Customer).getRecordTypeId();
        Id recordTypeIdProspectValid =  Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.ProspectValid).getRecordTypeId();
        Id recordTypeIdPromotionReq =  Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.PromotionRequested).getRecordTypeId();
        Id recordTypeIdCustomerValidation =  Schema.SObjectType.Account.getRecordTypeInfosByName().get(SM_Constants.EndCustomerValidation).getRecordTypeId();
        Integration_Log__c integrationlog = [Select Id, Integration_Status__c, Object_Id__c FROM Integration_Log__c WHERE ID = :integID];
        Account accRec = [Select Id, RecordTypeId FROM Account WHERE Id = :integrationlog.Object_Id__c];
        if (integrationlog.Integration_Status__c != 'Target System Error') {
            retString = 'No Error';
        } else {
            if (accRec.RecordTypeId == recordTypeIdPromotionReq) {
                accRec.RecordTypeId = recordTypeIdProspectValid;
                accRec.Prospect_promotion_status__c = 'Prospect promotion denied';
            } else if (accRec.RecordTypeId == recordTypeIdCustomerValidation) {
                accRec.RecordTypeId = recordTypeIdCustomer;
				accRec.Previous_Record_Type__c = String.valueOf(recordTypeIdCustomerValidation).substring(0, 15);
            } 
            update accRec;
        }
        return retString;
    }
}