src/objects/Integration_Log__c.object
<CustomObject>
    <description>This object contains the transaction statuses of messages sent to SAP PI.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>RouteSales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>OP_CancelationReasonMachine__c</fullName>
        <label>Cancelation Reason (Machine)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mothball</fullName>
                </value>
                <value>
                    <fullName>Not Needed</fullName>
                </value>
                <value>
                    <fullName>Machine issue</fullName>
                </value>
                <value>
                    <fullName>Customer issue</fullName>
                </value>
                <value>
                    <fullName>Not reachable</fullName>
                </value>
                <value>
                    <fullName>EoD Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLADate__c</fullName>
        <description>TS: Indicates the SLA date for the line item.</description>
        <label>SLA Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SendCounterReadingsOperating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Counter Readings (Operating)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S44</fullName>
                    <label>Workshop</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>Routesales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isFromRoute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isFromRoute</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_CancelRouteTasks_Batch.cls
/**
 * @author        Karen Hung
 * @date           02/04/2020
 * @description   Apex Class for Cancelling Route Tasks
 * @revision(s) 
 */
global with sharing class TS_CancelRouteTasks_Batch implements Database.Batchable<sObject>, Database.Stateful{
    public class TS_CancelRouteTasks_BatchException extends Exception {}
    public static Boolean hasException = false;
	private List<String> exception_List = new List<String>();
    
    Set<String> woIds = new Set<String>();
    
     /******************************************************************************
     * @author        Karen Hung
     * @date           02/04/2020
     * @description   Constructor
     * @revision(s)
     ******************************************************************************/
    global TS_CancelRouteTasks_Batch() {
    }

    /******************************************************************************
     * @author         Karen Hung
     * @date            02/04/2020
     * @description    This method is the start of the batch job
     * @revision(s)
     ******************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        CustomLogging.push('start', 'TS_CancelRouteTasks_Batch');
        DateTime dateToday = DateTime.now();
        String recordTypeId = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByName().get(TS_Constants.TS_WOLI_RECORDTYPE_OPERATINGTASK).getRecordTypeId();
        DescribeSObjectResult woliDescribe = WorkOrderLineItem.getSObjectType().getDescribe();
        List<String> fields = new List<String>(woliDescribe.fields.getMap().keySet());
        String query = 'SELECT ' + String.join(fields, ',') +' FROM WorkOrderLineItem WHERE RecordtypeId =' +'\''+recordTypeId+'\''+
                       ' AND Status NOT IN (\'Completed\',\'Canceled\') AND WorkOrderType__c =\'S20\' AND isFromRoute__c = TRUE'+
                       ' AND WorkOrder.SalesOrganization__c = \'SAP_0111\' AND SLADate__c <= :dateToday';

        CustomLogging.pop();
    	return Database.getQueryLocator(query);
    }

    /******************************************************************************
    * @author         Karen Hung
    * @date           02/04/2020
    * @description    This method proceses the result of query. Where the WOLI tasks are updated. 
    *                
    * @revision(s)
    ******************************************************************************/
    global void execute(Database.BatchableContext BC, List<WorkOrderLineItem> woliItems) {
        CustomLogging.push('execute', 'TS_CancelRouteTasks_Batch');
        
        List<Integration_log__c> iLogtoInsert = new List<Integration_log__c>();
        
        if(!woliItems.isEmpty()){ 
            for(WorkOrderLineItem woli : woliItems){
                woli.Status = TS_Constants.STATUS_CANCELED;
                woli.OP_CancelationReasonMachine__c = TS_Constants.EOD_BATCH;
				
				//add workorderIds for iLog creation in TS_CancelRouteWorkOrder_Batch
                if(woli.SendCounterReadingsOperating__c == true && woli.WorkOrderId != null){   
                    woIds.add(woli.WorkOrderId);
                }
            }

            try{

                //update woli
                database.update(woliItems);

                //Exception for test class purposes
                if (Test.isRunningTest() && hasException) {
                    throw new TS_CancelRouteTasks_BatchException('Force to throw an exception');
                }   
            }catch(Exception ex){
                CustomLogging.debugException(ex);
                CustomLogging.pop();
                System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());
            }


        }
  
        CustomLogging.pop();
    }

    /******************************************************************************
     * @author         Karen Hung
     * @date           02/04/2020
     * @description    This method to perform actions when the batch is finished
     * @revision(s)
     ******************************************************************************/
    global void finish(Database.BatchableContext BC) {        
        CustomLogging.push('finish', 'TS_CancelRouteTasks_Batch'); 
		
        //CHECK QUEUE CAPACITY
        List<AsyncApexJob> routeIntegrationBatch = [SELECT Id, ApexClassID 
                                            FROM AsyncApexJob 
                                            WHERE Status IN ('Processing', 'Preparing') 
                                            AND ApexClassId IN (SELECT Id FROM ApexClass WHERE Name = 'TS_CancelRouteWorkOrder_Batch') ];
        
        //COUNT THE PROCESSING JOBS AND THOSE IN QUEUE
        Integer batchCount_ProcessingPreparing = Database.countQuery('SELECT count() FROM AsyncApexJob WHERE JobType=\'BatchApex\' AND Status IN (\'Processing\', \'Preparing\')');
        Integer batchCount_HoldingQueued = Database.countQuery('SELECT count() FROM AsyncApexJob WHERE JobType=\'BatchApex\' AND Status IN (\'Queued\', \'Holding\')');

        if ((batchCount_ProcessingPreparing < 5 || batchCount_HoldingQueued < 100) && (routeIntegrationBatch == null || routeIntegrationBatch.size() == 0) && !Test.isRunningTest()) { 
           Database.executeBatch(new TS_CancelRouteWorkOrder_Batch(woIds), Integer.valueOf(System.label.TS_CancelRTBatchSize));

        }          

        //DISPLAY SUMMARY OF FAILED RECORDS
        if (!exception_List.isEmpty()) {
            System.debug(TS_Constants.ERRBATCH_MSG_02 + exception_List.size());

            //DETAILED LOG OF ERRORS
            for (String err : exception_List) {
                System.debug(err);
            }
        }

        CustomLogging.pop();
    }
}