src/objects/NPS__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>NPS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NPS Detail</label>
    <nameField>
        <displayFormat>NPS{0000000000}</displayFormat>
        <label>NPS Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPS Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Define a hierarchical custom setting (TriggerSettings__c) and create a CheckBox field per Trigger to turn the trigger off/on.</description>
    <fields>
        <fullName>NPSDetailTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NPSDetailTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Elevated_Access_Reason__c</fullName>
        <label>Elevated Access Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Authorization Issue</fullName>
                </value>
                <value>
                    <fullName>Batch job execution</fullName>
                </value>
                <value>
                    <fullName>Defect or Incident Resolution</fullName>
                </value>
                <value>
                    <fullName>Manual deployment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Elevated_Access_Reference__c</fullName>
        <label>Elevated Access Reference</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/NPSTriggerHandler_Test.cls
@isTest
public class NPSTriggerHandler_Test {
    //Description: This is for test setup of the test class
    static void testSetup(){
        //insert custom settings
        TriggerSettings__c ts = new TriggerSettings__c();
        ts.NPSDetailTrigger__c = true;
        insert ts;
        
        Profile p = [SELECT Id FROM Profile WHERE  Name =: 'System Administrator']; 
        User u = new User(Alias = 'standt', Email='sample@testUser1.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='sample@testUser11.com', Sales_Organization__c = 'SAP_0333', Country= 'Netherlands',
        Elevated_Access_Reason__c = 'Defect or Incident Resolution', Elevated_Access_Reference__c = 'ASDF');
        insert u;
        
        Account acc = new Account();
        acc.Name = 'accName';
        acc.Second_Account_Name__c = 'sAccName';
        //acc.Sales_Office__c = 'SAP_F020';
        acc.Phone = '+31302979111';
        acc.Customer_Relations_1__c = u.Id;
        insert acc;
        
        NPS__c npsRec = new NPS__c();
        npsRec.Account__c = acc.Id;
        insert npsRec;

    }
    
    private static testMethod void createTaskOnNPS() { 
        testSetup();
        
        List<NPS__c> npsRecords = new List<NPS__c>([Select Id, Name, Account__r.Name, Account__r.Customer_Relations_1__c
                                                    FROM NPS__c]);
        
        System.assert(npsRecords[0].Account__r.Name == 'accName');
        System.assert(npsRecords[0].Account__r.Customer_Relations_1__c <> Null);
        
        NPSTriggerHandler npsDetail = new NPSTriggerHandler();

        List<SObject> newItems;
        List<SObject> oldList;
        Map<Id, SObject> oldItems;
        List<SObject> newList;
        Map<Id, SObject> newItemsMap;
        
        npsDetail.BeforeInsert(newItems); 
        npsDetail.BeforeDelete(oldList, oldItems);
        npsDetail.BeforeUpdate(newList, newItemsMap, oldList, oldItems);
        npsDetail.AfterUpdate(newList, newItemsMap, oldList, oldItems);
        npsDetail.AfterDelete(oldList, oldItems);
        npsDetail.AfterUndelete(newList, newItemsMap);
                                                
        
    }
}