src/objects/OperatingSchedule__c.object
<CustomObject>
    <description>KTS-1103  Operating Work Orders in  Salesforce:   this Objects stores the  Operating Schedules for each Coffee Machine. These schedules defines which Jobs( Work Order Line Items) will be generated and send to ClickSoftware as Tasks.  The operator will pick them up and  executes them in his route for the day.</description>
    <fields>
        <fullName>Account_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Operating Schedules</relationshipLabel>
        <relationshipName>Operating_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Operating:  indicates whether the Schedule is active or not.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interval_in_Weeks__c</fullName>
        <inlineHelpText>Please determine the interval per weeks for which an operating task should be executed.</inlineHelpText>
        <label>Interval in Weeks</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <description>TS Operating, used to link an operating schedule to a Physical Asset record. via this  relationship  further information can be pulled onto the Schedule object</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Operating Schedules</relationshipLabel>
        <relationshipName>Operating_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <description>Defines the country  in which this record resides</description>
        <inlineHelpText>Country of record creator.</inlineHelpText>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Operating: indicates the start date the schedule should start</description>
        <inlineHelpText>Please enter a Monday (can be in the past) for Daily batch executions and Sunday for Weekly batch executions. For Daily (NL): Create MON = First task THUR; Create TUE = First task FRI; Create WED = First task MON; Create THUR/FRI = First task WED</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Operating Schedule</label>
    <nameField>
        <displayFormat>Schedule-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operating Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>AccountLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the account location where the asset is located at.</description>
        <label>Account Location</label>
        <referenceTo>Apttus_Config2__AccountLocation__c</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AssetStatus__c</fullName>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Activation</fullName>
                    <default>true</default>
                    <label>Pending Activation</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Machine_Care__c</fullName>
        <description>Global Picklist used on other objects as well ( Operating Tasks)</description>
        <label>Machine Care</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_MachineCare</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the product used for the asset.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>This indicates the sales organization / region to which the machine is sold to.</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SoldTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Sold To related to the asset.</description>
        <label>Sold To</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Physical Assets</relationshipLabel>
        <relationshipName>Physical_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SAP_0333</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>SAP_0975</fullName>
                    <label>Denmark</label>
                </value>
                <value>
                    <fullName>SAP_6706</fullName>
                    <label>France</label>
                </value>
                <value>
                    <fullName>SAP_6864</fullName>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>SAP_0976</fullName>
                    <label>Sweden</label>
                </value>
                <value>
                    <fullName>SAP_0080</fullName>
                    <label>Spain</label>
                </value>
                <value>
                    <fullName>SAP_6709</fullName>
                    <label>Ireland</label>
                </value>
                <value>
                    <fullName>SAP_6712</fullName>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>SAP_6750</fullName>
                    <label>Great Britain</label>
                </value>
                <value>
                    <fullName>SAP_0111</fullName>
                    <label>Netherlands</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <formula>Text(Pricebook2.Sales_Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <description>This object collects the information  that is needed for linking Engineer information to Work Orders for reporting purposes.</description>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>SAP Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Organization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TS_CloneScheduleController_Test.cls
/*Created by: Karen Hung 11/22/2018
 * test class for TS_CloneScheduleController
 */
 @isTest
public class TS_CloneScheduleController_Test {
	static OperatingSchedule__c opSched;
    static PhysicalAsset__c pAsset;
    static PhysicalAsset__C pAsset2;
    static Id opsRecordType;
    static Apttus_Config2__AccountLocation__c accLocation;
    
    /*data prep*/
    @testSetup
    static void dataPrep(){
        opsRecordType = TS_UtilityClass.getRecordTypeIdByName('OperatingSchedule__c',Label.APTS_Weekly);

        List<Account> account_List = TS_TestDataFactory.createAccounts(1);
        database.insert(account_List);
        
        product2 pd = TS_TestDataFactory.createProductTest('ProductTest','ZSPR');
        database.insert(pd);
        
        accLocation = new Apttus_Config2__AccountLocation__c();
        accLocation.Apttus_Config2__AccountId__c = account_List[0].id;
        insert accLocation;
        
        Resource__c resource_obj = TS_TestDataFactory.createResourceTest('ResourceTest');
        Insert resource_obj;	
        
        String recordType = Schema.SObjectType.PhysicalAsset__c.getRecordTypeInfosByName().get(TS_Constants.PA_RECTYPE_MACHINE).getRecordTypeId(); 
        pAsset = TS_TestDataFactory.createPhysicalAssetTest(recordType, pd.Id,'SAP_0333', account_List[0].Id, accLocation.Id, 'building', 'floor', resource_obj.Id, 'Full Operating');
        database.insert(pAsset);
        
        pAsset2 = new PhysicalAsset__c();
        pAsset2.RecordTypeId = Schema.SObjectType.PhysicalAsset__c.getRecordTypeInfosByName().get(TS_Constants.PA_RECTYPE_MACHINE).getRecordTypeId();
        pAsset2.Product__c = pd.Id;
        pAsset2.AccountLocation__c = accLocation.id;
        pAsset2.SalesOrganization__c = 'SAP_0333';
        pAsset2.SoldTo__c = account_List[0].Id;
        pAsset2.Machine_Care__c = 'Full Operating';
        pAsset2.AssetStatus__c = 'Activated';
        //TS_TestDataFactory.createPhysicalAssetTest(recordType, pd.Id,'SAP_0333', account_List[0].Id, accLocation.Id, 'building', 'floor', resource_obj.Id, 'Full Operating');
        database.insert(pAsset2);
       
       
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntrySTD= TS_TestDataFactory.createPricebookEntryTest(pd.Id,pricebookId);
        database.insert(pbEntrySTD);
        
        Pricebook2 Pricebook = new Pricebook2(Name=' Pricebook', isActive=true, Sales_Organization__c ='SAP_0333');
        database.insert(Pricebook);
        
        PricebookEntry pbEntry= TS_TestDataFactory.createPricebookEntryTest(pd.Id,Pricebook.Id);
        database.insert(pbEntry);

        
    }
    
    /*test the trigger*/
    static testMethod void opSchedTriggerTest(){
        User u = TS_TestDataFactory.createUser(Label.TS_Default_User_Profile);

        System.runAs(u) {
            
            test.startTest();
           
            dataPrep();
            List<OperatingSchedule__c> operatingScheduleList = new List<OperatingSchedule__c>();  
            List <BusinessHours> businessHours_List = [SELECT Id, Name FROM BusinessHours WHERE Name = 'Default' LIMIT 1];
            opSched = TS_TestDataFactory.createOperatingScheduleTest(false, false, 'AM', '0', '0', '0', 'PM', '0', '0');
            opSched.Start_Date__c = Date.newInstance(2018,09,07);//Date.newInstance(2018,08,06);
            opSched.PhysicalAsset__c= pAsset.Id;
            opSched.recordTypeId = opsRecordType;
            opSched.Account_Location__c = accLocation.Id;
            opSched.Interval_in_Weeks__c = '1';
            operatingScheduleList.add(opSched);
            database.Insert(operatingScheduleList);   

            OperatingSchedule__c opSched2 =  new OperatingSchedule__c();
            opSched2.Start_Date__c = Date.newInstance(2018,09,07);
            opSched2.Active__c=true;
            opSched2.Interval_in_Weeks__c = '1';
            opSched2.PhysicalAsset__c = pAsset2.id;
            insert opSched2;

            TS_CloneScheduleController.getPAs(operatingScheduleList[0].id); 
            List<Object> obList = TS_CloneScheduleController.getPAs(operatingScheduleList[0].id);
            String str = JSON.serialize(obList);
			TS_CloneScheduleController.createOpSched(str, operatingScheduleList[0].id);
            
            test.stopTest();
            system.assertEquals(1,operatingScheduleList.size());
        }
        
    }

}