src/objects/PhysicalAsset__c.object
<CustomObject>
    <description>This object is used to host all information regarding a physical asset.</description>
    <fields>
        <fullName>Connected__c</fullName>
        <description>Indicates whether the Machine has  connectivity.</description>
        <label>Connected</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Physical Asset</label>
    <nameField>
        <label>Physical Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>MachineCare__c</fullName>
        <description>Indication of the Type of Contract for Machine Care used in TS and Operating</description>
        <label>Machine Care</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PKL_MachineCare</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OP_CancelationReasonMachine__c</fullName>
        <label>Cancelation Reason (Machine)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mothball</fullName>
                </value>
                <value>
                    <fullName>Not Needed</fullName>
                </value>
                <value>
                    <fullName>Machine issue</fullName>
                </value>
                <value>
                    <fullName>Customer issue</fullName>
                </value>
                <value>
                    <fullName>Not reachable</fullName>
                </value>
                <value>
                    <fullName>EoD Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhysicalAsset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This indicates the physical asset applicable for the work.</description>
        <label>Physical Asset</label>
        <referenceTo>PhysicalAsset__c</referenceTo>
        <relationshipLabel>Service Jobs</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrderType__c</fullName>
        <label>Work Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S10</fullName>
                    <label>Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S15</fullName>
                    <label>1st Line Corrective Maintenance</label>
                </value>
                <value>
                    <fullName>S20</fullName>
                    <label>Machine Care</label>
                </value>
                <value>
                    <fullName>S30</fullName>
                    <label>Preventive Maintenance</label>
                </value>
                <value>
                    <fullName>S31</fullName>
                    <label>Preventive Check</label>
                </value>
                <value>
                    <fullName>S32</fullName>
                    <label>Water Filter Change</label>
                </value>
                <value>
                    <fullName>S40</fullName>
                    <label>Installation</label>
                </value>
                <value>
                    <fullName>S41</fullName>
                    <label>De-Installation</label>
                </value>
                <value>
                    <fullName>S42</fullName>
                    <label>Machine Movement</label>
                </value>
                <value>
                    <fullName>S43</fullName>
                    <label>Configuration Change</label>
                </value>
                <value>
                    <fullName>S50</fullName>
                    <label>Pick-Up/Drop Off</label>
                </value>
                <value>
                    <fullName>S51</fullName>
                    <label>Pre-Visit Installation</label>
                </value>
                <value>
                    <fullName>S52</fullName>
                    <label>After-Visit Installation</label>
                </value>
                <value>
                    <fullName>S53</fullName>
                    <label>Assistance</label>
                </value>
                <value>
                    <fullName>S60</fullName>
                    <label>Modification</label>
                </value>
                <value>
                    <fullName>S44</fullName>
                    <label>Workshop</label>
                </value>
                <value>
                    <fullName>S21</fullName>
                    <label>Counter Reading</label>
                </value>
                <value>
                    <fullName>S22</fullName>
                    <label>Counter Reading FUP</label>
                </value>
                <value>
                    <fullName>S25</fullName>
                    <label>Routesales</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TS_CancelCounterReading_Batch.cls
/**
 * @author        Karen Hung
 * @date          24/09/2019
 * @description   Apex Class for Cancelling Counter Reading Orders, scheduled every end of month
 * @revision(s) 
 */
global with sharing class TS_CancelCounterReading_Batch implements Database.Batchable<sObject>{
    public class TS_CancelCounterReading_BatchException extends Exception {}
    public static Boolean hasException = false;
    
     /******************************************************************************
     * @author        Karen Hung
     * @date          24/09/2019
     * @description   Constructor
     * @revision(s)
     ******************************************************************************/
    global TS_CancelCounterReading_Batch() {
    }

    /******************************************************************************
     * @author         Karen Hung
     * @date           24/09/2019
     * @description    This method is the start of the batch job
     * @revision(s)
     ******************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC) {
        CustomLogging.push('start', 'TS_CancelCounterReading_Batch');
        DateTime dateToday = DateTime.now();
        String recordTypeId = Schema.SObjectType.WorkOrderLineItem.getRecordTypeInfosByName().get(TS_Constants.TS_WOLI_RECORDTYPE_COUNTERREADINGTASK).getRecordTypeId();
        DescribeSObjectResult woliDescribe = WorkOrderLineItem.getSObjectType().getDescribe();
        List<String> fields = new List<String>(woliDescribe.fields.getMap().keySet());
        String query = 'SELECT ' + String.join(fields, ',') +' FROM WorkOrderLineItem WHERE RecordtypeId =' +'\''+recordTypeId+'\''+
                       ' AND Status NOT IN (\'Completed\',\'Canceled\') AND WorkOrderType__c =\'S22\''; 
                       //' AND MachineCare__c = \'Full Operating\' AND PhysicalAsset__r.Connected__c = \'No\''; //DOO-4582 05.28.2020 Francis Allen Alindogan
        CustomLogging.pop();
    	return Database.getQueryLocator(query);
    }

    /******************************************************************************
    * @author         Karen Hung
    * @date           24/09/2019
    * @description    This method proceses the result of query. Where the WOLI tasks are updated. 
    *                
    * @revision(s)
    ******************************************************************************/
    global void execute(Database.BatchableContext BC, List<WorkOrderLineItem> woliItems) {
		CustomLogging.push('execute', 'TS_CancelCounterReading_Batch');
        
        if(!woliItems.isEmpty()){
            
            for(WorkOrderLineItem woli : woliItems){
                woli.Status = TS_Constants.STATUS_CANCELED;
                woli.OP_CancelationReasonMachine__c = 'Not Needed';
                //woli.OP_CancelationReasonMachine__c = 'EoD Batch';
            }
                        
            try{
                database.update(woliItems);
                //Exception for test class purposes
                if (Test.isRunningTest() && hasException) {
                    throw new TS_CancelCounterReading_BatchException('Force to throw an exception');
                }   
            }catch(Exception ex){
                CustomLogging.debugException(ex);
                CustomLogging.pop();
                System.debug(ex.getMessage() + '\n' + ex.getStackTraceString());
            }
            
        }
     
        CustomLogging.pop();
    }

    /******************************************************************************
     * @author         Karen Hung
     * @date           11/27/2018
     * @description    This method to perform actions when the batch is finished
     * @revision(s)
     ******************************************************************************/
    global void finish(Database.BatchableContext BC) {        
        CustomLogging.push('finish', 'TS_CancelCounterReading_Batch');       
        CustomLogging.pop();
    }
}